- eloquent.md
Simple capitalization fix. (You -> you)
> Fixed typo in eloquent.md

- releases.md
Added the make:event to the to the New generators section.
> Added the make:event

- authentication.md
> Corrects SocialiteServiceProvider namespace.

- responses.md
This adds some documentation on the very-handy `back()` method.
> Add back() to responses.md

- installation.md
Missing links for "Configuration" and "Pretty URLs" sections.
> Added index links

- packages.md
To account for changes in https://github.com/laravel/framework/commit/7b315aa752896ec8fb8a684f1c0b8f8a8cac2116
> Swap arguments on mergeConfigFrom and loadViewsFrom

- authentication.md
The scopes() method doesn't apply to the Twitter provider. :(
> Fixed misleading example.

- database.md
Examples are using new array syntax. 
Configuration should do the same way.
> change configuration to new array syntax

- routing.md
Fixes a broken link to the templates section.
> 5.0 Minor Fix broken link in CSRF Section

- eloquent.md
The code examples above and below this change, as well as the text below of this change, talk about the "User" model, but the old code example creates a "Photo" model.
> Removed confusing example

- pagination.md
And move the section about creating it manually a bit up, so it reads more logical.
> Update note about Paginator::make

- pagination.md
Changed "server" to "serve" under "Using The Custom Presenter".
> Fixed a typo

- pagination.md
Changed "server" to "serve" under "Using The Custom Presenter".
> Fixed a typo in pagination

- elixir.md
update elixir.md app.scss->app.sass
> update elixir.md app.scss->app.sass

- artisan.md
- authentication.md
- elixir.md
- releases.md
> typo fixes

- upgrade.md
> Typo : Fixed a minor typo

- container.md
Would you really use a variable such as `$all` in your views?
> Change $all to $orders

- releases.md
**Complement** refers to something that completes or goes well with something.
**Compliment** indicates the offering of praise or flattery to another person.
> Compliment vs. complement

- cache.md
- commands.md
- eloquent.md
- helpers.md
- html.md
- localization.md
- mail.md
- migrations.md
- queries.md
- queues.md
- redis.md
- schema.md
- session.md
- ssh.md
- testing.md
- upgrade.md
- validation.md
All occurrences of `array(...)` replaced with `[...]`
> Use the short array syntax

- extending.md
Clarified interface and boolean return values
> retrieveByCredentials and validateCredentials

- pagination.md
Added hasMorePages, url and nextPageUrl methods to the pagination documentation. I used these methods while developing an API and found that they were missing from the documentation. Perhaps developers will overlook them if they aren't in there.
> Added hasMorePages, url and nextPageUrl methods

- contributions.md
Isn't Laravel 5 following the PSR-4 as autoloading standard?
> Update Autoloading Standard in Coding Style

- routing.md
For https://github.com/laravel/framework/pull/7528
> Add note about X-XSRF-TOKEN and X-CSRF-TOKEN difference

- contracts.md
Noticed this was missing while I was reviewing things, so just adding it in.
> Adding Bus Dispatcher to the Contracts reference

- elixir.md
Elixir allows to compile only scripts or styles.
> Added Elixir documentation to scripts and styles tasks

- middleware.md
Resubmitting #1074 against 5.0 branch
> Clarify middleware running before/after a request has been processed

- homestead.md
Add additional NFS info an example.
> Update homestead.md with additional NFS info

- filesystem.md
@GrahamCampbell @mattstauffer @barryvdh Sorry about the pull request spam guys.  Just learning a bit about squashing commits and was having trouble.  I think I got it figured out now, so I'll keep this one open and make updates to it as required.
> Document ability to add custom filesystems

- bus.md
- events.md
- extending.md
- facades.md
- filesystem.md
- packages.md
- queues.md
- releases.md
- testing.md
Updated all instances of the 5.0 docs to reflect the new name of the Laravel container.
> Updated all instances of IoC container

- upgrade.md
> Fix Laravel Collective link

- homestead.md
Seems silly but I was putting in my Client ID & Token as I was thinking my App was the client and not the server credentials.
> Very small change for backfire setting in Homestead file.

- authentication.md
> Added Social Authentication Provider Method

- homestead.md
> Update Envoy URI.

- cache.md
> [5.0] cache events

- contributing.md
fix version 4.2 -> 5.0 on contributing.md
> fix version 4.2 -> 5.0 on contributing.md

- installation.md
4.1 and 4.0 probably need updated as well
> Version number needs to come before --prefer-dist otherwise v5 is installed

- homestead.md
This is a small change to clarify the install options.
> Improve installation docs

- billing.md
Changed from:
$user->subscription->decrement();
to:
$user->subscription()->decrement();
> Adding missing ()'s to line 126

- envoy.md
Just a quick link to the Github repo if people want to check out the code for Envoy.
> Add link to Envoy Github repository

- eloquent.md
hasManyThrough second arguments missing namespace
> Need namespace

- validation.md
When you are using the built in validator.
> Explaining how to set a custom DB connection

- billing.md
This is corresponding doc changes for PR https://github.com/laravel/cashier/pull/150 (if that PR is accepted).
> [Proposal] Update Billing for Stripe

- upgrade.md
> upgrade.md bootstrap/cache typo

- billing.md
The word "method" isn't better in this context ? I'm not native english speaker, the word "command" in this context not sounds strange?
> Better word in this context.

- packages.md
Signed-off-by: crynobone <crynobone@gmail.com>
> Use database_path(), available since v5.0.22

- views.md
using the `view('app.view', $data)` format.
> Clarification on accessing data inside a view when passing an array..

- queries.md
Adding the missing docs on this awesome, unique feature.
> Adding document on dynamic where clauses

- routing.md
I'm still learning ... but assume nested route::group corresponds to nested namespace.
> Add additional "\User" level to namespace example

- templates.md
I had to look up outside the official docs what may be a common need.
> Add compact @section() syntax example

- schema.md
For https://github.com/laravel/framework/pull/8286
> Jsonb in schema.md

- eloquent.md
Adjusted to include 'plural' when table name isn't specified.
> Update eloquent.md when not specifying table name

- billing.md
The User model example found in the Model Setup section extended Eloquent. I've updated it to instead extend Model.
> Updated User class in Model Setup to extend Model

- schema.md
Add a note showing `doctrine/dbal` is required when changing columns
> Column changing requires doctrine/dbal

- contributions.md
Guessing on the changes made in laravel & framework, you also want this changed?
> Change email

- templates.md
As requested in https://github.com/laravel/framework/pull/8425.
> Documentation on Blade's directive() helper

- cache.md
File cache store supports increment and decrement methods.
https://github.com/laravel/framework/blob/5.0/src/Illuminate/Cache/FileStore.php#L124-L152
> Update cache.md because file supports increment and decrement

- routing.md
*Fixes issue laravel/framework#8579*
> Fix multiple middleware code example

- mail.md
SES Maildriver was added to config/mail.php. Here I'm adding documentation on how to set it up.
> Added SES mail driver

- upgrade.md
Reference: laravel/framework#8569
> Upgrade guide for model@create

- homestead.md
Just tried to setup an instance for the first time on Windows and came across this missing information.
> Added information on the provider for VMware Workstation (Windows)

- requests.md
Copy the `Request::ajax()` section as is from 4.2 docs.
> Add Request::ajax() to requests.md

- testing.md
I believe this represents the updated syntax.
> New $factory->define() syntax

- validation.md
> [5.0] Fix string validation rule syntax example

- pagination.md
Added: firstItem & lastItem.
This is important information as subtitution of getFrom and getTo.
> Add additional information according to Paginator Contract

- queues.md
As per laravel/framework@6df16d3d032128af9ee945f55f21e6fcf7902d20
> Update version for IronMQ driver

- collections.md
Showing unique ways to use the callbacks; things that can't be accomplished by simply passing a key.
> Better collection callback examples

- requests.md
"store" and "update" method have the same php doc
> Little fix on PHP doc

- upgrade.md
> Note upgrade for find method

- controllers.md
> Fix PHP Doc

- views.md
> $data['$key'] to $data['key']

- middleware.md
Add missing @param phpdoc at middleware parameter
> Add missing @param phpdoc

- eloquent-mutators.md
Hey! Little typo here? You're doing great with the Laravel docs, go on!
> Typo in User model

- blade.md
Since the auth login example view is using @endsection for @section.
> Change @stop to @endsection

- validation.md
> Unique requires table name

- scheduling.md
I started Laravel when 5.0 was released. This tripped me up, so this note will help others who are playing with scheduling for the first time.
> Note on task output and the call method

- eloquent-mutators.md
> Add Extends Model

- mail.md
add missing use statement for User class
> Add missing use App\User

- routing.md
Fix hyperlink to middleware section
> Fix hyperlink

- migrations.md
The link cannot be clicked since the name is different.
Please view the change, it should be clickable now :smiley:
> Update Foreign key constraint hyperlink

- eloquent.md
Remove the full namespace since there is already a use App\Flight statement. 
(As seen on '#Retrieving Multiple Models' section)
> Update object namespace

- helpers.md
last() should return the last element and not the first one.
> last function returns last element

- collections.md
Mby will be helpful to somebody
> closure can be passed into 'last' method, as in 'first' method

- migrations.md
> Fixed typo

- events.md
1. Broken link on defining event listener
2. Misplaced event helper
> Fix broken link and misplaced event helper

- encryption.md
Hi Taylor,
not sure if you refer to the same cipher as [here](https://github.com/laravel/laravel/commit/bacda07552d298c2b40fa378b616a504d1f3dd33). Then I think you should merge this commit.
Maybe one could change the upgrade instructions to cover the changed cipher in the app config part as well? Because I ran into this issue, while upgrading.
> Fix for correct encryption cipher

- requests.md
Link is not broken, but in context of Blade and it has its own page.
> Fix blade link

- helpers.md
- installation.md
config() was missing from helpers page; added it
> Add config() to helpers page

- installation.md
Fixes a previous PR I created for this issue which had merge conflicts.
> Add information about app environment name setting

- middleware.md
Use the class constant syntax as in the code of Laravel 5.1
> Update class references

- migrations.md
This is to accompany this pull request: https://github.com/laravel/framework/pull/9283
> Add description for `first()` modifier

- queues.md
Since $user is defined as class member rather than the function local variable
> Use $this to access class member

- eloquent-relationships.md
Added section about "Associating" and "Dissociating" Belongs To Relationships.
> Added section to Eloquent Relationships

- pagination.md
The text preceding the appends() method wasn't consistent with what was in the code sample.
Signed-off-by: Jesse Schutt <jesse.schutt@zaengle.com>
> Updated appends() description to match code sample

- scheduling.md
Docs updated for https://github.com/laravel/framework/pull/9353
> Add pre-task hook docs

- responses.md
> Add more specific section link

- session.md
Since the current link already points to the same page
> Fix facade link

- redis.md
Documenting this pull request https://github.com/laravel/framework/pull/7970
> Predis client options

- helpers.md
add array_sort_recursive() helper to documentation
> add array_sort_recursive() helper to documentation

- eloquent-relationships.md
Making it consistent with the rest of the docs.
> missing App\ namespace.

- helpers.md
I have added some missing global helper functions for routing and miscellaneous. :)
> Added missing global helper functions

- authentication.md
Explained how and where to set the $loginPath path variable if you
don’t want to use the standard redirect URI.
> Added loginPath note for custom authentication.

- errors.md
Added the emergency level to the docs and ordered in in the same way as in RFC 5424. (See [9518](https://github.com/laravel/framework/issues/9518))
> Added emergency level to docs

- redis.md
Fix artisan command link on redis page.
> Fix artisan link

- cache.md
Moreover the add() function is part of the documentation , but its not available in the contract and it's only implemented in MemcachedStore
> Added getPrefix function to be implemented.

- testing.md
The real code and the documentation have slight difference.
> Fixed example to be like the code

- testing.md
Added type requirement of the parameter like it is in the code
> Added type requirement

- eloquent-relationships.md
changed the text from "access the User the owns the phone" to "access the User that owns the phone"
> text correction

- redis.md
This is just a minor thing but still might confuse some people.
> Include key in Redis::command

- eloquent.md
Instead, point to relevant section within "migrations"
> Fix links to non-existent "schema" page

- authentication.md
Also added spacing for the github credentials to be consistent with the framework provided code.
> Removed opening <?php for consistency

- authentication.md
Also removed misc bootstrap markup for consistency.
> Add missing form labels

- scheduling.md
Update to mirror laravel's current codebase.
> Update scheduling.md - Add class resolution syntax

- authentication.md
Depends on laravel/socialite#96 being accepted.
> Add documentation for custom parameters feature

- authentication.md
- elixir.md
- eloquent-relationships.md
- queues.md
- upgrade.md
* Added a couple articles where needed.
* Made all occurrances of "ECMAScript" consistent inside `elixir.md`.
* Fill in a few missing words.
> Fix minor typos

- blade.md
The `@each` directive in blade is amazing and has needed documentation for a long time.
> Documentation for each

- eloquent-mutators.md
Inform default timestamp format
> Inform default timestamp format

- providers.md
Added the ::class annotation for consistency with `config/app.php`
> added ::class annotation for consistency

- scheduling.md
Added note regarding https://github.com/laravel/framework/commit/0371ed3c716229a6992a73f83b0579db54185620
> Small note about when() - quick grammar fix

- facades.md
> Added the gate facade

- elixir.md
> Fix filename to match elixir v3

- testing.md
Note on new make:test command from: https://github.com/laravel/framework/commit/79b6bfc4f5bc7ab40649c7df4de30a78771b717b
> Docs on the new make:test command

- authorization.md
In my opinion the documentation is leaving out the boot method here...
> This doesn't work without explicitly defining boot

- helpers.md
See: https://github.com/laravel/framework/commit/4ea1b5abe2ed9b921d1b552e07f4115b8b7d12e5
> Add global `request` helper

- elixir.md
In order to be more clear about issues with Windows host systems, the
documentation for elixir was updated with regards to that.
> Precised Windows problem with elixir

- helpers.md
Fixed subject/verb agreement typo.
> Docs for with() method

- helpers.md
Please let me know if this will be fine now.
> Session helper added to docs

- helpers.md
Ah, just noticed #1820. If you take it ping me, I'll update my PR.
> Helpers: add collect(), fixes

- authentication.md
I had to spend a long time Googling to find this information, figured it'd be more helpful if it was in the docs.
> Show how to handle errors on password resets

- migrations.md
https://github.com/laravel/framework/issues/2979
> Added note about exception when using SQLite

- testing.md
In response to https://github.com/laravel/framework/pull/10662
Trying to save time for other developers.
> DatabaseTransactions only affect the first database connection

- authorization.md
https://github.com/laravel/framework/pull/10535
> Authorization after callbacks

- validation.md
https://github.com/laravel/framework/pull/10670
> Validation `exists` docs update

- eloquent-collections.md
https://github.com/laravel/framework/pull/10627
> Eloquent collection docs update

- routing.md
See [this issue](https://github.com/laravel/framework/issues/10672)
> Alternative route alias definition

- artisan.md
You need to dig into the actual class to find this.
> Document line() method for console commands

- filesystem.md
Moving a file doesn't explicitly mean renaming it. Since move method is alias for rename, I think it should be said. And searching for rename should find something on page.
> Update filesystem.md - add rename

- quickstart-intermediate.md
In auth section 
changed file "registration" to "register"  to be consistent with the github example, and with the prior sentence.
> Changed file name in docs

- controllers.md
Just make this a bit more prominent, as "exclusively using controller based route" doesn't always sink in at first.
> More explicit note about closure routing and route caching

- validation.md
See https://github.com/laravel/framework/pull/10766
> Add required_unless documentation

- eloquent.md
Update docs on using `orWhere` method on soft deleted models. Issue [#1945](https://github.com/laravel/framework/issues/1945)
> Update docs on using orWhere method on soft deleted models issue #1945

- quickstart-intermediate.md
Small changes to match the tutorial with other docs.
> Changes to tutorial to match official docs

- events.md
Mentioning e.g. custom names and wildcards.
---
For some time I wasn't aware about the awesome flexibility of the event system due me only going by the docs.
Mentioning these features helps people easier grasp the richness IMHO.
> Add section about advanced event usages

- quickstart-intermediate.md
Change @yield('contents') to @yield('content')
> Fix small typo

- routing.md
Use escaped echo as changed by [PR](https://github.com/laravel/framework/pull/9440)
> Update field helpers echo

- contributions.md
> PHP-CS-Fixer

- collections.md
Documentation for https://github.com/laravel/framework/pull/10811
> Document prepend with key

- filesystem.md
The exists method does not exist in flysystem, the method to determine if a file exists in a filesystem is has.
> Rename exists to has.

- artisan.md
- authentication.md
- cache.md
- events.md
- mail.md
- views.md
Also updated several components to indicate what events they fire.
> Added a list of built-in events

- collections.md
Follow-up to https://github.com/laravel/framework/pull/10854.
> Collection: document except() and only() methods

- homestead.md
Added Git, Xdebug, Sqlite3, and Composer in the respective sections ordered by my impression of how likely they would to be used, or character length. 
It may be worth noting them for newcomers to servers and their management.
> Updating homestead's preinstalled software

- installation.md
Increment the version of `laravel/installer` to version `1.2`.
> Increment version of laravel/installer

- eloquent-relationships.md
$comment will change dynamically, there is no need to assign the result of save method.
> Remove unneeded assignment

- quickstart-intermediate.md
Trying to access the id) attribute instead id.
> Typing error

- quickstart-intermediate.md
> Revert "Typing error"

- structure.md
> Replaced filters with middleware

- authentication.md
- quickstart-intermediate.md
Added link and entry in the menu for Introduction -> Database Considerations.
Removed space from menu for better alignment.
Heading level chagned (h2 -> h3) for Manually Authenticating Users -> Remembering Users.
> Format improvements

- scheduling.md
Seems like you need six stars for the cron method to work. Hoping this makes it more clear for other users.
> Added an extra * on line 78.

- eloquent-mutators.md
Does not seem to be chosen intentionally thus it would be better to amend this for clarity sake
> disabled_at should be deleted_at

- eloquent.md
> [5.2] Remove where clause caveats

- events.md
change connection.{name}.beginTransaction to connection.{name}.beganTransaction
> fix connection event

- validation.md
Super serious stuff, here. Took me a while.
> Fix minor typo in example

- eloquent.md
Related: laravel/framework#11548
> Update eloquent.md to mention $incrementing property

- upgrade.md
This is breaking change and should be in upgrade guide.
> Added primary keys casting to upgrade guide

- authentication.md
> Guard specification.

- validation.md
> [5.2] Adjust Validation docs to clarify view $errors

- homestead.md
Blackfire removed from Included Software
> Blackfire removed from Included Software

- upgrade.md
> Pluralize word

- upgrade.md
I'm not sure whether the note is necessary or not actually :-/
> Session compatibility warning. Referencing laravel/framework#11663

- installation.md
Minimum PHP version for L5.0-2 is 5.5.9
> Minimum PHP Version

- scheduling.md
References https://github.com/laravel/framework/issues/11688
> [5.2] Add quarterly scheduling

- filesystem.md
The documentation referenced the method 'has' which does not exists.
> Fix 'exists' method name

- testing.md
It's an obviously named method - but might as well document it :-)
> Add a mention of the 'uncheck' form test method

- facades.md
Some of the facades mentioned in the docs has been removed from the framework.
> Remove legacy facades

- authentication.md
Referencing laravel/framework#11700
> Guard & Broker customizations on ResetsPasswords trait. Referencing laravel/framework#11700

- quickstart-intermediate.md
- quickstart.md
> unescape html + https

- testing.md
> Add asterisk notation to seeJsonStructure documentation

- collections.md
As a part of: https://github.com/laravel/framework/pull/12017
> [5.2] whereIn() and whereInLoose() methods

- installation.md
There was no single reference to this command belonging to Artisan. I'm sure it is clear for developers that are fluent in Laravel, but then again those don't really need help from these docs. This is for the starters, it should be as clear as possible.
> Use the full artisan command.

- authentication.md
Goes along with laravel/framework#12036
> adding the lockout event to the examples

- contributions.md
Per "going off-topic" discussions:
* https://github.com/laravel/framework/pull/12046#issuecomment-180022125
* https://github.com/laravel/framework/pull/12173#issuecomment-180297611
If I recall correctly, these notes were written before LTS releases appeared.
> Clarify where bug fixes should be sent

- quickstart.md
Update 'remove' button code sample to match source in git repo (https://github.com/laravel/quickstart-basic/blob/master/resources/views/tasks.blade.php#L65)
Changed to HTML comments to be consistent with other comments such as ""
> Update code samples of beginner task list

- quickstart-intermediate.md
The tutorial does not mention anything about making sure to fix AuthController to redirect to the '/tasks' endpoint after successful login/registration.
Additionally this change includes the same code sample changes as in previous pull request:
https://github.com/laravel/docs/pull/2129
> Add note about AuthController redirect

- testing.md
Related to https://github.com/laravel/framework/pull/12231
> Add Factory Models relationships definition

- eloquent-relationships.md
This PR adds documentation about the polymorphic relationship morph map
> Add docs for morph map

- responses.md
Added explanation of how to use the file responses, with example code.
> Add documentation for File Responses.

- validation.md
Add an example of using rules with fields on nested arrays.
> Update docs on array validation

- controllers.md
Adding information for the new resource route parameter naming ability.
> [5.2] Controllers - Add resource parameter overrides

- validation.md
Added documentation reference to the new `present` validation rule as well as the `filled` validation rule.
> Add documentation for "present" and "filled" validation rules

- database.md
> Database - stdClass instead of StdClass

- validation.md
Documenting the distinct validation rule.
> Document the distinct validation rule

- blade.md
Added a note about cached views not updating, when directives change.
> Added NOTE at the very bottom of the file

- templates.md
> [4.2] Escape @parent

- homestead.md
Updated note on VT-x, to include information on Hyper-V and it's interference with VT-x on windows-platform systems. https://social.technet.microsoft.com/Forums/windows/en-US/118561b9-7155-46e3-a874-6a38b35c67fd/hyperv-disables-vtx-for-other-hypervisors?forum=w8itprogeneral
> Note on Hyper-V & VT-x

- homestead.md
Hi Taylor, I added this new entry to the docs because I had a hard time figuring it out. Hope it helps everybody.
> Added NETWORKS homestead configuration to the docs. (5.2)

- homestead.md
Add to the list of included software.
> Add MariaDB to software list

- queues.md
Addresses small issues in the [Document the Queue::before](https://github.com/laravel/docs/commit/2ed0909076c159034fe773a0e1012583cc151e5a) method PR.
> Grammar corrections

- migrations.md
Add the word "be" to say "...you will be prompted..."
> Fix minor grammatical error

- localization.md
Information for [#12681](https://github.com/laravel/framework/pull/12681).
> Add isLocale method information

- eloquent.md
Related to https://github.com/laravel/framework/pull/12067
> explain further the default behavior for primary keys on models

- queries.md
Added JSON support note in query builders.
This commit adds a new section with instructions for retrieving JSON values from the database.
> Added JSON support note in query builders

- collections.md
I added the documentation for Collection::combine() which is a new function that has been added to the laravel framework.
i also added the documentation for Collection::flatMap() which already exists in the current version of laravel.
> [5.2] Added Documentation for Collection::combine() and Collection::flatMap()

- queries.md
Documentation for laravel/framework#12878
> Document the when() method in the query builder

- contributions.md
> Updated the contribution guide

- upgrade.md
As requested in https://github.com/laravel/framework/pull/12918
> [5.3] Document changes in scope behavior

- queries.md
Documentation for https://github.com/laravel/framework/commit/99bc4c39f73135b3551b23a5bf4bf6ac285fce09
> Document crossJoin method

- quickstart-intermediate.md
remove option to create a view only.
> fix make auth command

- localization.md
> Fixed a wording in Localization's page

- packages.md
> Fix wording

- database.md
So that it matches with other example, plus to follow PSR-2.
> Fix coding style (in code block)

- migrations.md
Added comment function to the column modifiers list.
> Added 'comment' in Column Modifier section

- validation.md
Add documentation for the `mimetypes` validator:
https://github.com/laravel/framework/blob/a675623d68442ceb0730b456d01dc5388b891e1e/tests/Validation/ValidationValidatorTest.php#L1651-L1664
> Update documentation to include mimetypes

- migrations.md
Documentation for Framework merged PR [#13333](https://github.com/laravel/framework/pull/13333)
> Enable or disable foreign key constraints.

- homestead.md
One of my students was a little thrown off when setting up homestead - thought this change would help clarify for future users.
Cheers
> Further explanation on when user will be able to access Homestead box

- eloquent-relationships.md
Explanation of fifth argument in hasManyThrough method is missing at docs
> Add explanation of fifth argument in hasManyThrough method

- homestead.md
It no longer changes your current working directory when using it.
Also it solves issue mentioned in this PR: https://github.com/laravel/docs/pull/2299
> Improved homestead function for daily usage

- upgrade.md
I documented some minor breaking changes.
Original PR: https://github.com/laravel/framework/pull/13576
> [5.3] Document join clause changes

- collections.md
I was going trough the collection class and I noticed this method (that I needed at that point). It was missing from the collection's documentation page.
> Added diffKeys collection method documentation

- controllers.md
- localization.md
* Adds hint for resource controller methods in HTML forms
* Adds hint for @lang Blade shorthand in localization docs
> Smaller improvements

- quickstart-intermediate.md
Just a quick fix that I noticed.
> Fix HTML comment

- errors.md
There is no mention in the documentation of the fix from this commit: https://github.com/laravel/framework/commit/50a3a3a9c759a3f4bf65a942ccaff76b499e238b
> On setting number of daily log files allowed.

- collections.md
This is a more practical example than [this](https://github.com/laravel/docs/pull/2330), though the wording can be improved.
> Add flatten depth example

- eloquent-serialization.md
The documentation currently only covers temporarily exposing hidden properties and not hiding visible properties.
> Added Temporarily Hiding Visible Properties

- eloquent-relationships.md
Adjust `{relation}-count` to `{relation}_count`
> [5.2] Adjust eloquent-relationships

- validation.md
Another two empty lines to comply to CodeMark specs
> Empty lines also needed here

- queries.md
DOCS for  Framework PR [#13983](https://github.com/laravel/framework/pull/13983)
> DOCS for whereDate, whereMonth, whereDay & whereYear

- blade.md
Added sentence about `key` variable.
> [5.2] Update blade docs @each

- helpers.md
This function does exists. But not in the documentation..
> Add resource_path function

- homestead.md
Latest version of Homestead is coming with Ubuntu 16.04.
> Update Ubuntu Version

- helpers.md
fix link to resource-path method on helpers page
> fix broken link in helpers.md

- validation.md
Add not empty text to all required field variations
> Required field not emply

- billing.md
Add update credit card function
Add view pending invoices function
Add cancel subscription immediately function
> Add missing functions to billing documentation for Laravel Cashier

- elixir.md
@see https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md
> Updates gulp's npm global installation command

- migrations.md
same correction for v5.2 and mater branch
> correct command description

- upgrade.md
See https://github.com/laravel/framework/pull/14477 for the PR itself.
> Add guide for removal of morph class

- database-testing.md
Fixed indentation in code examples at two spots in database-testing.md.
> Fixed indentation

- container.md
Remove old reference to mailer and replace it with UserRepository
> Remove old reference to mailer and replace it with UserRepository

- authentication.md
updated line 73 PasswordResetController to ResetPasswordController so correlate with the changes made to the controller naming and the rest of the document
> [5.3] replace old controller name

- authorization.md
New pull-request following #2457.
> [5.3] Add documentation for the Blade directive @cannot

- testing.md
> [5.0] Move test seeding text below heading

- blade.md
Update docs regarding Laravel/Framework#14706
> [5.3] Add $loop->iteration doc

- upgrade.md
> Fixing minor typo in upgrade.md

- notifications.md
Was doing a demo app, copy and pasted the code and noticed this.
> [5.3] Missing Semicolon

- upgrade.md
> spelling fixes to upgrade.md

- eloquent.md
Initial attempt at adding observer documentation for Eloquent models.
> Add observer docs for eloquent

- upgrade.md
Also in where method has changed order of parameters
> Arr class doesn't have contains method

- errors.md
Updated to $exception instead of $e to match the code
> Update Exception variable

- pagination.md
> Pagination - Fix typo

- upgrade.md
The directory should be in plural form.
> Minor issue with exception path

- passwords.md
How to change the default notification
> Password Reset Email Customization

- migrations.md
See https://github.com/laravel/framework/commit/52f2381020d70256afdd35143161b4090a45fe54
Inspired by @gabidavila's talk at Laracon EU!
> Add docs for generated columns in migrations

- installation.md
This chapter missed the most critical info about how to get up and run the newly created project quickly and easily, this breaks the entire flow of the learning process. The sections and chapters followed are all not mentioning a quick and easy way about how to set up this thing besides the complex Homestand and Valet. How can we not added this already? 
Come on, get the developers excited by adding this to the doc.
> Add the missing critical info about how to set up the server

- helpers.md
> Add array_prepend to list of available methods

- application-testing.md
Fix link for model factories
See: https://github.com/laravel/framework/issues/15273
> Fix link for model factories

- scheduling.md
Add examples and some additional details for [this feature](https://github.com/laravel/framework/pull/15216)
> [5.3] Include documentation for between and unlessBetween

- validation.md
I don't know if need to add this increment in other docs versions, please let me know and I will do it.
> Added Soft Deletes instructions into unique validation rule

- billing.md
If config is cached, then env doesn't work correctly
> Use braintree configuration from config not env

- broadcasting.md
Document how additional Pusher parameters can be passed, such as the cluster or force SSL.
> Document additional Pusher parameters for Echo

- events.md
> Add missing part manually-registering-events

- validation.md
> Add section for validation attributes

- collections.md
> Added missing collection method

- upgrade.md
This PR replaces the description of what should happen when utilizing the database queue driver with actual code that can be utilized in a migration.
> Added migration for queue database driver changes

- migrations.md
Added some available column types.
> Updated "Available Column Types"

- queues.md
Adds a note per an issue on the framework repository.
https://github.com/laravel/framework/issues/15235#issuecomment-245278313
> Added a note about binary data

- passport.md
Update Passport documents in line with Vue Resource update, reference
[pull request](https://github.com/laravel/laravel/pull/3957)
> Update Passport documents in line with Vue Resource update.

- views.md
> Add missing .blade extention

- upgrade.md
Docs refer to BC added in https://github.com/laravel/framework/pull/15757
First time contributing to docs, let me know if they need rework!
> Policy backward compatibility changes

- helpers.md
Just re-discovered this info function by looking at Taylor's Laracon Keynote. I had forgotten about it and realized it wasn't in the docs. Same thing for logger.
Xavier
> Add logger and info helpers functions documentation

- frontend.md
> Update link to single file component documentation

- upgrade.md
Improve the documentation by informing that the pluck method is also affected because of this change.
> Update docs: pluck method affected too

- authentication.md
Added a reference to `artisan migrate` in order do be really up and running after the quick tip
> Improvement of the quick tip

- broadcasting.md
Mention that you can specify your own name for events you're broadcasting.
> Broadcasting update

- artisan.md
It should be "Don't worry if this directory does not exist ...".
> Remove the unnecessary "you" from the sentence.

- scheduling.md
Addresses #2745 (but not the question in that issue)
> Add line on scheduling and maintenance mode (addresses #2745)

- upgrade.md
The has method do not longer provide a default parameter. Use any instead!
See also #2742
> add MessageBag method changes to upgrade guide

- eloquent.md
I'd like to have this in the docs just because I can never remember whether it's updateOrCreate or updateOrNew.
> Document the existence of updateOrCreate and provide an example

- validation.md
Update the docs in accordance with changes made to the validator, as outlined in #2705
> Update active_url validation docs

- frontend.md
> removing.html from frontend.md

- database-testing.md
This is what the current version of Laravel ships.
> Update factory code on database testing page

- filesystem.md
Beautiful software deserves nigh errorless documentation.
> Missing infinitive

- facades.md
> Replace empty cells in facade reference with nbsp

- queries.md
These methods are so useful, they should get a mention in the docs.
> show how to use latest() and oldest() on QueryBuilder

- blade.md
Add documentation for the `@includeif` directive.
> Add @includeIf documentation

- blade.md
- cache.md
- elixir.md
- eloquent-relationships.md
- eloquent.md
- errors.md
- filesystem.md
- helpers.md
- homestead.md
- queries.md
- redis.md
- routing.md
- seeding.md
- session.md
- upgrade.md
- validation.md
PSR-2 fixes and consistent use of spaces instead of tabs.
> Style fixes and PSR-2

- routing.md
> Adding regular expression constraints back

- upgrade.md
Otherwise, you'll copy the wrong file and will break your site during the upgrade.
> Reference 5.1 branch instead of master

- packages.md
as per: https://github.com/laravel/framework/pull/16483
> Routing example updated.

- queues.md
Moving up in the doc per #2856
> Add note about regular/delayed job behavior when using sync

- filesystem.md
- requests.md
Resubmit of #2863 with requested change.
> [5.4] Automatic filename generation now uses a different method

- filesystem.md
- requests.md
http://www.englishpage.com/articles/a-vs-an.htm
> grammar fix

- authorization.md
clarify what happens when policy filter (before()) returns true, false,
null
> Add tip for policy filters

- homestead.md
Small clarification for Windows users installation
> Fix Windows installation

- homestead.md
> Typo homestead.md

- homestead.md
* :books: Add mention of parallels provider since we also support Parallels
> :books: Add mention of parallels provider since we also support Parallels

- broadcasting.md
In Driver Prerequisites section, making more explicit which file to edit and where to find it for broadcasting via Pusher.
> Noting file to edit for Pusher events in broadcasting.md

- queues.md
This reverts commit 1ebb80b60dbf603e8465b49b7ce39a6ac1b27fd9.
> [5.3] Revert "Remove outdated "Resource Considerations" section"

- valet.md
Read Adam's comment here: https://github.com/laravel/valet/pull/156#issuecomment-249368630
> Add a note about share not supporting secure sites

- authentication.md
[Related to PR](https://github.com/laravel/framework/pull/16896)
> [5.3] Add auth redirectTo method

- eloquent.md
The fill method is missing from the docs, but it is actually there and works.
> Add mention of fill method in mass assignment

- queries.md
Based on upgrade guide, `pluck` returns Collections now.
> [5.3] Query Builder pluck returns Collections now

- installation.md
Added configuration for pretty urls!
> Update installation.md - Added pretty urls

- upgrade.md
Added the application name to the upgrade guide to 5.2.0 from 5.3.0
> Application name

- scheduling.md
Add `hourlyAt()` for https://github.com/laravel/framework/pull/17168
> Update scheduling.md to include hourlyAt()

- configuration.md
Added warning from "Upgrade Guide > Configuration > Caching And Env" to "Configuration > Configuration Caching".
> Added "Caching And Env" warning to "Configuration" page

- pagination.md
> Added note about passing data to paginator view

- elixir.md
Here's my first pass through the Elixir docs, to get them updated for Laravel Mix.
🕺🏻
> Updates for Laravel Mix

- upgrade.md
https://twitter.com/taylorotwell/status/822162757583798273
> Change develop link to point to master

- dusk.md
Don't know whether this should be targeting 5.4 or master, as it affects both
> Fix PHPDoc order

- upgrade.md
Upgrade docs for the change in laravel/framework#17493
> [5.4] Document the change to the factory amount

- mix.md
> Fix for Plain CSS Code Snippet

- releases.md
- upgrade.md
- Couple episode numbers didn't line up.
- Added a new link to the video on mapping Eloquent events to event classes.
> Fix video links and add new one

- upgrade.md
He's making the mention of the class, but he's not declaring it.
> add use Illuminate\Contracts\Console\Kernel;

- upgrade.md
route cache must be cleared after upgrading.
> updated upgrade.md

- upgrade.md
encourage users to check the Github comparision between 5.3 and master to find more obscure updates.  they can choose to update these changes as needed/wanted.
> miscellaneous notes

- collections.md
> Fix typo on Collection docs

- notifications.md
I've started to use the notifications feature, swapping existing `Mail::` calls and I wasn't sure how to use my custom email views, turns out to be simple but couldn't see any mention of it on the docs - had to go through the class to see how it works, this lil info may help others too 😄
> Add view() usage information to notifications

- filesystem.md
> Fix typo in Filesystem doc

- http-tests.md
I find it a bit hard to explain the difference between `assertJson` and `assertJsonFragment` in terms of wording :)
> Document assertJsonFragment

- upgrade.md
use BrowserKitTestCase instead of BrowserKitTest because PHPUnit thinks use BrowserKitTest is a test class.
> use BrowserKitTestCase instead of BrowserKitTest

- upgrade.md
https://github.com/laravel/framework/pull/17003#commitcomment-20714814
> Remove compiled.php to upgrade guide

- dusk.md
> Fix method name in dusk.md

- upgrade.md
composer.json has been updated a week ago;
https://github.com/laravel/laravel/commit/926f53bcc0c879b8580e55239453902a78914afa
> [5.4] Change PHPUnit to 5.7 in upgrade guide

- upgrade.md
The whereLoose method was removed from the collection class this might cause a breaking change.
> Breaking Change! The whereLoose method was removed

- dusk.md
Add docs for radio selection assertions
re: https://github.com/laravel/dusk/pull/138
> Updated dusk.md

- homestead.md
> Removes PM2 from homestead docs

- mix.md
> Extend Mix docs

- homestead.md
Minor fix: singular/plural typo in homestead docs.
> Fix typo in Homestead doc

- blade.md
> Replace htmlentities with htmlspecialchars

- homestead.md
Contains updates for Homestead 5.0.0 / Settler 2.0.0 release scheduled for March 1st (next Wednesday)
> ✨ 📚 Add JSON Config info, share() docs, notes about using stable versions

- dusk.md
> Replace "login" with "log in"

- collections.md
Documents the methods added by laravel/framework#18157.
> Document Collection::whereNotIn()

- eloquent.md
Related: https://github.com/laravel/framework/commit/3dbe12f16f470e3bca868576d517d57876bc50af
> [master] Update eloquent.md

- structure.md
Add `channels.php` to `routes` directory.
> Update structure 

- dusk.md
Thanks for adding these new methods! Thought I would submit some documentation on these methods too.
> Add new drag methods to documentation

- helpers.md
Was this method not documented so it will not break the 6 methods per column on 3 columns?
> Added kebab_case() to the string helpers

- eloquent-relationships.md
The pivot model must extend the the relations/pivot class
> changes for custom pivot table model

- upgrade.md
Changed "If you will still like to customize" to "If you would still like to customize"
> Fixed typo in upgrade doc

- notifications.md
> Fixes syntax error

- eloquent-relationships.md
The master branch has updated the docs, making the same changes in 5.4
https://github.com/laravel/docs/blob/master/eloquent-relationships.md#many-to-many
> Corrected wrong example code in sync with master branch

- collections.md
Documents the feature added by laravel/framework#14661
Also updates the Collection::unique() documentation to outline its behavior and where they differ.
> [5.4] Document Collection::uniqueStrict() method

- collections.md
Documents the features added by laravel/framework#14305
I also changed the Collection::avg() documentation with the same code snippet to better demonstrate where they differ since they all are related. Since they can be confusing to understand, I also added reference links to Wikipedia to each one.
> [5.4] Document Collection::median() and Collection::mode() methods

- collections.md
Documents the feature added by laravel/framework#16797
> [5.4] Document Collection::isNotEmpty() method

- authentication.md
Update use statement to match [actual code](https://github.com/laravel/laravel/blob/master/app/Providers/AuthServiceProvider.php#L6)
> Update use statement

- scheduling.md
I feel like the '/path/to/artisan' is a bit confusing a better use of words would be 'path-to-your-project'.
I also found out there are some more people thinking like me:
https://laracasts.com/discuss/channels/laravel/pathtoartisan-where-it-is?page=1
> Update scheduling.md file

- collections.md
Documents the new features added by laravel/framework#18457 and laravel/framework#18529 now that Laravel 5.4.17 was released
> [5.4] Document Collection::times() method and flatMap shortcut

- mail.md
This PR aims to add documentation for the callback functionality that exists on Mailable objects.
> Document the Mailable callbacks functionality

- routing.md
Since Laravel is the most friendly framework with great docs, it attracts a lot of PHP beginners like me & is the first introduction to the MVC pattern. The change committed in this PR is what I had to google to find out (which has been very rare in my laravel adventure) so thought it would save some time for other people as well. 
Also, I cannot find docs about making the most out of it, for eg: API based auth, etc. So if fellow contributors want it I can write it down as a PR. Thoughts?
> Documented accessing routes

- passport.md
> Since the keys are not in Git I had to do this to deploy

- mix.md
See [this PR](https://github.com/JeffreyWay/laravel-mix/pull/464).
> Show how to use Mix with environment variables

- authentication.md
- update authentication document to maintain consistence reading with other part of the document
> update authentication doc

- homestead.md
Documents Homestead site parameters features added https://github.com/laravel/homestead/pull/563 and tweaked https://github.com/laravel/homestead/pull/567
> 📚 Add docs on Homestead Site Parameters functionality

- releases.md
As seen in https://laravel.com/docs/5.4/releases
If accepted, I'll find time to check the releases page backwards, it may contain errors in other versions too.
> Fix broken links

- upgrade.md
Following up on https://github.com/laravel/internals/issues/584
> Add setJoin breaking change to the upgrade guide

- mix.md
Continues #3316, missed that one
> Fix there an S after url() looked weird

- authorization.md
documentation for PR https://github.com/laravel/framework/pull/19124
please do not merge until laravel/framework version > 5.4.23 is tagged.
Thanks!
> add docs for new `resource` method

- collections.md
Replaced some spaces with tabs.
> Fix layout of intersectByKeys() code example

- helpers.md
> Update the description for the route helper 

- billing.md
There is no information on how to get the stripe token on the documentation. This describes it and links to stripe documentation for code sample.
> Added information about stripe token.

- helpers.md
HI @taylorotwell, I made this change to align my previous example with the rest of `route` examples.
> Update the description for the route helper #3347 - Improvement

- queues.md
Update doc with `Dispatchable` trait
> Fix issue #3356

- queues.md
https://github.com/laravel/framework/issues/19458#issuecomment-305752582
> Note for Cache for Queue

- helpers.md
Updated the Helpers Docs to include `str_after`.
> Added str_after helper

- valet.md
Slim also works perfectly with valet.
> Added Slim

- dusk.md
There is no documentation for assertRouteIs in the Dusk section
https://github.com/laravel/dusk/blob/master/src/Concerns/MakesAssertions.php#L91
> Add docs for assertRouteIs in Dusk

- mail.md
https://github.com/laravel/framework/issues/19046#issuecomment-301887677
> Note for $message variable

- collections.md
See: [#19628](https://github.com/laravel/framework/pull/19628)
> Add "avg" and "average" to higher order proxy.

- dusk.md
There are a whole bunch of issues created in Dusk repo with question "How to make fullscreen browser?", so I made a little note. 
Also maybe I should make some modifications in DuskTestCase.stub and add code snippet for this?
> Described way for using ChromeDriver options in Dusk

- validation.md
> Use any() method

- broadcasting.md
Add docs for https://github.com/laravel/framework/pull/18970
> Update broadcasting.md (#1)

- dusk.md
This was annoying to track down,
and should be included in the documentation.
> doc fully qualified class name

- eloquent-relationships.md
Adds documentation under "Inserting & Updating Related Models" for the `createMany` method.
> document the createMany method

- scout.md
I only appended the search section to mention the raw method, I wasn't sure if it deserved a subsection.
Please let me know if you prefer adding a new section (and a TOC entry) or if you think more details should be added.
The method was added in Scout 2.x and 3.x https://github.com/laravel/scout/pull/194
> [Scout] Add note about the `raw` method

- helpers.md
This PR only makes sense if https://github.com/laravel/framework/pull/19940 gets merged.
I am just getting this work done so it doesn't get forgotten. ^^
AS
> Adding the str_before helper to the docs

- scout.md
This method is very useful for Algolia's replica. I assume it is for other engines too, so I thought it would be nice to document it.
> [Scout] Add note about the within method

- installation.md
@JeffreyWay also owns this domain, and (according to him), it'll always point to the latest 'Laravel from scratch' series on Laracasts.com
> use laravelfromscratch.com

- packages.md
Routing is already explained under resources
> This section appears twice

- helpers.md
Add the `str_before()` helper to the documentation
> Add str_before() helper to documentation

- requests.md
Adds documentation to test for multiple inputs using the Request `has` method.
> Request::Has(array) to test for multiple inputs

- helpers.md
This method exists only for 5.5
> [5.4] Remove str_before

- passport.md
see https://github.com/laravel/passport/issues/101
> Added notice about `CheckClientCredentials`, fixed #3444

- collections.md
Hello,
i'm adding the method intersectKey to the documentation.
thanks.
> Adding intersectKey from Support\Collection to documentation

- homestead.md
Extra info on running different PHP versions on CLI...
> [5.4] Update homestead.md

- blade.md
- Updated the Blade docs to include the directives for switch statement [added in Laravel 5.5](https://github.com/laravel/framework/pull/19758)
> Updated docs for the switch statement blade directives

- dusk.md
Add missing documentation based on dusk v1.0.15 (which has not been released yet due to wrong version tagging? See https://github.com/laravel/dusk/issues/324
> Update assertions for dusk v1.0.15

- broadcasting.md
the master `BroadcastManager` uses the new namespaced Pusher code
> update to pusher v3

- upgrade.md
> Spell check

- upgrade.md
> Added info about changed trans() helper

- helpers.md
the modified examples , and the function illustration are from this link 
[https://medium.com/@taylorotwell/tap-tap-tap-1fc6fc1f93a6](url)
> [5.5] Add tap helper function documetation

- mocking.md
This PR adds examples of how you can assert a job was pushed n times or a mailable was sent n times. I messed up on the first PR so I closed it
> [5.5] Add documentation regarding QueueFake and MailFake

- upgrade.md
- `request()` helper changes
- Policy behavior changes.
> Document breaking changes

- frontend.md
The ```preset none``` command in the frontend docs was not correct. This PR fixes the command example provided.
> Fixed preset none command

- eloquent-relationships.md
Redoing https://github.com/laravel/docs/pull/3534
> Add loadMissing eager loading method

- valet.md
Feels like it should be listed.
> Added OctoberCMS

- errors.md
Add log_channel configuration to errors.md, fixup as needed.
> Add log_channel configuration to errors.md

- releases.md
Adding Laracasts "What's New in Laravel 5.5" video links to each section.
> Add Laracasts links to 5.5 release notes

- contributions.md
change next LTS version 5.1 to 5.5
> change next LTS version 5.1 to 5.5

- releases.md
> [5.5] Update releases.md - typo

- database.md
> PostgreSQL right name

- homestead.md
- queries.md
https://github.com/laravel/docs/pull/3565
> PostgreSQL

- eloquent-resources.md
Fixed an anchor link, should work now
> Fix anchor link

- horizon.md
- upgrade.md
I find a  url link to 5.4, then I change it to 5.5
> change the url from 5.4 to 5.5

- upgrade.md
As discussed on https://github.com/laravel/framework/issues/20834#issuecomment-326240882, let's detail things a bit more to avoid confusion. 😉
> [5.5] Clarify the Filesystem changes a bit more

- validation.md
Documenting this https://github.com/laravel/framework/pull/20646
> Adding date_equals

- dusk.md
https://github.com/laravel/docs/pull/3615
> Add missing cookie assertion

- database-testing.md
- helpers.md
- mocking.md
- testing.md
- Update docs to use RefreshDatabase trait
- Add optional helper method
> [5.5] Update docs and examples

- filesystem.md
Updating based on laravel/framework#21157
> Adding Rackspace to "File URLs" and "Temporary URLs"

- dusk.md
- http-tests.md
> [5.5] Update docs to use RefreshDatabase trait

- passport.md
the previous code was not returning the token but an error page with the string array
> fix for returning the access_token

- blade.md
- upgrade.md
> Fixing #3645, add information about post-autoload-dump event

- validation.md
Add missing return to the validation's where closure so that it can work in a real Laravel setup.
> Fix validation's where closure

- collections.md
- eloquent-collections.md
With ref to https://github.com/laravel/framework/pull/21342
> Added pad to collection methods

- http-tests.md
https://github.com/laravel/framework/blob/25e7896cae7e9745d99d542950d6cd00d0969e78/src/Illuminate/Foundation/Testing/TestResponse.php#L552
> Update method signature

- homestead.md
seems to be a little confusing for some people to setup Mailhog on Homestead, so this will clear things up.
> add notes on how to configure Mailhog

- collections.md
Documentation for the `Collection::wrap()` method introduced in laravel/framework#20055.
> [5.5] Document Collection::wrap() method

- migrations.md
Add documentation for Geo Spatial blueprint methods in the migrations section
> Geo Spatial blueprint methods

- facades.md
This PR adds a small section into *Facades* that shows real-time facade functionality.
Please let me know if you have any questions. Thanks!
> Add documentation on real-time facades

- dusk.md
Added `append` short note and an example.
> Add Dusk Documentation on `append`

- upgrade.md
[#21550](https://github.com/laravel/framework/issues/21550) [#20869](https://github.com/laravel/framework/issues/20869)
> BelongsToMany breaking change undocumented

- homestead.md
* Update checkout version (ugh)
* Update `.app` TLD to new default `.localhost`
* Mention port 4040 for ngrok UI
> 📚 Updating docs for Homestead v6.3.0

- database-testing.md
Unify model factory code with the one in the laravel/laravel repo
> Unify model factory code

- queues.md
Small change but makes it slightly easier to then go on to follow the queue example below.
> Improve flow of queue doc

- homestead.md
relevant PR: https://github.com/laravel/homestead/pull/683
> add notes for elasticsearch installation

- homestead.md
while people can definitely choose any IP they like, let's keep them consistent on the documentation and use our default of 192.168.10.10
> make IPs consistent

- eloquent-mutators.md
The pull request adds a little section about accessors that don't just manipulate an already existing attribute, but can create more complex attributes.
> Show how accessors don't have to be for existing fields

- routing.md
User needs to take care of situation when model is not found while **Customizing The Resolution Logic**.
```php
Route::bind('user', function ($value) {
return App\User::where('name', $value)->first() ?? abort(404);
});
```
> Update custom resolution logic example code

- validation.md
Simplify docs from #3774 using existing example, just append a note
> [5.5] Second attempt to document new validation feature

- migrations.md
Ensuring alphabetical order of column types
> [5.5] Correct alphabetical order issue in available column types

- queries.md
This PR adds documentation around the following `raw` Builder methods:
* selectRaw
* whereRaw / orWhereRaw
* havingRaw / orHavingRaw
* orderByRaw
I've also moved the existing `havingRaw` documentation to this new group, so it can be by its friends.
Finally, a note about SQL injection in one of the paragraphs has been promoted to a red `{note}` to make sure users know that these methods aren't without risk.
Let me know if you have any questions or suggestions. Thanks!
> Add documentation of raw query builder methods

- helpers.md
Related: https://github.com/laravel/framework/pull/21745
> Add new array_wrap behaviour to doc

- filesystem.md
The snippet used the old Http\File instead of the Storage facade
> Fixed wrong use in code snippet

- http-tests.md
This was implemented in https://github.com/laravel/framework/pull/21793
**Warning:** This is not part of a tagged version and therefore not released yet.
> Add the new assertCookieExpired assertion

- http-tests.md
Please accept this humble offering. 🙏
> Add documentation for assertViewHasAll

- homestead.md
Dotenv is better for most cases, but sometimes you have variables (like API keys) that you just really want for all your local projects.
> Mention the possibility to set global env variables in Homestead

- filesystem.md
This documentation change complements changes made in laravel/laravel#4470.
> Update S3 docs with regards to default AWS CLI environment variables

- eloquent-collections.md
It was found by @ivangan2307 in #3820
> Fix link to collection's pad method

- facades.md
> [5.5] Document Broadcast facade

- filesystem.md
While I was coding I found no documentation about this feature. I after some searching in the source code I found that it works. I share it so it can help others too.
> Add another example for Deleting Files

- facades.md
[Preview](https://github.com/paulofreitas/laravel-docs/blob/facades-references/facades.md)
- *Auth (Instance)* entry mapping to `Illuminate\Contracts\Auth\Guard` class and `auth.driver` binding
- *Broadcast (Instance)* entry mapping to `Illuminate\Contracts\Broadcasting\Broadcaster` class
- *Cache (Instance)* entry mapping to `Illuminate\Cache\Repository` class and `cache.store` binding
- `db.connection` binding to *DB (Instance)* entry
- *Password (Instance)* entry mapping to `Illuminate\Auth\Passwords\PasswordBroker` class and `auth.password.broker` binding
- *Redis (Instance)* entry mapping to `Illuminate\Redis\Connections\Connection` class and  `redis.connection` binding
- *Response (Instance)* entry mapping to `Illuminate\Http\Response` class
- `session.store` binding to *Session …
> [5.5] Improved facades reference table

- helpers.md
This is the PR for correcting syntactical errors in array helpers
> Corrected mistakes in array examples

- installation.md
Mirror to PR #3847 for the most recent branch
Fixes issue #3483
> Wrong Composer Path Fixed

- documentation.md
- socialite.md
Retrying #3708 with correct Markdown formatting on code blocks
[Live Preview](https://github.com/paulofreitas/laravel-docs/blob/socialite/socialite.md)
If accepted I'll take care of submitting this to other applicable branches (with configuration changes) and later update Socialite's repository. 👍
> [5.5] Document Social Authentication (Laravel Socialite)

- socialite.md
I forgot to remove an unused header in the previous PR. I've also introduced a minor wording improvement to the *Configuration* section. 👍
> [5.5] Minor structure/wording improvement

- authentication.md
Replace `provider` by `extend`
> Fix wrong word

- configuration.md
I think the documentation could be a little more clear here. See https://github.com/laravel/framework/issues/18772
> Clarify .env.testing functionality

- homestead.md
The homestead multiple PHP versions support is a great feature and maybe we can welcome the users advertising it, surely this can excite people early in the page :)
> Add PHP supported versions to homestead documentation

- collections.md
Documents laravel/framework#22261
> Document the firstWhere collection method

- homestead.md
Update homestead version to latest tagged
> Update homestead version

- migrations.md
Add year column, related to [`laravel/framework#22377`](https://github.com/laravel/framework/pull/22377).
> Add year column

- notifications.md
Instead of of as a sms, i think it is supposed to be as an sms.
> Fixed determinant a to an

- installation.md
As mention in #3147 the $PATH for gnu/linux is not quite right
> fix $PATH in installation see #3147

- notifications.md
From issue #3912, changed determinant from a to an
> Follow up from issue #3912

- dusk.md
and you need to use DatabaseMigrations. 
Our team depends on these docs, and my concern is that more people on the team will lose time to this very very hard to track down issue.
> Try #2: Clearly document RefreshDatabase will not work

- eloquent-resources.md
- releases.md
Ref to #3933 i've change all classes name from `User` to `UserResource`
> Update and fix everywhere UserResource class name

- socialite.md
Added info about `userFromTokenAndSecret` which retrieves the user details from a OAuth1 server like Twitter
> Documenting userFromTokenAndSecret

- homestead.md
* https://github.com/laravel/homestead/pull/609
* https://github.com/laravel/homestead/pull/611
* https://github.com/laravel/homestead/pull/783
> 📚 Add note about symlinks not working on Windows + Virtualbox

- quickstart-intermediate.md
- quickstart.md
As per: https://twitter.com/freekmurze/status/951799431447314432
👍
> mixed-content and link to HTTPS

- blade.md
I noticed a past pull request for similar documentation was rejected because of its poor example, hopefully this one is more suitable.
> Add documentation for @hasSection directive

- csrf.md
According to https://github.com/laravel/framework/pull/22661
> Add full URL wildcards to except array in CSRF docs

- collections.md
https://github.com/laravel/framework/pull/22851
> Higher Order unique

- collections.md
https://github.com/laravel/framework/pull/22630
> groupBy to support multiple levels

- http-tests.md
This was implemented in laravel/framework#22849
> Add the new assertHeaderMissing assertion

- http-tests.md
These two methods were just merged into the 5.6 framework branch. So doing my duty and adding supporting docs.
> [5.6] Add docs for new order assertions

- logging.md
> Update logging docs with minor typo

- scheduling.md
Useful to know that you can control TTL of blocking cache key
> Schedule withoutOverlapping "expires at"

- upgrade.md
> New semantics for orWhere

- artisan.md
The third parameter is the index of the default value, not the value itself.
> Clarify docs for multiple choice questions in artisan commands

- homestead.md
Update to latest (7.1.0) homestead version
> Update homestead version to 7.1.0

- upgrade.md
to help users keep files outside of the `laravel/framework` repo in sync.
> add Miscellaneous upgrade note

- upgrade.md
changed this to include the path as I personally got confused by the wording and was diving all over in the vendor file to find it
> slight wording change

- helpers.md
This changes the list() for the new square bracket syntax for array destructuring assignment.
> Uses new square bracket syntax for array destructing assignment

- logging.md
As is evident by the code from `\Illuminate\Log\LogManager::createCustomDriver`:
```php
protected function createCustomDriver(array $config)
{
return $this->app->make($config['via'])->__invoke($config);
}
```
> logging: custom creator class receives config

- upgrade.md
Solves https://github.com/laravel/framework/issues/23095
> [5.5] Update upgrade.md

- passport.md
Clarify the file and location that the code example refers to
Closes https://github.com/laravel/docs/issues/3948
> [5.6] Update passport.md

- validation.md
This is an awesome feature I didnt know about. Document the ability to use closures right at the point of validation for "one off" rules you might need.
Closes https://github.com/laravel/docs/issues/3879
> [5.6] Add undocumented closure rule feature

- dusk.md
Took me forever to get Dusk working on Heroku CI.
> Add Heroku CI notes for Dusk

- facades.md
Citation: The Illuminate\Log\Writer class has been renamed to Illuminate\Log\Logger
> Changed logging facade class

- dusk.md
https://stackoverflow.com/questions/48815952/installing-laravel-dusk-on-5-5-34/48816062#48816062
> Use lower version for Laravel 5.5

- logging.md
See https://github.com/laravel/docs/issues/4102
> Logging - Customizing Monolog - Clarify/Fix Type

- installation.md
As discussed in https://github.com/laravel/docs/pull/4108
> [5.3] Definitive fix for markdown issue 

- authentication.md
Changed Hander.php to correct Handler.php
> Fixed typo in filename

- eloquent-resources.md
Fixes JsonResource.
Addresses the issue in the closed PR today https://github.com/laravel/framework/pull/23256
> Fix JsonResource

- eloquent-resources.md
Fixing the docs like the boss said https://github.com/laravel/framework/pull/23256
> [5.6] Extends JsonResource instead of Resource

- filesystem.md
Reference: [#23308](https://github.com/laravel/framework/pull/23308)
> Add SFTP driver configuration

- pagination.md
At the moment is talks of the default.blade.php as the default file, when at the moment in version 5.6 the botstrap-4.blade.php file is the one used as default.
> Update the default pagination section.

- contracts.md
> Remove Logging\Log from Contracts documentation

- horizon.md
This paragraph seems to be duplicated from line 68 (just above)
> Remove duplicate paragraph about horizon:terminate

- pagination.md
I assume you missed adding a word when updating the PR?
> fix missing word

- homestead.md
for https://github.com/laravel/homestead/commit/efcdd2222f5cffb2d8cae8cb0b51eceb220debe9
> update elasticsearch install instructions

- homestead.md
Update homestead to latest 7.2.0
> [5.6] Update homestead

- homestead.md
https://github.com/laravel/settler/pull/116
Add wp-cli to list of included software
> Add wp-cli to list of included software

- scout.md
Add note to use the new `getScoutKey` method introduced by https://github.com/laravel/scout/pull/268
> Scout: Add note about customizing id (getScoutKey)

- database.md
Configuration for the database hosts for the read and/or write resource should be an array
> DB Read's and Write's Hosts should be an array

- collections.md
> delete duplicated word

- billing.md
Changed user_id column to uint, added foreign key to migration example.
> Modified subscription table structure on billing.md migration example

- valet.md
php72 was migrated from homebrew/php to homebrew/core
> Update PHP homebrew link

- eloquent-resources.md
Corrected typo in _Eloquent - Resources_ section
> Updated eloquent-resources.md

- blade.md
Discussed at <https://twitter.com/assertchris/status/977938826030133248>
> Document the @prepend directive

- validation.md
> Fixes laravel/framework#23750

- configuration.md
this explains how to set and retrieve boolean, null, empty string, and multi-word strings from the project environment variables.
> add explanation of special environment variables

- collections.md
https://github.com/laravel/framework/pull/23759
> random doesn't always return Collection

- dusk.md
documentation for https://github.com/laravel/dusk/commit/be94053d0d4c0af4c462b88bf8f00363c8530fd0
> add docs for `waitForRoute`
