eloquent.md
Because Eloquent models are now namespaced by default, I added this to the relation definitions in the documentation.
=> Added namespaces to Eloquent relations

releases.md
There are more than two major changes listed below the statement 'First, let's examine two of the major changes'. In place of 'two' a more appropriate word is 'some'.
=> Replace the word 'two' with 'some'

quick.md
Not sure if this was more appropriate for only the stable or also future releases, but it would be very helpful for new users if the site mentioned the AppData directory that is meant to parallel `~/.composer`.
=> Make mention of the vendor\bin location on Windows

queues.md
> The number of seconds (0 to 900 - 15 minutes) to delay a specific message.
- http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessage.html
=> Add note about SQS delay limit

middleware.md
I assume this was copy-pasted from the L4 route filters docs but this reference was missed.
=> Fixed typo referencing route filters

configuration.md
Corrected anchor name to (name="after-installation"), as it was (name="configuration").
=> Corrected anchor name attribute.

helpers.md
Hello.
I think this helper doc should have `str_slug` in it because it's very useful when you don't want to use the `Str` facade. 
I've also add an example.
=> Add str_slug description to Helpers.md

responses.md
Added missing macro() method and replaced the use statement with the Response facade.
=> Fixed the example for creating macros

authentication.md
These classes have changed in Laravel 5:
`Illuminate\Contracts\Auth\Remindable` is now `Illuminate\Contracts\Auth\CanResetPassword`
`Illuminate\Auth\Reminders\Remindable` is now `Illuminate\Auth\Passwords\CanResetPassword`
=> Update which classes have to be implemented for password resets

configuration.md
Fixed typo under "Accessing The Current Application Environment"
=> Fixed typo.

database.md
Database query logging is now disabled by default in Laravel 5.0, so the docs should reflect this change.  I maintained most of the original language here.
=> Update Query Logging section of database.md

queries.md
Caching a query forever in the query builder wasn't mentioned before.
=> Add hint of 'rememberForever()' method

events.md
The current example of registering event handlers has a @handle after the name of the handler class ('App\Handlers\Events\EmailPurchaseConfirmation@handle'). If you put this in the EventServiceProvider file and run the 'event:generate' artisan command you actually get a file named 'EmailPurchaseConfirmation@handle.php' in the Handlers/Events directory with a class with the same name (which cannot happen).
Everything is fixed if you remove the @handle. Tried it on a clean laravel project, fired the event in artisan's tinker and the event was correctly handled by the @handle method that was created automatically.
=> Exclude @handle from the registering event example

routing.md
After some discussions here - https://github.com/laravel/docs/pull/1179 - this is an improved example for using CSRF tokens with AJAX.
=> Improve CSRF Ajax documention

templates.md
pattern from createMatcher() leads to: echo ($var)->format('m/d/Y H:i') -> not working
pattern from createOpenMatcher() with the additional brace leads to: echo ($var->format('m/d/Y H:i'))
=> example not working

homestead.md
use `homestead provision` (instead of `vagrant provision`) after editing `Homestead.yaml`
=> Fixed command to be used after editing Homestead.yaml

homestead.md
Update the documentation to show and demonstrate the option to add additional port settings from the `Homestead.yaml` config file.
Refers to the pull request, on the homestead project. [Config option for custom port settings in config file #132](https://github.com/laravel/homestead/pull/132)
=> Update homestead docs to show the adding of additional port forwarding settings.

homestead.md
Ubuntu LTS 14.04 users who install vagrant via `apt-get` will get [Vagrant 1.4.3-1](http://packages.ubuntu.com/trusty/vagrant):
```
➜  ~  vagrant box add laravel/homestead
This command was not invoked properly. The help for this command is
available below.
Usage: vagrant box add <name> <url> [--provider provider] [-h]
--checksum VALUE             Checksum
--checksum-type VALUE        Checksum type
-c, --clean                      Remove old temporary download if it exists.
-f, --force                      Overwrite an existing box if it exists.
--insecure                   If set, SSL certs will not be validated.
--cacert certfile            CA certificate
--cert certfile              The client SSL cert
--provider provider          The provider that backs the box.
-h, --help …
```
=> adding info for installing homestead on ubuntu

packages.md
Add note about publishing package assets to the public folder, including the public tag, --force flag and example public_path() dir
=> Add section about public assets

collections.md
Wrong variable name inside the callback, and replaced is_null with empty function because strtoupper function applied before returned an empty string when applied to null values, therefore is_null wont reject after strtoupper.
=> correct variable name, and update reject callback

filesystem.md
Just a minor issue I found while I wrote a custom filesystem: The used facade is called "Disk" there, but it should actually be "Storage"
=> filesystem.md: Rename Disk to Storage

routing.md
Since the app skeleton is updated, the `before` method does't exist. It should be the `boot` method instead.
=> rename before method to boot

elixir.md
I've had lots of trouble with elixir and gulp where essentially, calling mix.less twice produces some unstable results.
The documentation didn't say I could pass an array and since i'm new to gulp (and grunt). I had to inspect the elixir source code to find out.
=> Pass an array for more than one file in elixir mix.less

elixir.md
It may seem obvious to some, but for people who are new to Gulp or unclear on what Elixir actually does, the Usage section should clearly state that "gulpfile.js" is the file that you edit when using the examples listed.  The file "gulpfile.js" wasn't previously mentioned by name anywhere in the Elixer docs page.
=> Specifying 'gulpfile.js' as the file to edit.

homestead.md
Launching the homestead vagrant box via vagrant up will only work if you had homestead create a vagrant file for you first.
However homestead init will not do so.
So instead of using vagrant up you should use homestead up, which will first create the vagrantfile and only then run vagrant up.
Once the vagrantfile is there you can of course  run vagrant up instead, just not at this point in the install.
This is true for all versions of this documentation. I submitted this pull request to the 5.0 branch as that is the most recent version with the error inside.
The fix should probably be applied to the documentation for all Laravel versions, though.
=> Clarify the Launch of homestead

testing.md
The application's [call](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Testing/ApplicationTrait.php#L54) method has a `$cookies` variable before the `$files`, `$server` and `$content` arguments.
=> added missing cookies variable for call method

helpers.md
The `resource` function is the only remaining Routing helper that isn't documented.
=> Added `resource` to Routing section in helpers.md

artisan.md
The example in the current docs fails with exception 'LogicException' with message 'Must direct output to a file in order to e-mail results.'  It appears that you have to call sendOutputTo() first before emailOutputTo() can be used.
=> emailOutputTo() requires sendOutputTo() first

installation.md
Laravel 5 requires `Psy/Psych`. 
`Psy/Psych` requires `Nikic/Php-Parser`
`Nikic/Php-Parser` requires the PHP Exteniosn `tonkenizer` to be installed.
Therefore Laravel 5 requires this extension, otherwise composer will fail to install Laravel 5. Issue was discovered on this SO thread: http://stackoverflow.com/q/28914789/1317935
=> Update Server Requirements

queues.md
According to ironmq's docs :
Use branch 1.* - laravel-compatible, php-5.2-compatible version. No namespaces. Using default IronMQ servers.
=> Update IronMQ dependency

billing.md
The docs make no reference to the `services.php` file that exists with Stripe ready to go.
So this just helps to clarify that...
=> Clarify Stripe Key use

controllers.md
Was this lost somehow? It is correct in the 5.0 documentation.
=> Adding Controller method back into route

homestead.md
Blackfire has two sets of credentials: client and server. For homestead, we need the server credentials. Even if it is already mentioned in the docs, people are confused. So, this PR tries to make things a little clearer.
Also, what do you think about renaming the YAML `id` and `token` keys to `server-id` and `server-token` respectively? I can make the needed changes and PRs.
=> Tweaked docs about Blackfire

authentication.md
The part "You may have this via the `reminder.expire` option of your `config/auth.php` file." sounds rather weird, changing it to "[...] option in your `config/auth.php` file." sounds a bit better.
=> Change "of" to "in" in authentication.

authentication.md, configuration.md, elixir.md, eloquent.md, installation.md, routing.md, schema.md, templates.md, testing.md, upgrade.md, validation.md
Currently the indentation is, for the most part, tabs. However, some of the
indentation is spaces, and there doesn't seem to be a good reason for a
lot of this indentation switch.
For example, some of the indentation is only 3 spaces or 7 spaces instead of
4 or 8. This is even more inconsistent and has probably happened over time
as a result of PRs.  This fixes inconsistencies such as that and makes
it 1 tab or 2 tabs.
This does not change specifically-spaced formatting to tabs, such as
aligning far-spaced -> in the queries markdown document and other
documents, meaning that ->'s are still perfectly aligned.
For example, the following is changed:
Old:
if (Auth::attempt(['email' => $email, 'password' => $password, 'active' => 1]))
{
// The user is active, not suspended, and exists.
}
New: …
=> Standarize indentation to tabs instead of mixture.

upgrade.md
It looks like the 5.x upgrade guide is missing some method name changes for pagination. I ran into some brief trouble with this over the weekend, perhaps it will give a heads up for people upgrading in future.
=> Add pagination method changes to upgrade.md

facades.md
As of Laravel 5 seems to have replaced the name of the IoC Container to Service Container.
=> Replaced IoC

envoy.md
The current docs are wrong and very unclear at how to set up Slack notifications with Envoy. I've updated the docs to the old one which was present in the Envoy readme on Github which is much more clear.
=> Update Slack docs to correct usage

helpers.md
In the code example of the `array_fetch()` were used wrong closing -  `);` instead of proper `];`. Probably it is a leftover from v.4.2 where `array` uses parenthesis. 
Additionally, same typo is in the master branch :wink:
=> array_fetch wrong bracket parring - typo

commands.md
Using the docs I got
~~~
[InvalidArgumentException]
Impossible to have an option mode VALUE_IS_ARRAY if the option does not accept a value.
~~~
Looking in the code for `InputOption::VALUE_IS_ARRAY` I could not find and example, so figured it would be good to add to docs.
=> Add example for VALUE_IS_ARRAY

configuration.md
`Options +FollowSymLinks` will generate a 500 error if `AllowOverride None` is set in `httpd.conf`, which is by default in some systems due to a [security concern](http://serverfault.com/questions/244592/followsymlinks-on-apache-why-is-it-a-security-risk). HTML5Boilerplate also had [an instruction](https://github.com/h5bp/html5-boilerplate/blob/master/dist/.htaccess#L327) regarding this issue.
=> Added an instruction to replace FollowSymLinks with SymLinksIfOwnerMatch if necessary

homestead.md
Adds a terminal command tip for amending your path for composer executables.
Where people might typically land searching for `command not found: homestead`
- [zsh: command not found: homestead - Laracasts](https://laracasts.com/discuss/channels/general-discussion/zsh-command-not-found-homestead)
- [How should I set the PATH variable - superuser](http://superuser.com/a/324617)
This has hung a few people up in the past that are not very familiar with how PATH works. Might save 
some digging, though I know this can differ from system to system. I ended up in the same error state, until I remembered I shouldn't be using `export $PATH =`
=> Homestead Docs: Amend Path Tip

filesystem.md
The example of DropboxFilesystemServiceProvider Class does not extends anything, and it's not working until it's extending ServiceProvider Class, and also have a register method
=> DropboxFilesystemServiceProvider need to extends ServiceProvider

helpers.md
As laravel 4.X and 5 don't support php 5.3.x, i removed the references to it the help.
=> Removed references to php 5.3

routing.md
This commit adds some information about the availability of the `where` parameter in the `Route@group` attribute array and adds some more detailed information around `middleware`, `namespace`, and `prefix` attributes.
=> Improves Route@Group attributes documentation

eloquent.md
The old code that was here no longer works in Laravel 5, so I removed it and replaced it with the current way of error handling.
=> replace old ModelNotFoundException handling with new way

homestead.md
If you don't set the port to listen nginx won't restart due to bad configuration file.
=> Set port to listen for serve script

upgrade.md
The links to upgrade from 4.0 to 4.1 currently point to the master branch which is laravel 5.0
=> Updating 4.1 upgrade links

queues.md
This is to follow the code change in laravel/framework#8305.
=> [5.0] Added relative URL sample to queue:subscribe

routing.md
"Middleware (in general) are applied ..." vs "Middleware is applied ..."
=> Fix verb from singular to plural

middleware.md
Declaration of StartSession::handle() must be compatible with Illuminate\Contracts\Routing\Middleware::handle($request, Closure $next)
=> Missing Closure

billing.md
I recently added the `getTaxPercent` method, and figured I should update the docs too.
=> Adding docs for getTaxPercent method

events.md
there are many ways to register subscribers, but using the `subscribe`
property was not shown in the documentation
=> show users how to use the `subscribe` property to register subscribers

middleware.md
Add missing use Closure or alternatively use \ (backslash) in front of Closure:
public function handle($request, \Closure $next)
{
return $next($request);
}
or
use Closure;
public function handle($request, Closure $next)
{
return $next($request);
}
=> Add missing use Closure

authentication.md
Can't get user's email if I have set additional scopes like `user_birthday` for Facebook.
I only get email if I add `email` it to scopes manually or if user has its email available publicly.
=> Add note for scope overwriting (Socialite)

contributions.md, session.md, testing.md
Continuing from #881. Refer to "testing" in general instead of "unit testing".
=> Update testing copy

facades.md
The cache key in the IoC container, and thus the Cache facade, is actually an instance of `Illuminate\Cache\CacheManager` (as seen [here](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Cache/CacheServiceProvider.php#L23-26)).
=> Update to correct cache class.

elixir.md
Can't copy and paste without swapping or escaping the quotes as is.
=> Use single quotes for paths in version helper

middleware.md
Actually, the code example for the explanation of the OldMiddleware isn't right. There's the wrong comparison operator for this:  
> In this middleware, we will only allow access to the route if the supplied age is greater than 200.
But in the code example, we need the the `is less than or equal to (<=)` comparison operator instead of the `is less than` comparison operator.
=> Changed the comparison operator to the right one

events.md
Added the Pusher and Redis dependencies to events.md so you don't have to search on packagist for the right pusher package or click through to the Redis docs.
=> Added dependencies for event broadcast

upgrade.md
The new flysystem-aws version is already stated in the filesystem documentation, but it's missing from the upgrade guide.
=> [5.1] Add Amazon S3 driver upgrade instructions from 5.0 to 5.1

queries.md
Minor typo fix for #where-clauses index.
=> Fix #where-clauses index typo

eloquent-relationships.md
=> Fix link to mass assignment documentation

upgrade.md
Eloquent and Collection each have their own distinct lists() method, and both were changed to return a Collection instead of an array in Laravel 5.1.  The upgrade guide failed to mention that Collection's lists() method now returns a Collection, but it did mention that Eloquent's lists() returns a Collection... but it mentioned that under the "Collection Class" section of the instructions.  Hopefully this will clear up the confusion.
=> Eloquent's vs. Collections's lists() correction.

installation.md
The installation page would be frequented with new users who might not know about a facade. Pointing them to its documentation would greatly help.
=> Provide link to facade documentation

releases.md
the validation docs and this (Validation Quickstart) appears to be the
most appropriate place to redirect to.
=> Adjust link to controller validation as the anchor name doesn't exist in

queues.md
there are 8 processes (numprocs=8) in the config given in the example. if that is the case when the command is run 'laravel-worker' is a group of processes, not a single process; therefore must be referenced as a group: 'laravel-worker:*' which references the group and all processes within it. Otherwise the command fails.
=> Fix broken worker start command

controllers.md
If you look at the section on accessing requests in controllers here:
http://laravel.com/docs/5.1/requests#accessing-the-request
And then look at the similar example on method injection in controllers here:
http://laravel.com/docs/5.1/controllers#dependency-injection-and-controllers
You'll see a small discrepancy: the "Request" section gives an example of what the route looks like, while the controller section does not. This PR simply makes the "Controller" section consistent with the "Request" section, and adds the missing route example.
=> Adding consistency in method injection documentation

testing.md
The default `ModelFactory` file in Laravel 5.1 uses class name resolution - but the docs do not.
We should be encouraging the same convention...
=> Make docs use class name resolution

installation.md
I was trying to build a production environment with a minimum number of PHP extensions loaded. Even though I specifically ask composer to skip the require-dev, seems Laravel requires the PDO extension. I was just thinking maybe it would be worth mentioning in the docs.
````
composer create-project laravel/laravel test --no-dev
....
- Installing laravel/framework (v5.1.2)
Loading from cache
Writing lock file
Generating autoload files
PHP Fatal error:  Class 'PDO' not found in /var/www/test/config/database.php on line 16
Script php artisan clear-compiled handling the post-install-cmd event returned with an error
[RuntimeException]
Error Output: PHP Fatal error:  Class 'PDO' not found in /var/www/test/config/database.php on line 16
````
=> Added PDO as a PHP server requirement

elixir.md
Windows users (even when running Homestead) often need to include `--no-bin-links` when doing the install. This is because the symlink function does not work (even in Homestead).
Discussed here: https://github.com/npm/npm/issues/7308
=> Improve Elixir doc

installation.md
If the installation is run like this, it will install version 5.1. I've updated this to match the format used in the 4.2 docs and it works.
=> Must explicitly specify 5.0

eloquent-relationships.md
Inconsistent use of $q and $query when querying the existence of relationships.
=> Replaced $q with $query for consistency

upgrade.md
Because https://github.com/laravel/framework/commit/5d93473b56b7ce481000902ec8f2e3c426be7c03 was applied to Laravel 5.1 and was not documented anywhere else for package maintainers.
=> Added note about upgrading translation files for vendor packages.

validation.md
Two adjustments. Added a cool feature that I didnt know about (and is very useful - so should be in the docs) that you can use `after` against another field - which is extremely awesome.
Also - added a point that people should *not* use `date` and `date_format` in the same validation rule - otherwise you'll run into issues (which I've just had for the past 30mins). The reason is `date` will parse with `strtotime` - and that can cause certain formats to fail - such as `mm-dd-YYYY`.
=> Improve Date validation docs

redis.md
"Additinoally" -> "Additionally"
"...specify a of Predis client options" -> "...specify a set of Predis client options."
=> Fix spelling in redis.md

homestead.md
To get Homestead working in VMWare on Windows, the provider must be set to `vmware_workstation`. As fusion is exclusive to Mac and Workstation is exclusive to Windows. 
There is no VMWare Application called "Desktop".
=> Add vagrant provider option for Homestead in VMWare Workstation on Windows

filesystem.md
Small typo in filesystem description
=> Fix typo in 'copy' method description

homestead.md
I think Homestead should be installed as a dev dependency and not as an project dependency.
=> Install Homestead as a dev dependency

middleware.md
If middleware is not registered as singleton within container and it has terminate method, laravel will create a new instance of your middleware and call terminate on that instance, losing your previous instance properties.
This behaviour is not obvious without digging through the source code.
Previous issue here: https://github.com/laravel/framework/issues/9683.
=> Add important note about middleware terminate method

elixir.md
Elixir itself uses single quotes. Some parts of the elixir docs use single quotes and other parts use double. Since elixir is using single quotes I suggest using single quotes in the docs too.
=> Fix inconsistent use of double vs single quotes

quick.md
People around the net have been confused about the 4.2 quick guide installing version 5.*, this change will show people how to install the right version.
=> Changed --prefer-dist in the quick install guide to 4.2.*

authentication.md
A novice user might not catch that they have to include the Socialite facade in the AuthController if they are trying to use Socialite.
=> Include Socialite facade for the AuthController

queues.md
Current docs don't note that the failed() method needs to be defined on a handler class not the job class if you are using the job / handler system as per https://github.com/laravel/framework/issues/9799
=> update queues.md to clarify location for failed() method

quick.md
As this is now legacy documentation, changing link to download from v4.2 branch instead of master.
=> Changing Github download link to 4.2 instead of master.

authentication.md
I just lost about 20 minutes trying to figure out why changing the `$loginPath` property wasn't changing where I bounced when trying to access a protected route when not logged in. I'd like to save someone else the trouble.
=> Clarify $loginPath effect on bouncing users

container.md
I believe this is true but I'm not 100%. Based on my experience last night diving the code, I think that the container isn't smart enough to auto-detect the type from the type hint in the closure and that it actually has an `$abstract` passed to it.
I want to post a follow-up PR to this for `afterResolving` which I ultimately ended up using. Would it be safe to describe `afterResolving` as a hook that is fired after an object and all of it's dependencies (and their dependencies) have been resolved? Versus `resolving` being a hook that is fired as soon as an object is resolved, even if the object that depended on it hasn't been completely resolved itself yet?
=> The class-specific resolving example missed the abstract.

cache.md
As Cache Tags are a big help for me and I only found documentation in the 5.0 docs, I brought these back in to the 5.1 documentation. Doing so I noticed the Cache Events were also missing, so I brought those back as well. 
It seems they are still working, so I hope this was an OK move...
=> Bring Cache Tags and Cache Events back from 5.0

cache.md
This time in the right branch, sorry for the trouble Taylor.
So, while reading the cache docs I found this error.
`Anne` is tagged as `['people', 'authors']` while `John` is tagged as `['people', 'artists']`. So if you do `Cache::tags('authors')->flush();` then `Anne` will be deleted not `John` as suggested by the docs.
Fixed this logical mistake.
=> Names of tagged flush example where switched

artisan.md
The recommended methods progressStart, progressAdvance and progressFinish do not give access to the actual ProgressBar component, so it can't be customized without reading deep on Laravel's and Symfony's code. So the external link to Synfony's docs become misleading: http://stackoverflow.com/questions/32015511/laravel-5-1-how-to-set-a-message-on-progress-bar/32018827#32018827
There are two options to fix this section (I opted for the first one):
1) Recommend the createProgressBar method instead, so you have access to the actual ProgressBar object (and then Symfony docs won't confuse you, because you're just at home); 
OR
2) Add a note near Symfony's docs link, informing something like: "if you need to access the actual ProgressBar object in order to customize it, you should call …
=> External link about progress bar was misleading

installation.md
With the older version of installation procedure (simply telling
Composer to install "5.0"), it doesn't actually install the latest
version of laravel/laravel (currently 5.0.22), but instead installs
5.0.0. And there's a bunch of differences between those two versions, so
it's not ideal.
That wouldn't be an issue, if Composer could update laravel/laravel in
the current project, but of course it can't, so a developer is stuck
with older files.
My proposed fix is to tell Composer to install "~5.0.0" version, which
installs the latest version, up to (but excluding) 5.1 version.
Currently, this means 5.0.22.
But since 5.0.22 comes with composer.lock (5.0.0 doesn't), Composer
installs older versions of packages, which means we have to upgrade
those.
But there's another issue - since …
=> Help users install the latest version of Laravel 5.0

events.md, queues.md
Updated a few instances where strings were used to refer to classes with `::class` notation.
=> Use ::class notation for consistency

events.md, queues.md
=> Revert "Use ::class notation for consistency"

packages.md
Missing documentation for publishing translations functionality.
Maybe merge this common view - lang features into a single documentation?
=> Publishing translations

migrations.md
Updated increments and big increments explanations to point out that integers are unsigned.
This is important when creating foreign keys in MySQL.
=> Update increments explanations

seeding.md
The file isn't namespaced therefore the `use` statement will show the following error when running `php artisan db:seed`:
>  [ErrorException]                                             
>  The use statement with non-compound name 'DB' has no effect
This may confuse a newcomer or somebody unfamiliar in PHP namespaces.
=> Remove unnecessary use statement

scheduling.md
If you use the existing example, you'll get an error.
=> Removed bad parameter in schedule command

cache.md
Especially irrespective of the prefix.
I just nuked our production redis database (used for Resque)
because of this behavior (I'm calling `php artisan clear:cache`
on every deploy).
See https://github.com/laravel/framework/issues/5034 for "prior art".
=> Add note that flush() clears everything

billing.md
Without backslash Laravel will append namespace to main application namespace and will return an error "Class App\Http\Controllers\Laravel\Cashier\WebhookController does not exist".
=> Added backslash before route namespace

artisan.md
I was slightly confused when reading this section.
When it read ```In this example``` on line 120 I thought it was referring to the example below when it was actually referring to the example above.
So here's my proposal to make it a bit more clear .
=> Rearranged wording to make more clear

requests.md
The documentation said that `only` and `expect` only accepted a single array as an argument but the examples showed the arguments broken out. The methods will accept both as input. I changed the documentation to show both examples.
=> Fix the documentation for the `only` and `except` methods

routing.md
See https://github.com/laravel/framework/pull/9477
Explanation is similar to the documentation of `csrf_field()`, but a little more compact, as there is already an HTML example.
=> Add documentation for the `method_field()` helper

contributions.md
Doesn't seem to be any info on docblocks, yet there does appear to be an expectation from the Laravel team.
=> Add docblock information to contributions guide

queues.md
Fixed a small mistake about configuring the table name for failed queue jobs.
=> name of the failed jobs -> name of the table

elixir.md
Fixed a small typo, which instead of 'scripts', it should be 'Sass files', because right there, we're talking about Sass stylesheets compiling into CSS, and not scripts.
=> Fixed typo

validation.md
The fourth parameter of the unique validation rule isn't explained anywhere on the documentation.
I'm maintaining a Laravel app where the previous developer used 'custom_id' instead of just 'id' and it took me a while to figure it out why my validation kept failing! Had to check the next example (Adding Additional Where Clauses) to get it.
Maybe this could help someone in the same situation.
=> Adding documentation for the fourth parameter of unique validation rule

homestead.md
- using different directory name as an example for new clone
- adding condition of already having `~/.homestead/Homestead.yml`
(this condition is not true for older version of Homestead, from which one might also want to upgrade, and not be aware of the difference.)
- adding instruction how to upgrade from older version of Homestead
- clarifying the position of box directive
- clarifying from which directory to run `vagrant up` from
=> Update homestead.md - Upgrading To PHP 7.0 section

validation.md
take 2 (fixes problems with https://github.com/laravel/docs/pull/1829)
=> Clarify how `mimes` validation rule maps extensions to mimetypes

controllers.md
In 5.1, the `URLs To Controller Actions` section of this page was eliminated, and the explanation of `action()` was jammed into the `Naming Controller Routes` section. This was a step backwards in that the previous section name was more appropriate, and two important methods were scrubbed from the page.
Mention of the `URL::setRootControllerNamespace()` method was eliminated. This is a hugely useful method that is probably under-utilized because it is little-known. My feeling is that it has a place on this page.
Similarly, the `Route::currentRouteAction()` method was eliminated. There is no clear explanation as to why (at least that I'm able to find).
This change restores the `URLs to Controller Actions` section, verbatim, as it appeared in 5.0.
=> Restore useful content eliminated in 5.1

events.md
I've just read this issue (https://github.com/laravel/framework/issues/10236) and realize that we could override the broadcast event name. Maybe it should be added to doc. 
P.S: I'm not english, sorry if it's unreadable.
=> Overriding the default broadcast event name

validation.md
This PR does three things:
1. Correct the docs for `Validator::extend()`. There are four parameters passed to the extension, but the docs say there are only three. (Turns out that fourth param is pretty important for some types of extensions.)
2. Clarify what the `required` rule does.
3. Document the `Validator::extendImplicit()` method.
=> [5.1] Further Documentation for Validation Extensions

homestead.md
Changes:
"will boot the virtual machine and automatically configure your shared folders and Nginx sites automatically."
to
"will boot the virtual machine and automatically configure your shared folders and Nginx sites."
=> Remove redundant word "automatically"

authorization.md
Commit https://github.com/laravel/laravel/commit/50357d8bab3c43ac6b76a82038847c1061bf21c6 changes parent:: to $this.
Since upgrade guide links directily to [raw file](https://github.com/laravel/docs/edit/5.1/upgrade.md#L25), update documentation file to keep it consistent.
=> [5.1] Use $this instead of parent::

eloquent.md
Some uses complained about not being able to return a count in the query scope. We know the query scope should always return a query builder object. I added the note in the documentation to make this clearer!
See the following issues:
* https://github.com/laravel/framework/issues/10701
* https://github.com/laravel/framework/issues/5405
* https://laracasts.com/discuss/channels/laravel/scope-query-unable-to-return-false-zero-instead-eloquent-builder-returns-an-object?page=1#reply-108939
=> Add a note to the query builder regarding returning the correct object

artisan.md
Add example for specifying shortcut when defining an option.
=> Commands Option Shortcut

routing.md
Noticed that this was missing from the 5.1 docs, if this was intentionally left out please ignore the pull request.
I know that we'll have implicit route model binding in 5.2 but for LTS users this should suffice in the 5.1 docs.
=> Route model binding added to routing.md

migrations.md
In the create method, we're told the closure receives a Blueprint $table, but Blueprint was not specified in the example.
=> $table type should be Blueprint

quickstart-intermediate.md
If I am not wrong, there only should be one "to" instead of "to to".
("...so the framework knows on which policy to to fire the `destroy`...")
=> Spelling correction

authorization.md
The usage of the Gate facade was redundantly described in the Form Requests section.
=> Fixed redundant language

seeding.md
In the current boiler plate code found in DatabaseSeeder.php, there's a `Model::reguard();` at the end of the `run()` method. This change updates the documentation to reflect this.
=> Added reguard method

queues.md
I feel that the retry all option adds great benefit to anyone dealing with a list of failed jobs longer than a few records long.
=> [5.1] Include documentation for new retry all feature

queues.md
Update docs of ironMQ according to [https://github.com/laravel/framework/pull/10848](https://github.com/laravel/framework/pull/10848) and [https://github.com/iron-io/iron_mq_php/tree/v4](https://github.com/iron-io/iron_mq_php/tree/v4)
=> Update requirement of ironMQ to v3 API

queues.md
…and not the default abstract job class.
The current wording would lead you to believe that the method is defined right there in the base class but it's not, the base class just uses the trait which you can import for yourself elsewhere.
=> update queues.md to clarify that onQueue() from Queueable trait

testing.md
Added a section to the Testing documentation addressing the additional PHPUnit assertions provided by [AssertionsTrait](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Testing/AssertionsTrait.php).
=> Add a 'PHPUnit Assertions' section to testing.md

envoy.md
@include should not have a semi-colon ending:
With a semi-colon:
```@include('vendor/autoload.php');``` => ```<?php require_once('vendor/autoload.php'); ?>;```
Without:
```@include('vendor/autoload.php')``` => ```<?php require_once('vendor/autoload.php'); ?>```
=> envoy.md: @include should not have a semi-colon

artisan.md
Use class notation instead of string so that it is consistent with the rest of the framework following this commit: https://github.com/laravel/laravel/commit/58db25b9f5bef52b9cac0678e79eb2b8f1b322cb and best practices.
=> Use ::class notation

testing.md
The email in given in the description of the example in the section "Working With Databases" was "sally@example.com". But in the example it was "sally@foo.com" Corrected it now.
=> Corrected the mismatch in emails in the working with database example

installation.md
Being a complete noob, I was confused -- probably longer than I should have been -- about creating a fresh Laravel install for a number of reasons:
- it wasn't immediately clear to me the difference between using `laravel new ...` and `composer create-project ...`
- the example shown seemed inconsistent (a new `blog` project vs a new `laravel` in the other)
- the `composer create-project` implicitly creates `laravel` directory which is slightly different than the `Laravel` shown in the yaml
I'm probably obsessing and I don't really expect this PR to go through, I just wanted somewhere to discuss it. :smile:
=> Add `blog` for consistency between two examples

eloquent.md
Scope wasn't the name of the interface. It was ScopeInterface.
=> [5.2] Add an example for Global Scopes

eloquent.md
I noticed that anonymous global scopes are not documented, so I prepared a simple example.
=> [5.2] Document anonymous global scopes

upgrade.md
Not needed now that the final release is out.
=> [5.2] Remove beta instructions

billing.md
Getting the total amount for an invoice changed from $invoice->dollars() to $invoice->total() in Cashier 6.0. This should be updated in the documentation.
=> Update reference to dollars() function changed in Cashier 6.0

helpers.md
Reports that there is a second parameter in the old helper, the parameter $default
=> [5.2] default value in old helper

upgrade.md
Added appropriate quotation marks so you can easily copy and paste them into your composer.json file.
=> Copy / paste friendly format for 5.2 composer.json

upgrade.md
Added removal of loginPath() from `Illuminate\Foundation\Auth\AuthenticatesUsers`  to upgrade.md
=> 5.2 loginPath() removal not noted in upgrade guide

upgrade.md
The changes to Elixir mentioned in the 5.2 upgrade guide were not actually made. The function still returns relative file locations.
=> Remove Elixir changes from 5.2 upgrade guide

upgrade.md
I recently upgraded an app from 5.1.24 to 5.2.4. After the upgrade the app was broken because those 2 Service Provider got removed in [this commit](https://github.com/laravel/laravel/commit/1500a186966a4dad78032f13c5655d633c643d37#diff-ea70a5765dbab9fd8032c1d439521db8L143) long before 5.2.4.
Just thought we could add the removal of those Service Providers to the docs.
=> Add missing ServiceProvider Changes for Upgrade to 5.0.16

homestead.md
Xdebug no longer seems to be included in the latest version of Homestead. Will need to re-implement as part of the provisioning process, or update the base box.
=> Remove Xdebug from list of provided software

installation.md
If you follow the Composer Create-Project install instructions on the 5.1 page you will currently get 5.2. Now that 5.2 has been released if you want to install 5.1 LTS the version needs to be specified. (Version in quotes.)
=> Update how to create-project for 5.1

blade.md
There's no mention in any documentation of `@push` and `@stack`, which are very useful features, particularly when it comes to complex view structures or layouts. This change introduces the idea and shows two examples of the actions available.
=> Include mention of @push and @stack

upgrade.md
According to this commit: [101cb80] (https://github.com/laravel/framework/commit/101cb80750cb81fe26cd38686b8464a7e943330d) 
Composer.php was moved from `Illuminate\Foundation` to `Illuminate\Support` and not from `Illuminate\Foundation\Support`
=> Update path that Composer.php was moved.

upgrade.md
Refers to [this change](https://github.com/laravel/framework/commit/41ff1a1fc838007b981ee27b043feae8e4974680#diff-14de5015be74d92950add13254e6eccdR63), seems worth mentioning since not everyone might test their seeds are functioning correctly immediately after upgrading.
=> 5.2 upgrade note about db seeds being unguarded by default

eloquent-relationships.md
I think this is a more intuitive example that users will be able to follow more easily than staff, products, photos and imageables.
=> Use Posts, Comments and Likes for the polymorphic relationship example

quickstart-intermediate.md
This avoids having to add 'use' statements for them both (which is not in the documentation either).
See https://github.com/laravel/quickstart-intermediate/issues/10
=> Use full name for Task and TaskPolicy in AuthServiceProvider policies.

collections.md
This PR adds information about using a collection's keys for Collection filter and reject as implemented in: https://github.com/laravel/framework/pull/11759 and https://github.com/laravel/framework/pull/11727
=> Note that reject and filter can take an optional key parameter in callback

database.md
It looks like when you call `DB::listen()`, you no longer receive multiple parameters for the `$sql` and `$bindings`. Instead, you get a `QueryExecuted` DTO. This PR updates the docs to reflect that.
=> Update for QueryExecuted change

upgrade.md
`php artisan optimize` was erroring with :
>[ErrorException]
>php_strip_whitespace(/path/to/project): failed to open stream: No such file or directory
due to legacy service providers remaining in the `config/compile.php` file. Removing the listing solved the issue.
=> Remove legacy providers from compile config in upgrade

middleware.md
As per pull request #1974, removed the ambiguity associated with 'OldMiddleware'. This could imply an outdated middleware. AgeMiddleware is more apt.
=> Remove ambiguity associated with 'old' in middleware.md

testing.md
The name method does not exist. To type text into a form input field, the method is _type_.
=> Remove invalid method

upgrade.md
`Illuminate\Foundation\Validation\ValidationException` is deprecated in favour of `Illuminate\Validation\ValidationException`, so I suggest updating the upgrade instructions to tell people to use the non-deprecated file instead.
=> Reference non-deprecated ValidationException

quickstart-intermediate.md
Removed `plain` argument which has been removed in v5.2 and replaced with the `resource` argument (which defaults to plain: https://github.com/laravel/framework/blob/7f62d81acb2001faafb21a32544464ebfc92476c/src/Illuminate/Routing/Console/ControllerMakeCommand.php#L42)
Code in the tutorial as it is right now returns an error: `The "--plain" option does not exist.`
=> Updated call to make:controller in quickstart-intermediate.md

validation.md
Mentioning that the rules will be validated in the order that the user assign the rules. This will help them to assign the rules in proper order to avoid errors. If the order is wrong even after the `bail` rule is used, user will not get any advantage.
=> Mention about the rules order

elixir.md
As well as ES2015, by default, Babel 5.x runs with the react (JSX) transformation enabled. Elixir currently uses babel-core 5, but Babel 6 removes all default presets, which might cause some confusion as some developers might expect from looking at the current Babel documentation for the react preset to not be included by default.
=> Add references to JSX transformation in elixir docs

billing.md
The column name for canceling is called `ends_at` **not** `subscription_ends_at`
=> typo fixed

eloquent-relationships.md
Section went missing after eloquent documentation rewrite, seems it would be handy to include, so just pasted it back in with slight modification to example code for consistency with example code in this section.
=> Returning updateExistingPivot documentation

scheduling.md
Adds the timezone method which is missing from the docs.
=> Add timezone method.

helpers.md
Arr::has() accepts a string $key as its second parameter. With the original docs example I was misled into thinking the array_has() helper would accept an array of multiple keys to check. That would be pretty cool though.
=> Fix second parameter in array_has() usage example

installation.md
People following the docs to the letter on Windows machines will have trouble trying to do the installation via the Laravel Installer.
=> Different path for 'laravel' executable on Windows.

queries.md
The method 'lists' is deprecated, promote the use of 'pluck'.
=> Deprecated method 'lists', use 'pluck' instead

queues.md
The documentation on dispatching jobs from requests was removed in commit https://github.com/laravel/docs/commit/e756d8e029f90984f34e887b097332ad74105dbb, but the table of contents link has remained.
=> Update queue docs - Remove unused TOC link

installation.md
Adjustment to exclude PHP 7 do to the psy version in 5.0 using libraries that aren't ready for PHP 7.
>"Cannot use PhpParser\Node\Scalar\String as String because 'String' is a special class name"
=> [5.0] Adjust install PHP version requirements

artisan.md
In order to provide autocompletion to users, the “anticipate” method can be used. So, I think the base form of the verb is fitted.
=> Fix artisan document

homestead.md
I installed vagrant/virtualbox and followed the instructions to setup Homestead without any issues. Then proceeded to follow the Beginner Task List (https://laravel.com/docs/5.2/quickstart). I utilized composer to create the 'quickstart' directory as in the insturctions, completed the tutorial and navigated my browser to 'homestead.app' only to be presented with "No input file specified".
After reading through this forum post, in particular the answer by 'srhyne':
http://laravel.io/forum/06-04-2014-no-input-file-specified-using-homestead
I checked the /etc/nginx/sites-enabled/domain file only to see that the server.root path points to nonexistant 'Laravel' directory. I proceeded to change the ~/.homestead/Homestead.yaml to point to /home/vagrant/Code/quickstart/public and ran vagrant …
=> Add note about reloading vagrant after .yaml change

testing.md
The current docs use `$this->post` to send a request to JSON APIs.
However, the `$this->post` method sends form encoded data.
While this works for APIs using `Request::get`, it breaks for APIs which rely on `Request::json`.
This PR updates the docs to use the `$this->json` method for testing JSON APIs.
=> Update JSON post example to use `$this->json`

installation.md
Made this change so newer users understand that they need to use the "php" command in front of "artisan key:generate"
=> Change `artisan key:generate` to `php artisan key:generate`

middleware.md
Same as #2123 but for 5.2 branch.
=> [5.2] One can directly pass the middleware class name

requests.md
Newcomers may not know that Laravel automatically maps JSON data to the request input, especially if they are just sending data with something like jQuery and not setting their Content-Type header.
There was a note about accepting JSON input in the 4.2 docs, which is where I borrowed the language from.
At the very least, this will be a hint for anyone who comes to the Requests page of the docs and does a cmd+F for 'json'.
=> Add note about retrieving JSON input

localization.md
I got caught out by a new addition in 5.2; translation keys will be run through `Str::upper` and `Str::ucfirst` and replaced with the correspondingly capitalised value.
See https://github.com/laravel/framework/commit/1bb387927591f28fcac44ab8c0d949ccb107409d
Cool addition, but so far undocumented. No longer!
=> Adding a paragraph on string capitalisation in language parameter name

migrations.md
This add the easier syntax, instead of manually creating the index name.
=> Add array syntax for dropping indexes

queues.md
From 5.0 to 5.1 the description of the queue:work command was removed. I'm not sure whether this was intentional, since it was part of a much larger batch of edits (059a01b65089819c4d81b0378be694e2d5a1bfdd).
Right now if you read through the queue docs, it's not really clear what difference is between `queue:listen` and `queue:work` is - there is no description of the latter.
=> Restore description of queue:work command

elixir.md
Fixed a little issue with a link in the documentation for Laravel Elixir.
=> Fix formatting error in elixir docs

helpers.md
Many people see this page and go looking for a ```dd``` method that does not halt the execution of the script.
I'm not sure if here is the best place to put it, but for lack of a better place, it sure would save some time for those in the same situation as myself.
=> Add suggestion for `dump` method

authentication.md
I find "at least 60 characters in length" to be confusing for the password column, because `Hash::make()` uses `password_hash` with `PASSWORD_BCRYPT` which will always result in 60 characters string.
For best practice "at least" is equivalent to must be a little bit longer.
If an algorithm change results in a longer hash, than this should be stated under breaking changes in the upgrade guide.
=> Remove "at least" from password column length in Database Considerations

quickstart-intermediate.md
The first change set about "The example code for this application has the slash." is debatable. Either the tutorial should change to match the example code (as done in this changeset) or the example code should change to match the tutorial.
The second change set, is a genuine bug. This omission is causing people grief. It caused me grief and I see others having troubles in the issues for the example code repository.
The third change set, is just whitespace cleanup.
=> update quickstart-intermediate tutorial

authentication.md
Correct password column length in Authentication -> Database Considerations.
Ref: laravel/laravel#3670
=> Correct password column length in Authentication -> Database Considerations

migrations.md
When a database migration is being run on a table that contains an `enum` data type, and that migration involves modifying a column on the table, the following error occurs while running `php artisan migrate`:
```
[Doctrine\DBAL\DBALException]                                                                    
Unknown database type enum requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.
```
The error occurs because when a column is being modified with `->change()`, Doctrine's DBAL package iterates through the columns in the table in order to perform a diff for generating the appropriate `ALTER` statements. The package maps column data types (e.g. MySQL types) to PHP data types, but `enum` does not have a proper mapping and so it fails. Particularly, the …
=> Noting issue with modifying columns where an enum is present in the table

blade.md
Documented the `@continue` and `@break` directives under the Loops section of the Blade documentation page.
=> Document @continue and @break blade directives

upgrade.md
Was in the middle of an upgrade and ran into a migration error. This is mentioned in future versions of the docs, but this breaking change was not mentioned in the upgrade guide.
=> Add upgrade notes on the removal of doctrine/dbal

elixir.md
I think that most users can assume this is the case, especially since
this is who the second argument is used in the scripts method, but I
think it’s nice to see an example of it.
=> Adds a section describing alternate path and naming for browserify method.

releases.md
`bail` validation rule was added to Laravel 5.2 validator class. Need to mention that too in the release doc right?
=> Added Bail validation rule note

releases.md
Missed to add code syntax highlight by 4 spaces in  my previous commit.
=> Fixed missing '4 spaces' for code

elixir.md
This change seems trivial and useless, let me explain.
The *path* in the example now following the same naming convention as the CSS examples above, and it uses an redundant yet reasonable *path*, to avoid the confusion and misread with src path `resources/assets/js`.
=> Improve browserify example

configuration.md
For PR [#11844](https://github.com/laravel/framework/pull/11844)
=> Load .env file if it matches the current environment

eloquent-relationships.md
Added that the morphMap should be added in the boot function of a service provider, and added the FQCN of the Relation class used to the example code, so that users are not confused about what/where the namespace of the Relation class.
=> Added morphMap details

authentication.md
In the Authentication docs, under "Adding Custom User Providers" there is an overview of the `\Illuminate\Contracts\Auth\Authenticatable` interface - it had descriptions for all methods except `getAuthIdentifierName` so I've added one in the same style as the other descriptions.
=> Description of getAuthIdentifierName missing from Authenticatable interface

documentation.md
The link to the documentation on Contracts was missing from the main menu. The link has been added under Architecture Foundations between Service Container and Facades.
=> Add a link to Contracts in documentation menu

routing.md
Refers to issue at https://github.com/laravel/framework/issues/12131
=> Restore documentation for Regex Route Constraints, removed in fa6e3c1

eloquent-relationships.md
Alphabetical and singular naming convention of the pivot table name.
This change should probably be done in Master branch as well, as it might confuse some people.
=> Naming convention pivot table name

queues.md
This matches with the existing convention on line 425 of `queues.md`.
=> Update 'connection' to 'connection-name' for clarity

homestead.md
backslashes in path need to be escaped for windows:
vendor\\bin\\homestead make
using forward slash works as well:
vendor/bin/homestead make
=> homestead make - path escaped for windows

testing.md
The behavior I reported in https://github.com/laravel/framework/issues/12874 turns out to be the expected one. And it has indeed a pretty straightforward solution, however I couldn't find a mention to this in the Testing section of the documentation.
This PR adds a note addressing this particular topic. I think it might save developers some time if they come across this.
=> Add note regarding testing environment variables

events.md
Not relevant for the code samples.
=> Remove un-used imports

quickstart.md
Salutations. This PR updates the quick start example to remove the 'web' middleware group reference.
Bye.
=> Remove unnecessary 'web' middleware

eloquent-relationships.md
Added comment to reflect the fact that the local key can be different from `id` if not specified in `hasOne` but overwritten in `$primaryKey`.
=> `$primaryKey` is not necessarily `id`

migrations.md
The IP and MAC address types were [pulled](https://github.com/laravel/framework/pull/12884) and released with 5.2.27. I am proposing we add it to the schema builder column types documentation.
=> Update column types table with newly added types.

migrations.md
I'm new to Laravel, and didn't know you should drop foreign keys and re-add them when renaming tables. After making this mistake for a while, I eventually had rebuild all of the migrations on one of my projects. I figure I can't be the only one who's made this mistake.
=> add a note to migrations about dropping foreigns when renaming a table

eloquent-mutators.md, queries.md
- Changed "passing Closure" to "passing **a** Closure" as phrased elsewhere in the Laravel documentation.
- Changes "where exist" SQL clause to "where exist**s**" reflecting the real SQL instruction name.
- Changed a '<' to '>' because '<' seems not handled properly at parsing time thus resulting in a syntax highlight error in the Laravel documentation web page.
=> Fix wording

filesystem.md
This is explained here: http://taylorotwell.com/spark-storage/
But is not explained on the docs. I added it to make the 'standard' clear for everyone.
=> Add Public Driver explanation

database.md
I spent quite a bit of time trying to figure out how to configure the local SQLite database within the `.env` file.
In config/database.php, the sqlite section contains:
```
'driver' => 'sqlite',
'database' => env('DB_DATABASE', database_path('database.sqlite')),
```
I couldn't find in the existing documentation a way to (re)use this function `database_path` and it was only after searching online and trying both relative and absolute paths that I made it work. The answer is that it works with an absolute path.
It might be useful for others to see how to configure SQLite within .env file.
=> Add SQLite section and indicate .env configuration required

session.md
This anchor referenced here:
https://raw.githubusercontent.com/laravel/docs/master/installation.md
https://laravel.com/docs/master/installation#configuration
Configuration > Additional Configuration
```
- [Session](/docs/{{version}}/session#configuration)
```
> **Note:** This issue affects **5.1** & **master** branches too.
=> Add missing anchor reference

scheduling.md
Looks like the `reject` method doesn't exist in Laravel 5.2, and is instead called `skip`.
=> Change reject to skip

queues.md
Reconnecting to the database manually is no longer necessary (https://github.com/laravel/framework/pull/10609)
=> Remove section recommending DB::reconnect() on daemon workers

homestead.md
There is no need to wrap a function inside an alias
=> Replaced bash alias with bash function

errors.md
Sentry is mentioned in various places in Laravel, but historically has never been supported super well. This adds a link to the new (official) integration for Sentry + Laravel. We're about to start pushing back hard on "logging is not error reporting", and are trying to move away from the Monolog-as-a-default handler (which has its own problems in Laravel, that we'll hopefully provide a solution to in a followup PR).
Might be worthwhile to actually split this off from the paragraph and do some kind of "Third Party Services" section. Happy to help improve this, just let us know your thoughts for overall direction.
=> Link to Sentry's Laravel integration

filesystem.md
As far as I've been able to find there's no documentation on how the Storage facade is expecting you to pass visibility. It's a little different than Flysystem (which is expecting an array for the `put` method and not a string), so I figured there should be a little blurb about it on the docs.
=> Adding file visiblity documentation.

queues.md
Make sure it's clear you need supervisord for the daemon process to restart, as queue:restart only stops it
Related to: https://github.com/laravel/framework/issues/11821
=> specify queue:restart command only stops process

valet.md
- Use tap prefix for `homebrew/php/php70` so that the repository is automatically tapped if necessary
- Skip all the services related checks: calling `brew services ...` will automatically tap it silently
=> Simplify valet docs

valet.md
Just updating the introduction of Valet’s page so that it does not mention PHP’s built-in server any more.
=> Valet doesn’t use PHP’s built-in server anymore

helpers.md, quickstart-intermediate.md, quickstart.md, testing.md
Do not use `{!! !!}` on `Htmlable`s.
`routing.md` shows `csrf_field()` with the blade template syntax `{{ }}`, while on other pages it is wrapped with `{!! !!}` which is quite misleading.
=> Do not use {!! !!} on Htmlables

envoy.md
I had to look around a bit to find out that you can use Envoy locally. I thought it would be great if it was reference at the docs.
Reference:
https://github.com/laravel/envoy/pull/43
=> Adds localhost server reference to envoy.md

validation.md
Match dimension validation anchor name and make heading lowercase for consistency.
=> Fix broken anchor name

errors.md
Although the default log setting is `single`, as mentioned above on the same page, this paragraph said that the default is `daily`. This PR corrects that.
=> Fix log documentation

migrations.md
This appears to have been into Laravel since 5.0 but never documented here. 
https://laravel.com/api/5.0/Illuminate/Database/Schema/Blueprint.html#method_dateTimeTz
Postgres has such specific types.
=> Add dateTimeTz,timeTz,timestampTz to avaliable column types

envoy.md
All the code in the @after is actually executed as php, so the {{ @task }} gets compiled to "<?php echo $task ?> ran in the <?php echo $task ?> environment." which makes it actually not show, losing the braces will make it just parse the variable
=> Update to @after with variables

queries.md
This is just a request to add a missing quotation mark to the **whereColumn** example.
=> Add missing quotation mark

errors.md
This documentation ties in with changes in https://github.com/laravel/framework/commit/fbd6e7793766c4b3671328b80fb315391f11a3ed that were tagged in [v5.2.35](https://github.com/laravel/framework/releases/tag/v5.2.35) of the framework.
=> Add documentation about configuring the log level

session.md
In line with changes submitted in laravel/framework#13889, this documentation change outlines the addition of the `exists` method, as well as the difference to the `has` method.
=> Add documentation for exists method

eloquent-collections.md
As the [CommonMark specs](http://spec.commonmark.org/0.22/#html-blocks) state, an empty line between HTML and MD blocks is mandatory.
=> Add empty line to comply to CommonMark guidelines

testing.md
if you have a large number of models or many factory types for each model, having them all in the `ModelFactory.php` file quickly becomes unmanageable.  this note explains to users they are free to create multiple files in the `factories` directory, and they don't all have to go in the `ModelFactory.php` file.
IMHO I think multiple files should be the preferred and encouraged way. In fact, we could even make an Artisan `make` command for it as well. Wondering what your thoughts are on that?
=> add note for creating multiple factory files

valet.md
In discussion with @adamwathan, .local usually works fine with Homestead because it's explicitly mapped in the hosts file, but it looks like the OS X DNS resolver gets priority over Dnsmasq. 
https://support.apple.com/en-ca/HT201275
=> Use `.app` as alternative domain because `.local` is reserved by Mac OS X

testing.md
This caught my eye as the backticks show the contents differently in the Markdown code formatter.
=> Fixed backticks to single quotes

errors.md
`'log_level' => app_env('APP_LOG_LEVEL', 'debug'),`
should be
`'log_level' => env('APP_LOG_LEVEL', 'debug'),`
=> env not app_env

valet.md
Super pedantic, but the correct name is HTTP/2, as per [the homepage](https://http2.github.io/).
Formatting for RAM usage I've fixed as per formatting seen [here](https://en.wikipedia.org/wiki/Random-access_memory#Virtual_memory).
=> Fixed correct name for HTTP/2

authorization.md
`AuthorizeRequests` throws a `Illuminate\Auth\Access\AuthorizationException` not a `HttpException`.
=> [5.2] update authorization.md - exception thrown

queues.md
The current documentation (`5.2`) does not include any details about pushing jobs to different queue connections (although the functionality exists in the `Illuminate\Bus\Queueable` trait). Through this PR we hope we can contribute to making this easier to understand for other developers.
=> Updated queues doc to include details for pushing jobs to multiple queue connections

eloquent-mutators.md
As there is already "get" prepended to the method, "studly" case is correct I think. "studly" case is used in example as well.
=> StudlyCase instead of CamelCase

validation.md
The current implementation doesn't use `filter_var` but a regex.
See https://github.com/laravel/framework/blob/5.2/src/Illuminate/Validation/Validator.php#L1488-L1512
=> validation: remove mention of filter_var

collections.md, helpers.md
Scanned every file of the documentation and added empty lines (when needed)
Now the HTML method lists are compiled correctly under all MD compilers
=> Empty lines in favor of CommonMark guidelines

blade.md
Rest of similar control structures in the file have a space between the directive name and opening parentheses. This will correct the inconsistency.
=> Add a missing space to block-style control structures

authorization.md
In the Defining Abilities section from [Authorization](https://github.com/laravel/docs/blob/5.2/authorization.md) the following example doesn't work as expected:
```
$gate->define('update-post', function ($user, $post) {
return $user->id === $post->user_id;
});
```
In this case, the operator '===' won't return true even if the user id match the post id. Changing to '==' fixed the problem by comparing only by values, not by type.
=> Fix return of Defining Abilities example

validation.md
It's not clear from the docs what shape `ratio` should be, so I wanted to specify it.
I'm not sure whether the second code block was necessary, so feel free to drop if appropriate.
=> Add note about expected image validation ratio syntax

migrations.md
As noted by mzur, `json` and `jsonb` column types are not supported atm.
Will be resolved in 5.3 but needs notice for 5.2.
https://github.com/laravel/framework/issues/14356
=> [5.2] Add json to unsupported column types doctrine

eloquent.md
I have made an attempt to document the new cursor() method introduced here - laravel/framework#13030 .
I have also added a note about how chunking operates to prevent any gotcha moments.
Given that cursor() achieves chunk(), but with a more natural behaviour, should chunking documentation be updated or removed? Or is the note sufficient.
=> Documentation for new cursor method.

collections.md
Updated slice documentation to reflect that they preserve indexes by default and instead of an option you should use `values` to reindex.
See https://github.com/laravel/docs/issues/2428 and https://github.com/laravel/docs/pull/2437
=> Collection slice no longer has option to preserve indexes

quickstart-intermediate.md
The user's id attribute is an unsigned integer, the user_id of the tasks model should also be unsigned.
=> made user_id unsigned in quickstart-intermediate to be consistent 

eloquent-relationships.md
I think comments example is more easy to understand since `likes` table structure in current docs almost identical to Many To Many Polymorphic's `taggables` table, and may be confused as `likes` is a pivot table. 
Showing that `comments` table is not the same as `taggables` and may contain, for example, `body` column, makes documentation more clean.
=> [5.3] Use Comments instead of Likes in Polymorphic Relations example

broadcasting.md
Edit the wording since the subsequent paragraph says to return `false` for unauthorized users.
=> Tweak wording

upgrade.md
Your method should just expected the authenticated user instance
expected should be expect.
Sorry if I am not doing this right or if this is too small of an issue to merit this fork, first time trying to contribute.
=> Typo on Calling Policy Methods With Class Names

billing.md
After a while searching how to configure the Cashier currency I found a solution that I think must be in the docs.
I tried to explain it the easiest way possible.
=> [5.3] Add Cashier currency configuration

eloquent-relationships.md
Rejected in #326 but I think this is still useful (also given all the upvotes on http://stackoverflow.com/questions/17472128/preventing-laravel-adding-multiple-records-to-a-pivot-table/22885499#22885499 it suggests it's a real 'thing')
=> Note detaching parameter in sync()

filesystem.md
In two places the public storage folder was said to be storage/public but it is storage/app/public like it is said elsewhere in the doc, and in the official laravel/laravel repo.
=> Fixed path to storage/app/public

frontend.md
Vue is more of a library than a framework.
=> Rename Vue to a library instead of a framework

upgrade.md
fixed console error thrown:
$ php artisan clear-compiled
[Symfony\Component\Debug\Exception\FatalThrowableError]
Class 'Illuminate\Database\Eloquent\Relation' not found
=> fixed path for Relation

upgrade.md
Apparently the jobs table no longer requires the 'reserved' column. New jobs will fail to be created if this column is still present since it is not nullable.
=> Add 5.2->5.3 upgrade note for the jobs table

upgrade.md
The <code>make:auth</code> command uses <code>Auth::routes</code> method in route’s stub.
Check this commit: https://github.com/laravel/framework/commit/f33a735d959ba1a572a678b386598fd79bd26e52
=> Use Auth::routes instead of Route::auth

errors.md
Looks like the brand name for Bugsnag has the S lowercase, so I've updated it in the docs.
=> Make S in Bugsnag lowercase

structure.md
Now that `routes/console.php` is official, it needs to be included in the docs. :smiling_imp: 
I stole the description from other documentation and the comment in the file, but feel free to replace with something better.
=> Add console.php to the routes directory section

valet.md
And added upgrade instructions
=> [5.3] Update outdated Valet Release Notes to point to github

notifications.md
You probably only want to mark unread notifications, you don't want to update the `read_at` timestamp where it is already set.
=> Change notifications mass unread examples

authorization.md
`<a name="writing-gates"></a>` was missing.
=> Fix 'Writing Gates' link in Authorization docs

releases.md
Changed “without requiring your application use any given JavaScript or
CSS framework” to “without requiring your application to use any given
JavaScript or CSS framework”
=> Missing word in "Frontend Structure" section

upgrade.md
I found a [breaking change to the framework](https://github.com/laravel/framework/pull/13709) that isn't yet documented.
The framework [calls this method](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Exceptions/Handler.php#L135) but it was removed from the [base handler](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Exceptions/Handler.php) in favor of it being provided in the [app skeleton](https://github.com/laravel/laravel/blob/master/app/Exceptions/Handler.php#L50)
Projects going through an upgrade will be missing this method.
=> [5.3] Add unauthenticated method to exception handler

homestead.md
Remove HHVM references from Homestead docs in 5.3 to prevent confusion since HHVM support has been removed.
=> Remove HHVM references from Homestead docs

collections.md
These were new methods added recently to the collection class. The mapWithKeys example is from @adamwathan blog post, just updated for the changes that were made when the method was pulled into the core. I wasn't sure how best to do an example for the pipe method, so I just used the test case.
=> Added missing collection methods

database.md
Does not currently have a section in v5.3+ docs for multiple db connections on this page
=> Remove Invalid anchor link for Multiple DB Connections

broadcasting.md
Remove "extends Event" on ServerCreated class, since there in no App\Events\Event class anymore.
=> [5.3] Remove "extends Event"

migrations.md
This reverts commit 0fb2802faf24629f93568bc6abec28e05fd871cd.
As stated in the commit, json and jsonb work again in 5.3.
=> Revert "Add json to unsupported column types doctrine"

eloquent.md
After encountering an issue with mass deleting not calling the `deleting` and `deleted` events, I have added a note.
See issue: https://github.com/laravel/framework/issues/14427
=> Added note about missing mass deletes with events

notifications.md, packages.md
Make `--tag` syntax consistent with the rest of the docs.
=> Update vendor publish --tag syntax

notifications.md
The linking to Customise the templates wasn't working. there was a missing 's'
=> Notifications.md Customise the templates proper linking

queues.md
This update adds some context to the SQS disclaimer without adding too much more text. Since SQS handles queues in such a different manner, some further description could be helpful. I originally spotted the SQS disclaimer while re-reading the docs and the callout was definitely useful in the fact that I could disregard my failed-jobs issues, but left me with nowhere to go. Not sure how Laravel likes to use vendor URLs in documentation, so please close this PR if that's not acceptable, or I can re-write to use link-less descriptions.
=> Updates SQS disclaimer.

upgrade.md
References https://github.com/laravel/framework/issues/15366
The operator of the join clause is now checked by the query builder and must be one of these:
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Query/Builder.php#L192
=> [5.3] Add a note about a join clause

billing.md
Fixes this issue Laravel Cashier.
https://github.com/laravel/cashier/issues/225
Without the docs and to know you need to set it up you get this error:
`Type error: Argument 1 passed to Carbon\Carbon::lt() must be an instance of Carbon\Carbon, string given, called in /home/vagrant/pagefog/vendor/laravel/cashier/src/Billable.php on line 153`
=> Added mentioning setting up the date mutator for trial_ends_at on model definition

upgrade.md
Related to laravel/internals#181
Since laravel/framework#15375 wasn't merged, now ```as``` behaves differently than what ```prefix``` did before.
It requires an ```.``` at the end of the name in order to it be equal to the previous ```prefix``` naming.
Using ```prefix``` you would get ```admin.*``` meanwhile ```as``` generates ```admin*```
Also note that ```as``` doesn't append the name to the url, so you need to use both to maintain the behavior., not just replace ```prefix``` with ```as``` the doc's currently state's.
=> As behaves differently than the previous prefix

filesystem.md
When passing in a file name as the third argument, use putFileAs(), not putFile()
=> Fix method name

upgrade.md
In the `create_failed_jobs_table` migration, it uses `longText` type for `exception` column.
=> Change exception column type from TEXT to LONGTEXT

elixir.md
Make the path in the example block of code consistent with the path in the paragraph that introduces it.
=> Fix path in Webpack example

routing.md
Remove the Word  "implicit" because Customizing works for booth, implicit and explicit.
=> Remove  Note for only "implicit" binding Key Customizing

authentication.md
I came to know about Socialite only after seeing the **Social Authentication** heading in the v5.2 docs under Authentication.
I think it will help others too if we were to include it here.
=> Add path for Social Authentication

scout.md
In cases where you have unpublished/unwanted configs from other vendors and want to publish only scout.php
=> Publish only Scout Provider config

homestead.md
The current command (`vagrant provision`) wasn't working. This new one does and follows the documents own advice earlier on.
=> Change 'Adding Additional Sites' command to one that works

notifications.md
This PR adds documentation for the fresh new `to` and `from` methods on the `SlackMessage` notification.
https://github.com/laravel/framework/pull/14910
English isn't my first language, so feel free to tear me a new one if it reads funkily. I'm also thinking it might be a good idea to add screenshots. Thoughts?
=> Documented for the `to` and `from` methods on the SlackMessage class

installation.md
Updated path for Laravel installer `~` with `$HOME` in order to make it work in your `. bashrc` or `.zshrc`, using path as `~/.composer/vendor/bin` is not working
=> PATH for Laravel installer updated

upgrade.md
This PR adds a note about the newly required extension in Laravel 5.3.  There are several [search results](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=laravel%20pcntl) for people running into this issue and there's an [exception handling the error clause](https://github.com/laravel/framework/commit/40438b3b88d7164f3c18f463ee1587bde9ad8ef4#diff-8cb7a41b646a3fd1e7e37a6766a5dc75R69).  This adds a note to those considering upgrading so they understand the need to modify production environments during/prior to upgrading.
=> Added note about pcntl

broadcasting.md
Laravel Echo has an undocumented .leave() method, found here: https://github.com/laravel/echo/blob/a2cfe102b20b50d28fc9fe4894d2c557757058cd/src/echo.ts
I have added it to the Laravel Docs.
=> Added documentation for the Echo.leave() method.

eloquent-relationships.md
Querying relationship absence is currently missing in the documentation this adds a small section outlining the use of the methods `doesntHave` and `whereDoesntHave`.
=> Add `doesntHave` and `whereDoesntHave` docs

redis.md
What's still missing from the documentation is the difference in connection parameters.
Predis and PhpRedis both support:
- `host`
- `password`
- `port`
- `database`
- `timeout`
- `persistent`
Predis supports these:
- `scheme`
- `path`
- `async`
- `read_write_timeout`
- `alias`
- `weight`
- `iterable_multibulk`
- `throw_errors`
PhpRedis supports these:
- `read_timeout`
- `prefix`
Especially the `read_write_timeout` and `read_timeout` is noticeable. I tried to prevent that, but https://github.com/laravel/framework/commit/bae60487cd2749eb57d2e2eeb7bf8c3ce71ef3ec#diff-dbfdb06f6a76b9f93f18f77fa7f4b298 reverted my attempt.
I'm not quite sure how to mention that without adding new sections. Any suggestions?
=> PhpRedis Support

upgrade.md
Otherwise instructions like "take special note of the passwords.users.email configuration option in the new auth.php" are confusing, as passwords.users.email no longer exists in the master branch version of the file.
=> Point to 5.2 version of config/auth.php (rather than master)

facades.md
The `Password` facade uses the `auth.password` as the accessor which is an instance of `\Illuminate\Auth\Passwords\PasswordBrokerManager`.
=> [5.3] Fix class name

mail.md
This just adds some information about how you can use the `ShouldQueue` contract on a `Mailable` class so that it will always be queued by default, regardless of whether you call `send()` or `queue()` on it. 
The `ShouldQueue` contract is in the mailable stub (though the class doesn't implement it by default) but I think it's worth documenting why it's there and how it can be used.
=> Add information about the ShouldQueue contract

eloquent.md
The @return in the docblock is void, but the code is returning the $builder.
I also checked the source code and it's not using the return value of apply()
=> Remove unnecessary retun

database-testing.md
documentation for [factory states](https://github.com/laravel/framework/commit/91694f75cadaa9d6c35f7522aa0a338c7f4099bf)
=> add documentation for factory states

passport.md
Based on someone asking for help for forgetting to add use Carbon\Carbon;
=> Add Carbon\Carbon trait to AuthServiceProvider in configuring passport

mocking.md
Config cannot be mocked.
I spent some time researching why my Config mocking would fail and found that people hit this trap more often than not.
* https://github.com/laravel/framework/issues/4072
* https://github.com/laravel/framework/issues/11273
* https://github.com/laravel/framework/issues/8979
I believe, by adding this note, you can decrease the amount of issues reported and thus save your time for actual development and improvements, rather than discussing issues that are known.
=> Complement note about facades not to be mocked

homestead.md
It took me far longer than I care to admit to learn that you could pass-through arbitrary configuration options to vagrant synced folders from within the homestead.yml. Maybe my rsync case makes a bad example, but I think the docs should mention the fact that you can do this.
=> Let people know they can pass synced folder options in the homestead.yml

queries.md
Use different and more clear values for the day and the month to avoid any confusion.
=> Update where date examples

broadcasting.md
I've had some trouble finding out why my pusher.com didn't work, and that was because I didn't specify cluster and encrypted options.
I think it would be a good idea to have it in the documentation.
=> Add documentation for when using cluster and encrypted

passport.md
Added missing parameter 'client_secret' to the request all token example in passport.
=>   Missing Parameter in Passport Example #2781

authentication.md
There is no AuthController in Laravel 5.3+, so manually authenticating user should be done in LoginController now
=> Change AuthController to LoginController

configuration.md
currently it's undocumented that you can use a different .env file based on the app_env. This is needed when running tests that call artisan which won't respect environment variables defined in phpunit.xml
=> note that you can use a different env file when testing

database-testing.md
Currently the docs state testing with transactions trait can only work with default db connection but it can actually be used with any defined connections
=> transactions trait can be used with multiple database connections

collections.md
While the documentation still states that the default is strict and whereInLoose is the second method i found out that 5.3 now uses "loose" comparison and added a new whereInStrict method.
This pull request reflects the changes.
=> Change whereInLoose to whereInStrict and update the comparison type

authentication.md
This PR adds some additional clarity on how to change the default user key for authorization from `email` to something else, such as `username`. This is a common question that comes up from other devs, and since this behavior changed between 5.2 and 5.3, it seems like something that the docs could benefit from having.
Happy to make copy-edits, if requested.
=> [5.3] Authorization - Customizing `email` to `username`

migrations.md
Due to the doctrine dbal being used for the change method, not all column types can be changed.
As suggested by @GrahamCampbell in issue [#9636](https://github.com/laravel/framework/issues/9636) I'm submitting a PR for the docs.
=> Document unchangeable column types.

homestead.md
This is a pull request to fix a small typo where the noun "schedule" appears to be the intended word.
=> Fix small typo

collections.md
It better describes what's going on.
With the current example, there's no way from the code itself to see that we're checking keys and not values.
=> Use truthy example for has

configuration.md
With single quotes I get this error:
```
[Symfony\Component\Console\Exception\RuntimeException]
Too many arguments, expected arguments "command".
```
With double quotes it works fine.
=> Replaced single quotes with double quotes in Artisan command

eloquent.md
Instead firstOrCreate, newOrCreate is documented and there is no method "newOrCreate".
=> Wrong method name fixed

routing.md
I've fixed the examples of explicit route model binding.  In the current examples `$router` is used when the text refers to the `Route` facade.  This was probably missed from 5.2->5.3 since the parameters for `boot()` were removed in 5.3.  This change makes it more consistent.
I also added context of location to the example of a custom resolution using `Route::bind()` by wrapping the example inside the `boot()` method of the service provider.  The reasoning is the previous example shows putting the explicit binding in the `boot()` method, then refers to adding a route to the route file.  Adding context back to the `boot()` will make it more clear that we are back in the `RouteServiceProvider`'s `boot()` method rather than in the route file.
Hope these changes make sense,
Luke
=> Consistency and better context to route binding

passport.md
The sentence "The request should include the authorization code that was issued by when the user approved the authorization request" sounds awkward without the phrase "your application" after "issued by".
=> Fix typo in passport.md

helpers.md
Updated e()'s description by saying it runs htmlspecialchars instead of htmlentities.
=> Update e()'s documentation

artisan.md
Programmatically has two m's in it.
=> Programatically -> Programmatically

database.md
Updated docs to reflect new attempts parameter on DB::transaction as per https://github.com/laravel/framework/pull/14931
Language felt a little clumsy so please do edit if you can make it clearer.
=> Update database.md to document transaction retries

validation.md
The first or the last can be removed here. I chose to remove the first one ;)
=> Remove duplicate "For example" text

valet.md
Not that it's a big deal in the grand scheme of things but I notice the return type in the example for the `serves` method was `void` but doesn't the `is_dir` method return a boolean (ie. true or false), so the return type should be `bool`?
=> Fix return type for `serves` method example

elixir.md
Because of the `}}` blade vars (since it's HTML), it fails to show as a proper code block in the docs at the moment.
=> Fixed HTML code blocks

valet.md
When upgrading from v1, since it's semantic version, `composer global update` will not update anything. You need to run `composer global require laravel/valet` again.
=> Add a note when upgrading Valet v1

homestead.md
Navicat is not free / only has a short trial period. Sequel Pro is Mac OS X only. HeidiSQL is OpenSource, runs on Windows as well and is easy to use
=> Add HeidiSQL as alternative for GUI Database tool

queues.md
The example is what I use in my projects.
Another example is Laravel-Bugsnag batch sending report option. Inside a daemon queue worker instance, it flushes the report buffer on looping event.
The same technique may be used elsewhere, for example when sending events to Google Analytics.
=> [5.3] Document looping event

security.md
When trying to implement the reminder functions I missed the fact that the views are using Blade functionality and that a `password.remind` view should be stored as app/views/password/remind.blade.php. I think this is now more obvious.
=> [4.2] Changed Password Reminder Controller explanation

migrations.md
I don't know how to better describe that fields will be nullable:
```
Adds unsigned INTEGER `taggable_id` NULL and STRING `taggable_type` NULL
```
Or:
```
Adds nullable unsigned INTEGER `taggable_id` and nullable STRING `taggable_type`
```
=> Add nullableMorphs in migrations

database-testing.md
There is no example of Factory Type ( method 'defineAs') in 5.3 docs
=> Remove example of factory type

authentication.md
The Events section of the Authentication page currently only documents six of the possible seven events that are raised by Laravel during the login and registration process.  This PR adds the `Illuminate\Auth\Events\Failed` event, in the same way as the other events are listed.
=> Add Login Failed Event to Events List in Authentication

packages.md
As mentioned here - https://github.com/laravel/framework/issues/16991 - this is expected behavior. 
So just documenting it to make it clear that multi-dimensional arrays can be partially filled by users, and the missing sections wont be filled by the `mergeFromConfig()`
I'm open to better wording on this to make it clearer if anyone has any ideas...?
=> Clarify mergeFromConfig() limitation

broadcasting.md
Since we're already using ES6 arrow functions, we might as well use template literals.
=> Use ES6 template literals

broadcasting.md
```js
// Moved from most likely unintentional:
Echo.private(`App.User.${userId}`
)
// to:
Echo.private(`App.User.${userId}`)
```
=> Removed an unnecessary linebreak

queues.md
I noticed the `--sleep` option has disappeared from the docs?
Is this intentional?
If it is intentional - then there needs to be a different PR to remove the reference to `--sleep` from the supervisor demo code that still includes it there...
=> Update queues to add sleep

migrations.md
Added type hinting in `$table` in all examples, and not just part of them.
=> Made schema docs a little more consistent

cache.md
The false negatives are a breaking chance from 5.3 -> 5.4 and should probably be mentioned in the upgrade guide for 5.4.
=> Mention PhpRedis and false negatives.

cache.md
Maybe good to mention:
> {note} You should not store `null` values into cache, because `null` values will be regarded as cache miss when retrieved, e.g. via `Cache::has()` method.
Although I disagree, `false` is considered as a miss in 5.4 as well. If it remains so, it should be documented as well.
=> [5.3] note on caching null values

authorization.md
Duplication of pretty much the same tip from the section above, "Policy Methods"?
{tip} If you used the `--model` option when generating your policy via the Artisan console, it will already contain methods for the `view`, `create`, `update`, and `delete` actions.
=> Removes tip duplication

upgrade.md
The updated Queue::failing method was not mentioned in the upgrade guide. I just ran into it, so I updated the docs accordingly.
=> Added a section about Queue::failing

packages.md
Package developers all-too-frequently resort to putting closures in their config files. While this is an anti-pattern, it appears to work fine until a user tries to do `php artisan config:cache`, at which point the closure is not serialized correctly and the app breaks.
This PR is a (probably futile) attempt to make package developers aware of this issue before they cause it :)
=> Add a note about not using closures in config files

cache.md
Document `false` behaviour in `Cache::has()` that's mentioned in https://github.com/laravel/docs/pull/2953.
=> Mention `false` behaviour in `Cache::has()`

homestead.md
Updated yaml and hosts config for additional sites section
In order to clarify the instructions, I added an example project to the Homestead.yml sites configuration example. I illustrated this because in forums, people were updating the folders section instead of sites. I also added the instructions for /etc/hosts because that detail was omitted from instructions.
=> Laravel 5.4 Homestead instructions

broadcasting.md
- Socket.IO serves the client SDK by default. The CDN is not maintained/updated and is currently out-of-date (Current version is 1.7.2 and 1.4.5 is 1 year old)
- The socket should usually run on the same domain to provide session sharing. Otherwise authentication will fail (eg. when using IP instead of host). Also simplifies multiple environments, domain aliases etc).
=> Use app host for Socket.IO script + websocket

eloquent-relationships.md
Add a note to advise that Custom Intermediate Table Models must extend Illuminate\Database\Eloquent\Relations\Pivot.
=> [5.4] Custom Intermediate Table Models must extend Pivot

eloquent-relationships.md
`Methods` by definition are associated with an object, so given that the relationships are defined in the `Eloquent Model`, it makes more sense to called them `methods` instead of `functions`.
=> [5.4] Use methods concept instead of functions

collections.md
The example for `every()` was incorrectly calling `first()`
=> Fix typo in Collection docs

releases.md
There was a typo "you may defined custom models" should be "you may define custom models"
=> [5.4] Typo fix Custom Pivot Table Models section.

frontend.md
Replace references to elixir and gulp with mix and webpack
=> [5.4] Change references to elixir and gulp in JavaScript & CSS Scaffolding

upgrade.md
Not sure where you want to stick this, but it is pretty important to run `view:clear` to avoid all sorts of view errors once the 5.4 upgrade has been completed. I don't think it is common knowledge to run this command after an upgrade. I don't mind if you close this PR and add the info in yourself where appropriate.
=> [5.4] Add note to run php artisan view:clear

mix.md
Fix for a small typo in a file path in the 5.4 Mix documentation.
=> Fix typo in Mix docs

upgrade.md
This one caught me out when upgrading, thought it might be worth mentioning:
5.3
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Routing/UrlGenerator.php#L291
5.4:
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Routing/UrlGenerator.php#L485
=> [5.4] Document forceSchema change

upgrade.md
Failing to remove 'laravel-elixir' from package.json causes very confusing errors with Laravel Mix that cost me several hours of debugging. I have seen other people dealing with this issue, so I think it would be a good idea to include in the upgrade guide.
=> Migrating Laravel Elixir to Laravel Mix

notifications.md
When looking at the "Using The Notifiable Trait" section of the docs - there is no example of the minimum code requirements.
There are examples further down - but they are for different things. This just shows the minimum code required for a User, to help when browsing the docs.
=> Include Notification Trait example

redis.md
It should be `clusters` instead of `cluster` :)
=> [5.4] Fix clusters key

blade.md
passing strings through the slots is incredibly easy and well documented, but I ran into an issue when trying to pass PHP constructs through, like arrays or objects.  I was able to pass it as the second argument to the slot, and it worked fine.  I'm curious if this is the intended operation, and if so I'd like to add some documentation on it.
=> update slot documentation

passport.md
Now that Laravel 5.4 is out, and Passport has a 2.0 release to go with it, the composer require command in the 5.3 docs needs to explicitly target the 1.0 release
=> Update Passport install instructions

billing.md
Stripe doesn't use credit card token (it's another entity) in case of creating subscriptions. To manage subscriptions you need `stripeToken` - it's not related to credit card, but to a complex of data. Using it you can obtain other info and store subscriptions as usual.
See https://stripe.com/docs/recipes/subscription-signup 
I think the variable must be with the same name, like in original Stripe documentation.
=> Misunderstanding in variable names fix

upgrade.md
Useful if the developer created his own validator class and overrides the following methods.
=> [5.4] [Upgrade] Add information about API change in Validator class

mix.md
Less compiles to 'public/css/app.css' rather than 'public/css/app.less'.
=> Fix less output filename

http-tests.md
The docs contain a kind of misleading note about the assertJson method, this fixes it along with #3075.
=> Correct the note regarding assertJson

http-tests.md
This PR adds a note about `TestResponse::assertJsonStructure()` method.
🌵
=> Add note about assertJsonStructure()

releases.md
Since 4.1 documentation is not available on the web isn't necessary to keep its release notes.
=> Remove 4.1 release notes

authentication.md
Add simple return example. Clarifies redirectTo() method, if used, should return a path string.
=> Example for redirectTo() Method

upgrade.md
added changes for `assertNotFired` to `assertNotDispatched`
Tests are passing. This looks legit. 👍
=> Updated to reflect changes to Event Fakes in 5.4

mix.md
The [documentation for `mix.version()`](https://github.com/laravel/docs/blob/5.4/mix.md#versioning--cache-busting) says (emphasis mine):
> **When executed in a production environment** (`npm run production`), the `version` method will automatically append a unique hash to the filenames of all compiled files, allowing for more convenient cache busting
However, Mix actually creates the hashed names whenever you run it with `version()`, whatever environment you are in.  This has been updated [today](https://github.com/JeffreyWay/laravel-mix/commit/27902ec2f6720e39156e9ed1b111c15fbfc634db#diff-bb1bd93b5077affc1930c467e3197e96L30) in the Mix documentation, so it should be updated here.
This PR also adds an example of how to run `version` only in production, as the docs used to say it did.
=> [5.4] Mix docs incorrectly say that `version()` only runs in production

blade.md
This removes the docs for the `or` functionality blade provides, and recommends the use of PHP's built in null coalescing operator.
=> [5.5] Recommend the null coalescing operator

upgrade.md
I'm catching up on some Laravel 5.1 -> 5.4 upgrades.
Following the 5.1 to 5.2 upgrade - I ran into a small issue, because the upgrade docs point to the master `auth.php` file - which is no longer valid for 5.2 (the email variable is missing due to a commit for 5.4)
So this PR points the upgrade docs to a specific version of the `auth.php` file, and thus wont be affected by any future changes in the file.
=> [5.2] Change to 5.1->5.2 upgrade docs due to master changes

helpers.md
When describing the `resource_path()` helper, there was an incorrect mention of the "storage directory" – likely due to copy & paste from the `storage_path()` helper docs.
This PR just updates that to say "resources directory" instead.
=> Correct reference to resources directory name

homestead.md
This commit (https://github.com/laravel/homestead/commit/06b52c7f8aa7aabe1ef6253268f4763de7b6cc7d) removes the `.homestead` directory, placing the `Homestead.yaml` file in the Homestead directory instead.
=> Removing references to the .homestead directory.

notifications.md
Update Slack Notification documentation for feature https://github.com/laravel/framework/pull/18011
=> Update Slack notification documentation

dusk.md
related to this Dusk PR
https://github.com/laravel/dusk/pull/140
=> add notes for random dropdown selection

mail.md
Wondered why my emails were escaping @components and stuff, doh!
=> Added note about indentation level on markdown emails

upgrade.md
As per this commit the `ConfigureLogging` bootstrapper is no more in 5.4. Seems the Monolog setup being moved to a base service provider in `Illuminate\Foundation\Application` https://github.com/laravel/framework/commit/919f21b3fddf47a25ef85167817a8827f59b271f#diff-67364880bdf444edbf5e384f3686b9b9
=> Add note about the removal of the ConfigureLogging

homestead.md
Hello,
I have added a little section to the documentation which explains that you can add additional Ngrok commands to the `share` command in Homestead.
laravel/homestead#499 is the pull request with the change.
=> Add information about adding additional Ngrok commands to the share option

collections.md
Since I ended the sentence with a dot in the whereNotIn documentation because I had copy pasted it from whereIn, this puts a colon in whereIn as well. :)
=> Change dot to colon

middleware.md
There was some confusion with some developers because the documentation seemed to say that terminable middleware has to be defined in your *global* middleware list, but in fact terminable middleware can be used as *route* middleware as well.  I also decided to specify the location of Kernel.php rather than just saying HTTP kernel, but that change may not be as necessary.
=> Terminable route middleware clarification

helpers.md
This behaviour is not intuitive as the parameter is set to true per default in htmlspecialchars.
=> e function sets double_encode to false

upgrade.md
Currently the Upgrade guide references a change in the API to
relations where the name of the `getForeignKey` method has changed
to `getForeignKeyName`  In reviewing the code and API docs this
doesn't seem to actually be true.
Example (https://laravel.com/api/5.4/Illuminate/Database/Eloquent/Relations/BelongsTo.html)
This commit removes the seemingly false reference.
=> Update v5.4 Upgrade Guide

mix.md
Fixed the React navigation link on the Mix docs, current anchor goes to #react-support which doesn't exist. Updated to #react to match the name used on the title.
=> Fix Mix navigation, Updated React anchor link to #react

collections.md
Documents the feature added by laravel/framework#17756
=> [5.4] Document Collection::tap() method

collections.md
Documents the feature added by laravel/framework#14657
Also updates the Collection::contains() documentation to outline its behavior and where they differ.
=> [5.4] Document Collection::containsStrict() method

notifications.md
To make something in Bold you need to use `*bold*` not `**bold**`
=> Correct example for sending markdown slack attachements

collections.md, eloquent-collections.md
I did a thorough review of collections's documentation and ended up with a few minor corrections and additions:
- Added missing average() alias method (synced Eloquent collections documentation)
- Added missing containsStrict() anchor (sorry to have forgotten this!)
- Added missing cross-reference links to contains(), containsStrict(), slice(), unique() and uniqueStrict() methods
- Added missing explanations about "loose" comparisons to where(), whereIn() and whereNotIn() methods
- Minor change to merge() method to state that it also accepts another collections
- Minor change to toJson() method to better describe the returned value
- Minor formatting fixes, mostly on code snippets
Just to make Laravel's documentation even more awesome. ❤️
=> [5.4] Misc improvements to collections documentation

collections.md, eloquent-collections.md
Syncs Laravel 5.2 collections documentation (including Eloquent collections)
**Added**
- Added 4 missing methods:
- average() (backports #3228)
- median() and mode() from laravel/framework#14305 (since v5.2.40; backports #3223)
- pipe() from laravel/framework#13899 (since v5.2.40)
- Added 15 missing methods to Eloquent collections documentation; all the listed above plus:
- avg() (since v5.1.18)
- combine() (since v5.2.24)
- diffKeys() (since v5.2.15)
- except() and only() (since v5.1.24)
- flatMap (since v5.1.25)
- max() and min() (since v5.1.2)
- union() (since 5.2.27)
- whereIn() and whereInLoose() (since v5.2.12)
**Changed**
- Backported all the great documentation improvements from newer versions (wording, examples, etc.) while not changing any API usage neither notes formatting (to …
=> [5.2] Sync collections documentation

eloquent-collections.md
It remained unchanged since 5.2 days and I forgot to fix it within #3230. Sorry to have forgotten this, this *loose* => *strict* change was a bit confusing to track. :+1:
=> [5.3] Replaced wrong whereInLoose() reference to whereInStrict()

session.md
In the session database table, user_id should be an unsigned integer.
=> [5.4] Change user_id to unsigned integer

upgrade.md
Makes clear the `composer.json`'s change is required even for those who skip the *"Running Laravel 5.3 & 5.4 Tests In A Single Application"* section.
It's a common issue when upgrading: https://github.com/laravel/dusk/issues/40#issuecomment-274961021
=> [5.4] Clarifies tests namespace change

collections.md, eloquent-collections.md
Syncs Laravel 5.1 collections documentation (including Eloquent collections)
**Added**
- Added 2 missing methods:
- average() (backports #3228)
- flatMap() from laravel/framework#11010 (since v5.1.25)
- Added 7 missing methods to Eloquent collections documentation; all the listed above plus:
- avg() (since v5.1.18)
- except() and only() (since v5.1.24)
- max() and min() (since v5.1.2)
**Changed**
- Backported all the great documentation improvements from newer versions (wording, examples, etc.) while not changing any API usage or notes formatting neither introducing things from them
- Improved contains() and unique() methods to describe their comparison behavior
**Fixed**
- Fixed a minor typo on forget() method code
- Fixed a wrong anchor link on where() method
This completes the work …
=> [5.1] Sync collections documentation

facades.md
`use Cache;` is too confusing without the full namespace, to be in the documentation. It looks like an error or distracts the users from the topic, unless there is an extra line added, talking about AliasLoader which will check the facade class from array of class aliases in config/app.php.
=> Update code in facades.md for simplicity

responses.md
Reason to add this back is because it is handy to know the functionality already sits in the framework.
=> [5.4] Added deleteFileAfterSend() back in the docs

configuration.md
- Moves two general-topic paragraphs from *"Retrieving Environment Configuration"* sub-section into the main *"Environment Configuration"* section
- Adds a security note about committing `.env` files
- Adds a general note to clarify that `.env` files variables can be overridden by external environment variables
- Makes the *"Retrieving Environment Configuration"* sub-section linkable
- Adds a tip to the *"Determining The Current Environment"* sub-section to mention that the `APP_ENV` variable could be overridden at server-level configuration
These are issues I often see when answering questions about Laravel, so I think they're a good addition to make the environment configuration documentation even better. 👍 
I'm certainly not very skilled at writing in english, so feel free to improve …
=> [5.4] Improve the environment configuration documentation

eloquent.md
There is a second argument to these functions ( [as you can see here](https://github.com/illuminate/database/blob/5.4/Eloquent/Builder.php#L334) ).
It's not said in the text but adding a second argument to the examples should be clear enough.
=> Clarify 2nd argument of firstOrNew & firstOrCreate (5.4)

events.md
Replace old "mocking-events" to "event-fake" HTML ID
=> Fix event-fake link

validation.md
While doing some work today, I ran into a scenario where I was trying to validate a text input that was allowed to be empty. This instance was the first time where I needed to use this functionality, so I did a quick google search for `laravel conditional validation`. The top result was the validation documentation page, with a quick link to `conditionally adding rules`. I thought this was what I needed, and the fact that the rule is named `sometimes` seemed to confirm that it was what I needed. It wasn't until a couple hours later that I noticed there was a small section in the document about optional fields and the `nullable` keyword was actually what I needed. 
I'm proposing a quick, one-sentence "heads up" to other developers who might of had the same thought process I did, and are …
=> [5.4] clarify `optional` and `present`

blade.md
I think this is just a typo.
So: @empty checks if the variable is empty and not if the variable is not empty (that would be @isset)
=> @empty checks if $records is empty

queries.md
Removed MariaDB 10.2.3 from the list of databases that support JSON columns. It does not, and likely won't until 10.3 at least. 10.2.3 *does* include JSON *functions*, but not a JSON column type.
To confirm, I installed a fresh install of MariaDB 10.2.5, created a new Laravel app, added a migration that included `$table->json('test')`, and confirmed that the migration failed.
=> Update query builder JSON docs

mix.md
The third (`flatten`) parameter of `mix.copy()` is weirdly set to `true` by default, causing [some confusion](https://laracasts.com/discuss/channels/elixir/copy-folder-structure-with-laravel-mix-laravel-54) to users. This PR aims to at least document this.
=> Document "flatten" parameter of mix.copy()

filesystem.md
There are two problems with the current text that this PR aims to fix:
- the Dropbox adapter doesn't come out of the box
- the current Dropbox adapter by the league only supports v1 of the Dropbox API, which [will be shut down on 28th of June 2017](https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/). 
This PR updates the section to make use of the an adapter that makes use of v2 of the Dropbox API. 
Fyi this adapter is also suggested [in the Flysystem docs](https://flysystem.thephpleague.com/adapter/dropbox/) and their [composer.json](https://github.com/thephpleague/flysystem/blob/fc5836b/composer.json#L44).
=> Update custom filesystems section

dusk.md
`assertPathIsNot` was added recently, but isn't documented yet. laravel/dusk#183
=> Add assertPathIsNot in "Available Assertions"

queues.md
I've had a discussion with a fellow Laravel Developer, where we actually disagreed on the actual meaning of the --sleep option in the Queue Worker.
This should clarify the expected behaviour.
=> Clarify what queue:work --sleep exactly does

passport.md
When using the laravel passport guide I got stuck when using the api with my own application. I figured out that laravel automaticly prepends the standard api route with `/api`.
That's why I updated th route in the api.
On a brand new laravel 5.4 I followed the passport installation instructions and the code
```
axios.get('/user')
.then(response => {
console.log(response.data);
});
```
threw a 404 Not Found. [Link to docs](https://laravel.com/docs/5.4/passport#consuming-your-api-with-javascript)
When updating the url to `/api/user` it finally worked. This is my first attempt on using passport tho, if i did anything wrong please correct me 😄
=> Issue with api url in passport.md

broadcasting.md
When you use echo in conjunction with a customer broadcastAs event name you need to prepend the event name in your javascript with a '.'
=> Using echo with custom broadcastAs

views.md
Added  $data to the example code as is referenced in the text but not present in the code snippet
=> Changing Code Example to Match Variable Reference in Text

database-testing.md
Documentation for https://github.com/laravel/framework/pull/19060
I don't claim to be great at writing documentation, but it's an attempt. Feel free to discard or rewrite.
=> [5.5] Adds documentation for inline factory state arrays

eloquent-relationships.md
This updates the documentation for `HasManyThrough` relations to clarify how the different keys are used, and to document the addition of https://github.com/laravel/framework/pull/19114.
I'm not quite happy with the (in my opinion) too technical wording of the explaining paragraph, so I will gladly accept proposals for change.
=> [5.5] Update HasManyThrough Documentation

homestead.md
Changed the port forwarding example ports to the same ports that are in the default Homestead.yaml config file to keep them within the allowed port range.
=> Port forwarding example out of range

broadcasting.md
The `ShouldBroadcastNow` is not mentioned, so would be nice to add. Could also be placed near the bit about `ShouldBroadcast Interface` instead.
=> Mention ShouldBroadcastNow

upgrade.md
Since [#16283](https://github.com/laravel/framework/pull/16283) an exception is thrown when the query builder's `chunk` method is called without an `orderBy` clause.
This PR adds documentation to the upgrade guide clarifying this change as well as the automatic `orderBy` application by Eloquent's query builder.
It also removed a superfluous space in the `create` section.
=> [5.4] Document the `orderBy` changes to `chunk`

authorization.md
this functionality has existed for awhile, but was not defined in the docs.
a little bit of duplication with the previous code block, might be able to reword and work them in together.
=> add docs for defining gates with callback strings

billing.md
Using `composer require` will automatically add the dependencies to the `composer.json` file.
=> Use composer require in billing install instructions

billing.md
Replace wrong link with currently right one
=> Update Stripe documentation link for quantities

blade.md
This has caused some confusion, I think, because the documentation is ambiguous about the difference in variable inheritance between `@include` and `@each`. PR to master branch, but this technically could go to all of the documentation versions.
=> Add note about @each not inheriting variables

collections.md
Add documentation to the `intersectByKeys` method that [got added on 5.5](https://github.com/laravel/framework/pull/19303)
=> [5.5] Add intersectByKeys method documentation

eloquent-serialization.md
[Here](https://laravel.com/docs/5.4/eloquent-serialization#hiding-attributes-from-json) we have note that says 
`When hiding relationships, use the relationship's method name, not its dynamic property name.`
which I can't understand.
Can really dynamic property name be different from relationship's method name?
[Here](https://stackoverflow.com/questions/20671191/how-do-i-correctly-hide-model-relationships-from-returning-in-toarray-or-tojso) someone has similar question.
=> Unclear note on Eloquent: Serialization page

collections.md
Sorry guys, the PR I proposed was targeting `5.4` instead of `master`. This PR removes `intersectByKeys` from the 5.4 docs as it is not available.
=> Remove intersectByKeys method from 5.4 docs

homestead.md
See https://nystudio107.com/blog/local-development-with-vagrant-homestead , https://www.drupal.org/node/2485869 for explanations of why this plugin is important when using NFS to sync folders.
=> Recommend installing vagrant-bindfs

container.md
Updated Service Container Docs. Added `makeWith` method with an example of an associative array
=> Added makeWIth method with an associative array

notifications.md
The "receivesBroadcastNotificationsOn" method is used in "Illuminate\Notifications\Events\BroadcastNotificationCreated@channelName" which actually returns a string.
https://github.com/laravel/framework/issues/17883#issuecomment-301479258
=> Update "receivesBroadcastNotificationsOn" return value.

database-testing.md
Couldn't find `assertDatabaseMissing` anywhere in the docs, and only found it in the source code. Also stumbled across `assertSoftDeleted`
=> Missing helper methods in Database Testing

authentication.md
This bit of documentation is incorrect. The updateRememberToken is not called with null at logout, but with a new token.
=> Remember me token is always cycled at logout

mix.md
The latest version of Mix has `inProduction()` instead of `config.inProduction`, if I'm correct.
=> Fix inProduction detection

mix.md
I know it's easy to find it via Google but some people are confused how to start Mix on non Laravel project.
I suppose you don't want to insert full instuctions in Laravel docs so I propose compromise as link to @JeffreyWay repository.
https://github.com/laravel/docs/issues/3397
=> Add link to initial Laravel Mix repository

homestead.md
A new site type was added to Homestead in https://github.com/laravel/homestead/pull/600 this pr adds it to the documentation.
=> Add symfony4 as a site type

validation.md
Added `arrays` to the list of types that is evaluated the same as `size:value` for the `min` and `max` and `between` validation rules.
=> Add arrays to types evaluated same as size.

eloquent-relationships.md
it caused show only one table's data which is the first parameter without array type
=> fix: syntax error in Eager Multiple Relationships usage

dusk.md
Currently the test output is polluted by the PHP built-in server logging.
This silences requests for assets, such as `/favicon.ico` and `Invalid request (Unexpected EOF)` not fixed until PHP 7.2
https://bugs.php.net/bug.php?id=60471
=> doc travis-ci dusk squelch static assets

dusk.md
I went through the `WaitsForElements` trait and tried to document features that haven't been documented yet.
References:
- laravel/dusk#261
- laravel/dusk#176
- https://twitter.com/taylorotwell/status/879090376568602624
=> Add Undocumented WaitsForElements Methods

billing.md
The wording of the _Service Provider_ paragraph is such that someone might think they should place `Laravel\Cashier\CashierServiceProvider` as an entry in the `providers` array rather than the full `Laravel\Cashier\CashierServiceProvider::class`.
This is quite important as not including it kills the app without a stacktrace of any kind.  `Laravel.log` does have clues for it, but it's an unusual outcome so I think docs should make it as clear as possible.
=> Added the actual line to add to the `providers` array

container.md
Since Laravel 5.5 will be compliant with PSR-11, it makes sense to specify it in the **container** section as well as to explain the difference of use between `resolve` and `get`.
=> Add documentation about PSR-11 implementation

eloquent-relationships.md
in reference to https://github.com/laravel/framework/pull/19733
=> documentation on default relationship models

billing.md
As per issue #3416, I've updated the plan argument provided as an example to newSubscription to make it easier to understand.
=> Change newSubscription() plan argument

container.md
Fixes #3346 by correcting the capitalization under a model binding example input.
=> Fix case issue under Binding Instances

notifications.md
Add a link to the Slack documentation on _incoming webhooks_. Reading that for the first time I expected to find more info in the Laravel docs itself. Providing the link makes it clear that you should get the information outside and is just more convenient.
=> Add link to Slack documentation

upgrade.md
Be explicit about `laravel/browser-kit-testing` version when installing in 5.4, seeing as `2.*` release requires PHPUnit 6
=> Update upgrade documentation for Browser Kit Testing

validation.md
The `not_in` rule did not have any information about having an available fluent rule - I've added this.
=> add fluent rule information to not_in description

broadcasting.md
Hi,
The given code raises the following exception:
```php
Broadcast::channel('chat.*', function ($user, $roomId) {
if ($user->canJoinRoom($roomId)) {
return ['id' => $user->id, 'name' => $user->name];
}
});
```
```
Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Too few arguments to function App\Providers\BroadcastServiceProvider::App\Providers\{closure}(), 1 passed in C:\dev\myproject\vendor\laravel\framework\src\Illuminate\Broadcasting\Broadcasters\Broadcaster.php on line 60 and exactly 2 expected in C:\dev\myproject\app\Providers\BroadcastServiceProvider.php:29
```
When I use it as shown under https://laravel.com/docs/5.4/broadcasting#concept-overview, it works as expected.
Used code:
```php
Broadcast::channel('chat.{roomId}', function ($user, $roomId) {
if …
```
=> Name roomId parameter to be matched by pattern

dusk.md
I appreciate you may not want to add docs for every continuous integration service there is, but thought I would contribute the CircleCI 2.0 setup in case it was considered helpful. Much the same as CircleCI 1.0 but shows how to use the `background` flag with the new configuration file format.
=> Add documentation for CircleCI 2.0

dusk.md
I noticed that the session is maintained in each individual test file, which was causing some confusion when writing some different tests for a login form in the same file. I don't think it's an issue that this is the case, but I do think it's worth noting in the docs. It helps other developers recognise that it's intended behaviour and that they're not doing something wrong.
=> Make a note about the session being maintained

dusk.md
When configuring Dusk to connect to a Selenium hub the example uri is not complete. To connect to a Selenium node it should connect to the hub (`http://HOSTNAME:4444/wd/hub`).  This PR fixes this uri.
=> Connecting to a real Selenium hub

collections.md
Hello, 
i'm adding diffAssoc method to the documentation of the collection
it's resolving issue #3454 
the method diffAssoc was added on jun 15 there https://github.com/laravel/framework/pull/19604
it's merged into 5.4.27
thanks.
=> Adding diffAssoc method to collection

queues.md
See https://github.com/laravel/framework/issues/19584
=> Note to warn about the timeout queue that requires PHP 7.1 and pcntl extension

homestead.md
In Symfony 2 and 3, the `public` folder is actually called `web`.
=> Use 'web' as project root for Symfony2 projects

billing.md
Since https://github.com/laravel/cashier/pull/424/files, Cashier requires dompdf/dompdf by default.
=> Remove suggestion to install dompdf since now is required by default.

upgrade.md
We must use the `with` prefix to share variables dynamically. :grin:
=> [master] Minor fix to dynamic views variables change

authorization.md
By overriding the abilities array in the third parameter, The keys of this array will be concatenated with a period to the resource name in the first argument.
So keys should be `photo` & `image`, not `posts.photo` & `posts.image`.
=> Fix docs for `Gate::resource` method.

helpers.md
It was unclear that it doesn't append the value if the string already ends with it.
Closes #3505
=> Improve explanation of str_finish

upgrade.md
5.4 requires an `exception` column be added to the `failed_jobs` table, which is missing from the upgrade guide. This PR fixes that :)
=> Add queue's failed jobs schema change to upgrade.md

upgrade.md
Moved to the 5.4 upgrade guide: #3513
=> Removed irrelevant info about trans() helper

validation.md
I found `bail` example not so clear because if `required` fails other rules will not be checked whether `bail` exists or not.
=> Change bail example

http-tests.md
I feel that this is, for those who don't look through the main code base, a good method to have documented here.
I put the method first in the list because that is how it is in the `TestResponse` class.
I deleted the old branch when I made the last pull request, so I could not edit it. This one removes the `$uri` argument from the method. Sorry about that.
=> [5.5] Add assertSuccessful method

installation.md
Need to confirm if Tokenizer and XML PHP Extension still needed, since they are not in [composer.json require](https://github.com/laravel/framework/blob/master/composer.json#L17-L20).
=> Bump Laravel 5.5 PHP requirement

upgrade.md
Small change that will make the `composer require laravel/dusk` command to be consistent between the [Upgrade guide](https://laravel.com/docs/5.4/upgrade) and the [Dusk documentation](https://laravel.com/docs/5.4/dusk).
=> Add --dev to composer require laravel/dusk

blade.md
As discussed #3547 and #3538, `@show` has no explanation yet in the documentation and it's a confusing directive for beginners or developers coming from a template engine where the show is automated (I'm thinking of Pug where a block is automatically shown in a layout and replaced when you extend a layout).
Do not hesitate to fix this if my english is not correct or if I misunderstood the difference.
=> Explanations about @show and @endsection

broadcasting.md
Include example then using customize the broadcast name using the `broadcastAs` method. Need to add a leading `.` character at Echo listener.
=> [5.3] Broadcast Name include Echo example

helpers.md
Improves the explanation of the following three methods:
- array_last
- array_prepend
- array_pull
They all have an optional parameter whose behavior wasn't explained in the documentation.
=> [5.4] Explain optional parameters of a few array helpers methods

notifications.md
This PR makes a small change to some example code in the Slack notification section:
* The Slack API only allows certain values for the mrkdwn_in field for attachments (set by the `markdown` method). The "title" value is not valid, so that's been removed from the example code.
* Added more info above the code example about the acceptable inputs for the markdown method, with a link to the Slack API docs on attachment formatting.
Thanks, all.
=> Change example input for Slack attachment markdown method

upgrade.md
this is the same note I added in the 5.4 upgrade. it helps users keep their `laravel/laravel` files up to date, and helps cover a couple of the more nuanced upgrades to the framework.
=> add misc upgrade notes

upgrade.md
To prevent this error `... Request::all() should be compatible with Illuminate\\Http\\Request::all($keys = NULL) at ...`.
=> Add the missed `all` method on the Request

upgrade.md
This PR addresses the upgrade guide on the change on the method `has`. Currently it don't precise if we are talking about the input key or the input value.
=> Improves upgrade guide on the change in the method: has

errors.md
This pr contains updated docblocks for the render method in custom Exception classes.
=> Fix docblocks for Exception render method

eloquent.md, upgrade.md
Following the merge of https://github.com/laravel/framework/pull/20852, this PR brings the related documentation.
I made atomic commits to allow to select which parts are wanted, in case not all three of them are deemed necessary.
Two commits update the Eloquent documentation, and the third adds a warning in the 5.5 upgrade guide about a potential (although unlikely) naming conflict with previously existing code.
=> Document the new ‘retrieved’ Eloquent event & method

collections.md
In the example usage for ``intersectByKeys`` the method were called ``intersectKey``.
=> Fix typo intersectKey to intersectByKeys

upgrade.md
Added some information about adding filp/whoops package in `require-dev` after updating from 5.4 to 5.5 in the updating dependencies chapter.
=> Added some info about filp/whoops in updating dependencies

cache.md
`Cache::rememberForever()` is missing from official doc. This method is different from `forever()` because it allows to execute a callback and to cache the result.
`/docs/cache.md`
[Laravel APIs](https://laravel.com/api/master/Illuminate/Contracts/Cache/Repository.html#method_rememberForever)
=> Added Cache::rememberForever()

cache.md, passport.md
`Cache::rememberForever()` is missing from official doc. This method is different from `forever()` because it allows to execute a callback and to cache the result.
`/docs/cache.md`
[Laravel APIs](https://laravel.com/api/5.4/Illuminate/Contracts/Cache/Repository.html#method_rememberForever)
[https://github.com/laravel/docs/pull/3617](https://github.com/laravel/docs/pull/3617)
=> [5.4] Added Cache::rememberForever()

broadcasting.md
Current link is not the correct one.
=> Fix link to authorizing presence channels section of docs

eloquent-relationships.md
Recently I saw [a tweet](https://twitter.com/stidges/status/908076318964817923) that shows how we can [specify columns](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Eloquent/Builder.php#L1075) directly when eager loading a relation:
This PR documents this.
PS: This is my first PR for docs, so sorry about any mistakes! Also, this feature is available since [Laravel 5.3](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/Builder.php#L1130), so should we document it for those versions?
=> Doc specification of columns in with method

controllers.md
Documents the `Route::apiResource()` method added by [PR #19347](https://github.com/laravel/framework/pull/19347).
=> [5.5] Document API resource routes

filesystem.md, redis.md
Sort `use` statements by length in order to be consistent with the rest of the documentation.
Both changes would apply to the `5.4` branch, and the change in `redis.md` would apply to the `5.3` branch. Do you want me to create PRs for those too?
=> Sort use statements by length

authentication.md
The Illuminate\Auth\Events\PasswordReset event is missing form the docs for 5.5.
=> missing PasswordReset event added to Authentication

blade.md
Wording may be needed, or loosing the "tip" and just add it as text below the code.
I think experienced Laravel user will know this right away, but may help newcomers (as well as confuse them).
=> Add tip that directives auth & guest accept $guard argument

helpers.md
Corresponds with laravel/framework#21337
=> Update docs for optional array_sort callback

authorization.md
It's noted in the [upgrade guide (5.4 -> 5.5)](https://laravel.com/docs/5.5/upgrade#upgrade-5.5.0), but missing in actual documentation.
Wording may be needed to fit documentation **note** style.
---
I feel this needs to be in docs since I used policies heavily and during the development stage I usually have empty policy classes with only `before()` method...
=> Authorization before filter note

homestead.md
Really not absolutely needed, but just for convenience sake as most people follow the documentation rather than always looking for the latest version.
=> Update Homestead to latest version

mix.md
If we use this in windows, when executing the `npm run dev` command we get `cross-env is not recognized as an internal or external command` error.
`npm install` alone is enough and works well.
=> remove --no-bin-links description

collections.md
Documentation for the `Collection::unwrap()` method introduced in laravel/framework#20068.
=> [5.5] Document Collection::unwrap() method

upgrade.md
As referenced in https://github.com/laravel/framework/issues/20994 the inline `@php($teamMember = true)` blade directive is no longer supported.
Instead recommend approach is to use full `@php` and `@endphp` template or revert to php tags.
Suggestion on better wording always welcome
=> Add upgrade note on @php blade directive

homestead.md
mapping every project to a folder is best practice for performance reasons.
@svpernova09 this is in relation to our Slack discussion. does this cover this gist of what we were talking about?
=> [5.5] add note about mapping every project to a folder

database-testing.md
The factory name is `PostFactory`, maybe the model name should be `Post` instead of `User`
=> [5.5] Use the correct model name in relation with the factory name

homestead.md
low hanging fruit.
recently we switched the default install to use a lowercase `code` directory`.
ref:  https://github.com/laravel/homestead/commit/538c1f6b15038db18a5c33e8a7d60124a02d8c5c
=> [5.5] lowercase code directory

helpers.md
- Documents the missing `array_random()` function
- Documents the missing `preg_replace_array()`, `str_replace_array()`, `str_replace_first()`, `str_replace_last()` and `str_start()` functions
- Fixes the `str_limit()` position and improves its documentation mentioning the third argument (closes #3593). Also changed the example to better demonstrate that strings got trimmed when truncating.
- Documentation improvements to the `str_finish()` and `str_singular()` functions
- Documents the missing `app()`, `broadcast()`, `cookie()`, `dispatch_now()`, `policy()`, `resolve()`, `throw_if()`, `throw_unless()` and `validator()` functions
- Minor documentation improvements to the `auth()` and `dispatch()` functions
=> [5.5] Document some missing helpers and improve others

helpers.md
Just a small PR to quickly address formatting issues with `throw_if()`, `throw_unless()` and `validator()` functions - this might be some GitHub bug, there's some kind of special space characters that even copied aren't formatted the same.
Made also a small change to `str_finish()` wording applying the same change you applied to `str_start()`. 👍
=> [5.5] Fix helpers formatting

helpers.md
This PR adds documentation for these methods to `helpers.md`:
* `data_fill`
* `data_get`
* `data_set`
* `blank`
* `filled`
* `transform`
Additionally, I've added a note about the optional second parameter to `array_random`.
Let me know if anyone has questions or suggestions. Thanks!
=> Add documentation for missing helpers

dusk.md
When using RefreshDatabase, user record creation is inside a database transaction which is never committed and browser instance opened by Dusk cannot login using that user credentials.
=> Use DatabaseMigrations instead of RefreshDatabase trait

helpers.md
What makes Laravel unique in addition to its killer features and beautiful code is it's awesome documentation. Let's make it even more beautiful. 😄 
[Live PR branch file](https://github.com/paulofreitas/laravel-docs/blob/refactored-helpers/helpers.md) (so you can ensure the formatting was not broken)
- Changes the header name
- Changes the `array_dot()` example to look like the others
- Improves the `array_get()` example to better describe the behavior
- Simplified the `array_sort()` and `array_sort_recursive()` examples
- Improved the `data_fill()` documentation to better describe the behavior
- Improved the `data_get()` example to better describe the behavior (as in `array_get()`)
- Lots of minor wording/formatting fixes
- Improves the `config_path()`, `database_path()`, `mix()` and …
=> [5.5] Refactored helpers documentation

requests.md, responses.md
As per your request in #3724.
---
I have added this info, because it took me quite a while to figure out how to attach cookies from a Service Provider not accessing `Response` object.
[And](https://stackoverflow.com/questions/40405822/set-a-cookie-in-laravel-5-without-response) [it's](https://stackoverflow.com/questions/22345442/how-to-set-cookie-without-response-in-laravel) [not](https://stackoverflow.com/questions/31516762/how-to-set-cookies-in-laravel-5-independently-inside-controller) [only](https://laracasts.com/discuss/channels/laravel/make-and-get-cookies?page=1) [me](https://laracasts.com/discuss/channels/general-discussion/cookies-how-to-set-and-get-cookies-in-laravel-51).
=> Added a note about accessing cookies via a facade

helpers.md
Documentation for the `with()` helper function. 👍 
I had intentionally left out from the previous PR because it was intentionally removed in the past at the commit 561a2b0 before the Laravel 5.3 release. I was reading the 5.5 changelog yesterday and I saw that PR laravel/framework#21445 recently changed its behavior in a way that it's worth to document it back. 😃 
Since it's a bit tricky to understand how the behavior of `transform()`, `value()` and `with()` functions differ, I've made small adjustments to better describe their behavior.
Also includes a few minor formatting fixes and simplifications.
=> [5.5] Document with() helper function

dusk.md
Added some basic documentation describing how to resize the browser window when running Dusk tests.
=> Add browser resizing to Dusk documentation.

upgrade.md
Laravel Dusk is now under stable `2.*` and is not compatible with Laravel `5.4.*` so we need to specify what version we want to use when installing Dusk while upgrading from Laravel 5.3 to 5.4.
=> Fix Laravel Dusk composer require for Laravel 5.4

queries.md
The current note for PostgreSQL states the sequence name should be passed as the second parameter if the desired sequence is attributed to a column named other than the expected 'id'. It is actually the _column_ name  that should be passed (i.e., 'column_name' _not_ 'column_name_id_seq').
=> Change parameter instruction for 'insertGetId' PostgreSQL note. 

billing.md
I was looking for a way to disable prorate in my update of quantity and found this. Couldn't find any docs about thought it would fit in nicely.
=> Introduce the noProrate method in docs

seeding.md
according to this method https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Seeder.php#L32, you can pass an array of classes to the `call` method.  looks like the system was setup to work this way, so let's use it in the docs.
=> update the way seeders are called

homestead.md
This was updated in `v6.5.0` because of https://github.com/laravel/homestead/issues/695
=> Update homestead default TLD to *.test

mail.md
Found the existing text to not be perfectly clear as to when the event was fired. Had to dive into the source. Hopefully this helps.
=> Clarifies events fired upon mail being sent

testing.md
Fixed a typo where the `setup` _noun_ was used instead of the `set up` _verb_. Also fixed line endings this time, so it diffs properly.
=> Fixed typo in testing.md

migrations.md
Made changes @taylorotwell mentioned when closing #3793.
=> Makes it clear that false can be passed to the nullable modifier to disallow null values, less wordy than previous attempt.

database.md
The 'config/database.php' configuration file now has, by default, the SQL Server configuration.
=> SQL Server Configuration is no longer necessary

eloquent.md
It is not particularly clear, without digging into the Eloquent builder, that the second parameter is ignored by `firstOrNew` and `firstOrCreate` if the model is found in the database.
I've added some wording so this is explicit, as well as suggested that `updateOrCreate` would be the appropriate approach.
=> Clarify behaviour of `firstOrNew` and `firstOrCreate`

authorization.md
This PR fixes two small errors in example code for using policies in blade templates.
Since `create` doesn't require a model instance, `App\Post::class` should be passed into the `@cannot` directive's second parameter, instead of `$post`.
Let me know if you have any questions. Thanks!
=> Fix issue with policy blade example code

queries.md
=> Syntax error in selectRaw() query example

authentication.md
I added the sentence `You should pass the password to the `attempt` method without hashing it yourself` to clarify the issue mentioned in #3642
=> Clarify passing password to attempt method, fixes #3642

migrations.md
[Preview](https://github.com/paulofreitas/laravel-docs/blob/improved-migrations/migrations.md)
- Added 3 missing column type methods: `softDeletesTz()`, `tinyIncrements()` and `unsignedDecimal()`
- Added 4 missing column modifier methods: `autoIncrement()`, `charset()`, `collation()` and `useCurrent()`
- Added 1 missing index type method: `spatialIndex()`
- Changed `$table->char()` and `$table->string()` column types commands descriptions to state the column length is optional
- Fixed `$table->morphs()` column type command description to state the `taggable_type` column uses a VARCHAR column type
- Changed `->unsigned()` column modifier command description to state it is also MySQL only
- Overall command descriptions rewording with **lots** of small improvements
- Improved some commands …
=> [5.5] Improved migrations documentation

collections.md
Following on from the discussion on [laravel/internals](https://github.com/laravel/internals/issues/859), `collections.md` now documents that the keys are also reversed with `Collection#reverse`
=> Documents the keys being preserved in `Collection#reverse`

controllers.md
With Laravel Framework PR 21956, apiResources is now a function that can accept an array of controllers. This commit documents that functionality.
https://github.com/laravel/framework/commit/44680ec4f3d71b0064e3a416525d176cf613a92b
=> Added documentation for apiResources array

routing.md
Seems redundant to include 'instead' at both the start and end of the sentence.
=> Remove extraneous 'instead'

collections.md
Refs [5.5]. https://github.com/laravel/docs/commit/ceaf4b1dd155b6d9d50cb979e54d7dc4f50e1b14
=> [5.4] Add missing concat documentation

documentation.md, socialite.md
This introduces the Laravel Socialite documentation for 5.4 branch. It applies your formatting changes from #3856 and also includes the required installation instruction changes for Laravel 5.4 users. 😉 
Note: branches 5.3 and 5.2 are related to Socialite 2.0.x. Before documenting them I'll try to backport some Socialite 3.0 changes to Socialite 2.0 so they could share the same behavior and be documented uniformly. 👍
=> [5.4] Document Laravel Socialite

migrations.md
- Expands the *Table* section to document all available table options
- Fixes a tiny spelling typo
- Changes the `$table->nullableTimestamps()` column modifier description to state it's just an alias (from https://github.com/laravel/internals/issues/874)
- Updates the *Modifying Columns* note to list just the changeable columns
- Expands the *Renaming Columns* section to document the available command aliases
- Updates the *Available Index Types* section for changes introduced in https://github.com/laravel/framework/pull/21919
- Updates the *Dropping Indexes* section to include the new `$table->dropSpatialIndex()` method introduced in https://github.com/laravel/framework/pull/21919
- Minor table formatting adjustments
[Live Preview](https://github.com/paulofreitas/laravel-docs/blob/improve …
=> [5.5] Document missing migrations features

collections.md
It has been updated to match `dump`'s output in laravel/framework#22036
=> Update dd() output

routing.md
I can see controller name is singular like UserController, PhotoController in all Laravel docs except this example. This is confusing.
If you don't want to change that, could you explain why? The thing is I'm working on naming conventions table, so I'd really like to know what controller naming conventions exist https://github.com/alexeymezenin/laravel-best-practices#follow-laravel-naming-conventions
=> Changing UsersController to UserController

upgrade.md
Auto-loading of Artisan commands was not working for me when I upgraded from 5.4 to 5.5. I found that some code was missing from my `App\Console\Kernel::commands`.  This PR adds a note about that in the Upgrade guide.
=> Add note about auto-loading commands

seeding.md
Today I learned, after some struggle, that mass assignment protection is disabled during seeding. It might be useful to add a note somewhere in the docs about it.
I'm submitting another PR, adding the same note in the `Eloquent` section, so you can chose the best place to add the note in case you judge it pertinent.
=> Add note about mass assignment during seeding

homestead.md
* Update Virtualbox Version
* Remove old versions support / docs (multiple PHP versions should be used instead)
* Updated references to add PHP 7.2 and make it the known default
=> 📚 Update Homestead docs for v7 & PHP 7.2

upgrade.md
- The previous version seemed like it could use the article
"a" between "with" and "name", but this version reads a little
cleaner. "This method matches that name" is the same as saying
"this method's name matches that method's name".
=> Removed "with name" for clearer prose

eloquent-collections.md
In the example, users were filtered twice with the same criterion - once in query builder and then in reject collection method. Now only the filter using reject method is left.
=> fixing the code example for Eloquent collections

homestead.md
```bash
$ vagrant box add laravel/homestead
==> box: Loading metadata for box 'laravel/homestead'
box: URL: https://vagrantcloud.com/laravel/homestead
This box can work with multiple providers! The providers that it
can work with are listed below. Please review the list and choose
the provider you will be working with.
1) hyperv
2) parallels
3) virtualbox
4) vmware_desktop
```
=> Added mention of Hyper-V in Homestead

homestead.md
recently added support for ES6 to Homestead (https://github.com/laravel/homestead/commit/2d5f1b6f27b3d53082cb42c4450485f6860818ab)
since we support multiple versions now, tried to make the docs a little more generic
- new code allows you to specify a version. currently v5 and v6 supported.
- current users with a 'true' value will fallback to v5, so no breaking change
- added link to current ES configuration docs
- v5 defaults to 2GB, and v6 defaults to 1GB of memory, so I had to remove the hard coded values.
=> update elasticsearch notes

eloquent-resources.md
Hi, i've just rename resource name from `User` to `UserResource` >> `php artisan make:resource UserResource`.
I've rename it to avoid collision on model name so 
```
use App\Http\Resources\User as UserResource;
```
simply becomes to 
```
use App\Http\Resources\UserResource;
```
Sometimes some IDE misunderstanding which class have to import
=> Rename resource name from `User` to `UserResource`

seeding.md
Fixes laravel/docs#3935
Corrected model used in example of seeder edit for model "use" to correspond with reference in method call to "DB" Facade.
Fix current published documentation leading to error: In Container.php line 752: Class UsersTableSeeder does not exist
=> Seeder Doc prevent Class not exist error

responses.md
I just had a redirect to PayPal 404 only on mobile devices which has hell to debug until I remembered `away` exists so I think it's worth documenting.
=> Document Redirect::away()

http-tests.md
We should include the assertions from `InteractsWithAuthentication` in `http-tests.md`, or create a separated one like `database-testing.md`? :thinking:
=> [5.5] Document all available assertions for authentication

http-tests.md
This resolves #3937, by:
- Document [`laravel/framework#21917`](https://github.com/laravel/framework/pull/21917) and all missing assertion from `TestResponse`.
=> [5.5] Document missing methods from TestResponse

authentication.md
This middleware class is created locally with the 'artisan make:middleware' command. Existing namespace yields error: 
`"Cannot declare class Illuminate\Auth\Middleware\AuthenticateOnceWithBasicAuth, because the name is already in use in \app\Http\Middleware\AuthenticateOnceWithBasicAuth.php"`
=> Fix namespace issue

configuration.md, helpers.md
[Reference](https://github.com/laravel/framework/issues/21727)
Docs is not exactly clear on which are the consequences of using the `env` helper other than within configuration file when launching `config:cache` command.
`env()` description doesn't even put a notice about this behaviour.
This PR adds some warnings and explanations
=> env() - config:cache behaviour clarification

broadcasting.md
I came across this issue when the code in the docs wasn't working for me, I would get this error in the console.
```
Uncaught TypeError: Echo.channel(...).whisper is not a function
```
I saw in tlaverdure/laravel-echo-server#127 that `whisper` can only be used for private channels, so this updates the docs to indicate as such.
=> Use private channel to use whisper methods

homestead.md
apache is not installed by default, only if the user designates one of their sites as "apache".
mariadb is optional, and must be specified in the `Homestead.yaml` file
elasticsearch is optional, and must be specified in the `Homestead.yaml` file
=> list optional software

routing.md
Added missing documentation for route name method prefixes on groups in routing docs.
Tested rule:
```php
Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function () {
Route::resource('users','UserController');
});
```
Confirmed results:
* `namespace()` sets Controller namespace to \Admin\UserController
* `prefix()` sets request URi to /admin/users
* `name()` sets route name accessor to `route('admin.users.index')`
=> Document routing groups name method

homestead.md
some users have been noting recently that we don't document the ability to run both Nginx **and** Apache very well.
hopefully this makes things a little clearer, and documents the previously undocumented `flip` command.
=> add docs about homestead webservers

localization.md
Docs doesn't contain any information about parameters in pluralization strings, some users didn't notice that functionality.
=> Add information about parameters in pluralization strings

http-tests.md
There were 2 "assertJsonMissing" links in a row.
=> Remove duplicate link from http-tests

container.md
The container `extend` is quite a useful feature, and I've found myself on several occasions searching the docs for this and always forget that the feature exists but it's just not documented.
Thanks for all the hard work by the way on this project.
=> Add Documentation for Container Extends

upgrade.md
> the `optimize` command no longer providers any relevant performance benefit.
> the `optimize` command no longer provides any relevant performance benefit.
---
`providers` seems to be a typo, I guess it should be `provides`.
=> Replaced `providers` with `provides` in `optimize` section

eloquent-serialization.md
It's not obvious from the current documentation that you can alter the `$appends` list at run time on a single instance without having to include them in the model class.  This just adds a couple of examples of how to do it.
=> Include run-time modification of $appends

urls.md
A word like "create" appears to be missing in the sentence "The `url` helper may be used **to arbitrary** URLs for your application."
=> Add missing word

homestead.md
It looks like the word "links" was omitted here.
=> Add missing word "links"

upgrade.md
Laravel 5.6 requires `fideloper/proxy` v `~4.0`, but this was not documented in the upgrade guide before. It is now 👍
=> Add note about updating fideloper/proxy

mocking.md
Since Laravel version 5.5.28 you are able to assert how many times the event was dispatched. It's worth having it in a documentation.
As it is not available before 5.5.28, decided to put it in version 5.6.
=> Add event fake documentation for times dispatched

installation.md
Since 5.6 is out now, 5.5 needs to be specified when creating a Laravel 5.5 project via Composer.
=> Specify version for 5.5 installation.

scheduling.md
With the upgrade from component mtdowling/cron-expression to dragonmantank/cron-expression the part year of the Cron was obsolete.
=> [5.6] remove part year in cron method

upgrade.md
Small reminder to remove the optimize command from composer scripts (post-install-cmd & post-update-cmd).
=> Remove "php artisan optimize" from composer.json

releases.md
The phrase "at the same time" is not really ideal for the `onOneServer()` - because that phrase is more suited to the `withoutOverlapping()` function.
So I've tweak it slightly... I think it reads better?
=> [5.6] Update releases.md

deployment.md
Add a warning about using `env()` during `cache:config` for the deployment section.
This is already mentioned in the configuration page, but it could/is easily missed by people who only read the deployment section.
=> [5.6] Inclue cache config warning for deployment

installation.md
Closes https://github.com/laravel/docs/issues/3982
I checked, and these extensions are not included in some default PHP builds (such as FreeBSD etc)
=> [5.6] Update required PHP extensions

eloquent.md
Show how to remove global scopes that were defined as closures.
Closes https://github.com/laravel/docs/issues/3916
=> [5.6] Update eloquent.md

billing.md
Clarify the requirement to switch the router to point to your custom Cashier controller rather than the package one.
Closes https://github.com/laravel/docs/issues/3387
=> [5.6] Clarify custom Cashier webhook controller route declaration

billing.md
Document requirement for inclusion of `description` when using Braintree and `InvoiceFor()`
Closes https://github.com/laravel/docs/issues/3709
=> [5.6] Requirement for Braintree and InvoiceFor

dusk.md
The `assertHasQueryStringParameter()` assertion is inaccessible (protected) and doesn't provide any additional functionality. Calling `assertQueryStringHas()` gives you the same result.
See https://github.com/laravel/dusk/pull/456.
=> Remove inaccessible and duplicate dusk assertion

upgrade.md
I know this upgrade guide is quite old now - but there are at least two open issues relating to an error in the guide.
This PR tells people to pull in the config file for broadcasting, which is now set to `"null"` - so should prevent any issues after upgrading.
Solves https://github.com/laravel/docs/issues/2583 and https://github.com/laravel/docs/issues/2586
=> [5.3] Fix upgrade guide

upgrade.md
The current 5.3 -> 5.4 upgrade guide talks about the changes to `make()`.
There was `makeWith()` introduced in `5.4.16` - so we can include that as a pathway during the upgrades now.
Solves https://github.com/laravel/docs/issues/3250
=> [5.4] Change upgrade guide to mention makeWith

releases.md
The code in the current example isn't implemented. Updated the example to match the PR.
See https://github.com/laravel/framework/pull/23096
=> Fix release notes on Blade component aliases

passport.md
Passport tokens no longer last forever. They expire after 1 year.
I found the PR where this change was made (although it doesnt say why): https://github.com/laravel/passport/commit/5a69318d810b4c99373d163b220c9808ad868261
Closes https://github.com/laravel/docs/issues/3049
=> Fix Passport token expiry

database-testing.md
This includes a tip for the undocumented faker locale config option.
There was a PR to include it in the default `laravel/laravel` here: https://github.com/laravel/laravel/pull/4161, but you closed it and suggested to just document it instead.
Solves https://github.com/laravel/docs/issues/3172
=> Include undocumented faker locale config option

migrations.md
It wasn't clear that you can specify a name when creating an index. This is important for migrations, so you can use the same name when dropping it in the down() method. (Originally #4044)
=> Add note about specifying an index name

upgrade.md
The documentation specifies that overriding a table's primary key convention is accomplished by overriding the `$primaryKey` property instead of the alternative approach of overriding the `getKeyName` method.
=> Added note that overriding the `$primaryKey` property of a model could affect the foreign key relationship convention change.

envoy.md, queues.md
Before the PR, when clicking on HipChat (https://www.hipchat.com) in https://laravel.com/docs/5.6/queues#failed-job-events, we got redirected to https://www.stride.com, so the PR is here to rename the link and use Stride URL directly.
(another commit has been added afterwards to remove an unused HipChat anchor link in envoy documentation, here it is : https://laravel.com/docs/5.6/envoy#hipchat-notifications)
=> Rename HipChat link to Stride

routing.md
Added CSRF blade directive to complete the example as above.
=> Extended example for Form Method Spoofing

csrf.md, http-tests.md
I know you dont want too many tips/notes - but I'm not sure it warrents a full paragraph to explain it?
But the fact that CSRF protection is disabled in unit tests is not mentioned anywhere in the docs, so we probably should document it in both the "csrf" and "testing" sections.
=> Csrf disabled in tests

blade.md, readme.md
This fixes a syntax error on the blade docs.
Tested on a new install of 5.6 and have verified.
Solves https://github.com/laravel/docs/issues/4081
=> Fix blade syntax error

installation.md
Laravel 5.3 has known issues with PHP7.2 that are not being resolved - so we should doument the fact it is not supported.
Example of unsupportedd PHP7.2 function in Laravel 5.3 that was closed: https://github.com/laravel/framework/issues/22843
=> [5.3] Update requirements to show does not support PHP7.2

installation.md
When we added the PHP 7.2 limit the other day - somehow that broke the markdown parsing?
This PR wraps the php versions in code blocks to solve the issue.
See screenshot:
=> [5.2] Fix requirements markdown

installation.md
I've personally tested this on a cloned Laravel.com website with the docs.
I dont know what it is about a single `<` - but it totally breaks the markdown parser, even if wrapped in code blocks. (good to be mindful of in any future PRs we see).
The use of the HTML symbol code for `<` solves it and displays correctly (on my local server).
=> [5.2] Definitive fix for markdown issue

eloquent-resources.md
The example on conditional relationships for resources uses:
```php
Post::collection()
```
Instead of the resource class which is used throughout the other examples.
```php
PostResource::collection()
```
=> Use PostResource for conditional relationships example

notifications.md
In reference to laravel/framework#22289.
This isn't totally necessary but I think it's worth updating the notification examples to show that the notification is passed in as an argument to the method. In all the examples in the documentation it isn't actually used (and I presume for most use cases it won't be used either) but it would highlight the functionality to anyone that might need to use it.
=> Use notification argument in routing examples

routing.md
Example for Route Name Prefixes:
```
Route::name('admin.')->group(function () {
Route::get('users', function () {
// Route assigned name "admin.users"...
});
});
```
The route in example actually hasn't `admin.users` name, because it isn't assigned explicitly.
I think it can confuse some people, because from the example they could think that name of a route is automatically assigned by url.
=> Update example for Route Name Prefixes

requests.md
I was source diving fideloper's TrustedProxies package and found this:
```
// Trust any IP address that calls us
// `**` for backwards compatibility, but is depreciated
if ($trustedIps === '*' || $trustedIps === '**') {
return $this->setTrustedProxyIpAddressesToTheCallingIp($request);
}
```
[see file on github](https://github.com/fideloper/TrustedProxy/blob/master/src/TrustProxies.php)
It looks like the package docs still make a distinction between the two, so probably don't need this - but figured I'd put it out there.
=> "Trusting All Proxies": "**" is deprecated, use "*"

dusk.md
Makes navigation and reading Available Assertions faster. No more `ctrl-f` or `cmd-f` to find the right assertion.
=> [5.6] Update list format

helpers.md
Laravel 5.6's `e()` function now double-encodes the text by default.
=> [5.6] Update description of e() helper

dusk.md
"assertSelectHasOption" => "assertSelectHasOptions".
=> Fixed method name in heading tag. Added missing symbol "s".

passport.md
If one was to use `composer require laravel/passport` per the original docs, Composer would grab 5.0, which requires Laravel ~5.6.
=> Explicitly define Passport version to use

authentication.md, passwords.md, routing.md
Just noticed a few places where .dev is still referenced instead of .test and thought I'd update to keep it consistent.
=> Replace remaining mentions of .dev with .test

eloquent-serialization.md
Add that you can pass in a bitmask of options to `toJson()` that gets passed to `json_encode`.
See also https://github.com/laravel/framework/issues/3929
=> Include that toJson() can take an options parameter

broadcasting.md
_As a followup for this issue https://github.com/laravel/docs/issues/3173._
Laravel Echo Server can become a single point of failure for the entire Laravel app if we include Socket.IO library as currently described in [the official Laravel documentation](https://laravel.com/docs/broadcasting#driver-prerequisites):
```html
<script src="//{{ Request::getHost() }}:6001/socket.io/socket.io.js"></script>
```
In other words, if Laravel Echo Server stops working, then all JS code of the app will stop functioning with the following error:
> Uncaught ReferenceError: io is not defined
Include the Socket.IO client into the JS build process as a dependency instead of consuming the library, provided by Laravel Echo Server, by link.
An additional improvement has been requested for the Laravel Echo …
=> Improved Socket.IO section of the Driver Prerequisites

validation.md
Sidecar for https://github.com/laravel/framework/pull/23475.
=> [5.6] Add "Not Regex" validation rule

billing.md
This PR adds documentation for the trialUntil method for subscriptions in Cashier. I wasn't able to find a reference to this method in the docs, but I was delighted to find it in the source.
=> Add documentation for the trialUntil method in Cashier documentation

validation.md
Fixes an overlook from [b58a838](https://github.com/laravel/docs/commit/b58a838cf2a48c0e52326421f4334e187939204a#diff-eff160cdcda8f026fba936da7f3fea15).
(notice that during [#4158](https://github.com/laravel/docs/pull/4158/files#diff-eff160cdcda8f026fba936da7f3fea15) I fixed the TOC entry, but not the section itself)
=> [5.6] Correct ordering in validation rules

middleware.md
From the current version you can think that something will be done on server side, when the browser will really receive the response. THIS IS NOT TRUE - if you will put e.g. sleep(10) in the terminate method - you will see in the browser that you will have to wait those additional 10second for the response from server to be done.
I've checked this using php artisan serve and also by running it on Apache 2.4 with php 7.2 installed.
=> The middleware terminate method descripton is misleading.

scheduling.md
For scheduled jobs, the queue parameter is currently provided as an optional second argument - however, the documentation does not reflect this. This PR adds information about the second parameter, as well as a code example.
=> Missing documentation on job queue parameter

http-tests.md
This PR adds the following to the documentation: https://github.com/laravel/framework/pull/23526
=> [5.6] Add assertForbidden and assertNotFound to HTTP Tests

queries.md
Existing paragraph use a bit odd example, in that `where` grouping doesn't make any difference. Replaced it with an example using `(.. or ..)` when it really matters. Also added note when this can be even more important, ie. along with **global scopes**.
When this is merged, I will also create PRs targeting 5.3-5.5, where this paragraph exists.
=> make sense of the grouped wheres example

billing.md, migrations.md
Given edits to #4191 by @taylorotwell I assumed it would help to keep any fk columns to uint primary keys using the short-hand syntax of
``` php
$table->unsignedInteger('user_id');
```
rather than
``` php
$table->integer('user_id')->unsigned();
```
=> Improved consistency when declaring unsigned integer columns

validation.md
A quick poll of a few devs in one of the laravel chat channels showed that many people don't know about the bail rule because they never saw it in the list of available rules. This PR adds bail to the list of available rules.
=> add bail to the list of available validation rules

urls.md
The docs say that the `signed` middleware will automatically return a `401` response on invalid URL signature, however, it returns a `403` response as defined in [InvalidSignatureException](https://github.com/illuminate/routing/blob/master/Exceptions/InvalidSignatureException.php#L16).
=> Fix response status code on invalid signature

authorization.md
I found this part of the docs was deleted in mid 2016, but it's still present in Laravel 5.6 + I think it's still useful.
=> [5.6] Add documentation about Gate::before in authorization.md

authorization.md
The default example in the docs does not work, this does.
I can confirm this problem persists with a clean laravel installation. 
Also with `use App\Policies\PostPolicy;` it doesn't work.
Reference:
https://stackoverflow.com/questions/46324965/class-userpolicy-does-not-exist-view-f-xampp-htdocs-gates-policies-resources
=> Policy namespace

collections.md
There are two sentences that need small changes to read a little more smoothly:
- "to fluently *manipulate* the underlying array" instead of "to fluently *manipulating* the underlying array"
- "Each array element *will be applied to* the corresponding level" instead of "Each array element *will applied for* the corresponding level"
=> Fix the wording of two sentences

queues.md
Other parts of Laravel such as Cache use minutes as the time unit. Added phrasing to clarify that queue --sleep uses seconds.
=> Specify queue sleep command time unit (seconds)

authorization.md
I found this part regarding Gate resource confusing, as it says you may "add or override" but after doing some tests and checking the source code I found the third argument does not add but instead *overrides* the default options.
=> [5.6] Update authorization.md

dusk.md
these assertions already exist in Dusk, but are not documented.
=> add docs for URL fragment assertions

eloquent.md
This is also helping beginners. When they try to run `php artisan make:model User`, that will fails, because User model already exists.
=> Change User to Flight

artisan.md
According to v5.6.16, it's possible to execute artisan commands using class names
=> Artisan commands can be executed using class names

events.md
Fix param reference to full namespace in DocBlock
=> Fix param reference in DocBlock

collections.md
Resubmission of https://github.com/laravel/docs/pull/4263
______
Adding the example result to `partition` method on Collection.
Currently, it's documented with this description and example:
> The `partition` method may be combined with the `list` PHP function to separate elements that pass a given truth test from those that do not:
$collection = collect([1, 2, 3, 4, 5, 6]);
list($underThree, $aboveThree) = $collection->partition(function ($i) {
return $i < 3;
});
And that's it. This PR will add the results of the example:
``` php
$underThree->all();
// [1, 2]
$aboveThree->all();
// [3, 4, 5, 6]
```
=> [5.6] Collection's partition method: add example result

mail.md
Clarify the purpose of `mail/html` and `mail/markdown` directories. There seems quite a bit of confusion around this, and I believe the amended wording would help alleviate this.
I had to find https://github.com/laravel/framework/issues/17970#issuecomment-324159935 to discover this, and that took me quite a bit of digging!
=> [5.6] Clarify mail html and markdown directories.

dusk.md
It's a nitspick but there was an unnecessary space in front of `####`. so I removed it to make syntax valid.
=> Remove an unnecessary to fix Markdown syntax.

filesystem.md
It should be noted when using store/putFile  that a default file extension is chosen based on the MIME type in addition to a unique ID being generated for the file name.
=> Clarify store/putFile file extension behavior

queries.md
Neither in MySQL nor in SQLite does `whereTime()` work without the seconds portion.
=> {5.6] Fix whereTime() example

eloquent-relationships.md
Clarify how to query for absence of nested relations, as this works slightly different than one would expect.
See issue:
https://github.com/laravel/framework/issues/24023
As this is my first pull request, all feedback is welcomed!
=> Clarify querying the absence of nested relations

homestead.md
Adds "apigility", "expressive", and "zf" to the list of available site types for Homestead.
=> [Homestead] Note new Zend Framework site types

deployment.md
I think this should be included in any deployment script, no one wants to see that `Laravel Dusk is risky to run on production` error.
=> add --no-dev flag in deployment

validation.md
The text for the new comparison validation rules `gt`, `gte`, `lt` & `lte` make it seem like the supplied `field` parameter's value should actually be greater/less/equal to the field being validated. The source code confirms that the field being validated should be greater/less/equal to the supplied field parameter's value.
=> Adjust validation rule language to avoid confusion

logging.md
documentation for the `formatter` and `formatter_with` options. also removed unnecessary example for newrelic as it is repeated below.
=> formatter docs

horizon.md
Fixed a link in the Laravel Horizon docs that was still directing you to the 5.5 version.
=> Fixed link 5.5 -> 5.6

upgrade.md
These were still set to `develop`, and those files are different from what's in `master`. I'm assuming we want the `master` version.
=> Fix default configuration file links

installation.md
There is no empirical evidence for the existence of learning types.
Brief summary: https://en.wikipedia.org/wiki/Learning_styles#Criticism
APS paper: https://doi.org/10.1111/j.1539-6053.2009.01038.x
This question is present in branches 5.4, 5.5, 5.6, master.
I was thinking of a better alternative, but couldn't come up with anything useful. Overall I think this little advert is fine without an introductory question.
=> Remove pseudo-scientific slogan

releases.md
this table is a quick reference to see the bug and security fix end dates for each version of Laravel.
Inspiration was taken from the PHP supported versions table.  http://php.net/supported-versions.php
This will be an easy reference for when people request or submit PRs for backports.
=> add version support table

blade.md
Added an 's' to make 'iteration' plural, since it is about the number of iterations remaining.
=> Fix typo in blade section

filesystem.md
Keys in all the default configuration files use snake case, so I just changed this code example to use snake case as well.
=> Change authorization token to snake case

queries.md
From https://github.com/laravel/docs/pull/4349: 
> This was added in https://github.com/laravel/framework/commit/36b255013aeeb841d8fc441401825f9811b0993f, but wasn't documented until now.
=> Simplify '->when()' examples

queries.md
Reading up on another contributors pull request #23818 on improving sub query joins, I noticed that [the code](https://github.com/laravel/framework/blob/v5.6.26/src/Illuminate/Database/Query/Builder.php#L440) is still in `v5.6.26`, but no documentation was added so far.
I did that now, for the sake of completion. I hope my wording and example make sense.
_Side note:_ Low complexity on user contribution requirements is welcome, but maybe it makes sense to make documentation additions a dependency for any new feature pull requests? This would prevent "hidden features" to stay hidden and lower the amount of work required for new releases. Sadly I cannot propose an automated solution as I haven't done that before …
=> Documentation on sub query joins

collections.md
Callback for `groupBy` is passed instead of the string `key`, not in addition to it.
=> Clarify groupBy docs

mail.md
See https://github.com/laravel/framework/pull/24736
Since the old colors will be removed in the next version, I don't think we need to document them? Or should I add a deprecation notice here? (unless that's an upgrade guide thing)
=> Functional mail button class names

queries.md
Adds `whereJsonContains()` queries (https://github.com/laravel/framework/pull/24330, https://github.com/laravel/framework/pull/24448).
Adds JSON `where()` queries on SQL Server (https://github.com/laravel/framework/pull/24397).
=> [5.6] Add whereJsonContains() queries

scheduling.md
Ran into an issue where running the cron with a similar format to the existing example caused scheduled console jobs to not work if they were scheduled commands because the call to `Application::formatCommandString()` within `Schedule::command()` appears to generate the command string assuming that the caller is already in the working directory of the project. eg: `php artisan some:command`.
=> Cron entry example for schedule:run relative to project path

mocking.md
Add documentation about the Event::fakeFor method and that it can be used to fake the events for only a part of your test.
Instead of only one sentence as in #4334 it's now described in more detail.
=> [5.6] Add more detailed documentation about Event::fakeFor method

valet.md
Homebrew recently updated their default tag of MySQL to use version 8+. It caused issues with users of Valet that followed these instructions.
=> Specify MySQL 5.7 for installing via Homebrew

eloquent-relationships.md
- If the owning model uses a primary key other than `id`, let's say the `Post` model from the given example uses `uuid` as the primary key, then the current explanation will result in an error.
- The current explanation says it will prefix it with `_id` (hardcoded) i.e. doing `$post->comments` will look for `post_id` in comments table, but instead it will look for `post_uuid`.
=> Fix explanation of automatic foreign key detection in 'One to many' relationship block

controllers.md
Added information about --invokable flag (creating single action controller) implemented in this PR: https://github.com/laravel/framework/pull/24843
=> Added information about --invokable flag

authorization.md
Unless the full path to the policy is used in the Class@method style callback string an exception is thrown.
This may be implied here but because the gate definitions under the resource gates below show the full path, the description may be confusing.
=> Add full path to policy

mail.md
The example API endpoint is missing `/transmissions`. Default also uses this: https://github.com/laravel/framework/blob/c8682e11b9f0e153654ff5c2a3ad9f8b2dca56d1/src/Illuminate/Mail/Transport/SparkPostTransport.php#L146
=> Update SparkPost API endpoint EU example

broadcasting.md
Hello !
Overall, the Broadcasting documentation is using Pusher to explain most of the configuration. A small section is saying to use whisper() to exchange directly between connecteds peers, but in order to do that with Pusher, you need to allow it manually in your App Settings, otherwise it would fail silently, except from the Debug Console on the Pusher Dashboard.
Explaining that would be nice.
=> Explain how to enable whisper() when using Pusher

artisan.md, middleware.md, seeding.md, validation.md
There are some instances in the framework where some methods get called via the container and any type-hinted dependencies in those methods get automatically injected, but the docs were missing mentions of some of those methods.
=> [5.6] Update docs about methods whose type-hinted dependencies get injected via the DIC

scheduling.md
`weeklyOn(1, '8:00')` will be triggered on Mondays, but not Tuesdays.
=> Fix weeklyOn() example's explanation

cache.md
I was looking for documentation about it, could only find the [tweet](https://twitter.com/taylorotwell/status/875095973629919234). Copied over all examples from the tweet, and tweaked the message based on commit messages and other places where distributed locks are mentioned (task scheduling on one server).
Not sure if all the examples are still true, worth checking.
=> Add documentation about atomic locks

releases.md
I thought it should be grouped with the Email Verification feature but burying this edge-case-ish item at the bottom might make sense.
=> [5.7] Add notification localization in release notes

upgrade.md
https://github.com/laravel/framework/pull/23708
Regarding the "Likelihood Of Impact": Nested rules are probably used by a lot of people. But I think that most of them won't actually be affected by this change.
Also: The `Routing` changes are missing the "Likelihood Of Impact".
=> [5.7] Add #23708 to upgrade guide

providers.md
Was a bit confused about "View composer" when was reading about
the "The Boot Method" from page https://laravel.com/docs/5.6/providers#writing-service-providers
Hopefully this small change will make it more clear
=> Added link to 'view composer' page from  'providers' page

eloquent.md
We have this warning (Saved & Updated method will not fire in case of mass update) in updates section.
But its a Event related note/warning, I think it should (also) be in Events section so its hard to miss it, for someone whose looking for reference.
=> Add warning for Saved & Updated method will not fire in case of mass update

contributions.md
Current LTS version is 5.5 according to https://laravel.com/docs/5.6/releases#support-policy
I believe the same issue exists in branches 5.7 and master too.
=> LTS version corrected
