laravel/docs

mix.md

This sentence is missing a word.

Add a missing word

---

upgrade.md

Recently the laravel/laravel project changed its dependencies to use the caret operator.

Use semver caret operator

---

logging.md

Documentation both added and reorganized:
- added section that lists the built-in logger channels
- reorganized customization into an "advanced" section
- added documentation on `monolog` driver
- verbiage of `custom` driver to use word "factory"

[5.6] Logging.md updates

---

migrations.md

Update morphs() description, to suit field type change (from PR 23320)

Correct Blueprint->morphs() description

---

homestead.md

Adds information on how to use Minio object storage

Update Homestead with Minio Information

---

http-tests.md

This was implemented in https://github.com/laravel/framework/pull/24119

Add the new assertCookieNotExpired assertion

---

homestead.md

Add Homestead information about how to install neo4j.

Update Homestead with Neo4j information

---

validation.md

Fix typo in description of the new validation rules

---

passport.md

Andy and Simon took over the project from Alex last year.
See https://github.com/thephpleague/oauth2-server#credits

Update League OAuth2 server maintainers

---

upgrade.md

update example code

---

http-tests.md

Document the `assertLocation` method added in laravel/framework#24267.

Document TestResponse::assertLocation

---

database.md

Fixes formatting in database.md

Fixes formatting in database.md

---

queries.md

The `havingRaw()` example should show (and encourage)  the usage of bindings.

Use bindings in havingRaw() example

---

scheduling.md

Added the reference of weeklyOn method in Task Scheduling section. This solves Issue #4262 .

Add weeklyOn in Task Scheduling. Issue #4262.

---

homestead.md

I noticed that the docs version of homestead is a bit behind the most up to date version.

updated homestead version

---

homestead.md

https://github.com/laravel/homestead/releases/tag/v7.8.0

📚 Adding docs for Homestead DB export feature, bump version number.

---

eloquent.md

This pull request related to [laravel/framework(#24334)](https://github.com/laravel/framework/pull/24334)

Add make:observer command to eloquent doc

---

urls.md

See https://github.com/laravel/framework/pull/24738

Document callable action syntax

---

installation.md

[5.6] Added "-Indexes" option to doc block

---

scheduling.md

This PR simply references and implements @taylorotwell suggestion on a former [PR](https://github.com/laravel/docs/pull/4403)

Sentence for invokable object inplace of Closure for Scheduling calls  

---

artisan.md

This PR is a continuation from PR #4397 and issue #4396 - Update link from 2.7 to the latest version.

Update Symfony Link

---

upgrade.md

typo fix ("inherit to" changed to "inherent to")

---

eloquent-relationships.md

I wasn't sure if you could have a custom intermediate table model on a many to many polymorphic relationship, i ended up stubbling across #21065 that had the answer, a few people in that thread thought it would be a good idea to document, so i'm submitting this :)
Thanks
Daniel

Update eloquent-relationships.md to include information about intermediate table models for polymorphic relationships

---

upgrade.md

https://github.com/laravel/framework/pull/24936

[5.7] Add #24936 to upgrade guide

---

routing.md

- This PR updates the documentation with the information about `Route::fallback()` method.

[5.6] Add docs for fallback route

---

upgrade.md

This documents the breaking change that was made in https://github.com/laravel/framework/pull/25128

[5.7] Document validator interface breaking change

---

queries.md

Updating JSON columns is actually only supported on MySQL.

[5.6] Specify support for JSON UPDATE queries

---

verification.md

Fixed a tiny typo in the verification docs.

Fixed typo in verification docs.

---

releases.md

Fixed a tiny typo in the release notes
Fixes #4462

Fixed typo in release notes

---

contributions.md

Add Nova to Applications

---

homestead.md

Updates homestead release version and provides info on provisioning buckets through config file

Homestead Update & Minio Bucket Info

---

eloquent-relationships.md

Related to https://github.com/laravel/framework/pull/25519

[5.7] Document Model push method

---

mail.md

Explain how to configure additional options for the SES mailer, in relation to https://github.com/laravel/framework/pull/25536

How to configure additional options for the SES mailer

---

upgrade.md

Fixes two small issues when adding the email verifications to an upgrade.

[5.7] Fix email verification upgrade

---

homestead.md

See laravel/homestead v7.11.0 for more information.

Multiple versions of PHP are supported on Apache

---

readme.md

[5.7] Bump version

---

homestead.md

https://github.com/laravel/homestead/issues/942

📚 Adding docs around after.sh and Ubuntu gotcha for config changes

---

eloquent-resources.md

https://github.com/laravel/framework/pull/25625

[5.7] Add whenPivotLoadedAs()

---

eloquent-resources.md

Updates documentation to include an example of the collection resource `collects` public variable.

Updates eloquent-resources.md collection examples.

---

helpers.md

#4533 introduced a change that missed the quotes on some strings, which this fixes

Wrap strings in missing quotes

---

dusk.md

relevant PRs:
- https://github.com/laravel/dusk/pull/553
- https://github.com/laravel/dusk/pull/555

add documentation for new Dusk assertions

---

contributions.md

- we should send all bug fixes to the latest LTE (not the latest version)

[5.7] We should send all bug fixes to the latest LTE

---

upgrade.md

E.g. see the discussion in https://github.com/laravel/framework/issues/25451

[5.7][UPGRADE] Mention new data/ directory for cache

---

collections.md

Update variable name to match what it really contains. Now you could think looking at variable name that value `3` won't be included and it's not true

[5.7] Update variable name for partition method

---

validation.md

https://github.com/laravel/framework/issues/16113

[5.7] Fix "in_array" validation example

---

scheduling.md

See https://github.com/laravel/ideas/issues/1337 and https://github.com/laravel/framework/issues/25834#issuecomment-426175676 for some background

[5.7] Document how to run commands in the background

---

valet.md

[5.7] Update Valet path

---

contributions.md

According to [Taylor's Tweet](https://twitter.com/taylorotwell/status/1041767334833278976) there is a Discord Server that also has an #internals channel with quite a lot of activity.

Adds Discord server link to contributing guide

---

container.md

Docs for https://github.com/laravel/framework/pull/25891

Contextual Binding

---

eloquent-relationships.md

See https://github.com/laravel/docs/issues/4113

[5.7] Add note about additional create methods

---

mail.md

See https://github.com/laravel/docs/issues/4246

[5.7] Add docs about global reply_to and to addresses

---

eloquent.md

I wasn't sure if this was the correct section to document this. Feel free to move this or ask me and I'll update the PR.
See https://github.com/laravel/docs/issues/4430

[5.7] Document refreshing models

---

validation.md

See https://github.com/laravel/docs/issues/4518

[5.7] Add note about regex validation requirement

---

eloquent-mutators.md

See https://github.com/laravel/docs/issues/4476

[5.7] Make it clear how to append computed values

---

queries.md

Added two updates:
- Documented the `chunkById` method
- Added a note about deleting/updating records inside a chunk closure
Fixes https://github.com/laravel/docs/issues/4536

[5.7] Update Chunking Results docs 

---

blade.md

[5.7] Add csrf and method field to Blade docs

---

eloquent.md

Update the types accepted by the eloquent model destroy method

[5.7] Eloquent destroy method

---

authentication.md

Updating the path customization section to include `VerificationController` in the list of files to add a custom property/method to.

Update authentication.md path customization docs

---

scout.md

This will make it more clear that Scout can actually be extended pretty easily. Took some inspiration from the Response Macros docs.

[5.7] Document Scout Builder macros

---

scheduling.md

add information about conditional ping methods

Add info about pingBeforeIf and thenPingIf

---

mocking.md

This useful functionality is not yet mentioned in the documentation.

[5.7] Add 'Selective Event Fakes'

---

collections.md

Signed-off-by: MegaXLR <admin@megaxlr.net>

[5.7] Update the Bootstrap Grid link to 4.1

---

billing.md

From the merged PR (method name was updated afterwards): https://github.com/laravel/cashier/pull/567

[5.7] Document Cashier syncTaxPercentage method

---

billing.md

Adds a small section about refunding charges.

[5.7] Cashier refunding charges

---

billing.md

Adds documentation for the new `VerifyWebhookSignature` middleware in Cashier: https://github.com/laravel/cashier/pull/565
Also sent in a PR to add the config values: https://github.com/laravel/laravel/pull/4803

[5.7] Document Verifying webhook signatures with Cashier

---

eloquent-relationships.md

Mostly a copy/paste from the HasManyThrough relationship with the behavioral changes for single models.

[5.8] Document HasOneThrough relationship

---

upgrade.md

Documents https://github.com/laravel/framework/pull/25975 and https://github.com/laravel/framework/pull/25995

[5.8] Document some 5.8 breaking changes

---

eloquent-relationships.md

As requested, this is updated to import the class name.

Document $query Type for `whereHas`

---

upgrade.md

sync it with the actual content of the file in `laravel/laravel`

fix gitignore content

---

passport.md

It's just something little but it cleans things up a wee bit.

[5.7] Passport: move paragraph to intro

---

passport.md

This adds info on how multiple redirects can be added to clients.
https://github.com/laravel/passport/issues/627

[5.7] Passport: add info about multiple redirects

---

upgrade.md

Document https://github.com/laravel/framework/pull/26193 breaking change.

[5.8] Document #26193 breaking change

---

passport.md

This PR adds extra documentation about ways to configure Passport for your setup that were missing. I've tried splitting the different additions in different commit messages so it's clear what was added. Let me know if you want to describe some things differently.

[5.7] Extra passport configuration

---

validation.md

Documents the new UUID validation rule in laravel/framework#26135

Document the UUID validation rule

---

controllers.md

These controllers return a View instance, not a Response 😄

Controller return type

---

contributions.md

This is a resubmission of #4697 without the unnecessary files.
Thanks @driesvints for the feedback.

[5.7] Add telescope repository

---

mail.md

This commits documents the changes introduced by laravel/framework#24994

[5.7] Adds Mailgun region documentation

---

billing.md

I believe you meant "customer", but I could be wrong, in which case - carry on.

[5.7] Fix misspelling

---

homestead.md

A update to homestead was release not so long ago.
Here's the version bump for the docs, so it matches latest release.

Updated homestead to latest release

---

upgrade.md

https://github.com/laravel/framework/pull/26410

[5.8] Adds one more breaking change description to the upgrade guide

---

documentation.md
telescope.md

not sure if you have this cued up, but thought if not I'd get a simple docs page started for Telescope.

[5.7] Add documentation for Telescope

---

telescope.md

Depends on PR https://github.com/laravel/telescope/pull/401
Not sure this is the right path for the PR - let me know if you needed it somewhere else.

[5.7] Adding documentation for age parameter in pruning command

---

installation.md

moontoast/math 1.* requires ext-bcmath

telescope bcmath require

---

eloquent-relationships.md

Re-submitting https://github.com/laravel/docs/pull/4744 as requested by @taylorotwell .

[5.7] Clarify nature of using/withPivot interaction on M:N relations

---

homestead.md

Change `pkg::Options` to `Dpkg::Options`

Change pkg::Options to Dpkg::Options

---

queues.md

This was not clear to me at first so I suggest to note it at the appropriate place where `$this->release( ... )` is mentioned as well.

[5.7] Note that releasing jobs counts towards their attempts

---

eloquent-relationships.md

So this might be a big PR at first sight. It adds documentation for the `morphOne` relationship and cleans up the polymorphic relationships docs. It basically moves all polymorphic relationship documentation to their own section. The "Defining Relationships" was getting rather large so I thought it would be good to split it up. No existing anchor links have been renamed, just a few ones were added. 
It further does:
- Makes some documentation more consistent 
- Moves "Custom Polymorphic Types" to its own sub level so it can be linked to (wanted to do that a few times the past few days)
- Adds a new intro for polymorphic relationships
- Makes the polymorphic docs follow the one-to-one, one-to-many, many-to-many sequence consistently with the docs for "Defining Relationships"
Let me know …

[5.7] Add morphOne and cleanup polymorphic relationships

---

validation.md

See https://github.com/laravel/framework/pull/26612

[5.7] Document new starts_with rule

---

middleware.md

Apparently this wasn't documented yet: https://github.com/laravel/framework/issues/24854

[5.7] Document sorting middleware

---

routing.md

This PR just adds documentation for the `Route::permanentRedirect` method.

[5.7] Document the Route::permanentRedirect method

---

authentication.md

Describe the necessary steps to disable registration after running `php artisan make:auth` on a new application since this topic comes up [quite](https://laracasts.com/discuss?q=disable+regist) [often](https://stackoverflow.com/search?q=laravel+disable+registration).

[5.7] Add tip on disabling registration

---

collections.md

This adds documentation for https://github.com/laravel/framework/pull/26345. Resend for https://github.com/laravel/docs/pull/4733.
Fixes https://github.com/laravel/docs/issues/4801

[5.7] Document whenEmpty and whenNotEmpty methods

---

collections.md

[5.7] Fix times() code example confusing syntax highlighting

---

billing.md

This PR adds updates to the Cashier docs for the changes in the 9.0 release.

[5.7] Cashier 9.0 updates

---

redis.md

adding the default redis configuration array loaded with laravel 5.7 into configuration section

[5.7] Update redis.md

---

broadcasting.md

Was added in https://github.com/laravel/echo/pull/216

[5.7] Document Echo leaveOne method

---

billing.md

As per request [here](https://github.com/laravel/cashier/issues/282#issuecomment-447153140) I've added some more info on how to work with cards in Cashier.

[5.7] Add more documentation on cards in Cashier

---

dusk.md

Rename $year parameter on $day parameter in selectDate method signature.

[5.7] Fix parameter mismatch

---

billing.md

This PR addresses the issue brought up in issue [4876](https://github.com/laravel/docs/issues/4876).

5.7 Fix for issue 4876

---

billing.md

This PR addresses the concern brought up in issue [4876](https://github.com/laravel/docs/issues/4876).

5.6 Fix for issue 4876

---

billing.md

This PR addresses the concern found in issue [4876](https://github.com/laravel/docs/issues/4876).

5.5 Fix for issue 4876

---

structure.md

Seems to make more sense with this word added.

Added word test

---

dusk.md

Documents functionality added in https://github.com/laravel/dusk/pull/598

[5.7] Document waitUntilVueIs

---

eloquent-relationships.md

Hi, this is a useful feature but missing in docs, I didn't even know we could do that

update docs whereHas with count logics

---

eloquent.md

See: https://github.com/laravel/framework/pull/26985

[5.8] Add SoftDeletes deleted_at auto casting

---

collections.md

Adds `$collection->whereNotBetween();` method to Collections.
https://github.com/laravel/framework/pull/27028

[5.7] Add whereNotBetween Method

---

homestead.md

Bumped homestead version to latest release.
PR for 5.7 as requested in #4896 (not sure why 🤔)

[5.7] Updated homestead to latest version 7.20.0

---

homestead.md

Another attempt at intent expressed here... https://github.com/laravel/docs/pull/4907
How do version branches get back into master?

[5.7] issue #4905 clearer sites example config

---

blade.md

Fixes https://github.com/laravel/docs/issues/4919

[5.7] Document include aliases

---

passport.md

Document changes made in https://github.com/laravel/passport/pull/949

[5.7] Document changes made to wildcard scopes

---

cache.md

Updates the docs with the recent changes made to the Cache component.

[5.8] Cache updates

---

upgrade.md

Upgrade notes for the recent cache changes.

[5.8] Cache upgrade notes

---

dusk.md

Hi,
i have found a typo and updated it.

[master] fix: typo

---

valet.md

This PR documents the new `valet use php@X.x` command. https://github.com/laravel/valet/pull/710

[5.7] Add Valet use php command

---

scout.md

This Pull Request addresses the upcoming release Scout `v7.0`. Here is the code associated to it: 
- https://github.com/laravel/scout/pull/349
- https://github.com/laravel/scout/pull/353

[5.7] Updates docs for Scout 7.0

---

passport.md

A short tip describing how to get an access token after customize the authentication field.
It would save me a few minutes.

[5.7] Describing findForPassport method

---

queues.md
upgrade.md

Related to https://github.com/laravel/framework/pull/27227

[5.8] safe blocking pop

---

database-testing.md
helpers.md
seeding.md

These helpers are deprecated and will be removed in a future version.

[5.7] Replace helpers with their class implementation

---

helpers.md

Added in https://github.com/laravel/framework/commit/9172a67b783952c1d3e15452d9c8646dc0b3eb6d & https://github.com/laravel/laravel/commit/63a403912362654962654e30cec695128d418987
Because there was some confusion: https://github.com/laravel/framework/issues/27547

[5.7] Document new asset_url config option

---

upgrade.md

Updated the section so it links to the new helpers package.

[5.8] Link to new laravel/helpers package

---

queries.md

- Short description of the [updateOrInsert](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Database/Query/Builder.php#L2670) Query Builder method and an example of it's usage.

[5.7] Describe updateOrInsert method

---

upgrade.md

Adding additional named anchors for top level sections to improve linkability. This is inline to what what GitHub provides when viewing Markdown files within their UI.

Add named anchors for sections

---

validation.md

Adding document for using method `Rule::requireIf` which had been added in pull request https://github.com/laravel/framework/pull/25066.

[5.7] Document for Rule::requireIf

---

upgrade.md

Fixes some links caused by the 5.8 release.

[5.7] Fix links from 5.8 release

---

authentication.md

See https://github.com/laravel/framework/issues/27633.
Resubmitting as requested, without the code changes.

[5.7] Document exception thrown by Auth::onceBasic()

---

authentication.md

See https://github.com/laravel/framework/issues/27633.
Resubmitting as requested, without the code changes.

[5.6] Document exception thrown by Auth::onceBasic()

---

homestead.md

Clarify that repo is cloned to host machine, to avoid ambiguity about whether to clone to host or VM. See #5028

Clarify where to clone Homestead directory

---

collections.md

Adds docs for https://github.com/laravel/framework/pull/27770

[5.8] Add `countBy` to collection docs

---

console-tests.md

Add hash link

---

passport.md

pls delete if i'm wrong - (non native speaker)

perhaps a typo

---

eloquent-relationships.md

$query -> $posts

---

collections.md

This PR adds documentation to the `join` method: https://github.com/laravel/framework/pull/27723

[5.8] add documentation to `join` method on collection

---

logging.md

Missing Instructions for PaperTrail driver in Logging docs

Missing mention of papertrail driver in the logging docs

---

eloquent-mutators.md

Otherwise, the following notice is generated:
> Notice: Undefined offset: 1 in /path/to/vendor/illuminate/database/Eloquent/Concerns/HasAttributes.php on line 485

You *must* define the number of decimal digits

---

horizon.md

While this could be more detailed and verbose for the benefit of troubleshooting, it's unclear whether that would be accepted, so I chose to use the same brief wording as the Telescope docs use.

[5.8] Add upgrade note about publishing Horizon's assets

---

logging.md

(Same change as was merged into 5.8)

Fix listed default permission to be octal 0644

---

dusk.md

https://github.com/laravel/dusk/issues/631

[5.6] Fix Dusk installation

---

eloquent.md

- Remove unnecessary white spaces.
- Add 2 spaces at `@param` section.
Cheers! 🍻

[5.8] Fix code style in eloquent.md

---

events.md

To be used with Event Discovery

[5.8] Added Automatic Discovery section

---

responses.md

Two additional paragraphs to note the middleware purpose and usage.

 [5.8] Added Cache-Control middleware section

---

validation.md

This is an available rule that should be present in this list

[5.8] Add missing 'sometimes' rule

---

scheduling.md

[5.8] Document new scheduled task methods

---

collections.md

Fixes a couple of typos introduced in #5125

[5.8] Fix Collections duplicates docs

---

billing.md

See https://github.com/laravel/cashier/pull/641

[5.8] Encourage setting up Cashier webhooks

---

mail.md

Right-align text in table as denoted by table alignment syntax

[5.5] Right-align text

---

mail.md

Right-align text in table as denoted by table alignment syntax

[5.4] Right-align text

---

validation.md

Includes examples for showing a custom text, and the error message.

[5.8] Added @error blade directive

---

homestead.md

with Joe's latest "shift" to more optional software being installed in the provisioning process, rather than the base box, let's break these sections out so it's more obvious what's installed by default and what's needs to be optionally installed via a config value.

[5.8] Update homestead.md

---

eloquent-relationships.md

This PR adds documentation for the `$with` property and the `without` method.
Feel free to change any of the wording if necessary.

[5.8] Add additional eager loading documentation

---

filesystem.md

Using singular version "application" instead of plural version "applicationS"

[5.8] Remove "s"

---

homestead.md

Resolves https://github.com/laravel/homestead/issues/1113

add quotes around natdnshostresolver option

---

migrations.md

https://github.com/laravel/framework/commit/c19c04e383778f7a94e9f770d7a85ff45d4dd372

[5.8] Added SET Column Type

---

homestead.md

Updates to the latest 8.4.0 version. https://github.com/laravel/homestead/releases

[5.8] Update Homestead Version

---

dusk.md

See https://github.com/laravel/dusk/releases/tag/v5.1.0

[5.8] Document new ChromeDriver command

---

envoy.md
valet.md

- "retrieve" misspelt
- Double word "written written"

[5.8] Correct typos

---

filesystem.md

Took an hour to figure this out 😐

[5.8] S3 request parameter note

---

validation.md

This is in conjunction with PR [#28455](https://github.com/laravel/framework/pull/28455) to the framework.

[5.8] Document "ends_with" rule

---

filesystem.md
mail.md

These were deleted on the framework's master branch.

[5.9] Remove docs for deleted drivers

---

routing.md

https://github.com/laravel/framework/issues/28457
Added notes about same route path defined in multiple domains.

[5.8] Update Sub-Domain Routing

---

eloquent-relationships.md

[5.8] Update eloquent-relationships.md

---

queries.md

PR adds a small note about debugging the Query Builder.
https://github.com/laravel/framework/pull/28357

[5.8] Debugging the Query Builder

---

homestead.md

The tag version in the update instructions is lagging behind the current version.

Update Homestead version in "Updating Homestead"

---

homestead.md

https://github.com/laravel/homestead/issues/1126
Liberally taken from the great blog post https://stevegrunwell.com/blog/laravel-homestead-user-customizations-sh/

[5.8] Add info about user-customizations.sh

---

migrations.md

Hello community and Laravel docs maintainers 👋, this PR add documentation for the `Blueprint::dropMorphs` method.
Thanks in advance for taking the time to review it. I hope you all have a good rest of the day.

[5.8] Add documentation for dropMorphs

---

eloquent.md

Add saving & updating events to mass update note

[5.8] Update eloquent.md

---

http-tests.md

Two methods which don't appear to be documented.

[5.8] Document dump and dumpHeaders

---

blade.md

Document the optional @json arguments and warn about possible issues.

[5.8] Address @json issues

---

horizon.md

Unify an absolute URL to relative.

Unify to relative url for horizon.md

---

scout.md

There are eight methods in following codes. However explain "seven" method to implement.

[5.8] Correct number of method

---

upgrade.md

Laravel 5.7 Upgrade doc:
https://laravel.com/docs/5.7/upgrade
The "ConnectionInterface" file is in the "Illuminate\Database" path.

Fix ConnectionInterface file path

---

authorization.md

I could not find the mapping between my controller methods and my policy when using authorizeResource... I think it could help someone else...

[5.8] Update authorizeResource policy mapping

---

helpers.md

Adds documentation for the new `containsAll()`  string helper.
laravel/framework/pull/28806

[5.8] Str::containsAll()

---

http-tests.md

Adds doc for PR [#28851](https://github.com/laravel/framework/pull/28851/)

[5.8] add unauthorized assertion

---

blade.md

for https://github.com/laravel/framework/pull/28783
I was going to hold off until I had PR'ed `componentWhen` and `componentIf`, but those are proving to be a little more difficult, so getting these docs in now.

[5.8] add `@componentFirst` documentation

---

eloquent-relationships.md

https://github.com/laravel/framework/pull/28928

[5.8] Add whereHasMorph()

---

authorization.md

Add @canany to the blade usage as per the directives being added in [5.6](https://github.com/laravel/framework/pull/24137)

[5.8] Add @canany and @elsecanany documentation

---

database.md

"Listening For Query Events" and "Running Raw SQL Queries" are different topics.

[5.8] Restructure database headings

---

collections.md

This is a resubmit of #5284.
I removed the linebreaks as it was requested.

[5.8] Add docs for mergeRecursive, replace and replaceRecursive

---

collections.md

[5.8] fix mergeRecursive method's example

---

mocking.md

This PR adds a small section of documentation for the TestCase `spy` method.

[5.8] Add documentation for the TestCase `spy` method

---

queues.md

Briefly mention queue:listen command, my personal favourite in dev environment, thank to this [article](https://divinglaravel.com/queue-workers-how-they-work).

[5.8] Briefly mention queue:listen command

---

queries.md

https://github.com/laravel/framework/pull/25797

[5.8] Support JSON UPDATE queries on PostgreSQL

---

routing.md

Resubmit of #5307. 
Tried to clean up the context and make it a bit more straightforward as it was requested.

[5.9] Add docs for distinct rate limits

---

broadcasting.md

missing semi-colon

---

homestead.md

It seems the purpose of Blackfire, and how to use it, is somewhat unclear to some of the Laravel community, as per support requests we receive. This intends to clarify those points.
Please let me know if there's anything that should be changed.

[5.8] Add Blackfire usage and configuration details

---

migrations.md

https://github.com/laravel/framework/pull/29213

[5.8] Support collation() on PostgreSQL

---

dusk.md
seeding.md

The length of passwords used in database changed to 8 and "secret" does not satisfy this condition.

[5.8] Password default "secret" changed to "password"

---

validation.md

webp was added to image validation in v5.8.30

[5.8] Add WEBP to image validation rule

---

dusk.md

https://github.com/laravel/dusk/pull/661

[5.8] add assertButtonEnabled and assertButtonDisabled

---

http-tests.md

Reference https://github.com/laravel/framework/pull/29258

[5.8] Add Option test method

---

filesystem.md

Documenting how to specify permissions for local driver. Same #5338 with name of the config file added in this and the previous paragraph.

[5.8] Add "visibility to permissions" mapping, with file named

---

http-tests.md

Ref: https://github.com/laravel/framework/pull/29327

[5.8] Update HTTP Tests for assertSessionHasInput

---

migrations.md

Ref: https://github.com/laravel/framework/pull/29289

[5.8] Update doc on creating an UUID polymorphic column

---

billing.md

I think it's `stripe_status` instead of `status`.

Typo in line 403 & 797

---

billing.md

Just thought this might benefit folk who aren't used to the tooling and process surrounding developing with Webhooks.

[5.8] Added a section on testing webhooks locally.

---

passport.md

The examples in the Passport docs don't use the [state parameter](https://tools.ietf.org/html/rfc6749#section-4.1.1). If you follow the example verbatim your application will be [vulnerable to CSRF attacks](https://tools.ietf.org/html/rfc6749#section-10.12).
Adding the state parameter to the example only require a few extra lines of code and may protect someone from accidentally allowing CSRF on their callback route.

Use the state parameter in Passport examples

---

homestead.md

Add more clarity on where to put `minio: true` statement.

[5.8] Update the place to put minio in Homestead.yaml

---

notifications.md

Goes with https://github.com/laravel/framework/pull/29687
This is done in the same fashion as the Slack driver where it's also needed to manually implement this.

[6.0] Document new routeNotificationForNexmo requirement

---

queries.md

Reference https://github.com/laravel/framework/pull/29639

[5.8] Add insertOrIgnore method in Query Builder

---

horizon.md

We have fix the min and max processes, very nice to have this in the docs! :)

[5.8] Added min and max processes to horizon page

---

mail.md

Reported in https://github.com/laravel/framework/issues/29723.

[5.8] Fix typo

---

redis.md

[Fixes #29806](https://github.com/laravel/framework/issues/29806)

[6.0] Added additional step to setup PHP Redis

---

dusk.md

Add a starting point instruction on how to test the code using GitHub Actions v2.0

[5.8] Add instructions about GitHub Actions v2.0

---

installation.md

Add version constraint to `composer create-project` as this branch is now no longer master.

[5.8] Update installation docs to include version constraint

---

frontend.md

This explains how people can extend the package with their own presets and optionally create their own integrations and packages.

[6.x] Add docs for preset macros

---

validation.md

Change link for Date class documentation from es to en

Change link for Date class documentation from es to en

---

scheduling.md

Be more explicit about the time of execution for schedule tasks.

[6.x] Update scheduling.md

---

upgrade.md

The visiblity for method validationData() in FormRequest has been changed from protected to public

[6.x] Add note about validationData method change

---

installation.md

Updated Composer's system-wide vendor bin directory for updated Laravel installer from $HOME/.composer/vendor/bin to $HOME/.config/composer/vendor/bin

[6.x] Update installation.md

---

eloquent-relationships.md

Add a few uses of the loadCount function.

[6.x] Add uses of loadCount function

---

pagination.md

added getPageName() and setPageName() functions to pagination.md

[6.x] Update pagination.md

---

requests.md

The pull request adds documentation to `hasAny` method. 
Reference:
https://github.com/laravel/framework/blob/6.x/src/Illuminate/Http/Concerns/InteractsWithInput.php#L100

[6.x] Add `hasAny` method

---

envoy.md

[6.x] Document Envoy imports

---

billing.md

Document the new logging functionality from https://github.com/laravel/cashier/pull/790

[6.x] Document Cashier logger

---

seeding.md

Nobody is using refresh anymore. No need to recommend it for re-seeding, right?

replace refresh with fresh

---

http-tests.md

Adds strict params to `assertJson` and `assertJsonPath`. https://github.com/laravel/framework/pull/30142

[6.x] Add strict params to testing assertions

---

valet.md

Info on new command added here: https://github.com/laravel/valet/pull/824
We weren't sure of the branch you'd want it into so I've gone for 5.8,  I can update / make multiple if that's the preference. Cheers

[5.8] Add documentation for valet parked command

---

billing.md

Added array example to determine if an user is subscribed to `monthly` or `yearly` plan.

[6.x] Add array example for subscribedToPlan

---

frontend.md

This PR adds the link to the React documentation.

[6.x] Add react link

---

validation.md

Changed `requests's`  to `request`.

[6.x] Grammar fix

---

api-authentication.md

- In the API Authentication documentation, Table of content titled Database Migrations and the main topic was Database Preparation, So I correct it with Database Migrations.

[6.x] Topic Title

---

requests.md

Document the method added in https://github.com/laravel/framework/pull/30320

[6.x] Add the new "missing" method to requests.md

---

passport.md

[6.x] Fix docblock formatting of passport

---

http-tests.md

This pull request documents assertCreated()
Reference: https://github.com/laravel/framework/pull/30368

[6.x] Documents assertCreated

---

blade.md

Adds documentation for PR [#30492](https://github.com/laravel/framework/pull/30492) on framework repo.

[6.x] Added documentation for PR #30492

---

billing.md

Documents https://github.com/laravel/cashier/pull/801

[6.x] Document findPaymentMethod

---

billing.md

Documents https://github.com/laravel/cashier/pull/802

[6.x] Document new keepPastDueSubscriptionsActive setting

---

filesystem.md

Documents laravel/framework#30441

[6.x] Documents `missing` method in filesystem

---

billing.md

Documents https://github.com/laravel/cashier/pull/810

[6.x] Document webhook events

---

queries.md

Very minor. Noticed a weird comma in one of the headers. Removed it.

Remove weird comma from numeration in header

---

collections.md

This pull request documents https://github.com/laravel/framework/pull/30443

[6.x] Documents LazyCollection remember method

---

helpers.md

This merge request documents https://github.com/laravel/framework/pull/30507

[6.x] Document Str::afterLast() and Str::beforeLast()

---

controllers.md

I was wondering why the documentation says nothing about nested resources, since I really like this feature and use this a lot.
This can be found in the laravel 5.1 docs, however, since laravel 5.2 it's not documented anymore even though this is still possible. So I merged this over ;)

[6.x] Add nested resources to route resources

---

session.md

PR updates the outdated Redis information within the Sessions page.

[6.x] Update Redis Information

---

blade.md

Documents `includeUnless` directive
Reference: https://github.com/laravel/framework/pull/30538

[6.x] Documents includeUnless directive

---

broadcasting.md
queues.md

As a reaction to this tweet [https://twitter.com/taylorotwell/status/1195350041927593991](url), I thought it might be worth mentioning PhpRedis for Redis queues and for broadcasting since PhpRedis appears to be steadily updated as opposed to predis.

[6.x] Mention PhpRedis for Redis queues and for broadcasting

---

blade.md

per this commit
https://github.com/laravel/framework/commit/7ff698ddab815888759946a5a2b71b019de39911

[6.x] fix closing @componentFirst tag

---

eloquent-relationships.md

Documents `wherePivotNotIn`
Reference: https://github.com/laravel/framework/pull/30671

[6.x] Documents wherePivotNotIn

---

eloquent.md

This reflects the current stub generated.

[6.x] Added `forceDeleted` method to eloquent observer's stub

---

collections.md

Documents the `sortDesc`method  added in `Collection` at https://github.com/laravel/framework/pull/30672

[7.x] Document sortDesc method

---

authentication.md

Now the route `/home` can be edited from the `Home` constant in the `RouteServiceProvider` file.
**Motivation**
By https://github.com/laravel/laravel/pull/5173

[6.x] Customize const Home

---

authentication.md

This was introduced 4 months ago: https://github.com/laravel/framework/pull/29397
I submitted a PR: https://github.com/laravel/framework/pull/30839 because I wasn't aware.
Very cool addition that I didn't know existed.

[6.x] Describe other ways of logging users out

---

dusk.md

resubmission of #5658 
sorry, not sure what happened on that PR.

[6.x] document `fitContent` Dusk method

---

upgrade.md

do not merge this unless https://github.com/laravel/framework/pull/30867 is merged.
I wanted to get this opened, though, so I wouldn't forget.

add note that factory types have been removed

---

notifications.md

Refs https://github.com/laravel/docs/pull/5668
No longer a tip.

[6.x] Setting the recipient name in a notification

---

notifications.md

Fix array order as seen working in https://github.com/laravel/framework/issues/18439#issuecomment-567038986

[6.x] Custom recipient name notification fix

---

database-testing.md

I actually spent a day Googling this because I knew it could be done and found no results on it. Finally cribbed the answer from someone in our local Meetup group who I happen to know has done it. Thought it would be good to add it since it's not an uncommon use case and it's not necessarily obvious how to use `raw()` to accomplish it.

[6.x] Extending Factories

---

eloquent.md

I found this pretty cool method source diving and figured it might be worth documenting 🤙
Feel free to change the explanation or code example.

[6.x] Document the Builder firstOr method

---

queues.md

Update obsolete URL of `Beanstalkd`

Beanstalkd URL updated

---

validation.md

Adds documentation for laravel/framework#30896

Add doc about validateWithBag

---

homestead.md

Updated the per project dependency to 10.x rather than 9.x

Update homestead update directions

---

validation.md

Adds docs for newly added validation rules `exclude_if` and `exclude_unless`.
https://github.com/laravel/framework/pull/30835

[6.x] Validation Rules exclude_if, exclude_unless

---

upgrade.md

This pull request adds a note about collision on the upgrade guide.

[7.x] Adds note about collision on upgrade guide

---

passport.md

Adds docs for Authentication code with PKCE Grant - laravel/passport#1065

[6.x] Update passport.md to add Authentication code w/ PKCE grant

---

database-testing.md

Update static password in user factory example

[6.x] Update database-testing.md

---

eloquent-relationships.md

See https://github.com/laravel/framework/issues/31098

[6.x] Clarify relationship naming

---

filesystem.md

Added section for methods used for retrieving original filename and it's extension of uploaded file namely
`$request()->file('avatar')->getClientOriginalName()`
`$request()->file('avatar')->extension()`
in filesystem.md

[6.x] Added methods retrieving uploaded file details

---

helpers.md

documents https://github.com/laravel/framework/pull/31148

[6.x] Documents Str::isUuid method

---

eloquent.md

docs for `isDirty()`, `isClean()`, and `wasChanged()`

[6.x] Document Eloquent internal state methods

---

routing.md

This is an update to the docs related to using named rate limiting, which is so important to be clear for all Laravel users.
This is my first time making a pull request to a public repository, so I'm sorry if it's not a perfect one.

[6.x] Named rate limiting

---

http-tests.md

https://github.com/laravel/framework/pull/31131

[6.x] Document the `dumpSession` testing method

---

dusk.md

Fixing the dusk component example

Update dusk docs

---

requests.md

Updated the true cases to fit all situations a `true` will be returned. My mistake!

[6.x] Updated boolean() method docs

---

views.md

- notes about `view:cache`
- notes about new expiration check feature

[7.x] add docs for optimizing views

---

eloquent-relationships.md

There is sometimes more confusion than necessary when developers new to Laravel first create a Many To Many relationship.
The docs have example table structure for polymorphic relationships, I think it might help to include an example for Many To Many, too, as it's the first move away from a simple one-model-one-table structure in this page of the docs.

Add example table structure for Many To Many

---

billing.md

This is something that I often see people asking and I believe adding this will make people more aware that they can easily access Stripe objects this way.

[6.x] Document asStripe calls

---

valet.md

Fixes https://github.com/laravel/valet/issues/902

[6.x] Add clarity to Valet's site environment variables configuration

---

logging.md

since this [PR](https://github.com/laravel/laravel/pull/5214) got closed, I thought I'd add a note here.

[6.x] add note about Slack default minimum level

---

container.md

we need to reference the FQNs from the root.

[6.x] fix FQNs

---

eloquent.md

I just removed the non-needed apostrophe here.

remove wrongly-used apostrophe

---

filesystem.md

https://github.com/laravel/framework/pull/31355

[7.x] add notes about configuring additional symbolic links

---

dusk.md

[6.x] Fix url to GitHub repository for Dusk modifier keys

---

upgrade.md

There are some minor config changes required for running on Laravel Vapor that I ran into when upgrading from 5.8.

[6.x] Updated upgrade.md to include Cache and Queue config changes for Vapor

---

queries.md

I feel like some people may get a little confused about where() nesting and the end SQL query. This should hopefully add some clarity or at the very least inform people that they can pass functions and nest the where() statements.

[6.x] Add nested orWhere() example

---

socialite.md

Hello!
I know this is not a big thing, but while browsing the socialite docs I saw that there's a use statement missing for the Controller.
The code would throw an error as it can't find the Controller class in the App\Http\Controllers\Auth namespace.
Thanks!
Tom

Add "use" statement for Controller class

---

upgrade.md

Just a minor typo where `effect` was spelled as `affect` :)

Fixes minor typo

---

billing.md

This adds some additional docs based on recent questions by users on Discord and such.

[6.x] Improve Cashier customer docs

---

authentication.md

Adding visibility of undocumented methods for extending the login/logout response without having to alter the core Laravel behavior.

[6.x] Surfacing the overridable authenticated and loggedOut methods

---

billing.md

Documents https://github.com/laravel/cashier/pull/869

[6.x] Document findBillable

---

queries.md

This pull request documents query builder support for `groupByRaw`
Ref https://github.com/laravel/framework/pull/31498

[6.x] Documents groupByRaw

---

passport.md

For https://github.com/laravel/passport/pull/1159

[6.x] Document passport:purge command

---

broadcasting.md

This step is unclear on both Laravel's docs as on the Pusher site.

[6.x] Added .env instructions for Pusher

---

billing.md

Docs for https://github.com/laravel/cashier/pull/884

[6.x] Document extending trials

---

billing.md

Documents https://github.com/laravel/cashier/pull/887

[6.x] Document stripeEmail method

---

horizon.md

Specify additional information on the `minProcesses` and `maxProcesses`

[6.x] Add more info on auto-scaling

---

pagination.md

Add the new `withQueryString` method to 7.x docs.

[7.x] Add withQueryString method to docs

---

eloquent-relationships.md

I know it's minor but the loop will run 25 queries, not 26. It's the whole code that will make a total of 26.

[8.x] Minor fix

---

installation.md
readme.md

change php Requirement
change laravel version in readme

change php Requirement

---

upgrade.md

See https://github.com/laravel/framework/issues/31718

[7.x] Note PHPUnit requirement

---

upgrade.md

Not sure about the level of the impact, leaving it at low :+1:

[7.x] Add CORS section to upgrade guide

---

routing.md
upgrade.md

Document https://github.com/laravel/framework/issues/31732

[7.x] Route breaking changes

---

packages.md

This is my first time submitting PR, let me know if there's anything i can do to improve.
This PR adds the documentation on the new Laravel 7's view components.

Add docs on package's view components

---

upgrade.md

adding laravel/tinker to composer updating Dependencies

Add tinker to composer dependencies

---

upgrade.md

for correct work cors new dependency need to be added in composer.json at require section.

[7.x] Update upgrade.md

---

migrations.md

First parameter name is the column name.

[7.x] Fix softDeletes column parameters

---

errors.md

Reported here: https://github.com/laravel/framework/issues/31758#issuecomment-595865294

[7.x] Update to new Throwable

---

blade.md

Fix a small typo in the directory for Anonymous components.

Update components directory to be correct

---

blade.md

I'm not too sure on how to elaborate on this, as I don't want to put what I assume is the case for something or misspeak, feel free to modify this PR to clarify further.

[7.x] Document morphed property names for Component classes.

---

billing.md

I can't even begin to count the amount of times people asked me if this is possible so it's best that we document it.

[7.x] Document single charge without customer

---

eloquent-relationships.md

There doesn't seem to be any documentation on this anywhere else, I sort of had to guess at it and look at the code, I figured adding this tidbit to the docs would help someone else later.

[7.x] Document Relation::getMorphedModel and Model::getMorphClass

---

migrations.md

[7.x] Document SQLite foreign keys limitation

---

billing.md

Documents https://github.com/laravel/cashier/pull/896

[7.x] Document new Cashier success param

---

notifications.md

Second attempt to add missing piece saying how to customize notification type of a broadcast notification.

[7.x] Add information about broadcast notification type customization (2nd attempt)

---

eloquent-mutators.md

Clarify nullable attributes when casting.

[7.x] Update eloquent-mutators.md

---

billing.md

Since we've been getting a lot of questions lately about testing with Cashier I thought it couldn't hurt to write a small part for the docs. Might need some Taylor-polishing 😉

[7.x] Add testing part to Cashier docs

---

verification.md

[7.x] Fix incorrect link

---

billing.md

Updates the Cashier docs for v11.

[7.x] Cashier v11

---

helpers.md

Add fluent str is not empty

---

collections.md

Documents the new `until` method added in https://github.com/laravel/framework/pull/32262

[7.x] Document until collection method

---

migrations.md

Following https://github.com/laravel/framework/pull/32316

Add uuid type in changeable columns

---

billing.md

Documents https://github.com/laravel/cashier/pull/915

[7.x] Document multiplan swapping

---

contributions.md

Add a link to bugs on the issue trackers

[7.x] Update contributions.md

---

passport.md

Clarify that the JWT lifetime depends on the session lifetime setting. See https://github.com/laravel/passport/issues/909#issuecomment-482659835

[7.x] Document JWT lifetime

---

mail.md

Document the behavior from https://github.com/laravel/framework/issues/31810
I felt this deserved its own separate section.

[7.x] Document looping over mailables

---

migrations.md

Documentation for [laravel/framework#31853.](https://github.com/laravel/framework/pull/31853)

[7.x] Add documentation for constrained method

---

container.md

Documentation for laravel/framework#32454.

[7.x] Add documentation for binding typed variadics

---

homestead.md

Fixing a small typo where `the` was capitalized after a comma.

fixed small typo

---

eloquent-relationships.md

Documents https://github.com/laravel/framework/issues/23048

[7.x] Document relationship name

---

dusk.md

Documents https://github.com/laravel/dusk/pull/767

[7.x] Document in Dusk using `back()` or `forward()`

---

queries.md

We've had quite a bit of people who were thrown off by this behavior so I tink it's best we should document it.

[7.x] Add note about increments event behavior

---

homestead.md

Updates from latest Homestead release: https://github.com/laravel/homestead/releases/tag/v10.8.0

[7.x] Add versions for PostgreSQL & Add wildcard notes

---

eloquent-resources.md

It is possible to customize the wrap key by setting the $wrap attribute on the resource class.

[7.x] Add a note about customize the wrap key

---

passport.md

This documents how people can use uuid as primary key for their oauth clients if they wish.
Alternative to https://github.com/laravel/passport/issues/14

[7.x] Document Passport client primary key as uuid

---

passport.md

This adds some basic documentation around the new Passport functionality for multi-provider support.

[7.x] Passport multi-provider documentation 

---

notifications.md

Nexmo is now Vonage.
I did not change anything on the driver.

Nexmo became Vonage

---

dusk.md

Added more paths to store as artifacts after tests, so that backend logs and JS console logs would be stored as well, for easier troubleshooting after tests.

Add details for CircleCI config

---

http-client.md

[7.x] Added information about the `failed` method in the Http facade

---

helpers.md

this was originally for 6.x, but was requested to put it in 7.x
https://github.com/laravel/docs/pull/5943

[7.x] update helpers.md with Str::ascii

---

blade.md

For https://github.com/laravel/framework/pull/32742

[7.x] Document new Blade environment directives

---

blade.md

Since https://github.com/laravel/framework/pull/32742 got merged it's best that we update this example.

[7.x] New blade if example

---

blade.md

Eh, I forgot to update the actual implementation..

[7.x] Update Blade if example

---

blade.md

[7.x] Fix closing directive for Custom If Statements

---

configuration.md

add default config value sample code.

add default config value on Accessing Configuration Values

---

contributions.md

I'm not sure about the positioning, let me know if want to change the position.

Added GitHub discussions as one of support channel

---

authentication.md

Include path for `AuthenticatesUsers` trait

[7.x] Update path customization in Authentication document

---

eloquent-relationships.md

Refers to https://github.com/laravel/framework/pull/33025.
I'm not really sure where to place its documentation.

[7.x] Add docs for resolveRelationUsing

---

dusk.md

Documents https://github.com/laravel/dusk/pull/748

[7.x] Document typeSlowly

---

billing.md

[7.x] Note proration behavior with swapAndInvoice

---

queries.md

I'm not sure that joining sizes and colors will produce users and I decides to improve naming

[7.x] Rename query result variable

---

homestead.md

Add instructions to the "Updating Homestead" section so the user is always using the updated `aliases` file. 
I ran into this issue when trying out the `phpX` commands on an updated version of Homestead. 
See [this issue](https://github.com/laravel/homestead/issues/1433) for reference.

[7.x] Update homestead.md

---

dusk.md

Adds documentation for function, adds example for use in components.
Function added in [laravel/dusk#784](https://github.com/laravel/dusk/pull/784)

[7.x] Document Browser Function elsewhere

---

cashier-paddle.md

Since quite a few people have already reported that they were confused with how pay links worked I'm hoping to make things clearer by added these snippets to a few places.

[7.x] Clarify usage of pay link

---

session.md

[7.x]Update session example to match the stub created

---

deployment.md

this copy can surely be improved but it feels like Vapor belongs here.

added vapor to deployment section

---

eloquent-mutators.md

Note for https://github.com/laravel/framework/issues/33257

[7.x] Note about serializing value objects

---

valet.md

Adding this subsection to the docs aims to fix https://github.com/laravel/valet/issues/962

Add Expose note to Valet docs

---

eloquent-collections.md

`toQuery` method added at https://github.com/laravel/framework/pull/33356

[7.x] Add method toQuery

---

scheduling.md

Since the methods were added at https://github.com/laravel/framework/pull/33379
```
everyTwoMinutes()
everyThreeMinutes()
everyFourMinutes()
```

Update frequency options

---

billing.md

https://github.com/laravel/cashier/pull/966

[7.x] Cashier Customer billing portal

---

blade.md

Add documentation for functionality released in 7.18

Document whereStartsWith() on Blade Components

---

scheduling.md

This is updated because new methods were added here https://github.com/laravel/framework/pull/33393

[7.x] Update Schedule Frequency Options

---

collections.md

Revert "Add doesntHave() to collections.md"

---

dusk.md

- As per the rest of the file state the type of cookie: encrypted 🔒
- Correct closing tags
- Formatting

[7.x] As per the rest of the file state the type of cookie: encrypted

---

billing.md
collections.md
filesystem.md
helpers.md
logging.md
migrations.md
passwords.md
scout.md
socialite.md
upgrade.md

Trim trailing whitespace

---

eloquent-relationships.md

[7.x] Update eloquent-relationships.md

---

scheduling.md

documents `monthlyOnLastDay()`.
Ref: https://github.com/laravel/framework/pull/33241

[7.x] add monthlyOnLastDay

---

horizon.md

Because: https://github.com/laravel/horizon/commit/82d647cb38c079cce7e395eb943a5b6a230e3383

[6.x] Update horizon.md (Laravel 6)

---

eloquent.md

Add migration down method exemple for soft delete

[7.x] Update eloquent.md

---

dusk.md

You need to use `composer require --dev laravel/dusk:"^5.0"` with laravel 5.7.

[5.7] Update dusk installation

---

dusk.md

You need to use `composer require --dev laravel/dusk:"^5.0"` with laravel 5.8.

[5.8] Update dusk installation

---

mail.md

Add some missing DocBlock parameters.

[7.x] Update mail.md

---

helpers.md

Resubmission #6168
Add docs for `when()` Method to `Stringable`.
Ref: [laravel/framework#33455](https://github.com/laravel/framework/pull/33455)

[7.x] Stringable when

---

billing.md

Added the aforementioned and cleaned up the invoice category a bit.

Document retrieving a specific invoice

---

cashier-paddle.md

In draft until beta 2 is released.

[7.x] Update docs for beta 2

---

homestead.md

Updates for Homestead 11.0.0 & 10.12.0. Feel free to massage grammar, etc.
Thanks!

[7.x] Describe service usage & update wildcard behavior

---

queues.md

Related with laravel/framework PR https://github.com/laravel/framework/pull/33627

[7.x] Added new --range option to queue:retry command

---

blade.md

Use @show instead of @endsection in the layout so the content then is yielded instead of just defined

@endsection changed to @show in the layout view

---

notifications.md

[7.x] Update notifications.md

---

blade.md

See https://github.com/laravel/framework/issues/32497

[7.x] Document accessing extra data in render method

---

scout.md

Documentation for https://github.com/laravel/scout/pull/411

[7.x] Document auto identifying users in Scout

---

scout.md

Changed in
https://github.com/laravel/scout/commit/fe28ab26bf1e5c9c3b46f2535bea746b69fa6fb1

Rename SCOUT_IDENTIFY_USER to SCOUT_IDENTIFY

---

controllers.md

[7.x] fix typo in controllers

---

blade.md

Added note about `@once` directive into **Blade Templates** section.
Based on https://github.com/laravel/framework/pull/33812

[7.x] Add note about @once directive

---

blade.md

Added missing A tag for once directive

---

testing.md

The artisan test runner will be provided by Collision 5. It now supports `--stop-on-failure`, and gives even better error reporting.

[8.x] Updates docs about artisan test runner

---

queues.md

Related: https://github.com/laravel/framework/issues/34012

[7.x] Improved Queue Timeout Docs

---

providers.md

Fix typo in providers.md

---

helpers.md

I suppose we need to update the master branch as well?
I can do that once somebody approves this PR.

[7.x] Replace "a third argument" with "a second argument"

---

configuration.md

In my opinion a more descriptive word, with the added bonus of being more inclusive (or rather less exclusive).

[7.x] Replace "blacklist" with "disallow"

---

redis.md

Regarding changes in https://github.com/laravel/framework/pull/33892 and https://github.com/laravel/framework/pull/34017.

[7.x] Document connection schemes for redis

---

blade.md

Corresponds to the updates in https://github.com/laravel/framework/pull/33590

Document @env's parameters

---

helpers.md

This PR reflects changes found in https://github.com/laravel/framework/pull/34053.
cc @driesvints 
PR creation didn't seem to work like I expected, but everything seems OK to me.  Still, please make sure I haven't screwed something up. 😜 
Thx.

[7.x] Updated docs to reflect new string padding methods.

---

cashier-paddle.md

Follow up documentation to
https://github.com/laravel/cashier-paddle/pull/67

[7.x] Add webhook events to cashier-paddle.md

---

upgrade.md

Added some more dependency upgrades in the same fashion style of the Laravel 7 upgrade guide.

[8.x] Update dependency upgrades

---

upgrade.md

Fixes code indentation for docblock and method definition in the `Session` Contract section of the upgrade file.

Upgrade: Fix Code Indentation

---

queues.md

This information will help until a solution is found.
---
Related Issue: https://github.com/laravel/framework/issues/34153

[7.x] Improved Queue Timeout Document

---

upgrade.md

Even though the Installer isn't involved in the upgrade process, it's still a good place to mention this here.

[8.x] Add note about Laravel installer

---

releases.md

There're two bad images in this document, they no longer load.
I attach what I believe are the latest versions.

[7.x] Fix broken images

---

errors.md

Document change in https://github.com/laravel/framework/pull/34200

Renderable callbacks accept the request as a second parameter

---

authorization.md

Post model name was missing from some of the examples

Model name incorrect on some of the examples

---

upgrade.md

Upgrade phpunit to 9.0, because is required for nunomaduro/collision 5.0

Add upgrade of phpunit

---

passport.md

This isn't needed anymore with the latest Passport version.

[8.x] Update passport.md

---

dusk.md

Spent half a day trying to work this out, stumbled across this stackoverflow answer https://stackoverflow.com/a/50376781 - felt it should be inclued in the docs

[8.x] Added note regarding using in-memory database for dusk

---

blade.md

Documents https://github.com/laravel/framework/pull/34144

[8.x] Document class autoloading for Blade components

---

filesystem.md

Copy pasted @LukeTowers's PR. See https://github.com/laravel/docs/pull/6359

[8.x] Document gotcha with local filesystem driver url() method.

---

contributions.md

Add laravel/jetstream to repository list and remove laravel/ui as it shouldn't be used.

Add laravel/jetstream and remove laravel/ui

---

readme.md

bump version number of current standard release example from 7.x to 8.x

bump version number

---

installation.md

This PR updates composer create-project command for Laravel 7.x installation

[7.x] Update composer create-project command for Laravel 7.x

---

upgrade.md

The statement seemed a bit off and I think there's a missing and (It could be an 'or' though 🤔)

[8.x] Possible Missing Conjuction

---

migrations.md

Update docs based on https://github.com/laravel/framework/pull/34323

[8.x] Add SQLite migration squashing support to docs

---

migrations.md

Some people are running into this so it's probably best that we explain this in the docs: https://github.com/laravel/framework/pull/32275

[8.x] Explain schema dumping and in memory sqlite testing constraint

---

database-testing.md

User::factory()
->has(Post::factory()->count(3))
->create();
returns one User, not many.

Plural case used for Factory@has return, should be singular.

---

blade.md

[8.x] Minor grammatical fix

---

horizon.md

Documentation for the `horizon:clear` command based on https://github.com/laravel/horizon/pull/892

[8.x] Document the horizon:clear command

---

releases.md

Update the Laravel Jetstream link at Laravel 8 release page.

Update Laravel Jetstream link

---

migrations.md

This changed in https://github.com/laravel/framework/pull/32205

[8.x] Clarify that all types but enums can be renamed

---

notifications.md

This PR documents email notification attachments as well as raw data attachments.

[8.x] Document notification attachments

---

configuration.md

Hi, this isn't anything major. It's just an update for a little typo that I spotted on the configuration page for L8 :)

Typo update

---

blade.md

Using the Closure within the render method will implicitly return a view, if a view exists, or create a blade view from the string provided.

[8.x] Update blade.md

---

http-tests.md

PR adds documentation on testing blade components via TestView.  https://github.com/laravel/framework/pull/32601

[8.x] Testing Blade Components via TestView

---

sanctum.md

Hi,
Lets match `Kernel.php` code snippet with `laravel/laravel` 
https://github.com/laravel/laravel/blob/38bc9119eb369eed4d32adbc4132788177712b15/app/Http/Kernel.php#L42-L45

[8.x] Update sanctum docs

---

dusk.md

- Document `waitForTextIn` method (https://github.com/laravel/dusk/pull/823)

[8.x] Dusk - document `waitForTextIn`

---

installation.md

captalize `Extension` in installation required extensions list to be sync with another list items

captalize `Extension` in installation required extensions list

---

installation.md

- Change Fileinfo PHP extension by Fileinfo PHP Extension
inspired by #6460

[6.x] Capitalize Extension

---

controllers.md

- Add `\Illuminate\View\View for View`

[8.x] Fix docblock

---

scheduling.md

Documenting https://github.com/laravel/framework/pull/34618

[8.x] Document `schedule:work` command

---

scheduling.md

- Document the new Schedule frequency option: `yearlyOn()`
- https://github.com/laravel/framework/pull/34728

Document the new Schedule frequency option: yearlyOn()

---

scheduling.md

- Document `twiceMonthly()` and `unlessBetween()`

[8.x] Document twiceMonthly() and unlessBetween()

---

billing.md
events.md
session.md
validation.md

Found more as I read individual pages and by using the command: `grep -E '\W[aA] \W?[AEIOU].+' *.md`

[8.x] More indefinite articles before vowel sounds

---

dusk.md

- Document `assertScript` method (https://github.com/laravel/dusk/pull/821)

Dusk - document `assertScript()`

---

http-tests.md

Revert "Update http-tests.md"

---

queries.md

Address singular-plural issues in a paragraph

[8.x] Proofread queries.md

---

eloquent-relationships.md

Proofread eloquent-relationships.md

---

eloquent.md

* Possessive form needed for "column's"
* A few missing articles
* Fix some singular-plural issues

Proofread eloquent.md

---

eloquent.md

Added the `replicating` event to the Eloquent Model Events, because I think it is missing there.

[8.x] Added Replicating Event to Eloquent Model Events

---

installation.md

See https://github.com/laravel/framework/pull/34928

[6.x] Bump minimum PHP version

---

routing.md

See https://github.com/laravel/framework/issues/34939

[8.x] Add notes about reserved route parameters for view and redirect routes

---

validation.md

See https://github.com/laravel/framework/issues/34960

[8.x] Update validation.md

---

dusk.md

Added steps to upload `console` and `screenshots` folders when tests fail

[8.x] Improved GitHub Actions sample workflow

---

dusk.md

- Document how to execute JavaScript within the browser
- Update version numbers

[8.x] Dusk - document how to execute JavaScript within the browser

---

horizon.md

Document commands for the PR: https://github.com/laravel/horizon/pull/914

[8.x] Document Horizon pause and continue supervisor commands

---

notifications.md

Just a missing definite article.

Add missing article to notifications.md

---

queues.md

Just a missing definite article.

Add missing article to queues.md

---

queues.md

Adding documentation for unique jobs based on https://github.com/laravel/framework/pull/35042 to be released tomorrow.

[8.x] Documentation for unique jobs

---

queries.md

Clarify https://github.com/laravel/framework/issues/35157 behavior.

[8.x] Clarify cascading truncate in PostgreSQL

---

eloquent-relationships.md

[8.x] Document MorphTo relationship eager loading constraints

---

mail.md

this also aligns the docs with what the user would see in the default `services.php` file.
https://github.com/laravel/laravel/blob/8.x/config/services.php

[8.x] encourage use of environment variables for secrets

---

cache.md

list all the available drivers for caching, since it is not immediately obvious some of them exist, without diving into the source.
this whole section could probably use a little word-smithing, but I think this is good for now to get all of the drivers at least listed.

[8.x] list all the drivers

---

notifications.md

https://github.com/laravel/framework/pull/35273

[8.x] Add docs for per channel delay

---

blade.md

This wasn't documented yet and will prevent issues like these: https://github.com/laravel/framework/issues/35337

[8.x] Document creating components in sub directories

---

eloquent-relationships.md

I came across a broken anchor at the [Eloquent Relationships](https://laravel.com/docs/8.x/eloquent-relationships) page and made a simple script to check the links. 
With this script I found a couple more problems.
- fixes anchor `aggregating-related-models` (prev value `aggregating-related-models-related-models`)
- renames the link `Counting Related Models On Polymorphic Relationships` to match the heading 
- moves anchor `counting-related-models` to the appropriate heading
```php
<?php
/**
* Parses *.md files in the current directory for broken links.
* - [Link](#broken-anchor) without <a name="broken-anchor"></a> within the same file
* - [Link](another-file#broken-anchor) without <a name="broken-anchor"></a> in the another-file.md
*/
foreach (glob('*.md') as $file) {
if ($brokenLinks = …
```

[8.x] Fix anchors

---

routing.md

Documentation for [laravel/framework#35154](https://github.com/laravel/framework/pull/35154)

[8.x] Document whereAlphaNumeric route constraint

---

valet.md

Now homebrew install [php 8 by default](https://formulae.brew.sh/formula/php)

[8.x] Update homebrew default php version

---

dusk.md

Update description for the typeSlowly method

[8.x] Update dusk.md

---

dusk.md

Update description for the typeSlowly method

[7.x] Update dusk.md

---

eloquent-relationships.md

See https://github.com/laravel/framework/issues/35414

[8.x] Document has method and multiple connections

---

contributions.md

My contact at GitHub advised to add this next to the link which seems reasonable.

[8.x] Add note to issues list

---

migrations.md

we reference "on update" in the explanation, but don't show the example.

[8.x] Add `onUpdate` example

---

validation.md

As a follow up for https://github.com/laravel/framework/pull/35419 we should update the docs as well.

[8.x] Update image validation docs

---

installation.md

[8.x] Fix typo

---

sail.md

Typo Fixed

---

socialite.md

To be consistent with the rest of the 'example' domains used in the other parts of the documentation.

[8.x] Update socialite.md

---

homestead.md

Revised according to feedback in https://github.com/laravel/docs/pull/6630#issuecomment-741148852

[8.x] Clarify required software for Homestead - revised

---

fortify.md

[8.x] Update fortify.md - minor typo

---

database-testing.md

Change variable `users` to `user`
This returns me an instance of the User model

[8.x] Update database-testing.md

---

blade.md

I guess something went wrong during previous merge..

Fixed merge

---

telescope.md

Documentation for https://github.com/laravel/telescope/pull/1000.

[8.x] Document hydrations option in Telescope model watcher

---

billing.md

Docs for https://github.com/laravel/cashier-stripe/pull/1032

[8.x] Document new Cashier Stripe withPromotionCode method

---

dusk.md

- Documents https://github.com/laravel/dusk/pull/843

[8.x] Dusk - document `assertSeeAnythingIn()` / `assertSeeNothingIn()`

---

redis.md

Update documentation for https://github.com/laravel/framework/pull/35402

[8.x] Update Redis documentation: add name option

---

dusk.md

Fix URL for Sail documentation on configuring and running Dusk tests.

[8.x] Fix url in dusk.md

---

cashier-paddle.md

Docs for https://github.com/laravel/cashier-paddle/pull/95

[8.x] Document Paddle subscription modifiers feature

---

passport.md

Missing ";" on line 83

---

migrations.md

PR as requested @ https://github.com/laravel/framework/pull/35591#issuecomment-746438726

[8.x] Added configuration for timestamp modification to migrations.md

---

upgrade.md

Update upgrade documentation for https://github.com/laravel/laravel/pull/5456

[8.x] RateLimiter default key

---

mix.md

Just a couple changes to brings the docs current with Mix v6.

Tweaks for Mix v6

---

dusk.md

See https://github.com/laravel/dusk/pull/846

Document `elsewhereWhenAvailable`

---

sanctum.md

A determiner (**the**) cannot combine with a possessive pronoun (**your**).

[8.x] Use single determiner

---

homestead.md

Missed one small area in my previous PR.

[8.x] Add php80 to list of supported PHP versions

---

blade.md

to make alert component used this  
`php artisan make:component Alert `
but to call it used this 
`Blade::component('package-alert', AlertComponent::class);`

Change AlertComponent to Alert

---

queues.md

A few typographical corrections to recently added text. Mainly just missing words/letters.

[8.x] Proofread queues.md

---

upgrade.md

We ran into this issue at hipages. This will help to upgrade faster and is a breaking change for our scenario.

fix: document the change of event registration

---

homestead.md

Related to https://github.com/laravel/homestead/issues/1450

[8.x] Update references of master branch to main for Homestead

---

requests.md

For https://github.com/laravel/laravel/pull/5514

[8.x] Update trusted proxies docs

---

valet.md

Updating as suggested by @mattstauffer in https://github.com/laravel/valet/issues/1021

Fix controversy over "daemon"

---

testing.md

This pull request ports Parallel Testing from Laravel 9 to Laravel 8.

[8.x] Adds parallel testing

---

helpers.md

[8.x] Add pipe / tap method for fluent string

---

releases.md

Add a note that details named parameters don't fall under our BC promise.

[8.x] Named Parameters

---

helpers.md

Credit to @bakerkretzmar - https://github.com/bakerkretzmar/docs/commit/61a1273

Document `Str::substrCount()`

---

helpers.md

- Document `Str::pluralStudly()`
- See [PR #26421](https://github.com/laravel/framework/pull/26421)

[8.x] Document `Str::pluralStudly()`

---

queues.md

[8.x] Update queues.md

---

billing.md

I noticed this method wasn't documented yet.

[8.x] Document cancelNowAndInvoice method

---

blade.md

Feature PR: https://github.com/laravel/framework/pull/36131

[8.x] Added $attributes->class() to Blade docs

---

billing.md

Documents all caveats when creating subscriptions from the Stripe dashboard.

[8.x] Document creating subscriptions from the Stripe dashboard

---

billing.md

Documentation for https://github.com/laravel/cashier-stripe/pull/1048

[8.x] Document Metered Billing

---

eloquent.md

Example doesn't correspond to the previous code where it substracts 2000 years

[8.x] Eloquent global scope example fix

---

billing.md

Documents https://github.com/laravel/cashier-stripe/pull/1062

[8.x] Document endTrial method

---

authorization.md

I noticed it wasn't documented that there is an `@else` directive for `@can` directives.

[8.x] Add @else to @can

---

passport.md

[8.x] Only register passport routes if not cached

---

billing.md
cashier-paddle.md

Documents https://github.com/laravel/cashier-stripe/pull/1067 & https://github.com/laravel/cashier-paddle/pull/106

[8.x] Document custom Cashier models

---

queries.md

I think there is a typo here, suggested fix added.

Fix role titles reference to user titles

---

validation.md

Some changes to bool rule in docs + fetch origin

Boolean validation rule

---

routing.md

Import the `Illuminate\Support\Facades\Redirect` facade.

Import missing facade

---

middleware.md

Grammar correction

---

controllers.md

There was no import for these 2 namespace!
Then I added the full namespace.

Add namespace to comment section

---

envoy.md

Improving Envoy docs for when https://github.com/laravel/envoy/pull/219 and https://github.com/laravel/envoy/pull/220 are released, at @taylorotwell's [request](https://github.com/laravel/envoy/pull/219#issuecomment-786887087)

Add docs for @after, @error, @success and @finished

---

errors.md

Missed Full Stop like the other tips.

Format correction

---

controllers.md

Adds a missing word, `routes` in controllers.md

Add missing word

---

blade.md

Revert "8.x blade contents order fix"

---

requests.md

Code: https://github.com/laravel/framework/blob/0146a3b4b018494fc0faaaed9facd6bd09854458/src/Illuminate/Http/Request.php#L127

[8.x] Add `fullUrlWithQuery()` method
