queries.md
https://github.com/laravel/framework/pull/25328
=> [5.6] Support JSON SELECT queries on SQLite

mix.md
This is an update to my previous PR.
Laravel Mix's versioning/cache busting works differently now. Instead of appending hashes to the file, it uses url query.
=> Update mix's versioning/cache busting documentation(without the tip)

validation.md
The first idea that came into my mind on how to specify a custom column name using the Rule class was to write:
`'email' => Rule::unique('users,<custom_name>')`.
This caused an error:
`(ErrorException(code: 0): Undefined offset: 1 at /var/www/html/vendor/laravel/framework/src/Illuminate/Validation/Concerns/ValidatesAttributes.php:795`.
After sometime I discovered it should be passed as a second parameter to the unique method. I believe it would be nice to have this information in the documentation.
=> Added example for custom column name for unique method with Rule class

localization.md
There was no documentation of the default placeholder `:count` that you can use during localization. This caused confusion with the existing placeholder attribute documentation as users were thinking that they need to provide the value to `trans_choice()` twice in order to display the exact value that caused the pluralization to take effect.
Confusion that was caused: https://github.com/laravel/ideas/issues/1300
The feature is implemented in here: 
https://github.com/laravel/framework/blob/5.6/src/Illuminate/Translation/Translator.php#L210
It may be a good idea to merge this change not only in the 5.6 branch but also in the 5.7 and master as it's not documented in there as well.
=> [>= 5.6] Clarify the usage of the :count placeholder

helpers.md
This is a different attempt at #4461.
The current docs are misleading. It says that passing a Closure to `optional` will only call it **if the object is not `null`**, but the code example seems to imply that it will call the Closure **if the object actually _is_ `null`**.
This PR aims to clear that up.
We essentially have two entirely different signatures for the `optional` helper:
1. `maybeNullObject => Optional` - Calling `optional` with a single argument returns an instance of `Optional`, which allows you to access a property or call a method on the underlying object, noop-ing for when the first argument is actually `null`.
1. `(maybeNullObject , Closure) => maybeNullOtherObject` - Passing a Closure as the second argument changes the return value of `optional`. If the first argument is …
=> Improve docs for "optional" with second argument

upgrade.md
See https://github.com/laravel/framework/issues/25475.
I think this (currently undocumented) breaking change is a good decision overall.
But I also think it would be a good addition to explicitly mention in the upgrade guide for 5.7, as the impact can be quite significant and unexpected.
One scenario where this heavily affects the upgrade process is when you use:
* MySQL as your main database
* in-memory SQLite as your testing database
* have functional tests using the `refreshDatabase` trait, 
* and have migrations which drop foreign keys.
=> Update upgrade.md for Foreign keys in SQLite

upgrade.md
If you do not update Passport, the Encrypted cookies are still serialized by default :(
Or at least we need to mention to add Passport::withoutCookieSerialization() in the AuthServiceProvider for Passport 6.x
=> Passport and Encrypted cookies

verification.md
The `MustVerifyEmail` trait is already used by the parent class `Authenticatable`.
In `App\User`, `MustVerifyEmail` is the class alias for the contract. So using it as a trait would fail:
> App\User cannot use Illuminate\Contracts\Auth\MustVerifyEmail - it is not a trait
=> [5.7] Fix email verification

console-tests.md, releases.md
Fix the command name used in the console test example code to match the name of the example command specified above.
=> Fix the command name used in the console test example

dusk.md
A lot of users are using Gitlab CI as it is a free and powerful CI. Ive added the missing GitLab CI example for Dusk testing.
=> Add GitLab CI to Laravel Dusk

collections.md
`combine` uses the *values* of a collection A as keys and the *values* of collection B.
=> Clarify `combine` uses values

queries.md
Adds `Builder::whereJsonLength()`: https://github.com/laravel/framework/pull/25047
Also ports #4452 and #4453 to 5.7.
Regarding your [comment](https://github.com/laravel/framework/pull/25047#issuecomment-419103913):
AFAICS, the documentation already covers all the available JSON methods. Am I missing something?
Can you change the default branch to 5.7?
=> [5.7] Add whereJsonLength() queries

upgrade.md
Struggled a bit to find out why the verification email did not send when I registered a user when upgrading a project from `5.6`. 
Added the bit that, I found out I was missing.
=> Adding information about the events and listeners for the SendEmailVerificationNotification

broadcasting.md
Added `\Illuminate\Broadcasting\Channel` to the PHPDoc block under the `Broadcasting` > `Concept Overview` > `The ShouldBroadcast Interface` section.
It was a little bit confusing because the return type was array, but a channel was being returned.
=> Fix PHP Doc Block on broadcasting.md

helpers.md
This PR removes the assets directory from the resource path helper example.
=> [5.7] Removed assets directory. Fixes #4520

eloquent-resources.md
The example wouldn't work with a standard `$this->belongsToMany(Role::class)` relationship.
=> [5.7] Use default pivot table name

contributions.md
the current LTS is 5.5, not 5.6.
This PR removes the value, and links to the 'releases' page, so we don't have to keep updating it, and people can look if they'd like.
=> remove incorrect version

upgrade.md
This PR adds 2 additional steps to the Email Verification section of the 5.6 to 5.7 Upgrade Guide. These steps seem mandatory in order to fully implement this feature during the upgrade.
The steps included are:
- Implementing the `MustVerifyEmail` contract
- Adding the `verified` route middleware
Resolves #4447
=> Added missing steps in Upgrade Guide for Email Verification

notifications.md
A member on the community Discord was confused with where to place their webhook URL.
This can be clearer by showing an example of the webhook URL inline, instead of a fake property that implies there's something else.
=> Replace Slack webhook URL fake property with literal string

helpers.md
Default `array_sort_recoursive` realisation use `Illuminate\Support\Arr::sortRecursive` to sort input array.
`Illuminate\Support\Arr::sortRecursive` implement sorting using `ksort` for assoc and `sort` for numeric subarrays:
```php
/**
* Recursively sort an array by keys and values.
*
* @param  array  $array
* @return array
*/
public static function sortRecursive($array)
{
foreach ($array as &$value) {
if (is_array($value)) {
$value = static::sortRecursive($value);
}
}
if (static::isAssoc($array)) {
ksort($array);
} else {
sort($array);
}
return $array;
}
```
But old description of `array_sort_recoursive` contains information only about `sort` usage. I was confused at first time and create my own helper to sort assoc array recursive. Letter I open source code and found `ksort` usage …
=> Add clarifications in description of array_sort_recoursive

validation.md
A user visiting the docs and clicking directly to [the `before` rule](https://laravel.com/docs/5.7/validation#rule-before) wouldn't know that you can also pass another field name as a parameter to `before`, as it's only mentioned in the `after` rule section. This PR fixes that.
=> Clarify possible parameters to the `before` rule

dusk.md
- some lines read 'Assert that the' and others read 'Assert the'.  After some research and discussing with my content team, we landed on 'Assert that the' being more grammatically correct.   More importantly, this makes the docs consistent.
- most lines used 'the given', while a few omitted the word 'the'. I have made those consistent as well.
=> Update Dusk Assertions Grammar

upgrade.md
Several people have been confused about the asset directory being removed and wondering what to do with this change since it's not noted in the upgrade guide at all.
I've added a note explaining the changes to make it clear that it's not required but can be done anyway.
I believe this should be noted both to reduce confusion from users comparing the two versions, and as it may affect packages that could publish assets.
=> Add note about asset directory moving

upgrade.md
Document https://github.com/laravel/framework/pull/25525 breaking change.
=> [5.8] Document facade root service resolving breaking change

database.md, queries.md
Updated to use valid case for `stdClass`. Similar PR was merged in framework https://github.com/laravel/framework/pull/19735
=> [5.7] Use stdClass in valid case

valet.md
When installing a specific version of MySQL you need to start that specific version. Follow up from #4388
=> Follow up from #4388

upgrade.md
There is an issue with folder name in docs where in one line the folder is called scss and in webpack.mix.js it is called sass and also in the laravel project it is called sass.
=> [5.7] Rename the folder scss to sass in upgrade docs

urls.md
action() doesn't support callable array syntax in 5.6. This feature is 5.7+ only.
=> [5.6] No callable array syntax for action() in 5.6

redis.md
This is no longer required and is redundant.
Solves https://github.com/laravel/docs/issues/4214
=> [5.7] Remove old note

upgrade.md
#4553:
> Neither of these appear to require any action by the user during the upgrade process though? So why put them in the upgrade guide?
laravel/framework#25732:
If you are manually unquoting JSON values (`json_decode('"en"')`), this will no longer work.
laravel/framework#25517:
If you are accessing JSON values with ``$user->{'`options`->\'$."language"\''}``, this will no longer work.
---
Can you please not close PRs with a question? I and others find this disrespectful and discouraging. I understand that you don't read closed PRs, just leave the PR open for a day and give the contributor time to respond. Opening a new PR to answer a question is really not a pleasant and efficient way of communicating.
=> [5.8] Add #25517 and #25732 to upgrade guide 

cache.md
Documentation needs to updated because of the removal of indefinate block
as per laravel/framework@045e6f2 (fixes #4446)
=> [5.6] update cache documentation on removal of indefinate block

eloquent.md
It turns out that for newer users the docs on eloquent events aren't entirely clear on how to use them. These two small changes hopefully make them more clear.
See https://github.com/laravel/docs/issues/3915
=> [5.7] Make Eloquent events docs more clear

middleware.md
- Add missing middleware to `$routeMiddleware` list
- Remove confusing `example` wording
See https://github.com/laravel/docs/issues/4437
=> [5.7] Update middleware docs

upgrade.md
As of https://github.com/laravel/framework/commit/5fd4b899cc42d266fab34ee2d5f92fb47ca34fd0 the verification is now optionally.
If this notice in the upgrade guide is now no longer needed maybe consider reverting  6e02201e2c4858ed31d4a5a21fa4d0bb37cb60cd.
=> [5.7] Hash::check verifyAlgorithm is now optionally

container.md
Docs for https://github.com/laravel/framework/pull/25870 in case we choose this path.
=> [5.7] PSR-11 container

valet.md
Current Valet installation instructions mention installing Homebrew and PHP, but make no mention of installing Composer before instructing the user to use composer. Adding a line with a link to Composer.
=> Updating valet install instructions

upgrade.md
This is a question we see a lot at Laracasts. Although it shouldn't affect older application, unless you copy over the configuration files. However this is a mistake that is done a lot.
For more context see #4523
The documentation already describes that you need to look into the configuration files if you want to in the Miscellaneous section. So I can understand if this PR is not merged at all! However this is a mistake we see a lot so maybe we can help someone out here ;)
=> [5.7] Extra mention for renaming QUEUE_DRIVER to QUEUE_CONNECTION

scheduling.md
This will add information about the `environments` method that allows to limit execution of a scheduled task to a specific environment.
=> [5.7] Add information about environments method

dusk.md
The Travis CI example doesn't work in its current form:
- The PHP configuration is missing.
- The tests don't work without an encryption key (assuming `.env.testing` doesn't have a fixed key).
- The value of `APP_URL` is crucial: The default `APP_URL=http://localhost` doesn't work.
=> [5.7] Fix Dusk Travis CI example

cache.md
I've seen multiple people on Stack Overflow who did not know you could call cache functions using the helper. So I added this to the cache documentation.
=> Info about calling functions on cache helper

scout.md
This will make it more clear how developers can manipulate the searching behavior. Think it's good to have this in the docs as most people didn't seem to know this was possible. The example might need some tweaking.
=> [5.7] Document Scout search callbacks

mocking.md
The anchor is removed at 9c52feafbd533269035e207240e78d53e35ae3f2
=> [5.7] Remove ToC entry

billing.md
Add section about Subscription Anchor Date `anchorBillingCycleOn`
In relation to laravel/cashier#439
=> [Cashier] Add section about Subscription Anchor Date `anchorBillingCycleOn`

billing.md
Added this because Stripe's IDs are case-sensitive and their docs explicitely say it that when working with MySQL you should use utf8mb4_bin columns.
See https://github.com/laravel/cashier/issues/534
=> [5.7] Explicitly set collation for stripe_id columns

installation.md
This PR adds the authorization header handler for the alternative **.htaccess** in Web Server Configuration section at Installation page.
I found this rules must present especially for application that using Authorization header for their authentication feature.
=> [5.7] Added missing htaccess authorization header handler

billing.md
This explains how you can use Cashier to create customers in Stripe.
I added a new section "customers" which later can be extended with extra documentation about managing customers with Cashier if needed.
Fixes https://github.com/laravel/cashier/issues/388
=> [5.7] Document creating Cashier customers

upgrade.md
On one of our 5.6 projects, we had custom Migration commands (to run on each of our multi-tenant databases).
Updated the 5.7 upgrade docs to highlight that this has changed, with a link to the PR (https://github.com/laravel/framework/pull/24811)
=> [5.7] Added Migration Commands Output note to upgrade docs.

mocking.md
In 5.5 `AnonymousNotifiable` has been added (laravel/framework#21379). However, the feature never made it into the documentation.
Maybe someone wants to push that change also to the `5.5`, `5.6` and `master` branches.
=> [5.7] Document AnonymousNotifiable Usage in Mocking

responses.md
Symfony no longer requires the true flag for deleteFileAfterSend and defaults to true since 4.1
=> Removing true flag for deleteFileAfterSend

passport.md
Passport provides the route for token requests and by default uses the throttles middleware with its default settings. This was sometimes confusing to people who wondered why their requests were throttled by default.
https://github.com/laravel/passport/issues/506
=> [5.7] Passport: document default token throttling

passport.md
The `--client` flag on the `passport:client` command was undocumented and some people were wondering how to create a client credentials client.
https://github.com/laravel/passport/issues/601
=> [5.7] Passport: document creating client credentials clients

homestead.md
Code formatting was missing for command in Extending Homestead.
=> [5.7] Fix formatting for Extending Homestead command

helpers.md
This small addition to the docs makes note on the somewhat hidden feature of data_get() helper, namely that it, just as data_set(), accepts the * symbol as as wildcard selector. 
If this gets approved, I'll be happy to add this to the 5.5, 5.6 and master docs as well
=> [5.7] Small note on hidden wildcard behaviour of data_get()

passport.md
> This is a resend for https://github.com/laravel/docs/pull/4652 now that we can have back to back notes.
There seems to be a lot of confusion about the JSON API that ships with Passport:
https://github.com/laravel/passport/issues/839
https://github.com/laravel/passport/issues/371
https://github.com/laravel/passport/issues/842
The JSON API is guarded by the web and auth middlewares which means that they can only be consumed by the application they're implemented in. In most situations this works well but when you try to consume the API externally or from a subdomain it becomes cumbersome.
It would be better if the JSON API would behave as an actual api without having to go through all of the web middlewares and just use the auth:api middleware for authentication. There's a feature request …
=> [5.7] Passport: clarify JSON API usage

passport.md
Should explain how a client credentials route can be protected by the client middleware and specific scopes.
It's also not very logic to use the user endpoint in this example because you're not making the request with an active user. It's a machine-to-machine request. Adjusted this as well.
https://github.com/laravel/passport/issues/501
=> [5.7] Passport: client credentials scopes

documentation.md
I know it's already under the "Testing" section, but it is also an official package, and this could be an easier place for people to find the link
=> [5.7] add Dusk link to Official Packages

mail.md
Adds documentation for `attachFromStorage` and `attachFromStorageDisk`.
[Source in framework](https://github.com/laravel/framework/blob/d1be6e43207ed1bacd183f11b87c152dffd08a7c/src/Illuminate/Mail/Mailable.php#L755-L787)
@taylorotwell 👋 https://twitter.com/taylorotwell/status/1055224560705044481
=> [5.7] Add docs for attachFromStorage and attachFromStorageDisk

events.md
*provide* is more appropriate because the subject, *Laravel's events*, is plural.
=> Fix small typo on Events page

database-testing.md
This PR adds the new `email_verified_at` to the User Factory example.
https://github.com/laravel/laravel/blob/f9cf7ff1c834bd918a21930288d12d04e0f15a00/database/factories/UserFactory.php#L18-L22
=> [5.7] Update the User Factory definition

horizon.md
Trimming of jobs wasn't documented yet and some people were unaware of how to extend the jobs persistence time: https://github.com/laravel/horizon/issues/275
=> [5.7] Document Horizon job trimming

queues.md
The docs for Laravel 5.1 state to use the queue driver, however the command from https://github.com/illuminate/queue/blob/d5889a14dfc9890f3ff84dc350c6b6d77d1afa45/Console/WorkCommand.php is expecting a queue connection name as defined in config/queue.
This is confusing and caused our supervisor instance to error out with
```
InvalidArgumentException: No connector for [] in /var/www/sites/platform/releases/1332/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php:150
```
=> update driver to connection, command expects connection

mix.md
Shouldn't this be a reference to `resources` now that `assets` has been removed?
=> Change path

database.md, migrations.md
Documents the change introduced by laravel/framework#26298
=> document sqlite foreign key setting

contributions.md
I know that the bind method doesn't thrown an actual exception, but an example is really helpful, because i didn't knew if the `@throws` directive has a new line before it.
=> [5.7] Add an example of an exception being thrown

broadcasting.md
This config option was undocumented and some people were wondering how you could update Echo to use their own custom endpoint for authentication. See https://github.com/laravel/echo/issues/171
=> [5.7] Document custom Echo auth endpoint

broadcasting.md
It wasn't clear that you can also instead of binding the client to the window, pass it as a config option. In some situations this may be desired. See https://github.com/laravel/echo/issues/29 for more info.
=> [5.7] Document passing the Echo client as an option

dusk.md
CircleCI 1.0 has been deprecated and 2.0 is now the standard and only way to configure CircleCI: https://circleci.com/blog/sunsetting-1-0/
=> [5.7] Remove CircleCI 1.0 example

dusk.md, passport.md
Since pre-Laravel 5.5 releases aren't supported anymore we can safely remove notions about manually registering service providers. This is still documented if people need to refer to it: https://laravel.com/docs/5.7/providers#registering-providers
=> [5.7] Remove notion of manually registering service providers

mail.md
As per [MailgunTransport driver](https://github.com/laravel/framework/blob/b18c2535fcdaa69d83309ac4524a9a6b1a6850f2/src/Illuminate/Mail/TransportManager.php#L116) the `region` should actually be called `endpoint`.
Apologies for the mixup earlier.
=> [5.7] Update Mailgun region config key to endpoint

queries.md
`chunkById()` is not just a shortcut for `orderBy('id')->chunk()`. This clarifies the use-case and potential dangers of `chunk` when changing records inside the chunk.
=> [5.7] Clarify chunkById

notifications.md
https://github.com/laravel/framework/blob/8699a622a31a139d4a6094973f169af7a0806f91/src/Illuminate/Notifications/Events/NotificationSent.php#L52
Response returned from API is also available inside Notification events
=> Response is also available in notification events

notifications.md
There was typo in
https://github.com/laravel/docs/pull/4716
Sorry about that.
=> Fix the typo

validation.md
When you explained 'not_regex' rule , you gave an example no 'regex' rule. Just a simple mistake in typo
=> fix typo in not_regex validation reule

upgrade.md
This adds in notes about a breaking change I discovered with the `artisan` method on `InteractsWithConsole`, which results in test errors when tests are setup to run Artisan commands as part of test setup with `$this->artisan` rather than `Artisan::call`.
Not entirely sure on the phrasing here.
=> [5.7] Add notes about artisan tests breaking change

scout.md
@julienbourdeau , It's about to release Algolia PHP Client V2 which is not supported **yet** by Scout.
=> [5.7] Targets Algolia PHP Client V1

collections.md
This PR adds the new `some` method (alias to contains) as per https://github.com/laravel/framework/pull/26376
=> [5.7] Add some method to collections

eloquent-collections.md
Just realized, I missed adding the some method to the Eloquent collections page besides the collections page per laravel/framework#26376
=> [5.7] Add some method to Eloquent collections

horizon.md
Since Laravel 5.7 already requires at least PHP 7.1.3, the note is redundant.
=> [5.7] Horizon: removed PHP 7.1 requirement note

socialite.md
this **PR** adds gitlab to socialite documentation , since [this PR merged](https://github.com/laravel/socialite/pull/286) on socialite package
=> [5.7] Add gitlab to socialite documentation

billing.md
At the beginning of the Subscription Anchor Date section, there was an erroneous period and an extra word:
>By default. the billing cycle anchor will is the date the subscription was created...
Changed to:
>By default, the billing cycle anchor is the date the subscription was created...
=> Typos in Subscription Anchor Date section

homestead.md
The documentation of the recommended plug-in `vagrant-bindfs` states that it is necessary to make additional settings in the `VagrantFile` file.
This is a problem when updating `Homestead`, because every time you will need to re-add this setting, which you can just forget.
The proposed plugin `vagrant-winnfsd` does not require additional configuration settings. You just need to install it and specify parameter `type: "nfs"`. That's it.
=> [5.7] Replaced recommended plugin for homestead

validation.md
I am studying Laravel and it tooks me a few days to complete the Validation paragraph, because I could not get a custom not implicit validation rule not to run when the corresponding attribute in the request contains the `null` value.
Finally, I realized that this part of the documentation is a bit inaccurate. According to the [`presentOrRuleIsImplicit`][1] function implementation, the rule does not run if the attribute is not present or is an empty string. This function does not treat nulls as empty values.
```php
protected function presentOrRuleIsImplicit($rule, $attribute, $value)
{
if (is_string($value) && trim($value) === '') {
return $this->isImplicit($rule);
}
return $this->validatePresent($attribute, $value) ||
$this->isImplicit($rule);
}
```
I added the following test:
```php …
```
=> [5.7] Fixed errors in the Implicit Extensions description and example

mail.md
fixing typo in mail section. So it's logical to be $pathToImage not a $pathToFile because it's ```<img>``` tag
=> [5.7] Fix typo in mail section

broadcasting.md
I just had to deal with this yesterday. When using the example from the docs and writing it like `.Namespace.Event.Class` it does not ever get triggered, since the `format` method in `Echo` returns the event name as it is after removing the first dot:
```js
format(event: string): string {
if (event.charAt(0) === '.' || event.charAt(0) === '\\') {
return event.substr(1); // here the event with a `.` prefixed gets returned
} else if (this.namespace) {
event = this.namespace + '.' + event;
}
return event.replace(/\./g, '\\');
}
```
=> [5.7] Fixing listening to other Namespaced events example

mix.md
The whole version busting section refers to `app.js` examples - but it switches to a single example of `app.css` mid way, then reverts to `app.js` again. 
This clears it up to make it flow as expected.
=> [5.7] Update mix.md

mix.md
app.js refers to the wrong path
=> [5.7] Fixed js path in Mix.md

horizon.md
A lot of people (including myself) have run into the problem where they'd install Horizon by following the install instructions of it but then forget to install the failed_jobs table so they get exceptions thrown when Laravel attempts to save failed jobs in the database. It's good idea to include these install instructions in the Horizon docs because they're pretty complementary.
Fixes https://github.com/laravel/docs/issues/4782
=> [5.7] Add note about failed_jobs table to Horizon docs

authorization.md
This apparently wasn't documented before.
Fixes https://github.com/laravel/docs/issues/4769
=> [5.7] Document authorizing resource controllers

views.md
This adds a new subdirectory to the view composer example to be complementatry with the view creators below. Adds for a much nicer directory structure than the separate directories with the View prefix.
It also renames the service provider from `ComposerServiceProvider` to `ViewServiceProvider` to prevent confusion with the ambiguous "Composer" naming. Besides that it also doesn't hints that way that the service provider would be for composers only but for creators as well.
=> [5.7] Improve view composer documentation

routing.md
Documents the way https://github.com/laravel/framework/issues/22125 can be solved.
Similar to the docs in Symfony: https://symfony.com/doc/current/routing/slash_in_parameter.html
=> [5.7] Document encoded forward slashes

authorization.md
To reflect changes for https://github.com/laravel/framework/pull/24935
Also improved the wording of the first sentence to make it more clear that the after callbacks will be run after **all other** checks and not after every single check.
=> [5.7] Update Gate Intercept docs

upgrade.md
I've been testing upgrading an app and could not figure out how I was still logged in at first.
=> [5.6] Add remember_token note for upgrading to 5.6.30

dusk.md
Sometimes when installed the binaries will have a different permission set than required. Often this is in combination with a virtual machine. Clarifying that these binaries need to be executable would help.
As reported here: https://github.com/laravel/dusk/issues/81
=> [5.7] Add note about making Dusk binaries executable

eloquent-relationships.md
This is a resend for https://github.com/laravel/docs/pull/4404
We've been getting some more issues about this particularly behavior (#https://github.com/laravel/framework/issues/26635) so it would be good if we could document this.
=> [5.7] Add note about using withCount with select

upgrade.md
Documents https://github.com/laravel/framework/pull/26728, https://github.com/laravel/framework/pull/26726, https://github.com/laravel/framework/pull/26747 and https://github.com/laravel/framework/pull/26717
=> [5.8] Document some 5.8 breaking changes

telescope.md
Resubmit of #4811 after resolving conflicts.
@taylorotwell I've listed all the watchers in this PR because:
1. It's convenient for users to quickly understand what the watchers specifically do / record before having to enable and test them out
2. A lot of watchers have options that are either not listed in the config file or aren't apparent. E.g. the `events` option of ModelWatcher.
3. There are certain watchers that require some setup before properly being able to record data. E.g. the Redis watcher needs events to be enabled (which are disabled by default). Similarly the Dump watcher needs the dump screen to be open.
=> [5.7] Add documentation for Telescope watchers

middleware.md
Fixes incorrect link introduced in https://github.com/laravel/docs/commit/4144497c5bdfc2b537bd8d8bd79ad699998ce0ca (missing hash symbol). Without it, the link points to a 404.
=> [5.7] Fixed incorrect link to sorting middleware

telescope.md
Adds docs for https://github.com/laravel/telescope/pull/474.
=> [5.7] Document Telescope gate watcher

passport.md
Adds docs for https://github.com/laravel/passport/pull/879
=> [5.7] Document default scope in Passport

eloquent-mutators.md
Mentioned that `created_at` and `updated_at` are appended to `$dates` as long as `$model->timestamps == true`.
=> [5.7] Models have disable-able default timestamps

scout.md
Conditional indexing only applies when using the save method on a model, the query builder or relationships directly. This is because the behavior on models and collections directly is meant to "force" them to be applied and ignores the `shouldBeSearchable` method.
See discussion here: https://github.com/laravel/scout/issues/320
Fixes https://github.com/laravel/docs/issues/4813
=> [5.7] Clarify conditional indexing for Scout

eloquent-relationships.md
The word "delete" isn't used anywhere on the page, so if you search the page for the word "delete" to look up how to delete a many-to-many relationship you won't find it.
This PR changes changes the word "remove" to "delete" so you can search for either "delete", "remove", or "detach" to find how to delete a many-to-many relationship.
=> Use the word "delete" to improve searchability

validation.md
The date validation does not accept _any_ value that `strtotime` understands, as it does `date_parse` with `check_date` afterwards. 
There was an issue for this, but was closed, although I could reproduce it.
https://github.com/laravel/docs/issues/2542
`app('validator')->make(['foo' => 'yesterday'], ['foo' => ['date']])->validate()`
edit: Fixed typo
=> Fixed date validation not accepting relative dates

session.md
A colleague of mine that's just starting with Laravel wasn't able to find it in the docs today.
=> Add info about forget() accepting array argument

contributions.md
This isn't enforced anymore at the moment and the updated way is used more than the previous one.
=> [5.7] Remove white line for throws annotation

mail.md
The clarification that 'markdown' directory refers to plain text version of emails is also applicable to 5.5!
After the discussion [here](https://github.com/laravel/framework/issues/23076) it appears 5.6+ docs were updated, but 5.5 weren't.  LTS is still first recourse for me at least at this time.
=> [5.7] Make it clear that /vendor/mail/markdown refers to the plain text version of emails

mail.md
the PHP mail driver is no longer used. It is simply an alias for the sendmail driver.
the 'mail' driver will continue to work (for now), we just shouldn't document it to help avoid confusion.
with the current wording, the program may think the native PHP `mail()` function is still being used, which it is not.
=> [5.7] remove PHP mail driver

blade.md
The docs currently display a tip and then immediately display a new section with the same text. This change displays the {tip} after the first example so that users can learn the information when it's relevant and keeps the text in the next section for users who skip the previous section.
=> Move tip about 'htmlspecialchars' to first example

contributions.md
all compiled files should be generated by maintainers to defensively prevent malicious code from being snuck in.
https://github.com/laravel/laravel/pull/4882
=> [5.7] add note about compiled files

collections.md
This PR adds documentation to the `whereBetween` collection method which was introduced in PR [26888](https://github.com/laravel/framework/pull/26888)
=> [5.7] add whereBetween method

passport.md
The current docs, when used with an L5.7 install lower than 5.7.19 will result in failed Vue component registration. More details and a reason are needed because Laravel-mix 4.0.0 contains a breaking change.
=> Explain breaking change in component registration

migrations.md
There is an implementation for the PostgreSQL column comments in 
Illuminate\Database\Schema\Grammars\PostgresGrammar::compileComment() 
see https://github.com/laravel/framework/blob/5.7/src/Illuminate/Database/Schema/Grammars/PostgresGrammar.php#L380
=> [5.7] PostgreSQL column comments are supported also

errors.md
In `App\Exceptions\Handler.php`, the `report()` method does not return.
https://github.com/laravel/laravel/blob/d1db3cd089d6e9f81a4c8a65d401939f85cbbd5c/app/Exceptions/Handler.php#L29-L38
=> [5.7] Update exception report() snippet to match actual code

socialite.md
By default composer installs the last version of `Socialite`, now, the `Socialite's` last version is `4.0.1` and from `4.0.0` it requires Laravel 5.7 as minimum version, that's why guy which develops with Laravel 5.6 should install Socialite by saying that he wants last version which also requires Laravel 5.6, it's `3.2.0`
=> [5.6] Changed version of the package

deployment.md
Hello @taylorotwell!
You've probably missed my previous PR's (https://github.com/laravel/docs/pull/4847) comments, let me summarize to create a whole picture.
It constructs the `$fastcgi_path_info` variable from the given regex (with exactly 2 capture groups).
Most widely used value is `^(.+\.php)(/.+)$`. ([nginx docs](http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_split_path_info))
The `$fastcgi_path_info` value will be set to the processed path's portion after the `.php` extension.
Example: `https://laravel.com/test.php/foo/bar` => `/foor/bar`.
Now we may have some value assigned to `$fastcgi_path_info`, but we have to pass it to PHP via the `PATH_INFO` variable (the default `/etc/nginx/fastcgi_params` file does not handle it).
The standard way to do that: …
=> [5.7] Remove fastcgi_split_path_info from nginx config

collections.md
The mapSpread parameters takes the first value and then the second value, which is the even number 0, 2, 4, etc and the corresponding odd number 1, 3, 5, etc. This change corrects the parameters to correctly match to eliminate any possible confusion.
=> Update mapSpread Callback Parameters

dusk.md
Updated setup commands for PHP 7.2 and minor build improvements.
Codeship already has ChromeDriver installed out of the box. See [here](https://documentation.codeship.com/basic/continuous-integration/browser-testing/#chromedriver)
MySQL 5.7 tip found from this blog post: [Testing with a MySQL 5.7 Database On Codeship](https://mattstauffer.com/blog/testing-with-a-mysql-5-7-database-on-codeship/)
Be sure to set environment variable `APP_URL` to `http://localhost:8000`.
=> Updated Codeship instructions

mail.md
Fixes: https://github.com/laravel/framework/issues/27023
The documented mailable localization example:
```php
Mail::to($request->user())->send(
(new OrderShipped($order))->locale('es')
);
```
would always be sent using the default locale since `PendingMail@fill()` overrides 'es' with the `PendingMail` default value which is `null`.
`Mail::to($request->user())->locale('es')` should instead be used to set the locale through the mail service.
There may have been confusion since https://github.com/laravel/framework/pull/25752 started allowing this call for a `Notification`:
```php
$user->notify((new OrderConfirmation($order))->locale('en'))
```
since there is no intermediate object to assign a locale to.
=> [5.7] Correct Mail set locale code snippet

passport.md
Link to relevant 'terminology' overview on League's OAuth 2.0 doc pages.
=> [5.7] Link to League OAuth2 terminology

providers.md
See https://github.com/laravel/framework/pull/27067
=> Document new 'DeferrableProvider' interface

releases.md
To clarify that the Lumen and other libraries support policy differs from the framework one. Added this to prevent any confusion.
=> [5.7] Clarify libraries and Lumen support policy

facades.md
To point to the correct class that the `log` binding points to for laravel 5.7 as of this update to the framework: https://github.com/laravel/framework/commit/106ac2a7a1b337afd9edd11367039e3511c85f81
=> [5.7] Updating Log facade docs

collections.md
The `every()` method returns true for empty collections which is not documented but should be, since it goes against what the description would lead most developers to believe. After discussion with a few developers, we decided at least a documentation change should be put in, since changing the behavior may break many apps who rely on this in the wild.
=> [5.7] Update collection every() method documentation

mail.md
In [Preview Mailables In the Browser](https://laravel.com/docs/5.7/mail#previewing-mailables-in-the-browser) the `Route::get('/mailable'` has slash before mailable, but in other places in the documentation, the slash does not exist. 
e.g. https://laravel.com/docs/5.7/routing#named-routes
```
Route::get('user/profile', function () {
//
})->name('profile');
```
=> [5.7] Keep the route naming convention consistent

telescope.md
A recent PR, in the https://github.com/laravel/telescope project, has been made so that users can customise their use and publishing of database migrations for the Telescope package.
Please see https://github.com/laravel/telescope/pull/530
https://github.com/laravel/telescope/issues/525
=> [5.7] Telescope Docs: Add Migration Customisation documentation

homestead.md
PHP 5.6 and 7.0 no longer included in Homestead due to reaching EOL.
=> [5.7] Remove PHP 5.6 and 7.0 from Homestead docs

helpers.md
The function `data_set` was incorrectly saying that the third argument is the overwrite argument; when in fact it is the fourth.
=> [5.7] Corrected description of data_set

queries.md
Noticed that the rightJoin method is missing from the query builder docs. Added it for completions sake.
=> [5.7] Add rightJoin to Query Builder Docs

eloquent-relationships.md
The callout second sentence I came up with is kind of clunky so maybe we don't need the "why?" It's difficult to succinctly describe the groupwise-maximum query problem in a short warning alert.
This pull request covers issues:
* https://github.com/laravel/framework/issues/16217
* https://github.com/laravel/framework/issues/18014
* https://github.com/laravel/framework/issues/4835
* https://github.com/laravel/framework/issues/15585
Since 2014, GitHub issues have frequently been submitted to the framework with a misunderstanding that `limit()` can be used by:
* Eloquent relationships
* Eager load queries
The underlying issue is that developers don't realize these active record queries are not "regular"  queries since they must be built and run once to fetch many Eloquent models. So the …
=> [5.7] "Constraining Eager Loads" callout for unsupported eager load limit()

homestead.md
Just went through updating my Homestead VM and wanted to update the documentation a bit.
**Notable changes:**
- We're telling users to checkout a tagged release upon install, so they need to ensure they checkout a new tagged release after pulling the latest code.
- Once the new box is downloaded, you need to destroy and regenerate the VM to use the latest Vagrant box.
=> [5.7] Fix documentation for updating Homestead VM

queues.md
There was some confusion about why chained jobs were still fired after the original job was deleted but this is the intended behavior: https://github.com/laravel/framework/commit/b880ad19282db768718cfd1629ebbc41054daadc
Fixes https://github.com/laravel/framework/issues/26725
=> [5.7] Add note to job chaining when deleting

deployment.md
Hi! I added Laravel to my deployment workflow.
To keep it simple, I get nginx conf on documentation and... White page with status code 200.
On some distribution, ```include fastcgi_params;``` is not enough, ```SCRIPT_FILENAME``` is not include in ```/etc/nginx/fastcgi_params```, Ubuntu 18.04 in my case. This parameter is required for fcgi to correctly pass filename path to PHP FPM. So, I add it to documentation. We can use ```$document_root``` instead of ```$realpath_root``` but it offers better support for symlinks when modern deployment.
=> [5.7] Fix SCRIPT_FILENAME can be no present on fcgi nginx params

dusk.md
Being new to Laravel Dusk, I found out about interacting with JavaScript Dialogs through third party sites, so wondered if adding a section to the Dusk Docs for acceptDialog() and dismissDialog() would be helpful here.
assertDialogOpened() is already documented in the 'Available Assertions' section, but felt mentioning it in the new section may be beneficial.
Thanks!
=> [5.7] Added section for JavaScript Dialogs

homestead.md
There is no tag called v8.0.0 on the git repo! 😿
https://github.com/laravel/homestead/tree/v8.0.0
https://github.com/laravel/homestead/tree/8.0.0
=> [5.7] Upped to the latest Homestead version (8.0.0 -> v8.0.1) 🙄

collections.md
Keeping in sync with the new signature of the firstWhere method laravel/framework#26261, this pull request adds a new example of how it can be used to find the first element that meets the where clause.
=> Documents the new signature for the firstWhere method

queues.md
Sometimes people tend to believe that jobs only can be used asynchronously, how about to document that they can do more than they think with jobs?
=> [5.7] Documents how to dispatch a job synchronously

pagination.md
This PR adds a table to supply descriptions to the Paginator Instance Methods and also adds two undocumented methods.
- Add Description to each of the paginator instance methods
- ~~Document [`isValidPageNumber()` Method](https://github.com/laravel/framework/blob/b6a325446d222309f6457c28e9cbb14e4465db9a/src/Illuminate/Pagination/AbstractPaginator.php#L117-L126)~~
- Document [`getUrlRange()` Method](https://github.com/laravel/framework/blob/b6a325446d222309f6457c28e9cbb14e4465db9a/src/Illuminate/Pagination/AbstractPaginator.php#L140-L152)
=> [5.7] Paginator Instance Descriptions, Additional Methods

pagination.md
Adds the recently added `getOptions` method (https://github.com/laravel/framework/pull/27273) to the paginator methods.
=> [5.7] Add getOptions Method

testing.md
The existing documentation mentions the importance of calling `parent::setUp()` when defining your own `setUp` method, but it doesn't mention the same for the `tearDown` method.
It should probably be obvious, but I've forgotten it on a few occasions and the symptoms have always been far less obvious than when forgetting to call `parent::setUp()`. I think if it was documented, it might be easier to remember.
=> [master] Add a reminder to call parent::tearDown()

blade.md
2 previous sentences stated the view was in "includes.input"
=> [5.7] Add missing 's' in "includes"

horizon.md
At the moment it seemed as the simple balance strategy is the default strategy even if you leave it away but this isn't the case. Adding these words will make it clear that simple is only the default in the config file itself.
Ref.: https://github.com/laravel/horizon/issues/507
=> [5.7] Clarify Horizon balance default

dusk.md
This PR adds documentation for [waitForDialog()](https://github.com/laravel/dusk/blob/c30c8a01d35661e253a7d3ea7ae6a79faf3f8d92/src/Concerns/WaitsForElements.php#L193-L208) within Dusk JavaScript Dialog assertions.
=> [5.7] Add waitForDialog() to Dusk

valet.md
This PR changes `valet domain tld-name` to `valet tld tld-name`. `valet domain` was renamed as of Laravel Valet v2.1.0. https://github.com/laravel/valet/pull/241
=> [5.7] Valet Domain Renamed to TLD

scout.md
This Pull Request adds a missing `flush` method on writing-the-engine topic.
=> [5.7] Adds missing `flush` method on writing-the-engine topic

upgrade.md
The text says "so likelihood of impact to your application is low.", but the likelihood of impact says "medium"
=> [5.7] Consistent likelihood of impact

contracts.md
For 5.7, replaced Illuminate\Contracts\Redis\Database for Illuminate\Contracts\Redis\Factory
=> [5.7] Wrong Contract name/reference on the new documentation

valet.md
`valet share` now supports secured sites. https://github.com/laravel/valet/pull/630
=> [5.7] Remove note about sharing secure valet sites

upgrade.md
This PR notes an optional upgrade to PHPUnit 8.  https://github.com/laravel/framework/pull/27441
=> [5.8] PHPUnit 8 Optional Upgrade

artisan.md
I believe most people aren't aware of the fact that all commands are instantiated every time any command, job or test is run. It would be best to warn them about it in order to save them the trouble this can cause.
=> Represent injection more accurately for commands.

dusk.md, envoy.md, mail.md, mix.md, passport.md, passwords.md, providers.md, queues.md, valet.md
These changes remove some of the remaining old code block notations and fix a whole bunch of indentations. Some code blocks were unnecessary indented by one level.
=> [5.7] Clean up code blocks and indentations

mail.md
The rename is according to the clarification that this concerns the plain-text messages which corresponds with the directory rename we did earlier. I've also further clarified on *why* the $message variable isn't available for plain-text messages.
=> [5.8] Fix directory name and clarify note further

upgrade.md
* Fixes a mistake from branch merge, where #4972 change got applied to a different section (as the original section no longer exists).
* Minor wording fix following up to [`0ae0791`](https://github.com/laravel/docs/commit/0ae07914f93a594ba723be1f9c1462c5feb133af#diff-e6fbd6eb4a701f2e57b69c2f4696dbaeR302).
=> [5.8] Fixes in 5.8 Upgrade Guide about helpers

contributing.md
I couldn't find any usage for this file. I think it was used to link to from the docs repo but isn't anymore. We also now have a new contributions page.
=> [5.7] Remove unused contributing file

dusk.md, envoy.md
All the other package documentation have this convention so let's keep using the same one everywhere. I believe it should be clear from the docs itself what they're about without having to explicitly mention it in the titles.
Passport title was renamed here: https://github.com/laravel/docs/pull/4995
=> [5.7] Use consistent package titles

upgrade.md
While upgrading an app from 5.3 to 5.4 i noticied that the signature of Model::newPivot() changed by adding a new argument `$using`
This PR adds a note in the upgrade guide
=> [5.4] Add upgrade note for Model::newPivot() signature change

cache.md
The return value of blocking for an atomic lock is always going to be true, so it is not necessary to wrap it in an `if` statement
=> [5.7] Updated atomic lock code example

cache.md
When a `Cache::has` is performed, false is a valid value to have according to the PSR-16 spec. This is also the current behavior in the framework so the docs aren't correct at the moment.
Reported here: https://github.com/laravel/framework/issues/27630
=> [5.7] Cache has does not return false is value is false

upgrade.md
Introduced by https://github.com/laravel/framework/pull/25957
Low impact because should only happen when choosing or changing your password.
=> [5.8] Document default password length change in upgrade guide

billing.md, braintree.md
Since the Stripe and Braintree libraries are drifting apart further and further in terms of functionality and in the future even totally different implementations splitting the docs up is the most sane thing to do instead of trying to make both work side-along.
=> [5.8] Split Stripe and Braintree docs

upgrade.md
This adds a separate title to the void return type notice because currently it falls under the "PHPUnit 8" title and it wasn't clear that this is a general note which applies to all tests.
Also moved it one section up to make it even more explicit.
See: https://github.com/laravel/docs/pull/5024
=> [5.8] Add separate title to void notice

envoy.md
This makes it slightly more clear that you should put the task's name here even if it's explicitly stated in the comment above it.
=> [5.8] Use Envoy task name as example

horizon.md
As the Slack and Nexmo drivers have now been broken out into separate packages, the note in the Horizon docs should prompt developers to look at the notifications docs in order to hook either of these up.
=> [5.8] Link to notifications page for relevant drivers

passwords.md
Ever since it has been implemented in 5.3, the forgot/reset password `broker()` function has been `public`. Trying to override it with a `protected` method will throw an error:
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Foundation/Auth/ResetsPasswords.php
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Foundation/Auth/SendsPasswordResetEmails.php
https://github.com/laravel/framework/blob/5.8/src/Illuminate/Foundation/Auth/ResetsPasswords.php
https://github.com/laravel/framework/blob/5.8/src/Illuminate/Foundation/Auth/SendsPasswordResetEmails.php
=> [5.8] Update password broker to be 'public'

migrations.md
The following commit in the 5.8 branch (https://github.com/laravel/laravel/commit/426df7a0e4d489439002cf99c37246aeebdc5327) changed the default migration type for the 'id' field on the users table migration to bigIncrements.
Trying to create a foreign key relationship to that field using the current 5.8 docs example fails due to the mismatched data type, and should perhaps instead read `$table->unsignedBigInteger('user_id');`
=> Update - user_id field datatype in migration example

collections.md
Resolves https://github.com/laravel/framework/issues/27722.
The docs say that
> toArray also converts all of the collection's nested objects to an array. If you want to get the raw underlying array, use the all method instead.
which isn't exactly right. It converts only `Arrayable` objects to arrays. stdObjects can be converted into arrays too but aren't, because they are not `instanceof Arrayable`.
Feel free to improve the formulation of the note, I couldn't think of a better way to write it.
=> Specify that only Arrayable objects are converted into arrays

passport.md
Changed Class name of `TokenModel` to `Token` to match the other imported Passport Model naming convention.
=> Fix "Overriding Default Models" Section.

eloquent.md
It's not immediately obvious (although it is explained in the text), that the second parameter is an array of attributes. Adding a second attribute makes this clearer and should reduce questions like this: https://stackoverflow.com/questions/42695943/laravel-updateorcreate-method (and many others on SO with the same problem/answer)
=> Make attributes example clearer

scheduling.md
The docs is only calling the artisan option in sample code.
In artisan command docs, it called like ```Artisan::call('email:send', ['user' => 'Taylor', '--force']);``` which is difference with in Scheduling.
=> Cover both arguments and options

valet.md
Adds a brief undocumented section on server environment variables within Valet when using sites/frameworks that don't provide a way to configure server side variables causing mayhem in your server config. Ref: https://github.com/laravel/valet/pull/474, https://github.com/laravel/valet/issues/719
=> [5.8] Valet Site Specific Environment Variables

upgrade.md
I noticed [a thread come up on Laracasts](https://laracasts.com/discuss/channels/laravel/beware-in-env-files) that points out how the upgrade to the phpdotenv library in 5.8 may silently break applications if the environment file has an unquoted hashtag character in it.
This PR notes the breaking change and points to the phpdotenv upgrade guide for other (non-silent) changes that may break an upgrading application.
=> [5.8] Note the silently breaking changes in phpdotenv

helpers.md
There is some wrong paragraph of helper description for function `__` and `route`.
It happened at [Sort helper methods alphabetically](https://github.com/laravel/docs/pull/5042) merge. 
I fix it.
=> [5.8] fix wrong paragraph of helper

upgrade.md
Since the newly updated vlucas/phpdotenv library has some pretty significant changes it might be wanted to mark this as a high impact change.
See https://github.com/laravel/framework/issues/27850 & https://laracasts.com/discuss/channels/laravel/beware-in-env-files
=> [5.8] Mark environment changes as high impact change

helpers.md
Every code block has the use statement expect in Str::endsWith.
=> [5.7] Add missing use in Str::endsWith

helpers.md
Every code block has the use statement expect in Str::endsWith.
=> [5.8] Add missing use in Str::endsWith

upgrade.md
Mentioned in laravel/framework#27884
=> [5.8] Add `getOwnerKey` method in upgrade guide

upgrade.md
I guess RFC5630 was copied from the original PR https://github.com/laravel/framework/pull/26503
This corrects it to RFC6530 as per the link it goes to.
=> Display correct RFC number

blade.md
If I tried using double quotes instead of single quotes around `attr='@json'`, I'm sure somebody else will.
=> Clarify @json usage in element attributes

authorization.md
Incorrect indexing for resource controllers documentation. By removing one # tag the link redirects to correct location.
=> remove one hash tag to fix broken link

upgrade.md
This PR adds a new possible BC for the v5.8 upgrade guide.
Moving the (undocumented) `add()` method to the base collection class in laravel/framework#27082 may cause a BC, eg. artkonekt/menu#3, vanilophp/framework#39
=> Added v5.8 upgrade note about moving the `add` method to base Collection

eloquent-relationships.md
Respecting advice[/rule] to set intermediate table name in alphabetical order first_table_singular->underscore->last_table_singular, in same fashion here is proposed name for pivot model of that table.
=> [5.8] Intermediate model name change.

cache.md, upgrade.md
The get() method on a lock always returns a boolean result, not the instance of the lock. Thus the two examples given don't work unless the variable $lock is actually assigned to just the Cache::lock(...) part, achieved by wrapping that part in brackets.
=> [5.8] Add brackets to example since get() method on lock always returns boolean

upgrade.md
The change the `bigIncrements` in the default migration stub may have not affected any existing code in a project, but it is a good change to note when upgrading an application and continuing to work on it.
In particular, [Povilas pointed out that foreign key references need to be of the same type](https://laraveldaily.com/be-careful-laravel-5-8-added-bigincrements-as-defaults/). This may be clear in hindsight but is a small enough change that people are likely to miss and need to be aware of for any future code they write in the project.
=> [5.8] Note the change to bigIncrements in the default migration stub

contributions.md
I'm working on issue templates for the libraries and removing these two words make the docs agnostic and also applicable to the libraries.
=> [5.8] Make which branch docs agnostic

upgrade.md
The initial PR was reverted in favour of this one:
https://github.com/laravel/framework/pull/26472
=> [5.8] Link to the right PR

mocking.md
Documents the behavior added in https://github.com/laravel/framework/pull/26975\
Rewrote the example a bit to demonstrate multiple file assertions.
=> [5.8] Document multiple file assertions when mocking

validation.md
It sounds like the value should exists only once in the database. Added a tiny phrase in the description to clearly show that `unique` is just like an hypothetical `doesnt_exists`.
=> [5.8] Added more clear description to the unique rule

releases.md
In the release notes section, Intermediate Table/Pivot Model Events, the wording was the source of some confusion. An [issue](https://github.com/laravel/framework/issues/28050) was posted on the laravel/framework repo which stated that the user expected there to be new 'syncing', 'detaching', and 'attaching' events available in Laravel 5.8.
> In previous versions of Laravel, **Eloquent model events were not dispatched when attaching, detaching, or syncing custom intermediate table / "pivot" models** of a many-to-many relationship. **When using custom intermediate table models in Laravel 5.8, these events will now be dispatched.**
- A documentation link was added to the reference to "Eloquent model events", to clarify which events will be dispatched.
- The phrase "these events will now be …
=> Clarify release note pivot events

broadcasting.md
Changed as people may copy and paste the example with an incorrect docblock.
=> Updating example docblock return type

homestead.md, valet.md
This PR should improve readability, especially for low-res monitor.
Before on left side, and after on the right side.
=> Make long list to columns (improve readability)

notifications.md
The notifications md still documented the Slack and Nexmo channels as being available 'out of the box'.
=> [5.8] Updating notifications.md to reflect the extraction of Nexmo and Slack channels.

queries.md
There are 'or' versions of most 'where' functions (e.g. `orWhereNull`). Added these to the Query Builder page for the benefit of new developers who might otherwise not be aware of them. The current wording of the page makes it sound like there is only an `orWhere` function
=> Queries: note 'or' versions of various `where` functions

socialite.md
=> [5.4] Change community Socialite drivers website URL

socialite.md
=> [5.6] Change community Socialite drivers website URL

socialite.md
=> [5.7] Change community Socialite drivers website URL

socialite.md
=> [5.5] Change community Socialite drivers website URL

socialite.md
=> [5.8] Change community Socialite drivers website URL

events.md
To allow event auto discovery on subscribers you have to start the handlers with `handle*`. So this PR is to keep all event method names consistent.
=> [5.8] Start method names for event subscribers with handle

responses.md
updated correct reference for registered `cache.headers` MiddleWare
per https://github.com/laravel/laravel/blob/3001f3c6e232ba7ce2ecdbdfe6e43b4c64ee05ad/app/Http/Kernel.php#L57
swap options delimiter to `;` vs `,` 
per explode method https://github.com/laravel/framework/blob/5.8/src/Illuminate/Http/Middleware/SetCacheHeaders.php#L49
swap `max-age` to `max_age` option 
per https://github.com/symfony/http-foundation/blob/v4.2.5/Response.php#L932
=> [5.8] fix cache.headers middleware reference and params

queries.md
The `find()` method was absent from the Query Builder documentation page, so I've added it under the 'Retrieving a single row/column from a table' heading
=> [5.8] Added `find()` method to Query Builder docs

homestead.md
For details, see https://github.com/laravel/homestead/issues/1071. A new version hasn't been built or tagged yet but should be soon.
I'm a little unsure of how to document the new mDNS support. For our teams, _everything_ is set up on a per-site basis, so defaulting to mDNS is the simplest setup. It's especially useful if you're using DHCP for VM IPs instead of static addresses. But, we're not typically using Laravel in our projects either, so I'm not sure what the broader community defaults are.
/cc @svpernova09
=> [5.8] Document new features in Homestead

collections.md
This PR introduces documentation for the duplicates method which was added in 
https://github.com/laravel/framework/pull/28181 by @timacdonald
=> [5.8] Document new collections duplicate method

homestead.md
Answered a question in the Laravel Slack and noticed these versions were 2 minor releases behind.
=> Updating the version of Homestead in homestead.md from v8.0.1 to v8.2.0

blade.md
This pull request adds a note that `@yield` supports default values.
I do not think this is currently documented even though mentioned in #419.
=> Add note for @yield default value.

eloquent-relationships.md
Added explanation how to eager load "has many" relationships. Including just "id" as the current document claims does not work with "has many" relationships leaving users scratching their heads. I didn't not test eager loading other types of relationships but I assume the same would be true there as well.
=> [5.8] Added explanation how to eager load "has many" relationships. 

homestead.md
Since this note refers specifically to something used on Windows, it should point that out to avoid confusion.
=> Change Homestead NFS note to refer to Windows specifically

blade.md
Fix typo in Validation Errors code example.
* Missing `"` (double quote)
=> Fix typo in code example

validation.md
Added a missing quotation mark in the code example.
=> Fixed typo in code example for @error directive

valet.md
Adds brief documentation to the new `valet log` feature added in [Valet 2.3.0](https://github.com/laravel/valet/releases/tag/v2.3.0).
https://github.com/laravel/valet/pull/757
=> [5.8] Add Valet Log

billing.md
Remove an extra space from the billing documentation in the API Keys section.
=> Remove extra space from billing documentation

migrations.md
Update - id field datatype in migration examples to use the bigIncrements default method
=> [5.8] Update - id field datatype in migration examples

telescope.md
The `Laravel\Telescope\TelescopeServiceProvider` is already registered with auto package discovery. The provider that is added in `config/app.php` when you run `php artisan telescope:install` is the `App\Providers\TelescopeServiceProvider`. So this is the one that should be registered manually in this code sample.
=> [5.8] Telescope use proper provider in local environment only code sample

telescope.md
The `Laravel\Telescope\TelescopeServiceProvider` is already registered with auto package discovery. The provider that is added in `config/app.php` when you run `php artisan telescope:install` is the `App\Providers\TelescopeServiceProvider`. So this is the one that should be registered manually in this code sample.
=> [5.7] Telescope use proper provider in local environment only code sample

eloquent.md
I've been debugging my app for an hour trying to figure out why my observer isn't working, the problem was that I placed the `User::observe(UserObserver::class);` in the `register` method  instead of the `boot` method, in the docs the `register` method in placed below the `boot` method which causes confusion because it doesn't follow the Laravel generated order.
=> [5.8] docs(eloquent observers): method order

blade.md, cache.md, database.md, eloquent-resources.md, eloquent-serialization.md, eloquent.md, filesystem.md, packages.md, providers.md, queues.md, session.md, validation.md, views.md
The order of the `register` and `boot` method was changed in https://github.com/laravel/laravel/pull/4921. The docs weren't updated, which caused this problem: https://github.com/laravel/docs/pull/5158.
This PR updates the order of the `register` and `boot` methods for all code examples in the docs. It also updates the docblock text to match the text [currently used by the framework.](https://github.com/laravel/laravel/blob/3995828c13ddca61dec45b8f9511a669cc90a15c/app/Providers/AppServiceProvider.php#L10)
=> [5.8] Update service provider code examples

eloquent-collections.md
I believe that the Eloquent collection methods are extremely useful, but are not documented. I have 
documented each method in the Eloquent Collection class. I hope this proves useful to someone and is up to the standard of the Laravel framework.
Is there a way to generate the documentation to test links / style? 
If there are any improvements needed or style issues, please let me know, I am happy to help.
Thanks
=> [5.8] Add Eloquent Collection documentation

eloquent-collections.md
The `except` example was using `only` instead of `except`.
=> Wrong method name for the except example on Eloquent collection.

upgrade.md
There were several places where forward slashes were used on references to classes and interfaces on the update doc. This PR corrects those to back slashes.
=> Added correct slashes for classes references

passport.md
I discovered the `validateForPassportPasswordGrant` method when I was looking in the Passport source code. The related method `findForPassport` is already documented, so I added a section under the documentation of that method.
=> [Passport] Add 'Customize The Password Validation' section under 'Password Grant Tokens'

eloquent.md
PR adds examples of `$primaryKey`, `$incrementing`, and `$keyType` to keep things uniform with the rest of the page examples.
=> [5.8] Add examples of Eloquent Primary Key configuration

eloquent-relationships.md
Inform users that soft deletes cannot be used with pivot models. See https://github.com/laravel/framework/issues/28407
=> [5.8] Add note on soft deleting for pivot models

passport.md
This was added in https://github.com/laravel/passport/pull/683
Documenting this because people didn't know this was already added: https://github.com/laravel/passport/issues/997
=> [5.8] Document loading keys from env file

billing.md
Use `bigIncrements` `unsignedBigInteger` by default in [Database Migrations](https://laravel.com/docs/5.8/billing#configuration), because since Laravel 5.8 is used.
=> [5.8] Use bigIncrements by default in Billing

blade.md, validation.md
The `for="title"` in labels missing the `id="title"` in inputs.
=> [5.8] Id for labels added in @error directive

routing.md
Now it is more clear that the second example requires a path too.
=> [5.8] Making the 2 route examples similar for clarity

events.md
At this point in the documentation, a clarifying example comes in useful and makes the essence of event-discovery clear.
=> [5.8] Explain event discovery by example

database.md
PR adds note about the `url` option within the connection configuration.
https://github.com/laravel/framework/pull/28308
=> [5.8] Database Connection URLs

scout.md
Observed the following error when searching withTrashed() as documented. Switched the order around and it now functions as desired.
> Call to undefined method Illuminate\Database\Eloquent\Builder::search()
Laravel v5.8.14
Scout v7.1.1
=> [5.8] Incorrect withTrashed/onlyTrashed chaining order

billing.md, braintree.md
Stripe and Braintree Documentation reflects the Blueprint in the migrations examples thus the examples are consistent with the default users migration that is created with a new Laravel 5.8 installation and when a new migration is created using the **php artisan make:migration** command
=> [5.8] Stripe and Braintree Documentation

database.md
Hi, 
This PR just add another database connection to Read & Write Connections to avoid confusion like:
```
'read' => [
'host' => ['192.168.1.1'],
'host' => ['192.168.1.2'],
]
```
or
````
'read' => [
'host' => ['192.168.1.1', '192.168.1.2'],
],
````
Thanks
=> Add another database connection to avoid confusion

eloquent-relationships.md
Resolves https://github.com/laravel/framework/issues/28486 by adding a note to Eloquent Relationships docs.
I hope the wording is good.
=> [5.8] Add a note about orWheres canceling relationships' main constraints

installation.md
For easier inspection when run `php -m` command
=> [5.8] Sort required php extensions by alphabetical order

telescope.md
Because I couldn't find docs on how to edit add custom tags I reached out and got my answer from @themsaid.
I hope we can document this example for future references.
=> [5.8] Added example for custom tags in the docs

eloquent-serialization.md
`attributesToArray()` is a public method and is useful to avoid a potential infinite recursion if a model's relationships are not needed.  see https://stackoverflow.com/a/56400803/4468423
=> [5.8] attributesToArray documentation

telescope.md
Fix the typo in function name . tags  -> tag.
=> [5.8] Typo in Telescope Tag function name.

upgrade.md
The email verification feature in 5.7 also requires the 'signed' URL middleware to work. 
This updates the upgrade documentation to make that requirement clear.
=> [5.7] Mention requirement of 'signed' middleware for the Email Verification middleware

providers.md
Because it's not clear at first glance in you should add the same named class in the properties, meaning, that using no key in the array would register the Class as a number (given by the array).
=> [5.8] Added  a line for a simple binding example

.idea/vcs.xml, validation.md
Added in full path for validator import. The way it is now, if I use that code I get an error saying Validator class not found. It does say above that the Validator is a facade but you have to click there and realize that you need to add the Illuminate\Support\Facades\ in front of it to get it working. Idk if thats on purpose but I feel like it would be simpler if we had the right path.
=> Added in full path for validator 

passport.md
Replace undefined variable `$user` with `$this` (which is intended by purpose) in body of method `validateForPassportPasswordGrant`.
=> Fix undefined variable in validateForPassportPasswordGrant

passport.md
This PR adds documentation for the new functionality added in Passport v7.3.0 (https://github.com/laravel/passport/pull/1022).
=> Document Passport's Client::skipsAuthorization method

billing.md
=> Grammar mistake in billing.md

http-tests.md
Updates documentation on `assertJsonValidationErrors` to reflect that it can handle more than validation keys with the recent message value assertion addition.
laravel/framework/pull/28787
=> [5.8] assertJsonValidationErrors Message Value

scheduling.md
Although one can apply `->runInBackground()` always, it's only used for commands and exec but not for other types of scheduling (.e.g `->call()`).
=> [5.8] Clarify that running in the backgound does not work for all cases

validation.md
Which is required if you want your rule object validation also to run on empty attributes.
=> Add docs that there exists a `ImplicitRule` interface

broadcasting.md
=> Rename "Pusher" to "Pusher Channels" or "Channels"

broadcasting.md
=> Rename deprecated Pusher Channels `encrypted` to `forceTLS`

scheduling.md
In https://github.com/laravel/framework/commit/aa9fdd411f7a9cb168e09c0a968586354972bf99 the method emailOnFailre was refactored to emailOutputOnFailure.
The documenation isn't updated so people can have issues because of an unknown method.
=> Fix documentation after refactoring emailOnFailure

broadcasting.md
=> [5.7] Rename "Pusher" to "Pusher Channels" or "Channels"

broadcasting.md
=> [5.6] Rename "Pusher" to "Pusher Channels" or "Channels"

broadcasting.md
=> [5.5] Rename "Pusher" to "Pusher Channels" or "Channels"

broadcasting.md
=> [5.4] Rename "Pusher" to "Pusher Channels" or "Channels"

broadcasting.md
=> [5.3] Rename "Pusher" to "Pusher Channels" or "Channels"

broadcasting.md
=> [5.7] Rename deprecated Pusher Channels `encrypted` to `forceTLS`

broadcasting.md
=> [5.6] Rename deprecated Pusher Channels `encrypted` to `forceTLS`

broadcasting.md
=> [5.5] Rename deprecated Pusher Channels `encrypted` to `forceTLS`

broadcasting.md
=> [5.4] Rename deprecated Pusher Channels `encrypted` to `forceTLS`

broadcasting.md
=> [5.3] Rename deprecated Pusher Channels `encrypted` to `forceTLS

helpers.md
https://github.com/laravel/framework/pull/28507
=> [5.8] added `Tappable` trait documentation

eloquent-collections.md
Add parentheses to modelKeys for consistency with other zero argument methods found in documentation such as collection.md
Also assists with rendering (currently renders differently to the other methods listed)
=> Add parentheses to modelKeys

passport.md
I replaced every `\n` by `\\n` in the `load passport encryption keys in env file` example, as  phpdotenv V3 requires slashes to be escapes (https://github.com/vlucas/phpdotenv/blob/master/UPGRADING.md). If you copy and use the current example without escaped slashes, then a `fails with invalid escape sequence exception` error is thrown when the env file is read.
=> [Passport] 'load encryption keys in env file' example should escape slashes

authorization.md
Added a note that class should be given as an argument to authorize function if no Model is given. I ended up debugging this issue for hours only to discover that when arguments are null, the resolvePolicy() will end up resolving to UserPolicy, as the User model is inserted into the arguments.
=> [5.8] Added a note to pass class name as an argument to authorize function

broadcasting.md
A new major version has been released: https://github.com/pusher/pusher-http-php/pull/222.
=> [5.8] Update the major version of pusher-php-server

pagination.md
Currently there is no information about this in the documentation and also navigating the code of `Paginator` it uses `$this->items`, so I thought it would be helpful to add this method in the docs to let users know how to retrieve the paginated data.
=> [5.8] Add `items()` method for pagination

authorization.md
This was a breaking change for 5.8. It was merged back on 5.9
https://github.com/laravel/framework/pull/28957
=> [5.8] Update resourceAbilityMap

notifications.md
To define what data will be used for notification broadcasting, user can implement `toBroadcast` method inside notification, but instead of `toBroadcast`, user feel free to implement `toArray` method, according to code below:
```
File location - Illuminate\Notifications\Channels\BroadcastChannel.php
protected function getData($notifiable, Notification $notification)
{
if (method_exists($notification, 'toBroadcast')) {
return $notification->toBroadcast($notifiable);
}
if (method_exists($notification, 'toArray')) {
return $notification->toArray($notifiable);
}
throw new RuntimeException(
'Notification is missing toArray method.'
);
}
```
I'm not sure that we need tests here, this part very obviously to understand.
=> [5.8] Update notification broadcast

events.md
I came across [conditionally pushing event listeners to queue](https://divinglaravel.com/conditionally-pushing-event-listeners-to-queue) by @themsaid.
I think this is a pretty cool hidden feature and deserved to be in the official docs.
I simplify the example a bit.
=> [5.8] Add documentation for the shouldQueue function.

billing.md
It wasn't always clear at the moment that Stripe plan trials days are ignored when working with Cashier: https://github.com/laravel/cashier/issues/691
=> [5.8] Add note about Cashier trial overwrite

collections.md
I want to add one more example for duplicates() and list duplicatesStrict(), as it is not yet listed.
=> [5.8] Add one more example for duplicates() and list duplicatesStrict()

middleware.md
As opposed to https://github.com/laravel/docs/commit/984d7851832261261f3fa05badc416ed988a27cf
The previous version is actually true when i tested using nginx 1.16.0 and php 7.1.29 with fastcgi enabled in a Vagrant environment, not php artisan serve.
I put a 5 seconds sleep inside the terminate and added a log.
Made a request to the server via AJAX, got a JSON response from the server, after 5 seconds, my log was logged in the laravel log file.
=> [5.8] Correct middleware terminate method description.

homestead.md
with the new version of Homestead and Settler, there are a lot of changes.  I'm going to try and keep these PRs smaller when possible, so they are a little easier to review.
this one adds notes about the re-added PHP5.6 and 7.0 versions.
=> [5.8] update PHP versions available on Homestead

homestead.md
I will need to add some docs about the new way to enable "features" in Homestead, but we'll get this updated for now.
based off this list: https://github.com/laravel/homestead/tree/master/scripts/features
=> [5.8] update optional software

homestead.md
optional software installation scripts now live in a `features` directory, and are installed using the `features` config option in the Homestead file.
This adds documentation on how to use this new method.
Taylor, please hold off merging until @svpernova09 reviews.  I'm not exactly positive where we ended up on the syntax for the feature flags, because we went back and forth for awhile, so just want to make sure I got this right.
=> [5.8] add docs about new Homestead 'features' installation

eloquent-relationships.md
A common issue I see when implementing a "morph map" is that Laravel stops querying for the fully qualified name `App\Post` and only uses the morph map name `posts`. This has been the cause of some frustration as it makes various data in the database seem to "disappear" when querying for it.
I documented the requirement to swap the database's `{morphable}_type` columns with the "morph map" name instead of the fully qualified name when implementing a "morph map" on an existing application.
=> [5.8] Note to update morphable_type columns when using Morph Map

eloquent-relationships.md
Some of the examples of a `MorphTo` relation have a comment that would lead you to believe the relation resolves to a collection, where it resolves to a model instance.
=> [5.8] Updated example PHPDoc block for MorphTo relations to avoid confusion

eloquent-relationships.md
Noticed that the docs used type hints some places, but not others, so I tried hinting the Eloquent Builder and MorphTo classes consistently throughout the file.
=> Consistent type hinting in Eloquent relationships docs

homestead.md
now that we are recommending directly mapping every project directory in the guest for performance reasons, there's really no need for a `code` directory anymore.  It's already removed from some of the examples, so making everything consistent with this change.
=> [5.8] consistent directory structure

billing.md, contributions.md
Remove Braintree references since it's abandoned.
=> [5.8] Remove Braintree references

eloquent-relationships.md
I clarified the behavior of `doesntHaveMorph`/`whereDoesntHaveMorph` as it can be unexpected (https://github.com/laravel/framework/issues/29138).
There aren't that many use cases for `doesntHaveMorph()`, so I added an example for `whereDoesntHaveMorph()`.
=> [5.8] Improve whereHasMorph() examples

validation.md
specify that integer validation does not behave as expected and will not check type
=> [5.8] Update validation docs to reduce confusion on weakly checked integer validation

homestead.md
By default, the CLI version of PHP is 7.3 (currently).
Some users may only or mostly use a lower version of PHP, so rather than writing `php7.1 artisan` all the time, they can run `php71` and then only type `php artisan` to use version 7.1
=> [5.8] document aliases to update the default CLI version of PHP

horizon.md
In Laravel 5.8 queue driver became queue connection, however the docs still mention to change queue driver and not connection.
=> Update horizon.md for the right installation

mail.md
It is possible to assign a theme to a Mailable by overwriting its protected `theme` property, but this was not documented.
=> [5.8] Reword help for customising CSS for Mailables

notifications.md
This PR is to update the docs following the release of the feature to be able to choose which theme to use for a single Mail Notification (commit #29132 on laravel/framework)
=> [5.8] Document new feature to set theme for mail notifications

homestead.md
Removed the statement:
> For even more convenience, Laravel's .env file configures the framework to use this database out of the box.
As was changed in https://github.com/laravel/laravel/commit/6f3d68f67f3dab0e0d853719696ede8dfd9cc4e1
=> Updated docs to reflect .env defaults change

eloquent-relationships.md
#5294 added incorrect type hints for eager loading queries. Unlike with `whereHas()` or `withCount()`, `with()` and `load()` closures receive relationship instances (e.g. `HasMany`).
I think it's better not the type hint these examples. Especially for a new user, it would confusing if the code from the documentation doesn't work because they are using a different relationship type. 
I would keep the type hint for the [`MorphTo` example](https://github.com/laravel/docs/pull/5294/files#diff-8ee0e91f55a653895f3d8dc328c2cfc4R1103).
Reported in https://github.com/laravel/framework/issues/29352.
=> [5.8] Fix eager loading type hints

passport.md
I found trying to use envs for the public and private keys in the Laravel Passport package only worked once the config has been published. Before that I would get complaints from the framework that the keys could not be found.
Multiline ENVs are also supported by the dotenv library used by Laravel so I think it would be better to advertise that option rather than having to put it all on one line and inserting the new line characters.
=> [5.8] Adds vendor:publish --tag=passport-config

upgrade.md
Before:
rename the `/resources/views/vendor/mail/markdown` directory to `text`.
After:
rename the `/resources/views/vendor/mail/markdown` directory to `/resources/views/vendor/mail/text`.
=> [5.8] Add full path for better understanding

queues.md
Jobs are now only tried once by default, previously they were retried indefinitely: https://github.com/laravel/framework/pull/29385
However, it might make more sense to rewrite this paragraph of the docs, considering that jobs can now fail with default queue worker settings (before they wouldn't fail, and just end up in an infinite loop).
=> [6.0] Update default job tries

eloquent-relationships.md
I needed the data from the parent model when creating a default model, but `$this` gives the wrong context inside the closure.
After some time I realized the callback provides the parent model as the second argument.
Perhaps documentation of the second argument is useful for other developers.
This PR should be seen as an proposal and not the actual feature documentation, as I'm not sure how the documentation should be structured.
=> [5.8] Include parent model in withDefault method example

installation.md
This is on my Ubuntu 19.04:
```
~  ls ~/.composer 
cache  composer.json  composer.lock  keys.dev.pub  keys.tags.pub  vendor
~  ls ~/.config/composer 
keys.dev.pub  keys.tags.pub
```
=> [5.8] Update composer vendor/bin location for Linux

homestead.md
At the beginning of the current upgrade instructions we ask the user to ensure they have removed their current virtual machine with an inline mention of `vagrant destroy`, but without mentioning it should be run in the Homestead directory.
As the final instruction we ask them again to destroy their vagrant box, this time mentioning that the command should be run the Homestead directory, and with the `vagrant destroy` command included in a code block. If they've already destroyed it as instructed at the beginning, this second attempt will result in an error.
This change simplifies the instructions by:
1. Instructing the user to be in the Homestead directory from the beginning.
2. Placeing the first `vagrant destroy` instruction in a code block for consistency with the remaining commands. …
=> [5.8] Remove duplicate vagrant destroy instructions

horizon.md
Docs [PR requested](https://github.com/laravel/horizon/issues/563#issuecomment-501694826) by @driesvints 
Explanation provided by @mfn:
> I had the same problem (Laravel 5.8, Horizon 3.2.2)
> 
> My issue was this default code in the published `HorizonServiceProvider`:
> 
> ```
>         Gate::define('viewHorizon', function ($user) {
>             return true;
>         });
> ```
> 
> In my case I've no auth middleware because it's done on the webserver already via IP-addresses matching VPN, etc.
> 
> So, no authenticated user present.
> 
> However: when defining the closure like this `function ($user) {… }` and there is _no_ authenticated user, this gate is entirely skipped because of this code https://github.com/laravel/framework/blob/9b7520a2ac0009d4c1ff2322e3ef673ef702e7e2/src/Illuminat …
=> [5.8] Horizon auth example - clarify that Gate can accept optional user

upgrade.md
As the declaration of the primary key type will be required if the type is not an integer, I hereby document that.
Wrong declaration of the key type may from now break applications.
See [Pull 28153](https://github.com/laravel/framework/pull/28153) for further details.
=> [6.0] Document primary key type requirement

passport.md
Laravel\Passport\Client doesn't have a first_party attribute but a firstParty() method
=> Fix passport Client::skipsAuthorization() method example

helpers.md
somehow this gem wasn't documented.
=> [5.8] document `Str::words()` method

filesystem.md
Sorry that I am bringing this up but I think the wording is a bit misleading. "Default Permissions" seem to imply that these values can be overriden on case-by-case basis, but AFAIK as soon as a Storage disk is created, the permissions are locked.
I'm not a native speaker so I might be wrong on all of this...
=> Rename 'default permissions' to 'permissions'

filesystem.md
When passing pathnames with invalid characters they'll be stripped by the `Util::normalizePath` method and the file might end up on a different pathname. This won't be returned because the `put` method of the Flysystem Filesystem class only returns booleans. 
See https://github.com/laravel/framework/issues/29538
=> [5.8] Add note about cleaning up pathnames

billing.md, queues.md
This updates Cashier's docs for the upcoming v10 release.
I've moved the customer and payment method docs before the subscription docs because they're now a little more important to be know up-front.
WIP until finished and the new release has been tagged.
=> [5.8] Update Cashier docs for v10

billing.md
Webhooks are no longer under config there is a dedicated section for them: https://laravel.com/docs/5.8/billing#handling-stripe-webhooks
=> remove dead link to webhooks

passport.md
The line length of the code sample added in #5363 is a little too long and gets cut off in the docs.
=> Adjust the Passport example to not require scrolling

mix.md
Although this might not be effecting everyone, some environments simply don't offer support to `eval-source-map`. As stated here: https://github.com/JeffreyWay/laravel-mix/issues/1793
I believe that many people would benefit from knowing that there are more styles out there and that they can easily indicate the one they want.
=> [5.8] Updating source mapping documentation

validation.md
Documents https://github.com/laravel/framework/pull/29589
=> [5.8] Document new email validation types

queues.md
When I was reading the docs it wasn't clear to me in which order the chain of jobs would be run and if the this would run before or after the primary job. Hopefully, this little tweak will help others understand it better.
=> [5.8] Specify job chaining order

billing.md
It is important for Cashier Model to use Notifiable trait for the CSA notification to be sent
=> [5.8] Make sure Cashier Model uses Notifiable trait

homestead.md
Xdebug ships enabled on FPM SAPIs and disabled on CLI.
=> Homestead: Remove incorrect instructions for xDebug

homestead.md
MinIO is not included in the base box of Homestead, it's an optional feature.
=> Update Homestead included software

homestead.md
Alpha/Beta versions of the base box on Vagrant Cloud will cause confusion if these versions are the newest option and someone tries to run `vagrant box add laravel/homestead`
=> Homestead: Note about alpha/beta boxes causing issues

database-testing.md
I think it's worth mentioning as in [seeding](https://github.com/laravel/docs/blob/5.8/seeding.md#L23).
I had a problem with this and had to read the source code to find out what was causing it.
=> [5.8] Mentioning mass assignment protection is disabled when using a factory

cache.md, redis.md
In order to follow https://github.com/laravel/framework/pull/29688 and https://github.com/laravel/laravel/pull/5085 I changed the default configs about redis and predis to encorage the usage of `phpredis` instead of `predis`.
I created a *deprecation note* at `redis.md` but I don't know in sure how this handled. If this is not at right way please let me know so I can fix the issues.
=> [6.0] Setting phpredis as default client

authorization.md
Ref: https://github.com/laravel/ideas/issues/1761
=> [6.0] Explain that the Gate helper methods also accept $arguments as an array

database-testing.md
I found this super helpful in heaps of scenarios when I have to seed the status/type tables prior to running a test case. Some examples include order_statuses, item_statuses, product_types, book_genres... So maybe we should mention this in the docs.
=> [5.8] Add seeding test data for test cases

contributions.md
The new repo link is 
https://github.com/laravel/laravel.com-next
=> Update repo link

billing.md
Instead of setting this through the migration it's best that we add a note in the docs. This because collation can't be set universal for every DB type.
See https://github.com/laravel/cashier/issues/747
=> [5.8] Add note about collation in Cashier

collections.md
I needed a `whereNotNull` equivalent and had to source dive to find this.
Feel free to change the description or example.
=> [5.8] Document the `->where()` comparison operator

blade.md
Documentation for the changes made in laravel/framework#29750
Adding example of usage and a quick description of the new parameter, referencing the validation page's named error bags section.
I didn't feel it was necessary to clutter the example with actual multiple forms/inputs, so I left it to just one.
=> [6.0] Documenting new error bag @error directive parameter

upgrade.md
Method results were being assigned to a singular named variable, when it should be the plural version.
=> Typo in code example

releases.md
We don't need `latest()` in these examples, since we're already sorting by the `arrived_at` date.
=> Removed extra "order by" from subqueries example

filesystem.md
The second example of the temporaryUrl is not working because there is an extra ',' at the end of the last argument.
=> [5.8] Fix example. Remove last ',' in temporaryUrl

authorization.md
(an integer is passed and expected, so can't treat it as an object)
=> Fix example

valet.md
This command allows to add sudoers files for Brew and Valet to make valet commands run without passwords
=> [5.8] Document the valet trust command

billing.md
As per the default Cashier config, `CASHIER_CURRENCY` is defined as [`env('CASHIER_CURRENCY', 'usd')`](https://github.com/laravel/cashier/blob/10.0/config/cashier.php#L73) (i.e. in lowercase). The docs should reflect this.
=> CASHIER_CURRENCY should be in lowercase

collections.md
Adds information about the `Enumerable` contract, as well as the methods only available on the `LazyCollection` class.
=> Improve docs for `LazyCollection`

telescope.md
Have not needed to include the TelescopeServiceProvider because AppServiceProvider is in the `App\Providers`
=> Remove extra text

redis.md
[Deprecation](https://github.com/laravel/framework/pull/29803) has been modified to remove the explicit version where it will be unsupported.
=> [6.0] Removed explicit deprecation of Predis

authorization.md, collections.md, contracts.md, contributions.md, database-testing.md, eloquent-relationships.md, eloquent-serialization.md, encryption.md, homestead.md, queues.md, releases.md
- Add missing trailing commas to arrays
- Use `===` where appropriate
- Trim trailing whitespace
=> Formatting

telescope.md
The height should be computed automatically based on the width, so that the image won't appear distorted when viewed on mobile.
PS: This fix is also relevant for the `master` branch, should I also submit it there?
=> Fix Telescope image aspect ratio on mobile

eloquent-relationships.md, queries.md
Related to https://github.com/laravel/docs/pull/5422 but this time focussing on missing variable assignment or where I believe it should be included (e.g. update queries).
Also includes 2 more instances or missing trailing commas along with a formatting change to ensure method chaining calls appear on their own line as per the rest of the coding examples.
=> [6.0] Assign results of query to a variable

upgrade.md
Having these additional anchors helps link directly to the upgrade steps in posts, tweets, etc.
=> Add named anchors to reference specific steps

collections.md
Documents [the collection's `skip` method](https://github.com/laravel/framework/blob/fc7b632cc37a7a54d379a843b7fabb050eea97fa/src/Illuminate/Support/Collection.php#L968-L977).
=> [6.0] Document the skip() method

collections.md
[Now that `collect()` is part of the `Enumerable` contract](https://github.com/laravel/framework/pull/29823), this PR updates the docs accordingly.
=> [6.0] Improve docs for the collection's collect() method

upgrade.md
When i updated my application i was facing with some blade errors relationated to changes in `Lang` methods, because my view cache was using these methods.
This PR it for warn about clean view cache before uses application.
=> [6.0] Add warning of possible blade error when updating

upgrade.md
The `database.redis.client` config value was added in 5.4 and has technically been optional. Before 6.0, if not found, it would fallback to `predis`. But in 6.0, the [fallback was changed](https://github.com/laravel/framework/pull/29745/files#r317621260) to `phpredis`.
Ref @driesvints comment https://github.com/laravel/framework/issues/29864#issuecomment-528540434
=> [6.x] Add Redis client notice to upgrade guide

eloquent.md
If `latest()`  is the same as `orderBy`, I don't understand why the both are used here. Please correct me if I'm not right.
=> [6.x] Update eloquent.md

dusk.md
Documented a very handy way on CircleCI to access Dusk screenshots when the tests fail. I keep it light though to avoid confusions. If people want to know more about this, they'll probably Google "store_artifacts".
=> [6.x] Added build artifacts for CircleCI

installation.md
Installing Laravel in a subdirectory isn't supported but we still often get issues for it. Adding a note to the docs might be a good idea to let people know.
=> [6.x] Add note about subdirectories

console-tests.md
Update example test method name to be consistent with the rest of the example test methods.
=> [6.x] Update example test method name to be consistent

migrations.md
explain how `default` modifier can take either a value or an `Illuminate\Database\Query\Expression` and provide an example.
=> [6.x] add notes about default Expressions

queues.md
This is something I've been debugging for quite some time to be honest. I have no idea why `block_for` has been set to `0` in my application configuration, but it will block queue workers while being mid-loop, preventing any signals from being handled.
https://github.com/laravel/framework/blob/e11246c25faefecf5540b696b6942310e625a21c/src/Illuminate/Queue/Worker.php#L96-L139
_Explanation: `block_for => 0` will block the queue worker in `$this->getNextJob()`, preventing `$this->stopIfNecessary()` to be executed on a regular basis._
The issue with this is that the queue workers will only restart after the next job has been fetched and processed. Especially on queues with only few throughput (or very irregular throughput), this can be an issue when updating application code. This is because …
=> Add note about issues with block_for=0

redis.md
Encourage is spelled wrong here.
> Before using Redis with Laravel, we **encorage** you to install and use the PhpRedis PHP extension via PECL.
=> [6.x] Typo in Redis introduction section

passport.md
Document the new 'actingAsClient' method added by pull request [#1083](https://github.com/laravel/passport/pull/1083)
=> [6.x] Passport: document 'actingAsClient' testing method

upgrade.md
In documentation there is misleading information that route generation change affects optional paramters. But in fact it affects all paramters and not only optional. 
I've tested this today when making upgrade from Laravel 5.8 to 6.0.3 and confirmed it affects also normal parameters so when having code like this:
```
Route::get('/profile/{location}', function ($location = null) {
//
})->name('profile');
```
result is like below:
```
// Laravel 5.8: http://example.com/profile/active
echo route('profile', ['status' => 'active']);
// Laravel 6.0: http://example.com/profile?status=active
echo route('profile', ['status' => 'active']); 
```
=> [6.x] Remove misleading information about optional parameters

routing.md
The code example for the Route Name Prefixes section was missing a name assignment for the route. 
A similar docs issue has already been fixed for 5.6 (laravel/docs#4122). Future versions of the docs do not have this issue.
=> [5.5] Fix code example for Route Name Prefixes

helpers.md
Should be removed as the dump-server is no longer active.
=> [6.x] Helpers@dump - Removed tip to use dump-server

horizon.md
Ref: #5484 
On quoted PR I was asked to send this PR on 6.0 branch.
There is a small guide about how to install & configure supervisor on Queue documentation page.
It would be nice if we can add the same guide on Horizon Page.
=> Supervisor configuration details on horizon installation page

mocking.md
This could be merged into the docs for 5.5 and upwards.
Whilst the docs show how anonymous notifications sent using `Notification::route` can be tested, they don't show that you can check where that notification has been sent to as implemented in https://github.com/laravel/framework/pull/21379
=> [6.x] Document testing anonymous notification with callback

http-tests.md
This pull request fixes the wrong naming of the JSON API helpers. Previously the documentation reported only the `json()` helper, and misleading told that `post()`, `get()`, etc will issue a JSON API request.
=> [6.x] Describe the correct JSON API helpers

billing.md
I feel this makes more sense in the upgrade section of the docs.
=> [6.x] Move note about API version to upgrade section

upgrade.md
Hi there !
I noticed after experiencing it myself and seeing some posts on Reddit that there is no mention Carbon 2.0 being added to 5.8.
The requirement in composer.json became `"nesbot/carbon": "^1.26.3 || ^2.0"` so Carbon 2.0 will be installed if no conflicts are found.
Composer can't find conflict inside the user code and things can broke with Carbon 2 ([see upgrade guide](https://carbon.nesbot.com/docs/#api-carbon-2))
I think it should be worth mentioning it in the Laravel upgrade guide to 5.8.
I took the liberty to label it as "medium" impact because almost every project will have no conflict and Carbon will be upgraded.
I did not upped this to "hard" impact because the list of breaking changes is not that big and not every people will face these problems.
What do you guys think ? …
=> [5.8] Add mention of Carbon 2.* being required alongside Carbon 1.*

collections.md
Noticed a very tiny mistake in the grammar for the docs where it says "are are" for the following note:
> Methods that mutate the collection (such as `shift`, `pop`, `prepend` etc.) are are not available on the `LazyCollection` class.
=> [6.x] Fixes grammar for Lazy Collection note

dusk.md
to run a Dusk test the user will most likely need a database, so include it in the default suggestion for the Github Action.
=> [6.x] Create a database for Github Action

http-tests.md
Adds the new validation rule, `assertJsonPath`.
https://github.com/laravel/framework/pull/29957
=> [6.x] Add assertJsonPath

container.md
In the example of Contextual Binding, UploadController class was missing in the use parameter.
=> Missing UploadController added in use statement in example

database.md, releases.md
This adds version policies for the different database types and the minimum versions we support. I couldn't find a support policy for SQLite so I added the latest version (which was released in 2004). 
Also linked to the versions from the main support policy docs.
=> [6.x] Add support policies for databases

validation.md
The email validation rules dns and spoof need the php-intl extension to work as per the documentation of [egulias/email-validator](https://github.com/egulias/EmailValidator).
=> dns and spoof need php-intl

http-tests.md
Adds the new `assertNoContent` (https://github.com/laravel/framework/pull/30125) method in 6.1.0.
=> [6.x] Add assertNoContent

queries.md
Apparently the current explanation is incorrect according to https://github.com/laravel/framework/issues/30050#issuecomment-533480384
=> [6.x] Fix selectRaw explanation

middleware.md
The middleware method accepts a single string for one middleware, or an array of strings for a group of middleware.
=> [6.x] Show example for multiple middleware

releases.md
I'm not sure whether it's 6.x that's going to receive 2+1 years of support or just 6.0.x based on current documentation as it explicitly says "6.0" in same fashion to previous LTS "5.5" (and not "5.5.0").
Unless, of course, it's really only 6.0.x that's LTS (2 years bug fixes, 3 years security updates) and 6.1.x and later with their new features won't receive bug fixes/security updates after 1 year of its release date.
=> [6.x] Less confusing version naming

authentication.md, validation.md
Document new password rule and password confirmation functionality.
=> [6.x] Confirm password

notifications.md
This just extends the Nexmo part of the docs indicating how to use Shortcodes.
Relevant: laravel/nexmo-notification-channel#24
=> [6.x] Add Nexmo Shortcode usage

eloquent-relationships.md
I suppose, 'published_date' is the `Book` entity's field.
=> [6.x] load query fix

billing.md
Laravel Cashier: Documentation:
Splling mistake for word Subscription.
=> [6.x] Typo

collections.md, queues.md
1. Changed the word `recurse` to `recurs` to be meaningful.
2. Corrected spelling mistake for `middlewarwe` to `middleware`.
=> [6.x] Typo Fix

authorization.md, providers.md
Following fixes in this PR:
1. Make middleware singular to plural in `providers.md` file
2. Fix grammar mistakes in `authorization.md` file
=> [6.x] make middleware single word to plural

installation.md
One common mistake I see people make getting started with Laravel is how they rename .env.example to .env then don't have a copy of the file available in version control to get themselves started when they start the repo again.
The most common solution for this I've seen in repos is to just keep the .env.example file and make a copy of it instead. Seems like it wouldn't hurt to be worded that way in the docs.
=> [6.x] Recommend copying .env.example file instead of renaming

mocking.md
This merge request adds `partialMock` shorthand method.
Reference: https://github.com/laravel/framework/pull/30202
=> [6.x] Add partialMock shorthand method

homestead.md
On a fresh install of Homestead using Laravel 6 the Minio control panel is available at localhost, not homestead.
=> [6.x] Update minio control panel url

upgrade.md
Hi,
This PR adds instructions for a change in `Illuminate\Auth\Access\HandlesAuthorization` trait that was introduced in this pull request.
https://github.com/laravel/framework/pull/29117
The `deny()` method throws an exception and there is no need of `return` statement.
The return is useless here knowing that it will throw exception.
```php
public function update(User $user, Post $post)
{
if($user->role !== 'editor') {
// works without return
$this->deny("You must be an editor to edit a post.")
}
return $user->id === $post->user_id;
}
```
The `deny()` method no longer throws an exception, developer need to add a `return` statement in order to make the policy work.
Without the return statement, all of the `deny()` calls are being ignored.
```php
public function update(User $user, Post …
```
=> [6.x] Update upgrade guide to include HandlesAuthorization trait change

scout.md
The `Engine::map` method [takes a `Builder $builder` parameter](https://github.com/laravel/scout/blob/31ddbaa62791d0148bb79a0456e1c9a287c50e2c/src/Engines/Engine.php#L59) as the first argument.
=> Add missing Engine::map argument to scout docs

api-authentication.md
```php
Str::random(80)
```
because of
```php
$table->string('api_token', 80)->after('password')
```
=> Consistency: API token length 80 characters

database-testing.md
I notice a lot of examples where developers are using complex setups in order to build associations in their model factories - either using `factory(Model::class)->create()->id`, or doing it in a callback to make it happen lazily.
I think the docs should demonstrate that the easiest solution is simply to associate `factory(Model::class)` and let Laravel do the rest of the work, while still showing how closures can be used for more complex configurations.
=> [6.x] Demonstrate simplest method to attach relation

upgrade.md
new whereDate method can break code for users who used DateTime instances already
See https://github.com/laravel/framework/commit/d4cb93bb9e2bf0b9ee030341c988145ecf0b0526
=> [5.7] Note about whereDate method change

mix.md
As a follow up of https://github.com/laravel/laravel/pull/5126, this updates the javascript examples to use 4 spaces for indentation
Thanks @antonkomarev and @GrahamCampbell for your feedback!
=> Fix javascript examples indentation

upgrade.md
I noticed the `action()` helper is also affected if there is no matching key within the route path.
This PR makes that more clear in the upgrade guide.
I sent in #5548 this morning which was incorrect, I fixed that in this PR.
=> [6.x] Add section for action() helper in upgrade guide

scheduling.md
all the other examples use the full 'minutes' instead of 'mins'.
updating for consistency
=> [6.x] consistent wording for scheduling docs

requests.md
Hey there,
Just spotted this little syntax error in the `$request->missing()` method example.
=> [6.x] Fix syntax error in the '$request->missing()' example

validation.md
Throughout other rule definitions, the `size` rule is (helpfully) referenced, whenever it's related to a particular definition. The formats/links are a mixed bag, though. This just standardizes all `size` references within other rules, so they consistently link back to the definition of `size` itself.
=> [6.x] Standardize `size` references

database.md
If we check `config/database.php`, it actually uses `'foreign_key_constraints' => env('DB_FOREIGN_KEYS', true),`. So we should set `DB_FOREIGN_KEYS` in `.env` file, which is more portable. And you only need to edit one file to make SQLite work.
=> [6.x] Update the way of enable foreign keys in SQLite

dusk.md
In the [Components](https://laravel.com/docs/6.x/dusk#components) example, a `DatePicker` is created with the arguments `$month` and `$date`: 
https://github.com/laravel/docs/blob/6.x/dusk.md#L1318-L1322
In the next [using components](https://laravel.com/docs/5.8/dusk#using-components) example, the `DatePicker` is utilized with an unexpected year:
https://github.com/laravel/docs/blob/6.x/dusk.md#L1359-L1361
This PR cleans up the examples by providing the year to provide a better understanding of components.
=> [6.x] Fix Dusk Component Examples

http-tests.md
Update to #5564, reverting to `$keys` for consistency with source code. Kept other edits to `assertSessionHasErrors` and `assertSessionHasErrorsIn`.
=> [6.x] assertSessionHasErrors clarification

homestead.md
`7.#foobar` => `7.xfoobar`
1. `#foobar` is rendered as a comment in the docs
2. `xfoobar ` is not
=> Exchange # with x to avoid comment in backticks

artisan.md
- Anticipate can now accept a closure as a second parameter instead of an array, as of 6.0
=> [6.x] Document closure as second parameter

envoy.md
This clarifies on how to get task context when sending notifications with Envoy.
See https://github.com/laravel/envoy/issues/166
=> [6.x] Clarify task context for Envoy notifications

middleware.md
The `terminate` method use on the StartSession middleware was removed in https://github.com/laravel/framework/pull/26410
=> [6.x] Remove invalid example

eloquent.md
The doc should be more clear that NO events will be fired on mass update and mass deletion.
If you try to do `User::whereKey($id)->forceDelete()` the observer will be ignored. This doc update expands the warning in order to let the developer knows that.
I've targeted the 6.x branch but I think this affect any Laravel version that has Eloquent observer in it
=> Update eloquent docs on event firing

container.md
It seems like the extender closure receives the container instance as the second argument, this PR adds that usecase with an example to the extension part.
=> Add container usage for the extend method.

notifications.md
since Slack messages tend to be directed at a workspace/channel, and not a specific user, adding a line to show how to send on-demand Slack notifications
=> [6.x] add Slack on demand notification example

authorization.md
The code sample under `Policy Responses` mistakenly had a phpdoc block stating that it returns a `bool`, when the code shows it returning a `Response`
=> Update authorization.md to correct phpdoc output

session.md
The flashed data is available immediately not 'only' available on the subsequent request.
=> Updating Session flash wording

validation.md
unlike the `digits` rule, this rule does not mention the value needs to be numeric.
=> clarify `digits_between` rule

collections.md
Added missing filtered example results just like other `where` methods.
=> [6.x] Updates collection whereInstanceOf method.

validation.md
The 'active_url' validation rule in the docs is a little bit misleading.  
From the docs:
> The field under validation must have a valid A or AAAA record
> according to the `dns_get_record` PHP function.
To me, this sounds like the field being validated is passed straight to `dns_get_record`, when in fact the field is first passed to `parse_url` to extract the hostname portion of the URL.
From the source code:
```php
public  function  validateActiveUrl($attribute, $value)
{
if (! is_string($value)) {
return  false;
}
if ($url  =  parse_url($value,  PHP_URL_HOST)) {
try {
return  count(dns_get_record($url,  DNS_A  |  DNS_AAAA))  >  0;
} catch  (Exception  $e) {
return  false;
}
}
return  false;
}
```
This leads to unexpected behaviour: Note the difference between the …
=> [6.x] Clarify what 'active_url' actually does

contributions.md
So we can link to it from the repos and have one place where we'd need to make edits.
=> [6.x] Add code of conduct to docs

localization.md
Some parts of Laravel expect locale names to be formatted according to ISO 15897 (eg: https://github.com/laravel/framework/blob/e04a7ffba8b80b934506783a7d0a161dd52eb2ef/src/Illuminate/Translation/MessageSelector.php#L110). The doc does not mention this, so developers may think they're free to name their locales however they want. I personally got burnt by this and called my locales "en-gb / zh-cn" instead of "en_GB / zh_CN", and realised only later that `trans_choice()` did not properly handle plurals because of this.
English is not my first language so the wording may need improvements. Please native English speakers don't hesitate to correct.
=> [6.x] Note about locale name format

passport.md
I've seen several issues with people trying to override the default models without first extending the original ones so I hope these changes make it more clear.
=> [6.x] Clarify extending models with Passport

eloquent-serialization.md
Since this method is now deprecated by Carbon, we shouldn't recommend it anymore.
More background on this can be found here: https://github.com/briannesbitt/Carbon/issues/1870
=> [6.x] Remove docs for serializeUsing

eloquent.md
In the current 5.x branch are no information about the possibility to remove a global scope on relationships.
Since I am not a native speaker I am very pleased about any enhancements on the phrasing.
=> [5.8] Removing global scopes on relationship

upgrade.md
This caused major headache for us in our application. It wasn't noted in the upgrade guide that the email verification path had changed which meant that any people that registered to our site prior to the upgrade their email verification links no longer worked and they were all going to a 404.
Personally, I think it should be fixed by keeping the old verification route but deprecate it. For now we should at least add a note about it on the upgrade guide because this is a pretty nasty one to run into on production if your not aware of it.
=> [6.x] Upgrade note about email verification route path change.

dusk.md
This PR adds chrome driver update command during travis ci installation.
Without this command travis ci fails:
=> [6.x] Upgrade chrome driver for travis ci

dusk.md
Every CI env needs to have the proper APP_URL set for `artisan serve`. Also added the `dusk:chrome-driver` to every CI env.
=> [6.x] Clarify app url setting for Dusk CI

database-testing.md
This documents the new `assertDeleted` helper added in https://github.com/laravel/framework/pull/30648.
It also adds a brief section and code sample to demonstrate the shorthand invocation of passing only a model to `assertDeleted` and `assertSoftDeleted` helpers.
=> Document new helper and shorthand invocations

helpers.md
This PR adds a small addition to the `endsWith()` helper to note that developers can pass an array of values.
```
$result = Str::endsWith('This is my name', ['name', 'foo']);
// true
```
=> [6.x] Helper endsWith array of values

installation.md
As per composer's documentation [0], the default path for COMPOSER_HOME changed from "$HOME/.config/composer/" to "$HOME/.composer/".
[0] https://getcomposer.org/doc/03-cli.md
=> Update path to Laravel binary for *nix systems

eloquent-resources.md
Just noticed a small error while reading through the docs.
=> [6.x] Fix wrong class name in API Resources

validation.md
Documents how to use the Model class at the validation rules: https://github.com/laravel/framework/pull/30653
=> [6.x] Documents the explicit Model definitions in database rules

console-tests.md
There's no number sign next to the **Introduction** heading (and the whitespace is incorrect):
I'm not sure if this fixes the issue, but the anchor tag for the introduction heading is present in every other file.
=> [6.x] Add anchor tag to introduction.

collections.md
Add missing use statement in the collections docs
=> [6.x] docs(collections): add missing use statement

authorization.md
The type is `?User`, so calling `->id` on null will result in an exception.
=> [6.x] Add optional() call on a nullable User type

migrations.md
At the moment it's apparently not clear from the docs how you can increase the precision for timestamps when writing migrations.
See https://github.com/laravel/framework/issues/27200
=> [6.x] Document precision for timestamp columns

upgrade.md
The link to Carbon 2.0 does not work due to an extra "#" in the anchor name, updated to remove extra # and make the link work
=> Fix broken link to Carbon 2.0 upgrade section

eloquent-serialization.md, upgrade.md
This adds the recent date serialization changes of https://github.com/laravel/framework/pull/30715 to the upgrade guide and also adds documentation for overriding the default serialization format.
I've also added the new minimum PHP and Symfony version requirements.
=> [7.x] Document serialize date changes

redis.md
Hey!
When I read the doc about the pipeline command I at first thought that it was like a transaction using the MULTI and EXEC redis commands.
But I discovered that it was not :D
This means that if you have two processes pipelining commands they'll run concurrently on the redis server.
I am not a native english speaker so maybe my incomprehension comes from that.
Anyway I've made a small change to the doc on the part that I misunderstood. Feel free to edit/merge/reject it as needed.
=> Misleading Redis pipeline documentation

billing.md
This makes it clear that it can be used for all kind of plan changes, not just quantities. Some people on Discord mentioned this wasn't that clear atm.
=> [6.x] Document prorations during plan swap

valet.md
Some of this information is specific to Valet 2.6.0+, but most applies to older 2.x versions as well.
https://github.com/laravel/valet/releases/tag/v2.6.0
=> [6.x] Add technical information section to Valet docs

artisan.md
This PR accompanies https://github.com/laravel/tinker/pull/86 to move the documentation to the docs repo so we have a single place where we can maintain it.
=> [6.x] Move docs from readme

socialite.md
https://developer.twitter.com/en/docs/basics/authentication/overview/oauth
The Twitter driver currently makes use of OAuth 1.0 because it needs to authenticate on behalf of the user and not as the app. Therefor stateless authentication isn't available.
See https://github.com/laravel/socialite/issues/415
=> [6.x] Make note of twitter for stateless auth

seeding.md
If the user changed their Hash Driver passwords generated with `bcrypt()` won't work.
=> [6.x] Use Hash::make() instead of bcrypt() in the user seed example

database-testing.md, http-tests.md, testing.md
Starting Version 6.8(?) unit tests extend PHPUnit TestCases, resulting in more performance, but also don't boot laravel and its features like factories or assertions added by laravel.
=> [6.x] Starting 6.8(?) only feature tests extend laravels TestCase

valet.md
Explains ngrok a little more, and specifically adds a section to explain how to share sites on the local network for team members to access anytime.
=> Expand on local network sharing options in Valet

helpers.md
add a clarification that `Str::plural` can only pluralize single words.
=> [6.x] clarify Str::plural function

dusk.md
I don't see any reason to send the output to `/dev/null`. The output can be helpful in debugging if there is a problem.
=> [6.x] update Github Actions example

http-tests.md
I have been looking for this specific feature for a while now. Unfortunately, all responses I found online didn't mention the `withCookies` and `withCookie` methods at all. I had to take a look in `Illuminate\Foundation\Testing\Concerns\MakesHttpRequests`'s source to figure it out and thought it could help others if it was simply added to the docs.
I'm not sure if it's the right spot to add it in. Let me know if I should move it elsewhere.
Thanks!
=> [6.x] Added withCookies documentation to HTTP Tests

collections.md
Add a link for the subheader "Creating Lazy Collections" under "Lazy Collections", in `collections.md`.
=> [6.x] Add link for header Creating Lazy Collections

requests.md
Diactoros has been archived by Zend and support has been removed by Symfony's PSR Bridge.
=> Update the composer package reference. Reference Laravel/Framework #31017

dusk.md
PR adds documentation for the newly added `waitUntilMissingText` in Dusk.
https://github.com/laravel/dusk/pull/706
=> [6.x] Dusk: waitUntilMissingText

envoy.md
Reverts laravel/docs#5568
It turns out I was mistaken with this and the current slack and discord directives only work within the finished directive.
=> [6.x] Revert "[6.x] Clarify task context for Envoy notifications"

queues.md
I was suggested to explain the difference between `queue:work` and `queue:listen` a bit more in laravel/framework#31120.
When `queue:work` is used, since workers are 'long-lived processes', it actually lowers the degree of job isolation and some changes made by a job can affect subsequent ones, e.g. non-idempotent mutations to static variables. This is not by design (I think) but a limitation of PHP.
In such a scenario, users can use `queue:listen` instead at the expense of performance.
=> [6.x] Explain the job isolation difference between queue:work and queue:listen

dusk.md
documenting https://github.com/laravel/dusk/pull/704
=> [6.x] Add note about automatic resizing on failures in Dusk

mocking.md
This is #5721 sent to the right branch and simplified.
Long story short there aren't examples for passing an array of jobs rather than job classes to `assertPushedWithChain()`, which provides tighter assurances that may be necessary to attain the desired level of confidence from the test.
Couple observations that don't necessarily warrant a response. I am a newcomer to Laravel, but these things seemed weird:
It is strange to me that the tests in this mocking section of the docs are namespaced as feature tests.
To my fallible understanding, it seems to me that breaking Jobs out into traits in the particular way it was done -- one of which (`InteractsWithQueue`) is the actual holder of the property that implements the Job contract -- has polluted the domain concept of a job and created a …
=> [6.x] Add `QueueFake->assertPushedWithChain()` property-matching example

mix.md
Documents `app.mix_url` implemented in laravel/framework#28952.
I took a stab at the wording, figuring you'd shuffle/rearrange to your liking 😄 . I only documented it in 6.x, but happy to contribute it back to 5.8 as well once you're happy with the wording.
I also noticed this configuration option isn't included with `config/app.php` out of the box. Is that something you'd like a PR for?
=> [6.x] Document `app.mix_url` customizations

collections.md
some Collection methods have special behavior for Eloquent Collections. Add a link in the docs to this info for easy access, and to make the developer more aware of the overriding behavior.
=> [6.x] Link to Eloquent Collection methods

passport.md
Change the noun, `confidentiality`, to the adverb `confidentially` so the sentence is grammatically correct.
=> Fix grammar

requests.md
Added documentation in Requests about the upcoming "boolean" method.
I want to include examples to explain further, but worry it is (already?) too lengthy.
Related PR: https://github.com/laravel/framework/pull/31160
=> [6.x] Added "Retrieving Boolean Input Values"

eloquent-relationships.md
Considering "banned" as truthy, and "not banned" as falsy.  We could represent them with 1 and 0 respectively. In case of documentation which is "not banned", we can replace it with 0.
=> Representing truthy with 1 and falsey with 0

installation.md
> If your system uses freedesktop.org standards, then it will first check
XDG_CONFIG_HOME or default to `/home/\<user\>/.config/composer`
From [composer source code](https://github.com/composer/composer/blob/master/src/Composer/Command/GlobalCommand.php#L47-L48)
The doc is misleading developers on Linux leading to questions like [this](https://stackoverflow.com/a/40470979) and [this](https://laracasts.com/discuss/channels/laravel/i-add-homecomposervendorbin-to-my-ubuntu-path-but-it-then-removed-automatically)
=> Added composer global installation path for Linux

helpers.md
Fixes https://github.com/laravel/framework/issues/31256
Adding information of nonoccurrence on Str::after and Str::afterLast methods.
If there are no key occurrence on string, method will return whole text rather than null value.
There is a closed issue on laravel/framework. Explanation may prevent people from mistake.
=> [6.x] Adding information of nonoccurrence on Str::after and Str::afterLast 

controllers.md
Documents https://github.com/laravel/framework/pull/31208
=> [6.x] Document shallow nesting

authentication.md
This documents the behavior discovered in https://github.com/laravel/framework/issues/31223. At the moment the login route name is hardcoded in the `unauthorized` method so overwriting it is the only way to redirect to the login page when the route name was customized.
=> [6.x] Document unauthorized override

horizon.md
Adds recent `horizon:status` to horizon documentation as per https://github.com/laravel/horizon/issues/468
=> add the `horizon:status` Artisan command to the Horizon documentation`

passport.md
Added in Passport 7.0 is the ability to extend the Passport Client model to add a skipsAuthorization method. However, no documentation was included on how to tell Passport to use the extended model.
=> [6.x] Document how to use a custom Passport Client model

artisan.md
Currently there is no information about the fact that artisan command `choice()` method is capable of accepting multiple options. This PR adds information about attributes 4 & 5 (attempts and multiple) for the documentation in choice about choice method
=> [6.x] Add information about multiple answer attribute for artisan choice()

requests.md
Since there are two examples of the `$proxies` variable given and one of them is a string, I think it would make sense to provide the correct types.
=> [6.x] Fix PHPDoc variable type hint for $proxies

passport.md
I found that you can't check for scopes without also checking for the 'auth:api' middleware, which is logical, but I still wasted hours before figuring it out =")
Another solution is to wrap all your routes that check for scopes in an 'auth:api' group middleware .. someone probably should write an example about that
=> [6.x] Checking for scopes

controllers.md
Not sure how often people use these nested resources, but the example URL should use singluar model names. Also change URL to URI and prepend example URL with forward slash.
=> [6.x] Fix nested resources URL example

queues.md
Based on laravel/framework#22301
See; https://github.com/laravel/framework/issues/22301#issuecomment-351452235
=> Removed wrong example in queues/timeout

eloquent.md
I found this especially useful when we need multiple model instance that share mostly the same attributes.
An additional example:
```php
$newborn = Newborn::create(
'first_name' => 'John',
'last_name' => 'Doe',
'date_of_birth' => '2020-02-14',
'hospital_id' => 1,
);
$twinBrother = tap(
$newborn->replicate()->fill(['first_name' => 'Jack'])
)
->save();
```
=> [6.x] Add model replicate function.

helpers.md
This is a quite useful method since PHP doesn't come with a mb_ucfirst method, so it would be nice if it was included in the docs to make it easier to find.
=> [6.x] Add Str::ucfirst to docs

collections.md
since `whereIn` is using `filter` underneath the hood, the elements order is not manipulated at all, but rather maintains the same order as the original Collection.
=> [6.x] Fix order of output for `whereIn`

collections.md
Implemented in https://github.com/laravel/framework/pull/31425
=> [6.x] Document whereNull and whereNotNull collection methods

helpers.md
This PR adds the missing docs for the useful `Arr::crossJoin`.
=> [6.x] Add crossJoin docs

pagination.md
Fix issue on the pagination.md documentation.
If we follow the API documentation at [https://laravel.com/api/6.x/Illuminate/Contracts/Pagination/LengthAwarePaginator.html](url), the `hasMorePages()` method has the wrong documentation (it has the `hasPages()` one).
I fixed it, and added the documentation for the `hasPages()` method.
=> [6.x] Fix documentation on pagination.md

views.md
If `foo.bar` is a directory and `baz.blade.php` is a view inside that directory then you can't reference it as `view('foo.bar.baz')`.
See https://github.com/laravel/framework/issues/30709
=> [6.x] Cannot use dot directories

validation.md
This PR adds some further clarification and examples to the `size` rule. Especially the `integer` and `numeric` rule combinations needed some further clarification. See https://github.com/laravel/framework/issues/28483
=> [6.x] Clarify size rule

routing.md
Everytime I hear someone talking about routing in a multi-tenancy application, even a few weeks in the project, their minds are blown when they realise they missed the `Url::defaults` method. Last time was today on reddit.
I think part of the problem is people searching in routing.md instead of url.md, as it is usually where they are first introduced to url parameters and the `route` helper.
I don't want to duplicate content, so I copied the bare minimum from the urls#default-values section to introduce it, and just redirected to the other section.
Feel completely free to close this if you don't think it necessary.
Same for the exact wording, I'm not a native speaker and I know it.
=> [6.x] Mention the URL::defaults method in routing.md and redirect

blade.md
Just spotted that while digging the `master` docs for new sweets and candies 👀
=> Fix incorrect term (“directory” -> “namespace”)

billing.md
I've noticed regularly that people don't seem to understand that Stripe Plan trial days aren't used in Cashier and that trialing is always set on the subscriptions directly. I think it's important that we clarify this concept properly in the docs.
=> [6.x] Clarify trial days in Cashier

billing.md
This adds a suggestion to use the Stripe CLI to test webhooks which works much better than Valet itself.
=> [6.x] Suggest using Stripe CLI

blade.md
Added a few words between the colons so the reader won't get confused as to whether it is supposed to be a single or double colon.
=> [7.x] Added extra words between colons for readability

releases.md
Fixed a typo in section "Blade Component Tags & Improvements" of the releases.md file for version 7.x
=> Typo in releases.md

valet.md
The Default Site is used as a fallback for Emulators and IDEs which can only handle an IP address instead of a domain name that Valet would serve.
=> [6.x] Add "Default Site" / fallback section to Valet docs

valet.md
This provides a reference point for changing default memory limits etc
=> [6.x] Add PHP configuration section to Valet docs

installation.md
This is because of the following error with a default PHP installation:
Crafting application...
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.     
Problem 1
- Installation request for league/flysystem 1.0.64 -> satisfiable by league/flysystem[1.0.64].
- league/flysystem 1.0.64 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
Problem 2
Extension fileinfo is missing from your system.
- laravel/framework v6.17.1 requires league/flysystem ^1.0.8 -> satisfiable by league/flysystem[1.0.64].
- Installation request for laravel/framework v6.17.1 -> satisfiable by laravel/framework[v6.17.1].
=> [6.x] Add fileinfo php extension to documentation

installation.md
See following error on fresh PHP installation:
Crafting application...
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.        
Problem 1
- Installation request for league/flysystem 1.0.64 -> satisfiable by league/flysystem[1.0.64].
- league/flysystem 1.0.64 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
Problem 2
- league/flysystem 1.0.64 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
- laravel/framework v7.0.1 requires league/flysystem ^1.0.8 -> satisfiable by league/flysystem[1.0.64].
- Installation request for laravel/framework v7.0.1 -> satisfiable by …
=> [7.x] Add fileinfo to system requirements.

http-tests.md, upgrade.md
This notes the new `escaped` parameter for the `assertSee` and `assertDontSee` set of assertions in both the Upgrade Guide and HTTP Test sections.
=> Note assertSee changes in Laravel 7.x

frontend.md
Since Laravel 7 and Laravel UI 2, the Auth routes are defined in the latter. So the package should always be installed, not only in dev environments.
This change (https://github.com/laravel/framework/commit/aebd93d5f67de55473f3f0ff5056abbfc5972102) should be mentioned in the upgrade guide.
=> Fixed wrong info in frontend page

frontend.md
Current laravel/ui 2.0 requires laravel 7.0, laravel/ui#69.
=> Fix scaffolding package install command for 6.x

upgrade.md
Since it's now expected that all mail templates are un-indented, we should note that people need to republish their overwritten templates.
=> [7.x] Note re-publishing markdown mail templates

helpers.md
This helper was actually added in 6.x ([#31636](https://github.com/laravel/framework/pull/31636)), but I wasn't sure whether it should be added to the base 6.x documentation since it came with a later version. It is definitely missing from 7.x docs though :)
=> [7.x] Document Arr::hasAny() helper

frontend.md, passwords.md, verification.md
Since Laravel 7 and Laravel UI 2, all authentication scaffolding has been moved to the laravel/ui repository. So the package should always be installed, not only in dev environments.
=> Remove dev flag for Laravel UI 2

installation.md
'Composer' rather than 'composer' is used elsewhere in the file
=> [6.*] Fix for consistency

releases.md
The doc should show attributes variable name as `$attributes`, not `$attribute`.
=> Fix typo for attributes variable

dusk.md
This is a cherry pick of https://github.com/laravel/docs/commit/5896fb9dfe03210854f9b8cdc595f94345d43093
It should also be applied to the 5.5, 5.6, 5.7 and 5.8 branches
=> [5.4] Fix url to GitHub repository for Dusk modifier keys

upgrade.md
Add a section to the upgrade guide to explain that the `Assert` class has moved to a new namespace.
Also adds a TOC link for `TestResponse`, and fixes the duplicate `assert-see` named anchor.
=> Add note about moved Assert class

upgrade.md
For most applications that are already using UTC, the impact of the new date serialisation in Laravel 7.x poses no real issue.
For those that are using non-UTC timezones, the impact is slightly higher, as the `toJSON()` method that `serializeDate` calls, defers to the `toISOString()` method, which will force the timestamp to UTC.
=> Add UTC caveat to date serialisation in upgrade guide

upgrade.md
Hi. 
This is more an issue than a suggestion.
For the Laravel 6 to 7 migration I've followed the migration guide, which ask to change the same_site value from `null` to `lax`.
This broke my app local development (a SPA served by webpack web server).
Actually I don't understand why this change has been made, as it's a breaking change, but is absolutely not needed for symfony 5 compatibility.
Each time we create a Symfony cookie we set sameSite with the value from the config, and null is a totally accepted value 🤷‍♂️.
We actually also have to change the phpdoc of `config/session.php` file for:
```
Supported: "lax", "strict", "none", null
```
Thanks.
=> Remove the mention to same_site in upgrade guide.

eloquent-collections.md
I've been using the `findMany` method in some projects and I was wondering why it isn't in the documentation. Maybe this is intended, if not I think this is a useful addition. When this is intentional I'd love to know why you shouldn't use this method. I know that the `find` method can handle an array and uses the `findMany` method to do so.
=> Add findMany method to eloquent collections

valet.md
Valet can be used as is with ExpressionEngine default install. We can also provide custom drivers for common configurations if that is helpful.
=> Added ExpressionEngine as supported out of the box

upgrade.md
References the master branch now that Laravel 7.x is in general release.
Signed-off-by: Daniel Craig Jallits <dan@jallits.com>
=> Update URL for CORS config file

billing.md
This extracts the part of exception handling into a separate section that also details `PaymentFailure` exceptions. This clarifies the relation between SCA and `PaymentActionRequired`.
=> [7.x] Cashier improve exception docs

dusk.md
Following a Dusk PR being merged (laravel/dusk#751), this PR is about updating the documentation.
=> [7.x] Add new assert methods for Dusk

http-client.md
Added documentation for adding Guzzle options that are not supported out of the box by the HTTP client. I updated the table of contents.
=> [7.x] Added withOptions docs to Http client

upgrade.md
I am aware that the `shouldReport` and `renderForConsole` methods are not documented, but some projects are overriding them (or implementing the exception handler for other reasons) and it would be useful to know that these methods also accept `Throwable` instead of `Exception` now.
=> [7.x] Add all ExceptionHandler methods to upgrade guide

sanctum.md
To me, it was not obvious right away that this was a requirement.
Having read GitHub issues over and over again and after chatting in Discord's Sanctum channel, it seems it was not quite clear amongst people there either.
Even though it makes complete sense that this is a requirement, I think noting it in the docs is important as I have spend days trying to educate myself on this issue on why it wasn't working, instead of learning how the foundation is working.
So I hope this helps people not make the same mistake as me 🤦🏼‍♂️
=> [7.x] Sanctum - added note that API and frontend have to share the same TLD

dusk.md
This PR changes the *Dusk -> Continuous Integration -> Github Action* example with the following:
- Add command to start MySQL service before a database is created (using the MySQL service). This was a breaking change introduced on [March 3rd, 2020](https://github.community/t5/GitHub-Actions/Github-Actions-Can-t-connect-to-mysql/m-p/50610#M7891) where Ubuntu virtual environments no longer starts the MySQL service automatically and the [solution](https://github.community/t5/GitHub-Actions/Github-Actions-Can-t-connect-to-mysql/m-p/50610#M7891) is simply to start the service manually.
- Bump the version `actions/checkout` to the latest `v2`
=> [7.x] Update CI Github Action example

queries.md
This adds documentation for the new query builder `reorder()` method. (https://github.com/laravel/framework/pull/32186)
=> [7.x] Add query builder reorder() documentation

upgrade.md
Updating docs according to [this merged PR #32165](https://github.com/laravel/framework/pull/32165), and our initial conversation [in another PR #32145](https://github.com/laravel/framework/pull/32145#issuecomment-605655948).
=> [7.x] Swift Mailer Bindings Removed

eloquent-mutators.md
Docs for https://github.com/laravel/framework/pull/32129
=> Add castable docs

telescope.md
I had a hard time finding why Telescope was running in production in my apps by following the doc. It turned out that it was because of package auto-discovery.
So here’s an amendment to make sure Telescope isn’t enabled at all outside of local environment.
From [@michaeldyrynda’s article](https://dyrynda.com.au/blog/using-laravel-telescope-in-specific-environments).
=> [7.x] Prevent Telescope auto-discovery in production

queues.md
I assume the examples are meant to have comparison rather than assignment operators, otherwise there's not much point in using conditional dispatch.
=> [7.x] Fix example in queues.md

session.md
I notice the source link in the reference for the Session Fixation attack could be replaced for an official web application source [OWASP].
=> Session Fixation source link changed to an official security source

http-client.md
This PR mentions the new assertions for the HTTP Client `assertNotSent` and `assertNothingSent`.
Framework Pull Request: https://github.com/laravel/framework/pull/32197
=> [7.x] Mention new assertions assertNotSent and assertNothingSent

views.md
The PR to allow disabling checks for expired views (https://github.com/laravel/framework/pull/31206) was reverted because it didn't account for third party views. The docs still mention the 'expires' option and this confused me as I didn't see it make any difference. Digging into the view Complier code made me realize that this update must have been removed.
=> [7.x] Remove mention of disabling view expiration check

billing.md
Add a part about Stripe testing tokens. Think it's good we link to these tokens from the docs.
=> [7.x] Add part about Stripe testing tokens

authentication.md
As it currently reads, the docs imply that the auth controllers are installed by default, rather than by `laravel/ui`.
=> Move auth controllers

telescope.md
Version 2.1.7 is the last that supports laravel 5.8 as release 3.0.0 removed support for laravel 5.8.
=> [5.8] Changing the version of the laravel telescope

passwords.md
The doc mentioned that reset password tables migration is included with Laravel out of the box, while in fact that isn't true anymore. 
The reset password migration file has been removed from Laravel codebase on 21 Dec, 2019 by @taylorotwell, this is the diff https://github.com/laravel/laravel/commit/13e43893ba2457c3e49898f0066a5ce8d7ea74f4#diff-1dc5ac688c033a49fe866c452e212a4c. The reason for deletion is to host the file in laravel/ui package instead.
This pull request try to help the reader who read the doc to see the clear picture of where the file is.
=> [7.x] Mention that reset password tables comes with laravel/ui package

billing.md
- Cashier: Remove locale from Stripe guide link
Some users may be using Stripe in other languages, and we should not
override the language they are currently using Stripe in.
- Fix typo: API's -> APIs
=> Cashier: Minor fixes

http-tests.md
I found myself searching for the string `403` on the HTTP Tests page to find if there is an assertion for such status code. But could not find one, when I searched for `401`, I could. That let me to assume there wasn't one. Started digging through code and found `assertForbidden`. 
I think it would be useful to add, makes searching the documentation easier.
=> [7.x] Added status code to assertForbidden in HTTP Tests documentation

notifications.md
Apparently the current docs are referring to the newer way of setting up a custom app, rather than using the existing Slack one. The former doesn't supports customizing `from`.
=> [7.x] Use proper link to Slack app

eloquent-mutators.md
Super minor tweak:
This example currently uses the "date" cast, but since the "last_posted_at" includes the time (given that convention, it probably makes more sense to use "datetime" in this example.
=> [7.x] Tweak query time casting example

upgrade.md
Based on https://github.com/laravel/framework/pull/31196/files and https://github.com/laravel/framework/pull/31315/files more methods were updated that mentioned in upgrade guide.
=> [7.x] Mention all updated methods with auto escaping

eloquent-collections.md
Reverts https://github.com/laravel/docs/pull/5893
As mentioned by @guicapanema the `findMany` method does not exist on `Illuminate\Database\Eloquent\Collection`, it only exists on `Illuminate\Database\Eloquent\Builder`.
=> [7.x] Revert 'Add findMany method to eloquent collections'

authorization.md
If a resource controller is created by calling 
php artisan make:controller UserController --resource
it will not work with the described approach in the docs since the policy expects an injected model. If you do
class UserController extends Controller
{
public function __construct()
{
$this->authorizeResource(User::class, 'user');
}
...
it will fail to authorize and return a `403` for the methods.
Creating it with 
php artisan make:controller UserController --resource --model=User
will work as it creates matching signatures / type hints
=> [7.x] Adding a note on Authorizing Resource Controllers

eloquent-relationships.md
The new example:
* Explains clearly the relation between the three models in association order.
* Changes the table order to mirror the verbal explanation.
* Uses the _User perspective_, meaning, an active participant (mechanic) is who access far data (car's owner).
=> [7.x] Clearer HasOneThrough example

upgrade.md
`transformModelValue` Runs mutators then casts. This caught me out during an upgrade. Albeit perhaps in quite a niche scenario.
=> [7.x] Mutators are also now run on getOriginal

mail.md
Note for https://github.com/laravel/framework/issues/31977
=> [7.x] Add note about autolink in Markdown section

dusk.md
Every time Chrome releases a new version, a version mismatch exists for a couple of days. This causes Laravel Dusk to fail with the message: 
`Facebook\WebDriver\Exception\SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 81`
This problem exists until GitHub actions auto-updates their ubuntu-latest image. (about once a week). During that time the following version mismatch exists:
`php artisan dusk:chrome-driver` -> install the latest chrome-driver version (currently 81)
`/opt/google/chrome/chrome --version` -> Github's ubuntu-latests version is at 80.xx
This can be easily solved by installing the chrome-driver based on the chrome version of the current machine. 
This fix has been tested and is working for my use case.
=> [7.x] Github Actions -> match the correct chrome-driver

middleware.md
Add a note that `withoutMiddleware` does not applies to globally defined middleware.
=> [7.x] Document withoutMiddleware and global middleware

helpers.md
Documents `ltrim` and `rtrim` in the correct place. 
Reference https://github.com/laravel/framework/pull/32288
=> [7.x] Documents ltrim and rtrim

notifications.md
I think the email is intended to be sent to the '$notifiable' instead of (presumably) passing a user in through the constructor
=> use $notifiable in example instead of $this->user

upgrade.md
The flag was initially removed but then reverted back in https://github.com/laravel/framework/commit/24c18182a82ee24be62d2ac1c6793c237944cda8
=> [7.x] Remove --daemon deprecation message in upgrade guide

dusk.md
Documents https://github.com/laravel/dusk/pull/766
---
It's also worth noting that there is an example under 'Browser Macros' using `scrollToElement()`. This is misleading as there is no reason to macro this method as we have the undocumented `scrollTo()` as well as `scrollIntoView()`. Perhaps this example should be updated to something else. Equally it might also be worth documenting `scrollTo()`.
=> [7.x] Document in Dusk scrolling an element into view

container.md
=> [7.x] Document binding tags (giveTags)

collections.md
I just found that an instance of `until()` was not updated to `takeUntil()` in 
https://laravel.com/docs/7.x/collections#method-takeuntil
Possibly an oversight. Kindly merge this pull request to update.
=> Replaced deprecated until() with takeUntil()

logging.md
- Fixed Target class [Illuminate\Support\Facades\App\Logging\CustomizeFormatter] does not exist
- Added a formatter example to make it easier for beginners.
=> [7.x] improved logging Customizing Monolog For Channels

billing.md
At the moment it is not said where Stripe's webhooks should be directed to be picked up by the default Cashier webhook controller.
=> [7.x] Added Stripe webhooks path

helpers.md
The link in the documentation pointed to matchAll when it should have been match-all - corrected this in line with other anchor tags.
=> [7.x] Updated Fluent matchAll Anchor

collections.md
=> [7.x] Document `skipUntil` and `skipWhile` collection methods

releases.md
Dependency requirement for _laravel/ui v2.x_ not fulfilled in _laravel/framework 6.x_ thus only _laravel/ui v1.x_ works
=> fix: require laravel/ui v1.x

billing.md
It's in the wrong order, confused me :P
Prefix is `stripe` by default, set [here]( https://github.com/laravel/cashier/blob/11.x/src/CashierServiceProvider.php#L89-L95) and route defined [here](https://github.com/laravel/cashier/blob/11.x/routes/web.php#L6)
=> fix: correct webhook route in cashier docs

http-client.md
Now the order of displaying methods is as follows:
```
$response->ok() : bool;
$response->failed() : bool;
$response->successful() : bool;
$response->serverError() : bool;
$response->clientError() : bool;
```
It looks nice, but the failed method breaks the combination of methods `ok` and `successful`.
I think it would be better to make it like this:
```
$response->ok() : bool;
$response->successful() : bool;
$response->failed() : bool;
$response->serverError() : bool;
$response->clientError() : bool;
```
This code looks logically correct.
=> [7.x] Method order fixed

billing.md
Update Cashier documentation to make usage of asStripeCustomer() and createOrGetStripeCustomer() more clear
=> [7.x] Update Cashier documentation to make usage of asStripeCustomer() and createOrGetStripeCustomer() more clear

sanctum.md
Explains that the example using Axios relies on the fact that Axios will automatically read the `XSRF-TOKEN` cookie and re-inject its content into the `X-XSRF-TOKEN` header, otherwise a users who want to test Sanctum by manually querying the api might not understand why they end up with a token mismatch exception.
=> Explain what happens with the XSRF-TOKEN

eloquent-relationships.md
See https://github.com/laravel/framework/pull/32738 and https://github.com/laravel/framework/pull/32739
=> Document 'morphWithCount' and 'loadMorphCount' methods

telescope.md
https://github.com/laravel/telescope/pull/890
Cover the new `Telescope::avatar()` callback registration available to `TelescopeServiceProvider`.
=> Add Telescope::avatar() example

collections.md
The wording is a little confusing because these 2 methods do not share the same signature. `sort` accepts an optional callback, while `sortDesc` accepts an optional set of options. 
Added clarification you cannot pass a callback to `sortDesc`, and a suggestion for how to use `sort` to achieve the desired results.
=> [7.x] update `sortDesc` documentation

queries.md
PR adds note under the `whereIn` section about undocumented `whereIntegerInRaw` and `whereIntegerNotInRaw` methods.
Ref: https://github.com/laravel/framework/pull/26434
=> [7.x] Add note about whereIntegerInRaw, whereIntegerNotInRaw

blade.md
There was an unnecessary ` * @param  string  $message` entry in the docblock which is incorrect.
=> Fix incorrect doc block in Blade Templates under casing

helpers.md
This PR documents the `split` function in stringable. 
Reference: https://github.com/laravel/framework/pull/32713
=> [7.x] Documents split function in Stringable class

collections.md
This PR documents the newly added `doesntHave()` method from https://github.com/laravel/framework/pull/32873
=> Add doesntHave() to collections.md

telescope.md
A command is given to readers for adding telescope as a development package, but no version specification that is required for a successful installation on Laravel 5.8
=> Added version to telescope dev install command

configuration.md
Introduced in #6056
This is what it looked like before:
=> Fix a typo in the 7.x config retrieval example.

dusk.md
This PR simply fixes a syntax error for the step of creating a MySQL database.  The use of hyphens in the database name cannot be done without the use of single quotes around the database name.
Even though this is just an example Github Action configuration, then it would be nice for users to simply copy-paste this and not wasting time debugging the database step.
An alternative could be to change the example database name to `mydatabase` without a hyphen.
Running this example configuration on Github Actions without changing the database name would cause a somewhat confusing error like this:
``` bash
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-database character set …
```
=> Fix syntax error in Github Actions configuration

dusk.md
This PR adds a default `APP_URL=http://127.0.0.1:8000` environment to the Github Action configuration example for running dusk + a short description that Github will not serve the application on `http://localhost` which is the default `APP_URL` for a clean Laravel installation
If one creates a completely fresh Laravel installation then `APP_URL=http://localhost` which works for many use cases. If one simply copies this Github Actions configuration example provide here, one would expect that it works out of the box, but this is not the case since Github Actions does not respond on `http://localhost` (I have no source confirming this except testing).
With this PR, people will be able to simply copy paste this example and start using Dusk tests on Github actions without any further …
=> Add APP_URL to Github Action example

homestead.md
Update obsolete mail config option in "Configuring Mailhog" section of Laravel Homestead documentation.
=> Update obsolete mail config option

dusk.md
Fixes Error the error caused by the current Github Action for Dusk
```
Run php artisan dusk APP_URL:"http://127.0.0.1:8000"
Warning: TTY mode requires /dev/tty to be read/writable.
Cannot open file "APP/URL:http://127.0.0.1:8000.php".
```
=> Fixes Dusk Github action

deployment.md
Few tweaks to the example.
1. Things served by the server are supposed (according to common practices and [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard)) to reside in `/srv`.
2. In a Laravel app `index.html` or `index.htm` should not be considered for serving before `index.php`.
3. Update PHP version.
4. Remove `fastcgi_index` directive as it would never get executed (the location matches `.php` so it is already a file).
Not edited, but... would that `error_page 404 /index.php;` directive ever get executed?
=> [7.x] Improve NGINX example

billing.md, migrations.md
MySQL's utf8 encoding isn't actually utf8. It's a good idea to use utf8mb4 instead unless you specifically need MySQL's utf8 - e.g. for comparability with legacy applications or the like.
https://medium.com/@adamhooper/in-mysql-never-use-utf8-use-utf8mb4-11761243e434
=> [7.x] Change utf8 references to utf8mb4

validation.md
Added a section about using the fourth argument in `Validator::make()` as an alternative of using language files.
=> [7.x] Specifying Custom Attributes In Validator section

http-client.md
In https://github.com/laravel/framework/pull/33163 the phpdoc was updated to reflect that `$response->json()` can return arrays or scalar types. This pull request reflects that change in the client documentation as well.
=> [7.x] Update return type on json response

queues.md
Adding documentation for the Queue retryAfter method that was (re)-added for 7.x as mentioned in https://github.com/laravel/framework/pull/32370 but is not mentioned in the docs
=> [7.x] Documenting the Queue Job retryAfter method

cashier-paddle.md
I realised from this issue: https://github.com/laravel/cashier-paddle/issues/7 that the current plan parameters aren't correct. You'll always need to pass in the integer identifier of the product. I tried to make this clear by adding temp variables to still explain the plan types.
=> [7.x] Clarify Paddle plan parameter

cashier-paddle.md
Also added some more sensible Tailwind classes for the button examples.
=> [7.x] Clarify removing default Paddle button styling

filesystem.md
Added a explanation about how to specify a disk to `storeAs` method.
=> [7.x] Specifying a disk with storeAs

mail.md
It seems that the "autolink" feature of Markdown is supported now.
=> [7.x] Remove note about Markdown autolink feature not being supported

cashier-paddle.md
In the Cashier Paddle docs the not available `total()` method is referenced.
Switching to `amount()` works as expected.
=> [7.0] Cashier Paddle: Use amount() method instead of total()

http-client.md
It was not obvious to me that you could use the second array argument with `Http::get()` for query parameters. I found it buried in a GitHub issue so I thought to add it to the docs.
=> Add information about query strings

eloquent-mutators.md
When setting cast value objects, the value needs to be an instance of said value object. Otherwise the model's `$classCastCache` won't be cleared if another type is used and unexpected results will occur.
See https://github.com/laravel/framework/issues/33302
=> [7.x] Clarify cast set value

valet.md
I hope this is clear, but if a reference is needed, there's lots of discussion and detail in the PR: https://github.com/laravel/valet/pull/913
=> [7.x] Add docs for "valet proxy" commands

dusk.md
- Document `clickAtPoint` method (https://github.com/laravel/dusk/pull/788)
- Document existing `clickAtXPath` method (https://github.com/laravel/dusk/pull/723)
=> Dusk - document `clickAtPoint` and `clickAtXPath` methods

upgrade.md
This pull request adds Collision 5 to the upgrade guide.
Note that, this upgrade is required as `nunomaduro/collision:^4.0` series is not compatible with `vlucas/phpdotenv:^5.0` package ( that is required in the core of Laravel ).
=> [8.x] Adds collision 5 to upgrade guide

dusk.md
- Document the following methods available in Dusk:
- [`assertSelectMissingOption`](https://github.com/laravel/dusk/blob/6.x/src/Concerns/MakesAssertions.php#L514)
- [`assertAuthenticated`](https://github.com/laravel/dusk/blob/6.x/src/Concerns/InteractsWithAuthentication.php#L64), [`assertGuest`](https://github.com/laravel/dusk/blob/6.x/src/Concerns/InteractsWithAuthentication.php#L77) and [`assertAuthenticatedAs`](https://github.com/laravel/dusk/blob/6.x/src/Concerns/InteractsWithAuthentication.php#L93)
- [`visitRoute`](https://github.com/laravel/dusk/blob/6.x/src/Browser.php#L172) and [`refresh`](https://github.com/laravel/dusk/blob/6.x/src/Browser.php#L217)  
- [`inputValue`](https://github.com/laravel/dusk/blob/6.x/src/Concerns/MakesAssertions.php#L336)
- …
=> [7.x] Dusk - add missing documentation

frontend.md
`laravel/ui` is currently pointing to `^2.0` which is incompatible with laravel v6.x
=> Add version for laravel/ui at Using React section

dusk.md
- Document using cookies 🍪
- [`cookie`](https://github.com/laravel/dusk/blob/6.x/src/Concerns/InteractsWithCookies.php#L19), [`addCookie`](https://github.com/laravel/dusk/blob/6.x/src/Concerns/InteractsWithCookies.php#L72) and [`deleteCookie`](https://github.com/laravel/dusk/blob/6.x/src/Concerns/InteractsWithCookies.php#L95)
- Document using plain cookies including [`assertHasPlainCookie`](https://github.com/laravel/dusk/blob/6.x/src/Concerns/MakesAssertions.php#L69) and [`assertPlainCookieMissing`](https://github.com/laravel/dusk/blob/6.x/src/Concerns/MakesAssertions.php#L99)
- [`plainCookie`](https://github.com/laravel/dusk/blob/6.x/src/Concerns/InteractsWithCookies.php#L45)
=> [7.x] Dusk - add missing cookie documentation

telescope.md
Since it was previously pointed out that the default environment in the `.env.example` files will not change in the near future, I think we should at least warn users more explicitly about potential exposure of the Telescope endpoint in production environments if they set their environment incorrectly.
The previous discussions are located here:
- https://github.com/laravel/laravel/pull/5331
- https://github.com/laravel/framework/pull/33384
I hope this is somewhat of a compromise between what @lupinitylabs and I were proposing and what the position of @driesvints and the Laravel team on this issue is.
If you disagree with the exact wording, I'm open to suggestions, of course.
=> [7.x] Add Explicit Warning of Exposed Endpoint in Wrong Environment

notifications.md
To avoid confusion: https://github.com/laravel/framework/discussions/33406.
=> Clarified that the route method belongs to the notification facade

valet.md
The link in the Valet page's table of contents for "Proxying Services" didn't link to anything.
=> Fix link for Proxying Services.

migrations.md
Following the documentation I write:
```
$table->foreignId('avatar_id')->nullable()->constrained('images_table');
```
But get errors:
```
SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `users` add constraint `users_avatar_id_foreign` foreign key (`avatar_id`) references `images_table` (`id`))
```
Then I changed to:
```
$table->foreignId('avatar_id')->nullable()->constrained('images');
```
And it works.
I checked [the source code](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Database/Schema/ForeignIdColumnDefinition.php#L37) of the function. The first parameter is `$table`, no need of `_table` suffix.
=> [7.x] Fix constrained() usage

billing.md
Small update for Stripe's new prices feature. Everything in Cashier should still work as is but to prevent confusing with Stripe's new UI (all references to plans are gone in Stripe) it's best that we tweak the docs a bit to reflect this.
I've changed some of the plan identifiers in the examples from `monthly` to `price_monthly` (for example) which might be more clear to users on which identifier they should use. I can revert this if you don't want that.
=> [7.x] Update for Stripe Prices

cache.md
The [dynamodb cache driver](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Cache/DynamoDbStore.php) does not have a `tags` method, thus it currently throws `BadMethodCallException : This cache store does not support tagging.` This change clarifies that the driver doesn't support tags (although I don't see why `TagSet` wouldn't work for DynamoDb).
=> [7.x] Cache: dynamodb doesn't support tags

scheduling.md
This PR adds documentation for the scheduler's `days()` method.
=> [7.x] Document days() method

eloquent-mutators.md
As mentioned in #32972. I hit this "bug" today (the cast was added ages ago and did "work" up to the `7.12` release).
=> [7.x] Warn about cast names that equal relationship names

billing.md
This particularly example was still missing from the docs.
=> [7.x] Add multiplan example when creating subscriptions

billing.md
Clarifies how to set quantities when creating (multiplan) subscriptions or adding new plans.
=> [7.x] Clarify quantities when creating subscriptions

homestead.md
Updated Homestead udpate documentation to fit for v11.0.0 release of Laravel Homestead.
=> Homestead update documentation for v11 release

eloquent-relationships.md
The description of the example using whereDoesntHave with a nested relationship did not correctly describe the behavior of the function. Updated with correct description.
Originally brought to attention by 0xN0 via this [SO Question](https://stackoverflow.com/questions/63064693/laravel-eloquent-wheredoesnthave-documentation-confuses-me)
=> [7.x] Correcting description for whereDoesntHave

blade.md
It is like this 
```blade
@section('sidebar')
This is the master sidebar.
@show
```
should be 
```blade
@section('sidebar')
This is the master sidebar.
@endsection
```
=> fixed typo in blade.md

blade.md
PR documents the newly added `sectionMissing` blade directive. https://github.com/laravel/framework/pull/33614
=> [7.x] Add sectionMissing Blade Directive

eloquent-mutators.md
removed bit about $dateFormat being for date serialization as it is now dictated by serializeDate()
disclaimer: Not 100% about this
=> [7.x] date serialization bit removed as no longer relevant

eloquent-mutators.md
This typo was already fixed on the 7.0 branch via #6182. Not sure if it needs to be on master as well, but here it is.
=> Fix code example for custom casts

scheduling.md
This PR corrects the schedule `monthlyOnLastDay` to `lastDayOfMonth`. Attempting to use the schedule as documented results in an exception
=> Fix incorrect Artisan schedule method name

authentication.md
I have added the missing Auth events available in the API documentation at [https://laravel.com/api/7.x/Illuminate/Auth/Events.html] to the Authentication documentation
=> [7.x] Added missing Auth Events to Authentication Docs

collections.md
I discovered this awesome feature today by just trying it out because why not (I guess I read it somewhere and forgot). I was surprised to see undocumented so here it is… 🙂
=> Update collections: nested arguments in `pluck`

socialite.md
We've updated the domain where the socialite providers docs live, this updates that to match 👍
=> fix: update socialite providers URL

configuration.md
I think using the term "copied" when talking about the `.env.example` and `.env` files is more accurate. If a user _were_ to rename `.env.example` to `.env` they might accidentally commit the file deletion (since `.env` is in the `.gitignore`), ending up with no `.env.example` file in the git repo.
=> Replace "renamed" with "copied" when referring to the .env file

cashier-paddle.md
- Remove `Extending Trials` from the table of contents because the section does not exist, that method does not exist in the package.
- Remove the reference to `past-due-status` in the table of contents that does not show H4 titles.
=> Remove Extending trials and past-due-status

eloquent-relationships.md
old: the `Mechanic` can access to the `Owner` _through_ the `Car` itself
new: the `Mechanic` can access the `Owner` _through_ the `Car` itself
There are other ways to rephrase to sentence, but currently seems off to me... best of luck!
=> [7.x] Offer grammar alternative in hasOneThrough section

cashier-paddle.md
You had a missing word in the first sentence:
> Sometimes, payments for subscriptions.
I've added just a bit of explanation on when subscription payments can fail.
=> [7.x] Update wording for Cashier Paddle docs

requests.md
The type of `$headers` property is actually `int` not `string`. It's already changed in the middleware [sources](https://github.com/laravel/laravel/blob/master/app/Http/Middleware/TrustProxies.php#L20)
=> Fix type of "$headers" for trust proxies middleware

filesystem.md
This PR adds a documentation to the `storePublicly` and `storePubliclyAs` methods on the `Illuminate\Http\UploadedFile` instance.
=> [7.x] Document storePublicly and storePubliclyAs methods

eloquent.md
Very small thingy. The `use App\Scopes\AgeScope;` is not used in the example. The statement is probably there because it was copied over from another example.
=> [7.x] Remove use AgeScope that isn't used in example

upgrade.md
The 7.x upgrade guide contains a list of dependencies that should be bumped when upgrading. This PR changes that list to a bulleted list to improve readability.
=> [7.x] Change list of dependencies to a bulleted list

horizon.md, telescope.md
This PR adds the suggestion of hooking up the `telescope:publish` and `horizon:publish` commands to the app's `composer.json`'s `post-autoload-dump` list. This will make sure that assets are always kept up to date and prevents breakage of the dashboards. This was inspired by Livewire's docs: https://laravel-livewire.com/docs/installation
Added a new "Upgrading Telescope" section to be in line with other first party docs.
I've also moved "Dashboard Authorization" in the Telescope docs one level down to be in sync with Horizon's docs.
=> [7.x] Suggest asset publishing Composer hook

contributions.md
The current [list of GitHub repositories](https://laravel.com/docs/7.x/contributions#bug-reports) for Laravel projects is missing an entry for Laravel Echo.
=> [7.x] Add Laravel Echo to Contribution Guide

eloquent-mutators.md
The custom `\App\Address` castable was using the `options` key, but I'm assuming this should be something like `address` for clarity?
=> [7.x] Updated Eloquent address cast key.

controllers.md
This PR is adding docs for the recently merged `scoped` method: https://github.com/laravel/framework/pull/33752.
I basically just copy-pasted and slightly modified the content from original single route scoping docs.
=> [7.x] Add docs for scoped resource routes

notifications.md
Documents how people can pass a plain text view for a MailMessage. Will prevent confusion from: https://github.com/laravel/framework/pull/33816
=> [7.x] Document passing plain text view to MailMessage

redis.md
Documentation for https://github.com/laravel/framework/pull/33800 and https://github.com/laravel/framework/pull/33799.
The `url` configuration option was never documented when it was added, it's quite handy to know for environments like Heroku.
=> [7.x] Document Redis URL and PhpRedis `context`

envoy.md
Declaring servers on multiple lines throws a `Server [...] is not defined` error.
=> [7.x] Update envoy.md

redis.md
We can remove this now that Predis is maintained again.
=> [7.x] Undeprecate Predis

horizon.md
Because "queue combination" is not quite easy to understand.
=> [7.x] Improve Horizon 'waits' example

events.md, queues.md
This PR uses `Throwable` type instead of `Exception` in `failed()` methods in code examples.
This is because the framework [is passing](https://github.com/laravel/framework/blob/99c74a8eb040e9e030a121ffc27139c09e6fb93e/src/Illuminate/Queue/Jobs/Job.php#L192) `Throwable`, not `Exception`.
=> [7.x] Use Throwable instead of Exception in failed() methods in code examples

blade.md
We've had quite some reports in the last couple of months of people who asked why they couldn't use these. Hoping this at least makes them aware before they try it out. We can remove the `{{ $attributes }}` part at least in the Laravel 8 docs.
=> [7.x] Make using attributes and directives on components clear

queues.md
Hello @driesvints,
just a super minor fix: In the queue documentation an example still included `Exception` while `Throwable` was used otherwise.
Cheers,
Peter
=> Updating 'use Exception' to 'use Throwable' in queues

telescope.md
This PR depends on the following PR to be merged first:
laravel/laravel.com-next#128
=> [7.x] Fix non-active cloudinary link for the Telescope screenshot

telescope.md
This PR depends on the following PR to be merged first:
laravel/laravel.com-next#128
=> [6.x] Fix non-active cloudinary link for the Telescope screenshot

telescope.md
This PR depends on the following PR to be merged first:
laravel/laravel.com-next#128
=> [5.8] Fix non-active cloudinary link for the Telescope screenshot

telescope.md
This PR depends on the following PR to be merged first:
laravel/laravel.com-next#128
=> [5.7] Fix non-active cloudinary link for the Telescope screenshot

billing.md
Hey @driesvints 
I've noticed an internal jump anchor not working (missing #). It's currently treated as an internal link, which is broken. This PR fixes it.
Peter
=> Fixing internal jump anchor

collections.md
This follows-up on merging `chunkWhile()` into the 8.x branch of the framework. Related P.R: [#33980](https://github.com/laravel/framework/pull/33980#issuecomment-679851199) and [#33999](https://github.com/laravel/framework/pull/33999).
=> [8.x] Collections: document `chunkWhile()`

homestead.md
ElasticSearch won't install properly unless full version is specified, the documentation gives a false impression that it will work even if just a major version is specified.
=> [7.x] Update ElasticSearch version

testing.md
This pull request fixes the following problem...
```
$ phpunit
bash: phpunit: command not found
```
by using the relative path to the phpunit binary
```
$ vendor/bin/phpunit
PHPUnit 8.5.2 by Sebastian Bergmann and contributors.
............
```
=> [7.x] Fix path to phpunit if not composer global install

releases.md
These are the same dates as defined in the 7.x branch but were left omitted from master.
=> [8.x] Set release and fixes until dates.

releases.md
The examples for Model Factory Classes shouldn't use App\User since they're only available in Laravel 8 and the default directory for Models is App\Models in Laravel 8.
=> Use App\Models\User in the release notes examples

database-testing.md
The docs for Factory configure has a return type void, the `Illuminate\Database\Eloquent\Factories\Factory` defines the configure() function with the return type of the current object.
This PR resolves the example in the docs to include the expected return type.
=> Factory configure function return type

releases.md
Since 5.5 is now officially fully EoL we can remove these versions I think.
=> [7.x] Remove old releases

queues.md
Fixes typo in queue code example.
=> Use `Bus` facade instead of `Batch` facade in queue code example.

database-testing.md
If you are manually updating your current models, is not easy to found how to load the new trait `HasFactory` inside your models.
=> [8.x] Added HasFactory trait model example

database-testing.md
Otherwise it throws error: `Call to a member function count() on null` when creating a model with a configure method.
=> Update Factory Callbacks example code

authentication.md
The current phrasing is not clear that the user needs to use livewire or inertia and not 'livewire/inertia'
Question raised on Laracasts about this.
=> Clarify that user installs jetstream choosing inertia OR livewire

upgrade.md
Adding mention that --message option is removed in the upgrade guide per https://github.com/laravel/framework/issues/34211
=> Remove message option from artisan down command

upgrade.md
Because the `make:seeder` & `make:factory` command generate namespaced classes from their stubs, the upgrade to implement these namespaces is a required one. Therefor I think it's good that we document this in the Laravel 8 upgrade guide.
Closes https://github.com/laravel/framework/issues/34243
=> [8.x] Document new namespaced seeders and factories
