laravel/docs

- upgrade.md
When I went to update my application I got the following error in my terminal:
It makes sense considering the line above said to rename `database/seeds` to `database/seeders`, but to be honest I wasn't aware that this block was in the `composer.json` file.
This is a minor inconvenience at best and I just rewrote line 114 to make mention of it.
> [8.x] Updating docs related to composer.json changes and seeders/factories

- upgrade.md
I'd like to suggest adding the route syntax mod to the upgrade guide.  Per: https://github.com/laravel/framework/issues/34210
TL:DR part...
One of my preferred methods to upgrade and keep in alignment with the latest Laravel frameworks is to spin up a fresh copy of the latest Laravel framework, git init, then copy my old project on top of it so I can use GitLens to see all of the minute changes and align the project / clean out garbage.  I missed this one thing when I first tried upgrading (totally my fault) but it caused me a bit of pain as there didn't seem to be any documentation on it.  I've heard it mentioned elsewhere, I just think it would be a beneficial addition to the docs.
> [8.x] Adds route syntax change to Upgrade Guide

- authentication.md
> [8.x] remove unused link to Password Confirmation

- filesystem.md
In Temporary URLs section, while explaining the third additional S3 Request parameters, The current example educates the user in a quick glance how to customize the `Content-Type` response to a different MIME type.
While this illustrates the customization ability, I believe an example of `Specifying A File Name` (which is already documented for file uploads) might be more useful.
> [8.x] Temporary URLs in S3: Update request parameters example

- authorization.md
As "potential" modifies the adjective "auto-discovered", the adverb form (-ly) should be used.
> Grammar fix in authorization.md

- upgrade.md
If there are failed jobs in your database table when you run the migration without the `nullable()` default, the migration will fail to run due to duplicate empty string UUIDs (default being `''` when not explicitly defined).
This aims to provide a "safer" suggestion when adding the migration as part of an upgrade to Laravel 8.x
> Suggest using `nullable()` when adding `failed_jobs.uuid`

- database-testing.md
Reverts laravel/docs#6329 due to https://github.com/laravel/framework/pull/34298
> Revert "[8.x] Clarify that Faker is unavailable in States unless a closure is used"

- scout.md
`composer require algolia/algoliasearch-client-php:^2.2` throw "VERSION" error because laravel 8 is using "guzzlehttp/guzzle": "^7.0.1". Since Guzzlehttp removed "VERSION" constant from "GuzzleHttp\ClientInterface" from version 7, for this reason this error thrown. When we update the "algoliasearch-client-php" version from 2.2 to 2.7 OR just remove the version option then the issue solved.
`composer require algolia/algoliasearch-client-php:^2.7`
OR 
`composer require algolia/algoliasearch-client-php`
> Solved Undefined class constant 'VERSION'

- queues.md
The dispatching batches example incorrectly imports the facade as: `Illuminate\Support\Facades\Batch`, however, the correct name is `Illuminate\Support\Facades\Bus`.
This typo also causes a duplicate symbol exception with line immediately preceding it: `Illuminate\Bus\Batch`.
> Correct facade name in dispatching batches example

- upgrade.md
While currently the difference between config/mail.php in Laravel 7 and the develop branch are the same, this could change in the future and could be easily forgotten about. This could prove confusing for users trying to upgrade from 6 to 7 if it is changed to something not compatible in the future.
> Update upgrade.md to link to tag 7.x of mail config

- releases.md
- upgrade.md
I'm sending this in to revert https://github.com/laravel/docs/pull/6302. I noticed that while merging 8.x into master you almost each time have to resolve merge conflicts. It's probably not worth the hassle in the next 6 months to having to deal with that each time so let's do the Laravel 9 prep work when we get closer to its release date.
> [9.x] Revert Laravel 9 prep

- eloquent.md
The existing Eloquent model example is `Flights` being mapped to a `flights` table. Back when I was learning Eloquent by reading an earlier version of these docs, it wasn't immediately obvious to me how a `MultiWordModel` would get mapped to a `multi_word_models` table.
I didn't want to change `Flights` to a multi-word model, since it's used in a ton of other places in the docs, so I just added a quick example of `AirTrafficController` being mapped to `air_traffic_controllers`. The combination of the simple and slightly-more-complex examples should give people confidence about how Laravel maps models to table names.
> [8.x] Provide an example of multi-word model-to-table mapping

- urls.md
Clarify that the middleware for url defaults should be prioritized over the `SubstituteBindings` middleware.
See https://github.com/laravel/framework/issues/34342
> [8.x] Note about default url values and implicit binding

- helpers.md
This PR removes factory() method from the "Miscellaneous" list of helpers
> Remove factory() from helpers methods

- releases.md
There is a little mistake importing the Bus Facade
> [8.x]  Fix Bus namespace 

- queues.md
Update docs for the new queue:clear command based on https://github.com/laravel/framework/pull/34330
> [8.x] Add queue:clear

- upgrade.md
I found a typo when reading the upgrade guide.
I also think it's better to add the constant HOME and the method configureRateLimiting definition to avoid confusion.
> [8.x] Fix upgrade routing

- eloquent-relationships.md
While playing with the relationships, my IDE told me that after the "foreignKey" parameter is the "ownerKey" parameter not the "otherKey" in the "belongsTo" method for the model relationships.
> [8.x] The correct parameter is the "ownerKey" not "otherKey"

- upgrade.md
Recently Passport 7.x, 8.x & 9.x added a CookieValuePrefix as a security measure. This broke cookie token handling deep inside `auth:api`.
Fix is in Passport 9.3.2. Please merge this documentation fix so people who upgrade to LTS get informed.
Ref: https://github.com/laravel/framework/issues/34227
> [6.x] Fixes broken Passport API cookie security fix handling

- urls.md
It is not described in the documentation, that you can overload the route() url helper. If you overload it, the parameters will be added as query parameters. Added section and example for this.
This will avoid people doing something similar to this. Which you can only know if you look deep in the code.
`route('index') . '?search=laravel'`
> Url route helper overloading documentation

- validation.md
While writing up a [blog post](https://joelclermont.com/post/2020-09/understanding-dot-notation-in-laravel-validation/) on how to do this, I realized I should also PR the docs too.
Would it be useful to PR older release branches too?
> Explain how to use a literal dot in a validation rule

- events.md
The event dispatcher checks if `subscribe` method returns an array and if it does, it expects the returned array from the `subscribe` method to return an array of `events => listeners`
Reference: https://github.com/laravel/framework/blob/8.x/src/Illuminate/Events/Dispatcher.php#L176-L182
> [8.x] Updated code block example on using event subscriber

- queues.md
Many of us simply copy paste the example Supervisor config mentioned in the Laravel docs. I think we should add the `max-time` option in the example Supervisor config as it's a good practice to avoid memory leaks.
> [8.x] Add max-time to example Supervisor config

- billing.md
This PR attempts to explain how Cashier works with multiple subscriptions under the same "name" and that it only checks the lastly added subscription.
See https://github.com/laravel/cashier-stripe/issues/994
> [8.x] Explain lastly added subscription

- seeding.md
composer dump-autoload is not required now.
[psr-4 in composer.json](https://github.com/laravel/laravel/blob/v8.0.3/composer.json#L39)
> database/seeder is part of psr-4 now

- urls.md
Adding a backslash after `App\Http\Middleware` in `\App\Http\MiddlewareSetDefaultLocaleForUrls::class` to update `SetDefaultLocaleForUrls` middleware path.
> Update 'SetDefaultLocaleForUrls' Path

- upgrade.md
Hi,
During the upgrade process, we've followed the guide, however we removed the references to the `allOnQueue()` and `allOnConnection()` from our code, but it that stopped the chain to process the next joib in the chain. 
Using these methods with the helper `dispatch()` returned the previous - correct - behaviour.
I don't know if this is going to be the way in the future, but just suggesting a note in the docs to help other people and avoid problems.
Thanks!
> [8.x] Improve allOnQueue() / allOnConnection() upgrade notes

- horizon.md
- queues.md
Document the `horizon:forget` command based on https://github.com/laravel/horizon/pull/896
> [8.x] Document horizon:forget

- billing.md
- cashier-paddle.md
Documents https://github.com/laravel/cashier-paddle/pull/69 & https://github.com/laravel/cashier-stripe/pull/1000
> [8.x] Document trialEndsAt

- filesystem.md
This PR documents the `Storage::path()` method and explains how the path is returned whether `local` or `s3` driver is used. I assumed this should be documented, as there are some components that require absolute path when accessing files (attaching files in notifications), and I feel `storage_path('app/'.$path)` is a bit clumsy.
> [8.x] Document path() method

- eloquent-relationships.md
After researching https://github.com/laravel/framework/issues/34548 I've come to the conclusion that pivot tables always require both a `created_at` and `updated_at` column because of their behavior of inheriting parent timestamp column names. This isn't immediately clear because for regular Eloquent models you can disable them by setting `static::CREATED_AT` and/or `static::UPDATED_AT` to `null`. So it's best to clarify the specific behavior here.
It could also be that we just don't support setting these constants to `null` in the first place and that both a `created_at` and `updated_at` column are always required? If so, then I think we should explicitly state that somewhere in the docs.
> [8.x] Clarify required timestamp columns for pivot tables

- helpers.md
I find the `optional()` example when a Closure is provided as a second argument quite confusing. The callback is only executed if the user is not `null`. For that reason, returning a `DummyUser` seems silly. Returning a DummyUser would make sense if `optional`'s callback was used to determine the fallback value. But the fallback value is always `null` when a Closure is provided.
A more realistic example is:
```php
return optional(User::find($id), function ($user) {
return $user->name
});
```
which is equivalent to the previous example:
```php
return optional(User::find($id))->name;
```
and makes a lot more sense from a practical viewpoint.
> [8.x] Update optional() example

- upgrade.md
As decodeResponseJson does not requires paramaters anymore, we should instead, use `json`
> [8.x] decodeResponseJson is a breaking change

- telescope.md
Documents two missing watchers in the Telescope docs: Batch Watcher and View Watcher
> [8.x] Document missing Telescope Batch Watcher and View Watcher

- releases.md
We've been releasing early March and early September since more than a year now so these changes reflect the new situation better.
> [8.x] Update release months

- artisan.md
Submitting this one again since something seems to have gone wrong in the original PR (#6432). I am not actually removing any lines from the file, even though the GitHub diff view makes it appear that way.
If you look at the rich diff view and the line count you can see that this diff only adds content.
Anyways: this diff documents the previously undocumented events that Artisan dispatches when a command is run.
> [8.x] Document Artisan Events - take 2

- redis.md
Changed "Reids" to "Redis". Just a little typo.
> [8.x] Fixed typo in redis.md

- dusk.md
- facades.md
I was updating a project to laravel 8 and I noticed some of the docs pages had references to the old factory syntax.
> [8.x] Updated a few factory declarations to the new syntax

- contributions.md
Looks like this filter is unnecessary
> [8.x] Removed -repo GitHub search filter from the  Contribution Guide -> Bug Reports section

- requests.md
https://github.com/laravel/framework/pull/33829
> [8.x] Added whenHas() and whenFilled() to Request docs

- collections.md
https://github.com/laravel/framework/pull/34600
> [8.x] Added pipeInto() to Collection docs

- lifecycle.md
* The word "script" in this sentence is out of place because the sentence is referring to `bootstrap/app.php` as a distinct thing,
but it would be alright to say "the `bootstrap/app.php` script".
* Removing the word "script" seems like the better choice because now it matches the phrasing of the next paragraph that says,
"let's just focus on the HTTP kernel, which is located in `app/Http/Kernel.php`"
> Fix very small typo

- migrations.md
For one reason or another you might have tables in the database that you don't want to be managed by Laravel migrations even when developing. In those cases `migrate:fresh` should not be used.
Adding a warning  as suggested in [this comment](https://github.com/laravel/framework/issues/27851#issuecomment-693351362).
> [8.x] Add warning to `migrate:fresh`

- http-client.md
Explanation for https://github.com/laravel/framework/issues/34505 & https://github.com/laravel/framework/pull/34666
> [8.x] Explain middleware not ran when faking HTTP client

- releases.md
Two changes here:
- We decided recently to always provide at least one month of support for a previous major version series after a new one was released to give people some time to transition. Which means we provide bug fixes up to 7 months after a new major release was done.
- In regard to the above I've extended the bug fixing period for Laravel 6 LTS by one month so people have time to upgrade to the new Laravel 10 LTS version.
> [8.x] Update support policy

- passport.md
In 8.x the default User model have the `HasFactory` trait by default. 
It should be reflected in the example given by the documentation in the same way as the `Notifiable` one.
> Use the default traits of User in the example

- upgrade.md
I ran exactly into that problem while updating from 5.x to 8
Can you please label the the pull request ‘hacktoberfest-accepted’
https://hacktoberfest.digitalocean.com/hacktoberfest-update
> [5.8] update Prefer String And Array Classes Over Helpers

- upgrade.md
I ran exactly into that problem while updating from 5.x to 8
Can you please label the the pull request ‘hacktoberfest-accepted’
https://hacktoberfest.digitalocean.com/hacktoberfest-update
> [6.x] update Prefer String And Array Classes Over Helpers

- requests.md
* The word "the" is missing before "entire request payload". Even though so many noun phrases in this sentence are already preceded with "the", the only noun phrase where "the" seems optional is "values". Anywhere else, it seems quite necessary.
> [8.x] Add missing article

- eloquent.md
- queries.md
Documents the new `upsert` method on the Eloquent and base query builders based on https://github.com/laravel/framework/pull/34698
> [8.x] Document the new upsert method

- authentication.md
- authorization.md
- blade.md
- contracts.md
- eloquent.md
- filesystem.md
- helpers.md
- notifications.md
- requests.md
- urls.md
Thank you for accepting my pull requests. This one is a bit more substantial, but very important.
A number of pages use the indefinite article "a" before a word with a vowel sound instead of "an". There's no absolute authority on English, but Grammarly is an excellent guide, and [they agree](https://www.grammarly.com/blog/articles/) that it would be best to fix this so that just like if one were reading this text out loud, they would say "an `Illuminate\Contracts\Auth\Authenticatable` implementation", or "an `App\Models\User` instance".
> [8.x] Indefinite articles before vowels

- validation.md
* As our [friends at Grammarly remind us](https://www.grammarly.com/blog/grammar-basics-what-is-subject-verb-agreement/), subjects and verbs in phrases should agree in number. There are a few sentences where    the subject is omitted and not all too strongly implied so that the sentences sound a little off.
> [8.x] Subject-verb agreement in validation.md

- artisan.md
This adds `newLine()` to the Artisan Console docs (from [this PR](https://github.com/laravel/framework/pull/34754))
> [8.x] Add `newLine()` method to Artisan Console docs

- eloquent-mutators.md
`\Illuminate\Contracts\Database\Eloquent\Castable` interface defines the `castUsing` method with an `$arguments` parameter of type array.
> Fix castUsing signature to respect the Castable inferface

- blade.md
Changed "be evaluate" to "be evaluated" and addressed some indefinite articles. Note that `x-slot` would be pronounced "ex-slot"
> [8.x] Small typos in blade.md

- authentication.md
A couple missing definite articles and a missing conjunction. Most are self-explanatory, but in the sentence "For example, we may verify that user is marked as 'active'", it is referring to a user in general as opposed to a particular thing called "user", so the word "the" should be before "user".
> [8.x] Small typos in authentication.md

- deployment.md
I realized that I had misunderstood the current docs for quite a while. I had interpreted the highlighted section below such that `env()` always returns null after running `config:cache`, but this only applies to variables in `.env`, not in the server runtime.
I realize that a common convention is to map runtime environment variables to config values, but I have a use case where that is not possible. Our build process generates a docker image with the `config:cache` already run, before any runtime variables exists.
> [8.x] Clarify when env() returns null after caching

- database-testing.md
Replaced `$users` with `$videos` to better reflect what the factory returns
> [8.x] Fix variable name for factory return

- redis.md
Without the "it", the clause sounds incomplete.
> [8.x] Proofread redis

- upgrade.md
The instruction to add the new `failed_jobs.exception` column is missing from the 5.2 to 5.3 docs. Please see [this 5.3 source code](https://github.com/laravel/framework/blob/v5.3.31/src/Illuminate/Queue/Failed/DatabaseFailedJobProvider.php#L61-L63) illustrating the insertion into the new `exception` column. 
This instruction already exists in the 5.3 to 5.4 docs, but I would suggest leaving it there for folks who are already on 5.3.
> 5.3 Upgrade: Add missing instruction to add new `failed_jobs.exception` column.

- eloquent.md
- queries.md
This PR clarifies how indexes need to be setup to properly use the `uniqueBy` constraints in upsert.
Closes https://github.com/laravel/framework/issues/34850
> [8.x] Clarify upsert index requirement

- sanctum.md
This updates the Sanctum middleware to show the full namespace to be consistent with other middleware in the Kernel and documentation.
> [8.x] Use full Sanctum middleware namespace for consistency

- passwords.md
When building a SPA, I wanted to change the reset password link for the default `ResetPassword` notification.
I didn't find any documentation on this so why not creating one for future users in this case :smile:
> [8.x] Add new section to customize the password reset link

- http-tests.md
Added a semicolon after `assertJsonPath()` method because seems necessary.
> [8.x] Added a semicolon after assertJsonPath method

- queues.md
Adds a note to say that `WithoutOverlapping` middleware requires a cache driver that supports locks. Ref: https://github.com/laravel/docs/pull/6505#issuecomment-715374207
> [8.x] Add cache driver requirement note to WithoutOverlapping middleware

- validation.md
See: 
- https://github.com/laravel/framework/pull/34788 (add rule)
- https://github.com/laravel/framework/pull/34858 (add replacer)
- https://github.com/laravel/laravel/pull/5449 (add translation)
> [8.x] Add multiple_of validation rule

- validation.md
Reverts laravel/docs#6526
Can be reverted now https://github.com/laravel/framework/pull/34971 is merged.
> [8.x] Revert "[8.x] Update validation.md"

- validation.md
>  This can be useful when validating a number input that utilises the `step` attribute.
This would lead users to expect consistency with how the attribute works in HTML. However, HTML's step works relative to `min`, while this does not. For example, if `min=10 step=3` HTML would allow 10, 13, 16, ... while Laravel's validator with `'min:10', 'multiple_of:3'` would allow 12, 15, 18, ...
13 is not a multiple of 3, so it would also be confusing if the behaviour of `multiple_of:3` was changed to accept that, unless it gets renamed to `step` 🤔
> [8.x] Remove reference to HTML's step

- upgrade.md
The example documentation did not indicate that the parameter is optional.
If we use this example, then we get the error:
```php
Missing required parameters for [Route: profile] [URI: profile/{location}].
Missing required parameters for [Route: ] [URI: profile/{id}].
```
> [6.x] Update upgrade.md

- upgrade.md
When adding the UUID during upgrade, existing failed jobs will be left as null and will cause issues. So I added a small snippet you can run in Tinker to generate UUID for existing rows.
> [8.x] Added snippet on how to generate UUID for existing failed jobs

- testing.md
`php artisan test --group=feature` vs `php artisan test --testsuite=Feature` (fresh Laravel install) :
> [8.x] Fix unit testing by group example command

- eloquent-resources.md
Regarding [Resource Collections](https://laravel.com/docs/8.x/eloquent-resources#generating-resource-collections). Example snippets are all singular except for the flag example. Maybe with a specific reason (in that case, sorry), but otherwise this might be more consistent.
> [8.x] Change plural to singular for resource collection.

- contributions.md
- structure.md
The change to the contributions docs is obvious since the skeleton doesn't has a sass directory anymore. The one to the resources directories is similar. I removed LESS and SASS from being mentioned to group them as "CSS" which is more conform the current directory name.
I left all other occurrences of SASS in the docs because the parts where they were mentioned still warranted their context.
> [8.x] Generalize CSS occurrences 

- routing.md
When trying to Explicitly Bind a model you need to make sure you add a "backslash" before class.
"App\Models\model::class" -> "\App\Models\model::class"
Throws error "App\Providers\App\Models\model".
> [8.x] Need Slash before class otherwise throws error

- routing.md
As per #6545, 
> We don't document array usage anymore. Only method usage.
Removed reference to array format to reduce confusion.
> [8.x] Remove reference to route group array usage

- collections.md
I guess method `all()` should be preferred to `toArray()` in most cases, as the intent is to expose the underlying array without "arrayifing" everything.
> Collections: favor all() over toArray()

- localization.md
After an internal Slack discussion it seemed best to clarify this gotcha in the docs.
> [8.x] Clarify language filename conflicts

- http-client.md
The Docs page for Http-Client uses test.com instead of example.com
Test.com is a real registered website that someone owns and potentially does not desire unwanted traffic.
[Example.com is a reserved Top and Second Level Domain ](https://tools.ietf.org/html/rfc2606) designed for exactly this purpose, eg as an example domain.
This pull request updates all occurrences of test.com to example.com.  
I searched the entire documentation but this seems to be the only page this is relevant to.
> [8.x] Change all use of test.com to example.com 

- sanctum.md
Fix missing Token Class usage on overriding section, use `PersonalAccessToken` directly when use custom `PersonalAccessToken` model on boot
> [8.x] Fix missing Token Class

- mail.md
Previewing mailables with inline attachments will lead to broken images as they use CID embedded images behind the scenes. Viewing these images is only possible in an actual email.
See https://github.com/laravel/framework/issues/35169
> [8.x] Add note about inline attachments and previewing

- migrations.md
This PR documents the `useCurrentOnUpdate()` modifier introduced by https://github.com/laravel/framework/pull/35143
> [8.x] Add description for the `useCurrentOnUpdate()` modifier

- routing.md
when i use whereNumeric method appears with me **Method Illuminate\Routing\Route::whereNumeric does not exist**.
it should be whereNumber not whereNumeric
> [8.x] Update routing.md

- middleware.md
This PR updates the middleware doc to reflect the 8.x default `$middlewareGroups` .
> [8.x] Update middleware doc

- database-testing.md
Laravel uses FakerPHP/Faker starting from Version 8. This update is to reflect the changes in the documentation.
> Update Faker repository link to FakerPHP/Faker

- scheduling.md
`->yearlyOn(6, 1, '17:00')` creates cron expression `+expression: "0 17 1 6 *",` which corresponds to 0 minute, 17 hour, day 1, month 6, any year.
From the example in the docs previously it was not possible to know the order of the parameters.
> remove ambiguity from yearlyOn() method

- broadcasting.md
The default user channel name is 'App.Models.User.{id}' in 8.x
> Update channel name

- redis.md
This appears to be a supported option when connecting to Redis using phpredis client
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Redis/Connectors/PhpRedisConnector.php#L124
See `retry_interval`
https://github.com/phpredis/phpredis#connect-open
This is in `ms` and I THINK will happen a max of 10 times, awaiting confirmation on this one - https://github.com/phpredis/phpredis/issues/1883
> [8.x] Add retry_interval option for phpredis

- cache.md
Based on https://github.com/laravel/framework/pull/35139
> [8.x] Add file locks to docs

- broadcasting.md
Hello,
The socket.io-client 3.x version package doesn't work with current version of Laravel Echo (1.9). This problem can avoid with install version 2.x. 
Daniel
> [8.x] Update Socket.IO section.

- database.md
Documentation for https://github.com/laravel/framework/pull/35304
> [8.x] Document the Artisan db command

- blade.md
Helps readers know that the @json directive encodes unsafe entities, and that they don't have to include these flags manually.
> Explained the default flags used by @json

- homestead.md
Updated Ubuntu versions and added PHP 8 to the stack.
> [8.x] Updated Homestead Docs for PHP 8 & Ubuntu

- notifications.md
This confused me for a couple hours today. I was only creating one Notification, but was seeing it show up in my queue multiple times.  After some digging and testing, it became more clear that a queue entry is made for every combination of recipients and channels. Documenting it so people understand what's happening.
> [8.x] Add clarifying note about queued Notifications

- homestead.md
This PR is the result of the following discussion: https://github.com/laravel/homestead/pull/1555
> [8.x] Update wording of Elasticsearch versions in Homestead docs

- collections.md
https://github.com/laravel/framework/pull/35295
> [8.x] Document `splitIn()`

- collections.md
> [8.x] Fix typo: split -> splitIn

- database.md
This PR is a response to the following issue: https://github.com/laravel/framework/issues/35380
After careful evaluation I decided that it'd be best to simply document this behavior than to work around it in the framework. The commit for `unprepared` can be removed if you don't think it's wise to document that method. But the behavior of implicit commits in regard to transactions should best be documented I believe. Afaik it's only MySQL/MariaDB related so we could note that as well perhaps. I'll leave it up to you to decide on that.
> [8.x] Document unprepared statements and implicit commits

- container.md
When reading this documentation from top-to-bottom the term `tag[ging]`is used and examples are given of using tags _before_ the docs on tagging are presented.  
This PR adds links to the anchors for tagging only to those places where tagging is used before the documentation has been presented.  
Notes on this approach:  one might ask about an 'all or nothing' approach such as `->make` is used often before the actual docs on `make` but it is not referenced by name and only through code which makes linking to the docs unwieldy.  And, should all references to other methods of the container also be cross referenced?  In my reading I did not find any other use of terminology preceding its definition.
> Where the term tag[ing] is used before the docs section on tagging a link to the tagging anchor is added

- contributions.md
Reverts laravel/docs#6607
The previous link is working as expected. The new one only shows the issues on framework repository while the old link shows bugs across the entire organisation as intended.
> [8.x] Revert "Update contributions.md"

- queues.md
Hi, in the rate limiter section I noticed that the example didn't point the namespace of the Limit class. Here I'm adding so newcomers get it.
> [8.x] Add missing use in rate limiter example

- database.md
- installation.md
After struggling with this today, I wanted to see if this had a place in the documentation.
Out of the box, Laravel will use `pdo_odbc` to connect to a MSSQL database and this will work...until you start running into really annoying to troubleshoot bugs. For example, if you use `pdo_odbc`, datetime fields will appear in the database as `Y-m-d H:i:s.v`, but when you attempt to access those dates through the driver, it drops the milliseconds, which Carbon is expecting based on the Laravel SQL Server Grammar, so you get a cryptic "Data Missing" error.
Once you install the `sqlsrv` and `pdo_sqlsrv` drivers, the behavior works as expected. There is another bug regarding how UUIDs are returned from the database, you need a special PDO directive to make them work if you're not using these …
> [8.x] Add MSSQL driver notes to System Requirements section

- session.md
The example schema for the `sessions` table (when using the `database` session driver) does not match the one that is generated by the artisan command `php artisan session:table`. This PR aligns these two.
The differences are:
* The `id` column is set as primary key instead of (only) unique.
* Indices are added to the `user_id` and `last_activity` columns.
I noticed this since I copied the documentation schema and had some concerns about the `gc()` function without the index on `last_activity`.
> [8.x] Align sessions table schema with generated schema

- collections.md
Introduced in https://github.com/laravel/framework/pull/34444.
> [8.x] Document takeUntilTimeout

- blade.md
- broadcasting.md
- configuration.md
- requests.md
- validation.md
This PR fixes anchors in the following files:
- `blade.md`
- `broadcasting.md`
- `configuration.md`
Here the whole section _Hiding Environment Variables From Debug Pages_ is missing, so I removed the link. 
You might want to restore the section instead.
- `requests.md`
- `validation.md`
I used [a simple  script](https://gist.github.com/andreich1980/a58deabb237e13c162b581530d262b93) to find broken anchors
> [8.x] Fixing anchors

- homestead.md
Updates from laravel/docs/pull/6631
> [8.x] Vagrant uses Providers. Homestead should require Virtualbox 6.1.x

- dusk.md
1. `assertSelectHasOptions`
1. `assertSelectMissingOptions`
1. `assertSelectHasOption`
1. `assertSelectMissingOption`
---
Previously:
1. `assertSelectHasOptions`
1. `assertSelectMissingOption`
1. `assertSelectMissingOptions`
1. `assertSelectHasOption`
> Dusk - correct order of assertions

- http-tests.md
Nothing special, just a little typo fix  `assertJsonStruture` -> `assertJsonStructure`
> [8.x] fix typo in http-tests.md

- sail.md
The existing docs don't mention the mail host needed, and it isn't super clear, after hours of troubleshooting someone suggested I use "mailhog" as the host, which worked.  This PR updates the doc to make it a bit clearer.
> [8.x] Sail docs updated with more clear mailhog info

- authentication.md
The section detailing logging out was duplicated. This removes the first copy and leaves the main section.
> [8.x] Removes Duplicate Section in authentication.md

- queues.md
Added docs for the new prune batches command added in:
https://github.com/laravel/framework/pull/35694
Again I kept it very similar to the telescope docs for the prune command available in that package.
> Add docs for new prune batches command

- console-tests.md
- database-testing.md
- dusk.md
- http-tests.md
- testing.md
As I understand since the big documentation overhaul test case naming convention has changed to `snake_case`, some tests cases were still following `camelCase` convention.
> [8.x] Update few test cases to follow snake_case naming convention

- blade.md
Small addition to the docs to add the existing `get` and `has` methods of the component attributes bag.
Additional: https://github.com/laravel/framework/pull/35562
> [8.x] Add attribute checking and getting docs.

- mail.md
This PR adds to the docs an explanation of how to set a specific Postmark `message stream`, which is possible since my merged PR on the framework: https://github.com/laravel/framework/pull/35755
> [8.x] Explain how to set a specific Postmark message stream

- documentation.md
Super small suggestion to add a link under packages section to info about Breeze.  I realize this is a second entry (similar to how the Dusk docs are wired) but I feel like this will be a common place people look for this.  I know I just did.  =)
> Adds auxiliary link to Breeze in packages section

- eloquent.md
Docuement that `saved` is always dispatched, even if nothing has changed.
> [8.x] Document the weird semantics of the `saved` event

- cache.md
Change "it can retrieved quickly" to "it can be retrieved quickly".
> [8.x] Add missing word 'be'.

- homestead.md
Php8.0 was missing from the PHP Versions section. 
I also added a quick note on how to fix `command not found` when running `php80` , which a lot of people will experience as many upgrade to php8.0
> [8.x] Added php8.0 to PHP versions section

- starter-kits.md
I wasn't sure if this should be updated to use `2.x` with the existing link, or just point to `jetstream.laravel.com` which automatically redirects to the latest. 🤔
> docs: update link to Jetstream docs

- collections.md
I had to read these a couple times through, but these descriptions are at worst wrong, and at best very confusing, so trying to fix them.
The `whereNull` returns a new collection whose values of the given field **are** `null`, so it is removing ones that **are not** `null`.
The `whereNotNull` returns a new collection whose values of the given field **are not** `null`, so it is removing ones that **are** `null`.
> [8.x] Fix wording of `whereNull` and `whereNotNull` methods

- upgrade.md
The anchor link `/database-testing#creating-factories` does not exist.
> Non-existent link

- container.md
In Laravel 7.x Service Container docs, 'HelpSpot\API' was used as a sample class.
In Laravel 8.x Service Container docs, the sample class was switched to 'Transistor'.
The old sample class 'HelpSpot\API' is accidentally still used in two places. In four places, the old variable name `$api` is used aswell, this pull request will fix mentioned typos.
> [8.x] Typo - 'HelpSpot\API' to 'Transistor'

- seeding.md
Noticed that `times()` and `count()` are doing the same thing, with `times()` just calling the `count()`:
```
* @param  int  $count
* @return static
*/
public static function times(int $count)
{
return static::new()->count($count);
}
```
So to avoid confusion, I suggest sticking to `count()` in all documentation.
> Using Factories: replace times() with count() for consistency

- validation.md
It isn't clear from the docs what the `numeric` validation rule actually does, in my opinion.
This PR aims to clarify that.
> Clarify what the numeric validation does

- eloquent-resources.md
I would like to propose to change `User` in the Generating Resources section example to `UserResource` to avoid conflict with the `User` model namespace when importing the `User` resource in the `UserController`.
> [8.x] Change User to UserResource

- mocking.md
Ref: https://github.com/laravel/framework/pull/35835
> [8.x] Add Event::assertNothingDispatched to mocking.md

- collections.md
Adds documentation for the merged pull request: https://github.com/laravel/framework/pull/35839
> [8.x] add reduceWithKeys to collections available methods

- session.md
- Document [`Session::now($key, $value)`](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Session/Store.php#L363-L375)
- Solved a recent problem whereby data was persisting over two requests: https://stackoverflow.com/questions/14517809/laravels-flash-session-stores-data-twice?#answer-49626423
- There also seem to be other SO questions querying the difference between `flash()` and `now()`: https://stackoverflow.com/questions/58593433/laravel-difference-between-session-flash-and-session-now
> Document `Session::now($key, $value)`

- session.md
- Document `Session::invalidate()`
> Document `Session::invalidate()`

- database-testing.md
> [8.x] Added documentation for a specific seeder in tests

- collections.md
- mocking.md
This updates Collection docs to reflect latest changes in `reduce`
As discussed here: https://github.com/laravel/framework/pull/35839
The new pull request to framework here: https://github.com/laravel/framework/pull/35878
Previous change to the docs that was merged and needs to be updated because the underlying changed was reverted here: https://github.com/laravel/docs/pull/6740
> [8.x] Update the docs to reflect the merge of reduceWithKeys into the existing reduce method

- eloquent.md
I think this `$fillable` example is missing a `protected` declaration.
> Adds missing protected declaration on fillable example

- collections.md
locale argument is out of order. but in PHP 8 you can set name to argument for example:
> [8.x] Add replace argument to method get in  Facade Lang

- authentication.md
I see quite a lot of people asking for "multi auth" or "multi guard auth" while referring to roles/permissions like admins/teachers/students, see Laracasts thread: https://laracasts.com/discuss/channels/laravel/possible-to-make-multiple-guard-with-fortify-without-jetstream 
To avoid this confusion, I suggest adding this paragraph (which I will refer to when I get similar questions in the future), but not sure about the tone and structure of sentences, feel free to make changes.
> [8.x] Suggestion for Auth to avoid confusing guards and gates/roles

- mocking.md
PR adds missing documentation of [`assertNothingQueued()`](https://github.com/laravel/framework/blob/0d601f598a2434b8b126c06af75a0f089b10a102/src/Illuminate/Support/Testing/Fakes/MailFake.php#L174).
> [8.x] Add assertNothingQueued to Mail Mocking

- migrations.md
The current implementation of DBAL v2 on Laravel 8 is semi-broken and I don't see a clean way to fix this properly. The DBAL v3 implementation should work however.
> [8.x] Add note about SqlServer and DBAL v3

- eloquent.md
I didn't realise this wasn't documented yet so it's probably best that we add a note to the docs here.
> [8.x] Document composite keys unavailability for Eloquent models

- migrations.md
I just learned that I don't have to suggest `--create=flights` if I stick to the naming conventions.
And I've seen a lot of people who don't know that they are not obliged to use snake case for the migration name.
> [8.x] Elaborate on migration generator features

- blade.md
This PR adds documentation for [escaped Blade attributes](https://github.com/laravel/framework/pull/36042).
> [8.x] Escaping Blade Attributes for JavaScript Frameworks

- releases.md
So the feature is called "named arguments" for the arguments you pass to a function. "parameter" is still the correct term for describing the function parameters themselves (which have a name that can be altered).
> [8.x] Use correct terminology

- releases.md
I've updated the docs with the new release schedule.
source: https://blog.laravel.com/updates-to-laravels-versioning-policy
> [8.x] Update docs with the new release schedule

- testing.md
This adds a small section to the docs to make it clear that the original location of the `CreatesApplication` should not be changed as some functionality depends on it.
See https://github.com/laravel/framework/issues/36053
> [8.x] The CreatesApplication trait

- errors.md
This fixes the incorrect return type for report method on exceptions. A return type can never be `void` in combination with something else. Since the report method allows to either return nothing (`null`) or `false` we should properly indicate those types.
See https://github.com/laravel/framework/issues/36109
> [8.x] Update return type for report method

- helpers.md
Documents https://github.com/laravel/framework/pull/36071
Credit to @amberlampsio
---
**Note:**
- My code examples don't include the trailing `\n` the converter also appends as shown [in the PR tests](https://github.com/laravel/framework/pull/36071/files#diff-be47dbd336aece128f999b4c2d8b4fc7ee809a1d1e0ddd178547542201d4e897R517)
- Might be worth linking to the [converter docs](https://github.com/thephpleague/commonmark#-installation--basic-usage) so developers know all the options available to them
- Might be worth defining what [GitHub Flavored Markdown is versus normal markdown](https://github.com/thephpleague/commonmark#-github-flavored-markdown)
> [8.x] Document `Str::markdown()` and `Str::of()->markdown()`

- billing.md
Documentation for https://github.com/laravel/cashier-stripe/pull/1007
In draft until above PR was merged.
> [8.x] Stripe Checkout docs for Cashier

- homestead.md
> [8.x] Updated Homestead for the v12.0.0 release

- notifications.md
I took a very very deep dive into the behavior of defining recipients when using Mailables instead of MailMessages in mail notifications and came to the following conclusion: when using Mailables the recipients are always defined explicitly by using the `->to` method on the mailable based on the notifiable.
This means that in the case for regular notifiable models the `routeNotificationForMail` method (or default of `->email` for that matter) and for the case of on-demand notifications the recipient defined by the notifiable needs to be explicitly passed to the mailable.
I was genuinely confused myself at first after reviewing the following issue: https://github.com/laravel/framework/issues/36115. I believe adding this extra part to the docs here can clarify a lot for our users.
> [8.x] Clarify defining recipients when using Mailables in mail notifications

- requests.md
Added **retrieve**
The sentence should be: **For convenience, the `bearerToken` may be used to retrieve a bearer...**
See [here](https://laravel.com/docs/8.x/requests#request-headers)
> Fix grammar in requests.md

- testing.md
This pull request adds a note concerning the missing PHPUnit options when running tests in parallel.
> [8.x] Adds note about missing PHPUnit options when running tests in parallel

- database.md
Bumps the minimum version for database versions which aren't supported anymore.
> [8.x] Drop support for old database versions

- blade.md
Make it more explicit that these properties/methods are reserved. Also documents the `$except` property.
> [8.x] Document reserved keywords for components

- valet.md
I spent quite a bit of time figuring out how to get subdomains to work with Valet but turns out Valet automatically allows you to use any wildcard subdomain with the base registered site 😅 
@mattstauffer @drbyte Hope I got this correct?
> [8.x] Document wildcard subdomains with Valet

- artisan.md
Currently, the documentation does not specify how to combine the Artisan Console's optional arguments with the argument arrays. This adds a simple explanation and example based on the current implementation that works in the framework.
> Document optional console argument arrays

- cashier-paddle.md
Using the method returns the builder instead of the collection of receipts and thus makes the example invalid.
> [8.x] Fix receipts typo

- envoy.md
I added descriptions about the optional third parameter to overwrite the default message.
> [8.x] Add descriptions for Envoy slack directive.

- validation.md
The integer validation rule still causes confusion sometimes. I've tried to reword the note on it to make it more clear what the rule exactly does and guide people to the `numeric` rule which is probably what they need in combination with this.
See https://github.com/laravel/framework/issues/36321
> [8.x] Clarify integer rule

- eloquent.md
Eloquent doc page has comparing section where it introduces the `is` method. I see `isNot` method is missing. I discover `isNot` method from the Laravel API documentation. I use it quite a lot and thought it should be in the documentation. 
Note: It is my first PR, pardon any mistake. I'm open to redoing/modifications.
> Add isNot method in eloquent documentation comparing section

- sail.md
Suggest using the `sail` command is more consistent in this document.
> [8.x] Use sail command instead

- dusk.md
Added documentation for [new dusk function](https://github.com/laravel/dusk/pull/879)
Does this need some kind of note for which version of dusk it will be added in?
> [8.x] Add documentation for new dusk function: `assertNotPresent`

- http-client.md
This adds reference to the new HTTP Client `collect` method added in `8.29.0`
I've kept this quite light, as it seems documentation on the `json` method is pretty lightweight too. I'm happy to write a more in depth paragraph/code examples on both `json` and `collect` if that would be useful?
> [8.x] Adds the `collect` method to the HTTP Client documentation.

- controllers.md
Here we have an unused parameter in the comment section which IDEs will get an error.
> Remove unused parameter

- sanctum.md
Imports the personal access token class from Sanctum rather than Passport
> [8.x] Fix namespace in Sanctum docs

- fortify.md
Hi,
As I've been using this package, I noticed that when I got to the part about displaying the recovery codes, there was no information about how it was returned and what actions had to be taken to view them correctly.
I got my answer via a YouTube channel as I was not aware of the `decrypt()` helper method.
I figured this could be useful information to someone else who, like me, got stuck at it.
I don't know if using the `decrypt()` helper method is the most elegant way to achieve this, but it seems the simplist.
Thanks,
Chris
> [8.x] Fortify - Mention how to decrypt the recovery codes

- validation.md
My impression from reading the docs was that the specified field needs to be present (in the data array), with its emptiness being irrelevant, in order to force the field under validation to be required.
However, as an example, `required_with` makes the field under validation required only when the specified field is present and not empty.
Adding that the specified field must be not empty makes it more clear, I hope.
> Clarify `required_with*` validation rules

- configuration.md
The current note says that all calls to `env` would return true, but in fact it can contain the variables from the environment.
```sh
$ php artisan tinker
Psy Shell v0.10.5 (PHP 8.0.2 — cli) by Justin Hileman
>>> env('DB_HOST')
=> "127.0.0.1"
>>> ^D
Exit:  Ctrl+D
$ php artisan config:cache
Configuration cache cleared!
Configuration cached successfully!
$ php artisan tinker
Psy Shell v0.10.5 (PHP 8.0.2 — cli) by Justin Hileman
>>> env('DB_HOST')
=> null
>>> ^D
Exit:  Ctrl+D
$ export DB_HOST="127.0.0.1"
$ php artisan tinker
Psy Shell v0.10.5 (PHP 8.0.2 — cli) by Justin Hileman
>>> env('DB_HOST')
=> "127.0.0.1"
```
The other (in my opinion more problematic) issue is that it's not entirely clear that the config is not merely combined, but the functions are also executed and stored. And thus …
> Clarify `env` behaviour

- facades.md
In this example, `Route` is a facade just like `Cache`, so I think it would make sense to add the `use Illuminate\Support\Facades\Route;` statement here.
> [8.x] Add Route facade alias

- http-tests.md
`assertJsonPath` parameters was incorrect.
> [8.x] Fix assertJsonPath incorrect method signature

- broadcasting.md
The laravel/framework now supports the latest version of the pusher library. https://github.com/laravel/framework/commit/3404185fbe36139dfbe6d0d9595811b41ee53068
> Update pusher/pusher-php-server dependency to ^5.0

- contributions.md
All the github links to laravel projects are included except for laravel Sail. 
This is just an addition for Laravel Sail
> Add Link to Laravel Sail

- queues.md
Documentation for https://github.com/laravel/framework/pull/36473 and https://github.com/laravel/framework/pull/36518 for the upcoming release.
If https://github.com/laravel/framework/pull/36518 isn't merged before the upcoming release, we can just delete the last "tip" line from this PR.
> [8.x] Document new ThrottlesExceptions job middleware

- validation.md
Just adding in documentation for the new `prohibited_if` and `prohibited_unless` validation rules introduced in 8.x (https://github.com/laravel/framework/pull/36516)
> Add prohibited_if and prohibited_unless documentation

- installation.md
This re-adds the note about directory configuration which got removed during the docs revision. I've also fixed a title indentation for the section above it.
> [8.x] Re-add note about directory configuration

- facades.md
"was" should be used instead of "were" with singular nouns.
> Grammar correction

- deployment.md
This feature has been deprecated (or never implemented) by major browsers.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection
It is superseded by CSP, but I don't think we can suggest a default CSP header that would be more helpful than confusing.
> [8.x] Remove deprecated header

- installation.md
With the just released Installer patch this note isn't necessary anymore.
> [8.x] Remove note about Git protocol

- collections.md
An example for the `mode` method on the collection when returning multiple values
> [8.x] Clarify `mode` can return multiple values with example

- eloquent.md
- Adds a mention in the model observers section on how to instruct them to only run after a DB transaction is committed
> [8.x] Adds mention to firing model observers after db transaction

- helpers.md
Laravel 6 has `Str::upper()`, but it isn't in the documentation.
> Add Str::upper() to Laravel 6 docs

- validation.md
Documentation changes for https://github.com/laravel/framework/pull/36667 and https://github.com/laravel/laravel/pull/5569
> [8.x] Add docs for prohibited rule

- eloquent.md
- queries.md
Ref https://github.com/laravel/framework/pull/36699
---
I'll let you rewrite it in your own voice, but this should give you a good starting point.
> [8.x] Document the query builder's new `lazy()` method

- valet.md
There is no `valet expose` command available. In order to share a site through expose, you only have to call `expose` after its installed globally.
> Fix expose share command

- queries.md
MySQL ignores the second parameter.
https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html
> [8.x] Add note about upserting to mysql database

- blade.md
Add `whereDoesntStartWith()` line to Blade - Retrieving & Filtering attributes section.
> [8.x] Add whereDoesntStartWith to blade attributes section

- valet.md
This was added in 6.x just a day before 7.x was released so it didn't make it into the 7.x or 8.x docs.
6.x version: https://github.com/laravel/docs/pull/5828/commits
8.x PR: https://github.com/laravel/docs/pull/6956
> Add "Default Site" / fallback section to Valet docs (7.x)

- helpers.md
Adds example showing the ability to pass multiple needles to Str::startWith.
> Add Str::startsWith array example

- collections.md
This pull request improves the `partition` documentation by using "array destructuring" instead of the "list()" method.
> [8.x] Uses array destructuring instead of list()

- helpers.md
As per @taylorotwell's remark [here](https://github.com/laravel/framework/pull/36743#issuecomment-811107049) we shouldn't document this anymore.
> [8.x] Remove dispatch_now from docs

- routing.md
It's not clear how to get same rate limiter experience as from 7.x. Because previous throttle was setting limit on authenticated user or ip. But after 8.x if no `by` is provided rate limiter is set on limiter key, which is not clear from a docs.
> [8.x] Add tip for rate limiter per user (or ip)

- sail.md
Resolve issue with vendor folder permissions for existing application. Currently the vendor folder is created under the root user. Fixed it to install under the current system user.
**Preconditions:**
- OS: Ubuntu 18.04.5 LTS
- Current system user: non root user
**Steps:**
1. Run composer install for existing project:
```
docker run --rm \
-v $(pwd):/opt \
-w /opt \
laravelsail/php80-composer:latest \
composer install
```
2. Check ./vendor folder permission:
```
ls -l ./
```
```
drwxr-xr-x 52 root  root    4096 apr  2 23:25 vendor/
```
- **Expected result:** ./vendor folder has current system user and group
- **Actual result:** ./vendor folder has root user and group
> Resolve issue with vendor folder permissions

- homestead.md
Meilisearch has been added in Homestead (https://github.com/laravel/homestead/commit/646f19ee84b0286354621106c74d1e049b21b60a), and this PR adds a little information in the documentation on how to enable it.
> [8.x] Add Meilisearch to "Optional Features" section

- queues.md
Apparently failed jobs within a batch doesn't marks them with a `finished_at` timestamp. This causes these batches not to be pruned and thus leaving them in the database. It's best that we document this behavior.
See https://github.com/laravel/framework/issues/36864
> [8.x] Document finished_at behavior for failed jobs

- queues.md
The backoff method on job middleware appears to accept a number of minutes, not seconds as the docs currently state.
> Correct 'seconds' to 'minutes' on job middleware backoff time

- http-tests.md
I was reading this https://stackoverflow.com/questions/42657551/match-jsonstructure-in-phpunit-test-laravel-5-4
And then I looked at `\Illuminate\Testing\AssertableJsonString::assertStructure` and I found that I can use start "*" to assert multiple array elements.
I can't find it in documentation, but it's very useful
> Add docs using 'star' for asserting json structure

- artisan.md
Adds `warn` to the list of output methods, in line with the existing documented methods.
> Add `warn` to list of output methods.

- mocking.md
The current example doesn't works as you can only pass a class name. I do see references to matching closure based listeners in the source code of `assertListening` but I'm unsure how that would work.
See https://github.com/laravel/framework/issues/36939
> [8.x] Fix incorrect closure reference

- fortify.md
There are a small documentation inconsistencies for declaring views. Some code examples are in php 7.4 syntax instead of 7.3. 
And, having in mind, that Laravel 8 minimum requirement is php 7.3, then syntax from php 7.4 (new features) are not correct in this context.
Code examples that are NOT OK (7.4 syntax used - closure), are for:
- Login (https://laravel.com/docs/8.x/fortify#authentication)
- Registration (https://laravel.com/docs/8.x/fortify#registration)
- Email Verification (https://laravel.com/docs/8.x/fortify#email-verification)
Code examples that are OK (7.3 syntax), are for:
- Requesting A Password Reset Link (https://laravel.com/docs/8.x/fortify#requesting-a-password-reset-link)
- Resetting The Password (https://laravel.com/docs/8.x/fortify#resetting-the-password) 
- ... 
I …
> [8.x] fortify.md

- database-testing.md
- releases.md
In concordance with [#5583](https://github.com/laravel/laravel/pull/5583), as after Faker PHP 1.14, using properties is deprecated, and it is recommended to use methods instead.
See [#164](https://github.com/FakerPHP/Faker/pull/164) for details.
> [8.x] Using faker method instead of properties

- billing.md
This is an attempt to clarify 3D Secure screens. These screens often contain vastly different ways of confirming payments depending on the issuer or bank. A small note about this in the docs can't hurt and should help inform app developers to clarify this before a customer initiates a payment.
When this PR is merged and cleaned up I'll send follow up PR's to Cashier Paddle, Spark Stripe and Spark Paddle docs.
> [8.x] Clarify 3D Secure

- session.md
Reference
https://github.com/laravel/framework/pull/36937
> [8.x] Add missing method to session docs

- upgrade.md
`nitpick (non-blocking)`: `This` should be `The`
I hope this helps!
`praise`: **Thank you for developing Laravel!**
> [8.x] Upgrade Guide > Routing > Automatic Controller Namespace Prefixing > `This` should be `The`

- eloquent-relationships.md
I recently had an experience where I used saveMany to add multiple models to a relationship. Before calling the saveMany() method I altered some properties on the models but did not intend for these changes to be persisted as I only wanted the relationship to be updated. 
From the official documentation, I wrongly understood that the save and saveMany() methods when called only updates the many-to-many relationship and not the models passed to the method as well and worked similarly to the sync() method, with the only difference being saveMany() takes model instances as input instead of an array of model ids. 
I realize the methods do have the word "save" in them, but as a new Laravel developer relying heavily on the documentation, I feel some clarification here would not hurt.
> [8.x] Add clarification on save() and saveMany() relationship methods

- validation.md
This PR fixes the typo in `:attribute:` (last `:` is not needed).
PS: I've checked - these two matches are the only two places with that issue, and `7.x` doesn't have this problem.
> [8.x] Fix typo `:attribute:` => `:attribute`

- collections.md
One of the examples for the [Collection's `reduce` method](https://laravel.com/docs/8.x/collections#method-reduce) uses the `reduceWithKeys` method; this PR fixes that.
PS: These two methods are [100% identical](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Collections/Traits/EnumeratesValues.php#L736-L763) under the hood:
So, I think we could simply call the `reduce` method from the `reduceWithKeys` to make it obvious _(I'll create a PR)_.
> [8.x] Fix usage of Collection's `reduceWithKeys()` in the `reduce()` description

- queues.md
Just a small fix to add a semicolon in one of the examples.
> [8.x] Fix typo (missing semicolon in one of the examples)

- migrations.md
The description for the Blueprint's `ipAddress` method [says that it creates an `INTEGER` equivalent column](https://laravel.com/docs/8.x/migrations#column-method-ipAddress).
When in reality, for most of the grammars it creates a `VARCHAR` equivalent:
- [MySQL](https://github.com/laravel/framework/blob/597f5ab16d0d2df67e50fedfd2fa66789b29998c/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php#L812-L815)
- [SQLite](https://github.com/laravel/framework/blob/597f5ab16d0d2df67e50fedfd2fa66789b29998c/src/Illuminate/Database/Schema/Grammars/SQLiteGrammar.php#L734-L737)
- [SqlServer](https://github.com/laravel/framework/blob/597f5ab16d0d2df67e50fedfd2fa66789b29998c/src/Illuminate/Database/Schema/Grammars/SqlServerGrammar.php#L722-L725)
And only [Postgres has a separate …
> [8.x] The `ipAddress` method creates `VARCHAR`, not `INTEGER`

- blade.md
- eloquent-mutators.md
- eloquent-relationships.md
- eloquent.md
- urls.md
Modify some absolute URLs to a relative. These will make trouble when hosting them on the no laravel.com site.
> Unify absolute URLs to relative URLs.

- testing.md
Parallel Testing was originally created for Laravel 9, then back-ported to Laravel 8. Due to this, earlier versions (5.0, 5.1, 5.2) of `nunomaduro/collision` package had a restriction to only use `--parallel` option on Laravel 9, but version 5.3 removed that restriction. 
We need to let users know in case they are using version < 5.3 of collision and trying to use Parallel Testing.
Edit:
Link below shows comparison of collision version 5.2 to 5.3. Checkout `src/Adapters/Laravel/Commands/TestCommand.php` file at line 74 for the removal of restriction.
https://github.com/nunomaduro/collision/compare/v5.2.0...v5.3.0
> [8.x] Document users must use `nunomaduro/collision: ^5.3` for Parallel Testing in L8

- passwords.md
- validation.md
This pull request adds documentation about the `Password` rule object: https://github.com/laravel/framework/pull/36960.
> [8.x] Adds `Password` rule object documentation 

- urls.md
After experiencing https://freek.dev/1977-dealing-with-expired-signed-urls-in-laravel?preview_secret=I9e6ZvUlTU I felt it might be worth to document this. Thanks to @freekmurze 
Although I feel like we could do better out of the box with a better message for the 403 exception? 🤔
> [8.x] Document rendering signed route failures

- fortify.md
Highlight email and username field for consistency and avoiding field name confusion
> [8.x] Highlight email / username as field name

- csrf.md
Help users understand that "POST", "PUT", "PATCH", and "DELETE" methods require CSRF protection, while "HEAD", "GET" and "OPTIONS" requests do not.
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php#L94
> [8.x] clarify which <form> methods need CSRF protection

- validation.md
Clarifies unless rules when _anotherfield_ is missing from the request data and the separate behavior for `null`.
> [8.x] Clarify unless rules

- queues.md
This adds a note about using job properties when handling failed jobs using `failed` method on the job class. Coming from answer I got in this issue: https://github.com/laravel/framework/issues/37043.
I thought it would be useful to document.
Cheers!
> Add a note about failed method on queued job

- pagination.md
Documentation for https://github.com/laravel/framework/pull/37216.
> [8.x] Document cursor pagination and its advantages/limitations

- collections.md
Developers may get confused with key and value comparison here.
We should keep the values different so that it is clear that `union` merges by key.
> Remove Confusion of the Union Example

- collections.md
In previous documentation versions of the contains method, the documentation of this method started with a brief explanation of what this method does. If accepted, this PR restores this brief explanation to the top of the method description.
> Add brief explanation back to the contains method

- octane.md
This pull request fixes the default Octane port should use. Examples - such the Nginx template - expect Octane to be using the port `8000`.
In addition, it adds the `--rpc-port` option that should be used when roadrunner.
Addresses: https://github.com/laravel/octane/issues/276.
> Fixes default Octane port

- fortify.md
`Fortify define routes that are intended` --> `Fortify defines routes that are intended`
> Fix tiny typo in Fortify docs

- validation.md
- Adds documentation about using the `array` and the `in` validation rules combined (link to the [source code](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L1052-L1060))
> Document the array+in validation rule combo

- validation.md
This PR adds a bit of documentation for the ability to validate that array keys must be present in a list ([source code](https://github.com/laravel/framework/blob/6a42e1216210b3ad3f738ab27e51e850190d9a1f/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L295-L306) and [tests](https://github.com/laravel/framework/blob/6a42e1216210b3ad3f738ab27e51e850190d9a1f/tests/Validation/ValidationValidatorTest.php#L703-L718))
This feature was also present in Laravel 7 ([source code](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L323-L334))
> Array key validation

- configuration.md
Release https://github.com/laravel/framework/releases/tag/v8.42.0
included PR https://github.com/laravel/framework/pull/37385 from idea https://github.com/laravel/ideas/issues/2558
that added a `--refresh` option to the `artisan down` command.
> Document refresh option for artisan down command

- billing.md
I think that we cannot skip trial with ```trialDays(0)``` because Stripe API want a future date. So, we need to use ```skipTrial``` to bypass trial for user.
> Fix skip trial on cashier

- upgrade.md
We just ran into the issue where we copied the new mail config file when updating to Laravel 7.x, however we did not realize that the environment variable MAIL_DRIVER has been changed to MAIL_MAILER. I think it would be helpful to mention this here.
> Added a note about the changed .env variable MAIL_MAILER

- authentication.md
Changed the manual authentication example:
Two parts:
• Validate the post data coming in exists, and the email is an email.
• Pass a translated error message (shipped standard in lang/en/auth.php)
I realise it's not required, but it shows some best practice perhaps for other routes - we don't assume data exists, and blindly pass it to a function. The translation part introduces how translations can be used from the start in an application, very easily.
> [8.x] Improve manual authentication example

- eloquent.md
- Added a tip to observer, to state the all model event functions can be implemented.
- Added definition of the difference between `-ed` and `-ing` events.
---
I found that many colleagues didn't realise the observer can implement the other model event function, therefore it should maybe be more explicit.
I'm open to changing the wording, if need be.
> Add reference to model events and describe different between -ed and -ing events

- collections.md
The current documentation for the `sole` method in Collections has an example which suggests the expected result. However, the expected result seems to be wrong. Instead of (int) 3, I expect (int) 2 to be the result. Implementing the given example confirms this (in Tinker):
```
>>> collect([1, 2, 3, 4])->sole(function ($value, $key) { return $value === 2; });
=> 2
```
The current proposed change is simply to replace "3" by "2" in the documentation.
> Wrong return value of sole funciton in example

- eloquent-relationships.md
Hello,
i'm proposing to add a mention in the "Other Aggregate Functions" section about the order of these methods when combining with a select statement.
it's a follow-up of this issue :
https://github.com/laravel/framework/issues/37557
thanks.
> Adding a mention about select in Other Aggregate Functions

- billing.md
SCA (Strong Customer Authentication) is there to protect European customers. Even more important than where the merchant is living is the location of the customers.
> Added SCA info on Cashier Stripe

- eloquent-mutators.md
After investigating https://github.com/laravel/framework/issues/37465 we came to the conclusion that there's a discrepancy between a regular datetime cast and one with a custom format. The one with the custom format will have the `app.timezone` applied when serialized while the other one will have UTC applied (default Carbon behavior). 
I feel this is an important gotcha that we need to note about in the docs.
> [8.x] Explain timezones for custom datetime format

- packages.md
I often come across packages that use a `config` or `views` tag, which means that running `vendor:publish --tag=config` publishes _all_ `config` assets for _all_ packages you have installed that use that tag. Common practice these days is to "namespace" tags by prefixing with your package name, and I think the docs should promote that, to prevent such conflicts.
> Switch example to better package tag convention

- passwords.md
In the closure for handling the password reset, `use ($request)` is written. However, the request instance is not used in the closure.
> Remove use of $request in password reset closure

- eloquent-relationships.md
Hello,
there is a typo in eloquent-reationships.md after the formatting of c919d4.
it's not really worth a PR so i made a comment on that commit but i don't think anyone saw it,
so i made this pr.
feel free to merge this pr or fix the typo directly.
thanks.
> Fixing typo introduced by c919d4

- http-tests.md
The test framework included with Laravel enters undefined behavior should multiple requests be performed in the same test method, as the framework only boots once per test method (https://github.com/laravel/framework/issues/27060).  For example, Sanctum may behave unrealistically when this guidance is not followed (https://github.com/laravel/sanctum/issues/272#issuecomment-853902783).
> [8.x] Document that only one request is supported per test method

- database-testing.md
The `$seed` and `$seeder` properties work only if `RefreshDatabase` trait is used in a test.
As confirmed [here](https://github.com/laravel/docs/commit/967b638e518654120735c13f40c4b7495b5b3dd8#commitcomment-51165186).
> Note about RefreshDatabase trait for using seed features in tests

- packages.md
The `loadViewComponentsAs` call, just like the `callAfterResolving` call belongs in the `register` method of a service provider since it wires dependency resolution.
> [8.x] Indicate correct service provider method

- urls.md
This adds documentation for the hasValidSignatureWhileIgnoring macro added by laravel/framework#37604
> [9.x] Add hasValidSignatureWhileIgnoring to the signed url verification docs

- billing.md
Docs for the upcoming Cashier v13 release.
Besides all the plan to price renames I also took the time to use proper prefixes for price and tax rate ideas so people know more clearly what these mean and how to couple these with the ID's in their Stripe dashboard.
> [8.x] Cashier v13 docs

- validation.md
This PR adds documentation for the current_password rule introduced in [#37650](https://github.com/laravel/framework/pull/37650). It also adds a deprecation notice for the password rule.
> Document current_password validation rule

- broadcasting.md
- container.md
- Adds a reference to the `$model->broadcastChannel()` method available on any Eloquent model as for `^8.45`. I suggest this method in the Turbo Laravel documentation, so thought it would be useful to be documented. This can be useful when passing down the Echo channel name to Inertia.js pages or something like that;
- Adds references to scoped instances in the container;
> Missing broadcasting method and scoped instances docs

- billing.md
I found that when we are swapping a price for a subscription we are explicitly setting the ends_at date of the subscription to null. This will re-subscribe any user who has canceled their subscription, this note is to make it clearer.
> More detail on swapping prices for canceled subscriptions

- cashier-paddle.md
When overwriting Cashier routes, it's important that the default name also stays in place.
> [8.x] Add name to overwritten Cashier Paddle webhook

- billing.md
When overwriting Cashier routes, it's important that the default name also stays in place.
> [8.x] Add name to overwritten Cashier Stripe webhook

- notifications.md
With on-demand notifications, you can call the `->route('mail', $email)` to route to a given email address, but previously it wasn't documented how to specify the recipient name, and it's the same approach as in the `routeNotificationForEmail` method.
> [8.x] Document how to specify the recipient name with on-demand email notifications

- eloquent.md
The documentation regarding `eloquent->replicate()` was missing some key information on how to use the `$except` parameter, I had to reverse engineer to see how it works.  I thought it might help other people who wish to use it.
> Document the $except parameter of replicate

- collections.md
Added missing semicolon to the code snippet for the duplicates() collection method.
> Added missing semicolon to code snippet

- fortify.md
`All of Fortify's view's rendering logic` --> `All of Fortify's view rendering logic`
> Fix typo in Fortify docs

- dusk.md
Copying the GitHub action for instance to run will output
> You are using the deprecated option "--no-suggest". It has no effect and will break in Composer 3.
> Removed deprecated --no-suggest composer flag

- contributions.md
Freenode's webchat no longer connects to its own network (see screenshot), so this PR updates the IRC support link to point to Libera's webchat instead. See also laravelio/laravel.io#635
> Update IRC support link

- queues.md
Reference https://github.com/laravel/framework/pull/37696
> [8.x] Add queue prune-failed command

- database-testing.md
https://github.com/laravel/framework/pull/37799
> [8.x] Use index or count property of Sequence object

- billing.md
This PR documents the new `invoicePrice` method: https://github.com/laravel/cashier-stripe/pull/1213
I've adjusted the docs to put the emphasis on the `invoicePrice` while recommending against the `invoiceFor` method (as Stripe does).
> [8.x] Document invoicePrice

- cache.md
Within this paragraph 
> This table should also have a string partition key with a name that corresponds to the value of the `stores.dynamodb.key` configuration item within your application's cache configuration file. By default, the partition key should be named key.
The table key is intended. However, the mentioned config is for aws client configuration. The config that should be used to change the table partition key, would be `stores.dynamodb.attributes.key`. 
See `vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php:246` 
```
new DynamoDbStore(
$client,
$config['table'],
$config['attributes']['key'] ?? 'key',
$config['attributes']['value'] ?? 'value',
$config['attributes']['expiration'] ?? 'expires_at',
$this->getPrefix($config)
)
```
> Fix documentation error dynamoDB cache

- migrations.md
The description of `nullableTimestamps` in migrations implied that it behaved differently from `timestamps`. The link to `timestamps` was dropped because I used the same formatting as the description of `foreignId`.
> [8.x] Clarify that `nullableTimestamps` is an alias of `timestamps`

- eloquent-relationships.md
It's at the moment not possible to use UUID's in combination with one-of-many in PostgreSQL because of PostgreSQL's lack of an implementation of `MAX` for UUID's. Other engine's like MySQL do support this. I am not aware of an alternative for PostgreSQL to find the max UUID. Therefor I think it's important to document this.
See the related issue here: https://github.com/laravel/framework/issues/37854
> [8.x] Clarify UUID's and one-of-many with PostgreSQL

- errors.md
I get this question quite a lot: how to override the behavior of the default Laravel/Symfony exception. 
The latest example from my Youtube comment: https://www.youtube.com/watch?v=0xLiqZQZT8w&lc=UgxgyEBcA3SVstlkuPR4AaABAg
"thanks for all videos!, i have a question. how to customize this message for every no query result: "message": "No query results for model [App\\Models\\Order].", in return json?"
So, in addition to creating a video about it, decided to suggest this paragraph and example into the docs.
> Error handling: overriding default exceptions

- billing.md
I think there is a little typo about `downloadInvoice()`, method needs `data` array parameter with at least `vendor` and `product` keys.
> [Cashier] Missing mandatory parameters to downloadInvoice

- pagination.md
If PR https://github.com/laravel/framework/pull/37762 is merged, the limitation on order by clause will no longer be valid.
> [8.x] Remove limitation from cursorPaginate()

- http-client.md
I found the object method not documented on the `Http` client based on this [tweet](https://twitter.com/JuanDMeGon/status/1413511760993263619)  and I figured I will update it on the docs so others might find it useful.
> Updated HTTP Client

- billing.md
Now that Cashier Stripe supports checkout redirects, we can remove the docs for the checkout button to encourage people to use the redirects.
> [8.x] Adjust Cashier docs for checkout redirects

- eloquent.md
This pull request adds documentation regarding this feature: https://github.com/laravel/framework/pull/37889.
> [8.x] Adds "Prunable" models documentation

- eloquent.md
Current:
> This method will be **_called called_** before the model is deleted.
The second `called` was removed.
> [8.x] Fix typo, duplicated word

- queues.md
Hi there,
Just to comment that I think there's a wrong parameter value in the first example of **Throttling Exceptions** section of **Queues**. The docs says: "if the job throws 10 exceptions within 5 minutes, we will wait 5 minutes", but the ```retryUntil()``` method returns a date *30 minutes* after now when it should be *5 minutes*.
I hope I'm not missunderstanding the docs.
> Fix number of minutes in example for retryUntil() in Throttling Exceptions

- filesystem.md
See https://github.com/laravel/framework/issues/38006
1. Using `^` over `~` version constraint
2. Using `--with-all-dependencies` to clear dependency conflicts in `guzzlehttp/psr7` when requiring `aws/aws-php-sdk`
> Update flysystem s3 composer require

- sanctum.md
Use the fully qualified namespace in the "Sanctum Middle" section to be consistent with the other example shown in the "Installation" section
> [8.x] Use fully qualified namespace in Sanctum

- seeding.md
Removed the word `test` from the seeder introduction. Seeders can also be used to seed the database with non-test data.
> [8.x] Remove test from seeding docs

- migrations.md
I found it misleading that the docs stated that the `foreignId` is only an alias for the `unsignedBigInteger` method, while the `constrained` method can _only_ be used with the `foreignId` method.*
I edited the wording and added a warning message learning from my mistake.
Also, I found that the `foreignUuid` method works similarly and was missing from the docs, so I added that also.
_*I am not familiar with Laravel's code, I hope I get the situation right._
> The foreignId method as an alias of unsignedBigInteger is ambigous.

- sanctum.md
I was fishing for an answer for hours all over the web. If you do not send "Accept: application/json" as a header, you get a 200 OK with your skeleton HTML layout as the render. I am using postman and it had "Accept: */*" which gave the a false 200 OK.
If the bearer token passed is not expired and correct, the framework returns a proper response. If the token is mistyped or expired, you get a 200 OK.
> Add note about Accept header

- upgrade.md
Current `master` branch in the Symfony project doesn't have an `UPGRADE-4.0.md` file so it gives a 404 error.
Link updated.
> Update broken link to Symfony upgrade guide

- eloquent-relationships.md
Hi,
I was using ```withSum()``` aggregate method which gave me ```{relation}_{function}_{column}``` attribute but I didn't like it and wanted to specify column own alias.
I searched through the docs about how to column alias but didn't find anything..
so here is my contribution.
Thanks,
Anees 
sorry for bad English though.
> added specify column alias of Aggregate Functions

- blade.md
Updated the example of the @class directive to show that you can use `!` to activate classes in an if-else manner. So in the example, if the `$isActive`  is false, the `font-bold` not show up but additionally the `text-gray-500` class will be rendered.
> Updating example of @class directive

- sail.md
In laravel/sail#201 appends publish sail script. Without [this changes](https://github.com/laravel/sail/pull/201/commits/692adb345528e7294339d11a2302cc8d7280a6ef) you can't use alias with published script.
> Alias for published sail script

- eloquent-relationships.md
The One of Many Polymorphic [docs](https://laravel.com/docs/8.x/eloquent-relationships#one-of-many-polymorphic-relations) are missing the name argument on the `morphOne()` method. This PR adds a name argument of `imageable`, as it exists in other `morphOne()` examples.
> Add missing name arg to One of Many Polymorphic docs

- billing.md
According to Stripe documentation (and tests), debits are positive and credits are negative.
> Fix applying balance

- dusk.md
The `assertInputPresent` and `assertInputMissing` assertions were added in https://github.com/laravel/dusk/pull/914
> Document `assertInputPresent` and `assertInputMissing`

- valet.md
This update to the docs describes how you can specify the PHP version at a project level with a `.valetphprc` file that was added as a feature in Laravel Valet v2.16.0 https://github.com/laravel/valet/releases/tag/v2.16.0
> Updated Laravel Valet with instructions on how to use the new `.valetphprc` file with `valet use`

- validation.md
For clarity reasons, `$v` was previously renamed to `$validator`, but two code blocks were missed.
> Fix variable name in examples

- http-tests.md
Hey! This PR is only a small one, but it just adds a quick description to the HTTP testing page for the new `assertRedirectToSignedRoute()` method that was added in my PR the other day (https://github.com/laravel/framework/pull/38349)
> [8.x] Added assertRedirectToSignedRoute() to docs

- billing.md
Please feel free to make any adjustments, not sure if leaving this separate from above snippet was repetitive or not.
This is based off the following documentation: `https://stripe.com/docs/payments/checkout/custom-success-page`
> [8.x] Add documentation surrounding stripe checkout session id callback.

- urls.md
Using a model as a route parameter per this example doesn't use the primary key of the model - it uses the route key defined by `getRouteKeyName` (which just so happens to be the primary key by default, but isn't always true)
> [8.x] Note that Eloquent routing uses the route key, not primary key

- queues.md
This adds a section to the `RateLimited` middleware docs to mention the `dontRelease()` method (similar to how it is mentioned in the following `WithoutOverlapping` middleware section).
> Update Queues docs to include `dontRelease()` on `RateLimited` middleware

- billing.md
The route helper returns an invalid route error if the session_id param is appended inside the helper. The param must be appended to the string outside of the helper.
> Fix Stripe session_id param in success URL

- validation.md
adjust `$data` variable instead of `$request->all()` on sometimes rule example
as the text below said
In the example above, the `email` field will only be validated if it is present in the `$data` array.
> [8.x] adjust variable on sometimes rule example

- documentation.md
The current link leads to a 404 page.
> [9.x] Fix link to API docs

- billing.md
- cashier-paddle.md
While working on my Cashier talk I realized that the docs are still using the old recommended way of overwriting the Cashier webhook controller while there's a much better and easier alternative to integrate  with the `WebhookReceived` and `WebhookHandled` events.
> [8.x] Rewrite event handling docs

- lifecycle.md
I found myself reading through the last paragraph of this section a couple of times. I think grouping the two paragraphs about method call order could help with readability and avoids the need to recap on the context (about calling all the `register` methods before any `boot` methods).
> [8.x] Combine provider method call paragraphs

- authorization.md
The message in the comment of the code example contradicts the condition
> Fix contradiction

- http-tests.md
Fix from whereTypeAll to whereAllType on line 416.
> Fix typo in Asserting JSON Types section

- scout.md
Adding this note will inform users to review Meilisearch breaking changes when they update their Meilisearch binary.
This also contains a note about compatibility between meilisearch-php and the meilisearch binary.
See https://github.com/laravel/scout/issues/516
> [8.x] Add Meilisearch upgrade note to Scout docs

- events.md
The subscribe method in the example returns an array and is not void.
> Fix method doc for return value

- sail.md
When using the docker method to install composer dependencies with Sail, if any of the dependencies use symlinks then the path mapping breaks when `sail up -d` is run. 
Sail operates in `/var/www/html` but the read me uses `/opt` for the composer install. In a situation where there's a local package dependency, the composer install will use relative paths for `/opt` for the package location and not `/var/www/html` where the rest of the code base sits. 
While this is an edge case, by having the read me use the website working directory `/var/www/html` it overcomes potential issues caused by symlink references in composer.
> Fix volume mount for symlinked directories.

- cashier-paddle.md
- As with #7298, the event list looks like it should be a bullet list instead of a code block.
- The events should be `Laravel\Paddle\Events\*` instead of `Laravel\Cashier\Events\*`.
> [8.x] Cashier (Paddle): Fix event class names

- billing.md
Based on the format of the list of webhooks in [Handling Stripe Webhooks](https://laravel.com/docs/8.x/billing#handling-stripe-webhooks), I am guessing that the list of events in [Defining Webhook Event Listeners](https://laravel.com/docs/8.x/billing#defining-webhook-event-handlers) should actually be a bullet list instead of a code block. (It looks more natural to me, anyway.)
> [8.x] Billing: Fix event list formatting

- mail.md
While working on the Symfony Mailer upgrade for Laravel 9.x I saw an undocumented feature of using AWS Session Tokens with temporary credentials which is also available in Laravel 8.x.
This PR adds the feature to the documentation.
Code where the SesTransport is created and the `token` entry of the config can be used if available:
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Mail/MailManager.php#L258-L293
More about temporary credentials here:
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html
> [8.x] Add AWS Session Token to the SES Documentation

- passwords.md
I often find people asking about creating custom commands to clear expired records from the `password_resets` table, not knowing a command already exists.
> Add missing auth:clear-resets command.

- queries.md
The `insertOrIgnore` method is very helpful, but it is important to understand the consequences. The method is accurately described in code as:
```php
/**
* Insert new records into the database while ignoring errors.
*/
public function insertOrIgnore(array $values)
```
However, the documentation describes it _in the context of duplicate errors_:
```markdown
The insertOrIgnore method will ignore duplicate record errors while inserting records into the database:
```
The statement may be interpreted as `insertOrIgnore` being equivalent to something like `skipOnDuplicate`. Unfortunately, `insertOrIgnore` has a number of consequences -- depending on database engine -- such as bypassing multiple MySQL Strict-mode restrictions: it is important that it is **not** considered equivalent to …
> [8.x] Clarify `insertOrIgnore` is not just duplicate record errors

- sail.md
The current documentation recommends the use of `sail down` command to stop the containers execution. This command stops and also removes the containers in Docker. A better option would be to use `sail stop` instead which only stops the containers but doesn't remove them.
This is better for using services like Vapor. If you remove the containers next time you need to authenticate again with Vapor before being able to deploy.
> Use `sail stop` command instead of `sail down` command

- contracts.md
- mail.md
Laravel 9.x will use the Symfony Mailer instead of the discontinued SwiftMailer.
Waiting for https://github.com/laravel/framework/pull/38481 to be merged.
Changes:
- Guzzle is no longer needed because symfony-http will be used by the API Transports instead.
- Each Transport now has now a symfony transport install (except array and log)
Unchanged:
- Config entries
Some things which should be discussed:
- Laravel 9.x will use Symfony 6.0 therefor the Links are absolut to https://symfony.com/doc/6.0/mailer.html there also exists a link to the current documentation if that is wished for: https://symfony.com/doc/current/mailer.html (Currently v5.3)
- Symfony Mailer is based on Symfony Mime which could be mentioned somewhere if necessary.
> [9.x] Update from Swift Mailer to Symfony Mailer

- installation.md
This option is available, but was not yet documented. Tried it out (just to be sure) using  `curl -s "https://laravel.build/example-app?with=mysql,minio" | bash`, which generated an entry in the `docker-compose.yml` as expected.
> [8.x] Add `minio` to "Choosing Your Sail Services"

- mocking.md
In the Mail Fake, it is also possible to pass a closure to the `assertQueued` and `assertNotQueued` methods.
> Added assertQueued and assertNotQueued 

- queries.md
When I run these sample codes in my local environment, it throws an exception:
```
• Tests\Feature\Database\QueryBuilderTest > lazy
RuntimeException
You must specify an orderBy clause when using this function.
```
My English is not good, so I didn’t add some explanatory text in the context.
> fix bad sample code

- eloquent.md
Add documentation to the Eloquent page that there exists an option to create policies when creating a model using the `php artisan make:model` command with the new `--policy` flag added in [laravel/framework#38725](https://github.com/laravel/framework/pull/38725)
> [8.x] Document the new --policy option in make:model

- broadcasting.md
The method is undefined without this trait. It should be included in the docs.
> Add trait to broadcastVia example

- routing.md
Covers https://github.com/laravel/framework/issues/37639
Five failed pull requests (+ Dries' unsubmitted dev branch) have been attempted for that issue but I think this is just a problem with routes being defined in an ambiguous order.
When defining multiple routes sharing the same URI, their call order will affect which route the incoming request is matched with. The specific route definition should be defined before any general route. If defined in the opposite order, command `php artisan route:cache` can cause the general route to always override the specific route.
```php
Route::any('/foo', function () {
// GET /foo matched after 'php artisan route:cache'
});
Route::get('/foo', function () {
// GET /foo matched without 'php artisan route:cache'
});
```
```php
Route::get('/foo', …
```
> [8.x] Add callout for ordering ambiguous route definitions

- helpers.md
> Add parenthesis to end of `Str::wordCount` heading

- homestead.md
Please feel free to wordsmith. Homestead now officially supports Apple Silicon as of base box version 11.5.0.
Please add the hacktoberfest-accepted label if merged. 🧑‍💻🎃
> [8.x] Homestead add mention of Apple Silicon support

- eloquent.md
When digging deeper to `upsert` func, I find that `MySqlGrammar` has no use with params `uniqueBy`, but `SqlServerGrammar` do, as image below. After some investigate around google, I think this is a mistake in the documentation, not the source code.
> Correct note upsert

- billing.md
I was getting the following error when copying from the example in the docs:
```php
Stripe\Exception\AuthenticationException
No API key provided. (HINT: set your API key using "Stripe::setApiKey(<API-KEY>)". You can generate API keys from the Stripe web interface. See https://stripe.com/api for details, or email support@stripe.com if you have any questions.
```
Adding Stripe::setApiKey(<API-KEY>) fixes this error.
> [8.x] Fix error with Stripe Checkout

- homestead.md
Updating Homestead's default IP to be [Virtualbox friendly](https://github.com/laravel/homestead/issues/1717).
> [8.x] Update Homestead's default IP in examples

- notifications.md
I needed a way to track SMS usage per client. After speaking with nexmo support I discovered that there is a method already on the nexmo channel driver, it just needed documenting.
Hope this is accepted as it would have helped me quite a bit.
> document nexmo client reference method

- cashier-paddle.md
A double forward slash broke a link within the testing section of the Paddle documentation.
> Broken Link

- notifications.md
There was no documentation for `NotificationSending` event and its features like preventing from sending notifications by just returning a `false` value.
> [8.x] Add docs for the `NotificationSending` event

- billing.md
Looks like it could have said either `and use the checkout method` or `and make use of the checkout method`. Went with the shorter option.
> Remove word

- homestead.md
With  v12.4.0, Homestead no longer exposes ports for the various services that are offered. The Laravel docs do not currently reflect the change. Updated the ports and moved the previously mapped ports to a list of services you may want to forward.
> Update Homestead default port listing

- notifications.md
Slack's Incoming Webhooks are being deprecated (and possibly removed):
> Please note, this is a legacy custom integration - an outdated way for teams to integrate with Slack. These integrations lack newer features and they will be deprecated and possibly removed in the future. We do not recommend their use. Instead, we suggest that you check out their replacement: Slack apps.
I've updated the documentation to explain how to create a Slack App, then configure Incoming Webhooks.
> [8.x] Update Slack Prerequisites

- dusk.md
To fetch the output you would need prepend a `return`. Otherwise it's always null.
Original example is a little bit confused. I add a new line to indicate that you can use a `return` to get the evaluation result.
> [8.x] add `return` in the example code of Browser::script()

- validation.md
Adds declined and declined_at validation rules to the documentation
Should only be merged if feature PR (https://github.com/laravel/framework/pull/39579) is merged.
Laravel PR: https://github.com/laravel/laravel/pull/5723
Framework PR: https://github.com/laravel/framework/pull/39579
> We are running a financial application where users answer yes, and no selectors, such as are you registered as a bad payer or if do you have existing debt. We could solve our issue by reversing the question's phrasing, e.g. "not_registered_as_a_bad_payer", and using accepted but this reduces intent.
> 
> At the same time, we allow financial instances to select their configurations of what they allow or disallow. This rule could help us align validation closer to the original intent and limit developer or …
> [8.x] Added declined and declined_if validation rule documentation

- migrations.md
It's possible to change spatial column type (PostgreSQL) between the default `geography` become `geometry` by adding column modifiers `isGeometry()`.
In one of my project I was having trouble how to create database migration of spatial column type `geometry`, but fortunately solved my problem after reading this code [Illuminate/Database/Schema/Grammars/PostgresGrammar.php#L943](https://github.com/laravel/framework/blob/b2be94b68aec532c90d878497748dcc837b95d25/src/Illuminate/Database/Schema/Grammars/PostgresGrammar.php#L943)  
Example of migrations code:
```php
Schema::create('some_table', function (Blueprint $table) {
//....
$table->geometry('geometry_column')->nullable()->isGeometry(); // this generate spatial column type geometry
$table->geometry('geography_column')->nullable(); // this …
```
> Add column modifiers docs for PostgreSQL spatial column type

- telescope.md
As this [PR](https://github.com/laravel/telescope/pull/1146) has been merged, I think it's better to add the method in documentation so it will be easier for developers to find it.
```
Telescope::filter(function (IncomingEntry $entry) {
if ($this->app->environment('local')) {
return true;
}
return $entry->isReportableException() ||
$entry->isFailedJob() ||
$entry->isScheduledTask() ||
$entry->isSlowQuery() ||
$entry->hasMonitoredTag();
});
```
> Add $entry->isSlowQuery() in documentation.

- filesystem.md
This pull request clarifies that both `getClientOriginalName` and `getClientOriginalExtension` methods are unsafe.
> [8.x] Clarifies `getClientOriginalName` and `getClientOriginalExtension` methods

- upgrade.md
This pull request adds upgrade notes regarding https://github.com/laravel/framework/pull/39648.
> [9.x] Adds `Application::storagePath` upgrade notes

- eloquent.md
Word "example" is used two times side by side and I added a new row to be more readable and to separate definition from example.
> [8.x] Muting Events - small changes

- billing.md
Accommodates https://github.com/laravel/cashier-stripe/pull/1284.
I kept the anchor links unless you also want me to update those?
> [8.x] Renamed cancelled to canceled in Cashier Stripe docs

- contributions.md
The invite URL has changed. It's correct in the other two instances of it.
> Update Discord invite URL

- octane.md
> [8.x] Change to openswoole

- cashier-paddle.md
It seems that this snuck in somehow, probably by copy/paste from the Cashier Stripe docs. This isn't possible with Paddle. See https://developer.paddle.com/api-reference/subscription-api/users/updateuser#usage-notes
> [8.x] Remove note about Paddle swap during trial

- cashier-paddle.md
This borrows from the new [Spark documentation](https://spark.laravel.com/docs/1.x/spark-paddle/configuration.html) to let users know they'll need to expose their local URLs in order to test webhooks locally.
> Include notes on webhooks and local development

- broadcasting.md
Should there maybe also be a note that match expressions are available as of PHP 8.0.0?
Since Laravel 8.x's [server requirements](https://github.com/laravel/docs/blob/8.x/deployment.md#server-requirements) are PHP >= 7.3
> [8.x] add space to match expression

- queues.md
Calling `$this` in callbacks of `Bus::batch` is not supported, as clarified here: https://github.com/laravel/framework/issues/38573
However, this was not documented yet. I've added a small note.
> [8.x] Add note to 'Dispatching Batches' chapter to not use $this in callbacks

- configuration.md
Our project stores a bunch of .env files for particular environments as `.env.[environment]`. We didn't realise that Laravel auto-loads from these if an `APP_ENV` is specified.
This just adds some details documenting the feature, in the hopes that it doesn't catch someone else out like it did to me 🙂
> [8.x] add details about environment-specific .env files

- releases.md
This PR adds the supported PHP versions to each Laravel version in the release notes. This should make it clear which PHP versions are supported on which Laravel major version.
(note that it says 8.2 for Laravel 10 in the screenshot, please ignore this, I've updated it to 8.1 again in the Markdown file).
> [8.x] Add PHP versions to release notes

- eloquent.md
https://github.com/laravel/framework/pull/39749
> [8.x] Add documentation for optional 'exclude' parameter of the PruneCommand

- database.md
I was looking for the (re) throw behaviour of exceptions in a `DB::transaction()` call. Looked it up in the code and thought it'd be good to mention in the docs.
> Small clarification database transaction exceptions

- collections.md
If the callback given to `skipWhile` never returns `false`, then an empty collection would be returned. Currently the documentation states the opposite. If the callback never returns `true`, then the whole collection is returned unfiltered.
```
>>> $collection = collect([1, 2, 3, 4]);
=> Illuminate\Support\Collection {#4833
all: [
1,
2,
3,
4,
],
}
>>> $subset = $collection->skipWhile(function ($item) { return false; });
=> Illuminate\Support\Collection {#4835
all: [
1,
2,
3,
4,
],
}
>>> $subset = $collection->skipWhile(function ($item) { return true; });
=> Illuminate\Support\Collection {#4824
all: [],
}
```
> [8.x] Fix skipWhile callback note

- sail.md
Just a minor change, the default php version is 8.1.\
See docker-compose.yml :)
> fix default php version from 8.0 to 8.1 in sail

- sail.md
Update Sail Default PHP Version to 8.1
Ref:
https://github.com/laravel/sail/releases/tag/v1.12.9
> [8.x] Update Sail Default PHP Version to 8.1

- dusk.md
Sepcify that `assertPresent` searches in the source, like `assertNotPresent` does.
> Clarify assertPresent usage

- notifications.md
Remove queue able trait from this example because it'll conflict with the `afterCommit` property.
See https://github.com/laravel/framework/issues/39888
> [8.x] Remove queueable trait from example

- eloquent.md
- queries.md
This PR adds a documentation to [#39646](https://github.com/laravel/framework/pull/39646) and a minor fix for #7470
> [8.x] Add documentation for `lazyByIdDesc` method

- passport.md
The user model already comes with a default HasApiTokens trait provided by Sanctum.
Add an extra note to the documentation to replace the default trait with the passport trait.
> Passport : replace existing HasApiTokens trait

- starter-kits.md
The Breeze API scaffolding creates and references an environment variable named `FRONTEND_URL` (see, e.g., https://github.com/laravel/breeze/blob/9abe49ebe4ff941660b7af1df318344f728d8f3d/src/Console/InstallsApiStack.php#L50), but the existing docs prepend `APP_` to the name of this environment variable. This PR removes the prepended `APP_` to make the name in the docs consistent with the name in the code.
> Correct FRONTEND_URL environment variable name

- artisan.md
Stumbled upon this typo today.
> [8.x] Artisan input descriptions typo fixed

- sail.md
The [sail documentation](https://laravel.com/docs/8.x/sail) mentions xdebug support, but does not mention that Laravel 8.53.0 is the first version that supports the passing through of the `XDEBUG_MODE` and `XDEBUG_CONFIG` variables to the underlying server process. I ended up spending a chunk of time this afternoon troubleshooting my local xdebug configuration, only to realize I was on too old of a version of the framework.
I added a note in the xdebug section that spells this out much more clearly - it clearly states that you need at least version 8.53.0 in order to support browser debugging. I reworked the wording several times (pre and post commits), but still feel the wording could use a bit of work, so super receptive to rewordings. Likewise, I placed this as a note within the …
> [8.x] Add note about xdebug browser requirements

- eloquent-mutators.md
The markdown parser closed the "\<digits\>" tag in the current (view-source:https://laravel.com/docs/8.x/eloquent-mutators)
This commit fixes this behaviour.
> [8.x] Prevent this tag to be closed by the markdown parser

- releases.md
Structural inconsistencies will make bad results by tools that convert markdown to HTML or other formats.
Therefore, it must be fixed.
> Fix table structure mismatch.

- horizon.md
People keep trying to name this `horizon` while it's reserved. See https://github.com/laravel/framework/issues/40073
> [8.x] Note reserved Redis connection for Horizon

- billing.md
I've integrated cashier following the official doc, but when I tried to update a user without `stripe_id`, I get this error message:
```
Stripe\Exception\InvalidArgumentException: The resource ID cannot be null or whitespace. in /var/www/html/vendor/stripe/stripe-php/lib/Service/AbstractService.php:94
Stack trace:
#0 /var/www/html/vendor/stripe/stripe-php/lib/Service/CustomerService.php(319): Stripe\Service\AbstractService->buildPath()
#1 /var/www/html/vendor/laravel/cashier/src/Concerns/ManagesCustomer.php(101): Stripe\Service\CustomerService->update()
#2 /var/www/html/vendor/laravel/cashier/src/Concerns/ManagesCustomer.php(193): App\Models\User->updateStripeCustomer()
#3 laravel-serializable-closure://function ($customer) {
$customer->syncStripeCustomerDetails();
}(3): …
```
> [8.x] add stripe id check for automatic sync stripe customer details

- sail.md
Now that 8.1 is the default. I also added a note about the correct PHP version to use.
> [8.x] Bump Sail to PHP 8.1 container

- passport.md
Someone on the Laracasts forums claimed protecting routes with the client credentials grant type was confusing because they had read the “Protecting Routes” section, so had erroneously added `auth:api` to their routes, instead of using the `client` middleware as instructed in the “Client Credentials Grant Tokens” section.
This attempts to mitigate that misunderstanding by adding a note highlighting if you _are_ using the client credentials grant type, to use the `client` middleware and not the `auth:api` middleware.
> [8.x] Add client credentials grant note

- mix.md
The 'purge' option in the Tailwind configuration has been renamed to 'content'. The 'purge' option generates warnings when running npm.
Reference: https://tailwindcss.com/docs/upgrade-guide#configure-content-sources
Reference to wording: https://tailwindcss.com/docs/content-configuration
> Remove reference to 'purge' option from Tailwind configuration

- deployment.md
The NGINX configuration example on the deployment page only has an IPv4 listener. I suggest adding an IPv6 listener to the example as well.
http://nginx.org/en/docs/http/ngx_http_core_module.html#listen
> [8.x] NGINX example IPv6 support

- mix.md
The contents section is specified to remain used classes in html/js files. So maybe meaning reversed.
However, I'm not an English native, please correct/purge if I'm wrong.
> Correct meaning of sentence reversed

- authentication.md
Both `GET` and `POST` requests have the same route name which isn't compatible with route caching.
> Remove duplicate route name from POST request.

- sail.md
Yarn support was added in [laravel/sail#29](https://github.com/laravel/sail/pull/29) but was not documented.
> Add Sail yarn documentation

- filesystem.md
Hi! This PR just adds a bit of info about the `Storage::buildTemporaryUrlsUsing()` method added in https://github.com/laravel/framework/pull/40100 :)
> Added buildTemporaryUrlsUsing() docs.

- dusk.md
Document [`clickAndWaitForReload()`](https://github.com/laravel/dusk/pull/953)
I chose not to keep the `waitForReload()` example as I couldn't think of a scenario where it wouldn't be combined with a preceding click event.
> Document `clickAndWaitForReload()`

- broadcasting.md
"Open Source Alternatives" are used in H3 and H4. So correct it.
> Correct duplicated header.

- dusk.md
I noticed that the old description wasn't accurate. I've updated it.
I've also changed `assertSee` to `press`. An assertion won't cause a page reload, pressing a button will.
> [8.x] Fix `waitForReload` example

- artisan.md
Artisan Console option shortcuts require a single hyphen, but the mention of {--Q|queue} in the doc can mislead slow thinkers like me :)
Cf. this closed issue from 2017 : https://github.com/laravel/framework/issues/19594, others ran into this ambiguity in the past.
> Precision about Console option shortcuts requiring a single hyphen

- logging.md
I created a channel named `deprecations` so my config looked like:
```
return [
'deprecations' => env('LOG_DEPRECATIONS_CHANNEL', 'null'),
'channels' => [
...
'deprecations' => [
'driver' => 'single',
'path' => storage_path('logs/php-deprecation-warnings.log'),
],
],
]
```
But it was logging even if I didn't specify a LOG_DEPRECATIONS_CHANNEL in .env. I finally understood that the name I chose for my channel did overwrite and it made it log warnings anyway.
Not easy to write but I hope this PR make it a bit clearer...
> clarify how to define a logging channel for PHP deprecation warnings

- eloquent.md
- queries.md
The return value from running a delete statement was missing in [`queries.md`](https://laravel.com/docs/8.x/queries#delete-statements).
In comparison, it is mentioned in [`database.md`](https://laravel.com/docs/8.x/database#running-a-delete-statement) and [`eloquent.md`](https://laravel.com/docs/8.x/eloquent#deleting-models-using-queries).
---
(Similar to PR #7552)
> Add missing return value

- validation.md
It is actually "mac_address", not "mac".
> Fix misnamed validation rule.

- releases.md
It uses one of the images of my pull request.
> [9.x] Adds `route:list` image to release notes

- helpers.md
Documents `between` method for fluent strings.
`Str::between` was already documented.
> Document between method for Stringable

- filesystem.md
- releases.md
- upgrade.md
Following https://github.com/laravel/framework/pull/40411, this pull request moves the docs from Flysystem v2 to v3. 👍🏻
> [9.x] Moves documentation from Flysystem v2 to v3

- eloquent-mutators.md
According to https://github.com/laravel/framework/pull/40022 accessor's argument isn't defined.
> Remove `$value` from accessor method

- releases.md
Fix typo describing the new version of Flysystem to be 3.0 instead of 2.0
> [9.x] Fix release typo

- passport.md
I realize we already have a "Passport or Sanctum" section on top but I feel we should also add one here.
See https://github.com/laravel/passport/issues/1518
> [8.x] Refer to Sanctum from the Personal Acces Token docs

- collections.md
Documenting the new `sortKeysUsing` method in the `Illuminate\Support\Collection` class. See also laravel/framework#40458.
> Add sortKeysUsing to the collection docs

- mail.md
Fix docs to match names merged from [PR](https://github.com/laravel/framework/pull/40460) and add `[]`s.
> fix function names

- upgrade.md
Hi! I was just looking through the upgrade guide and noticed that there wasn't any mention of the `sole` method being added to the `Illuminate\Support\Enumerable`. It might not be needed, but I just made this PR in case it was something that's slipped through accidentally and was missed off.
I also added a heading to the contents list at the top of the page too that I think was missing.
Apologies if none of these are needed though :)
> [9.x] Add 'sole' and missing header to upgrade guide

- collections.md
Partly reverts e9e85ff since the capitals `ID` were intended to show how the `sortKeysUsing` method can sort the keys case insensitive (unlike the `sortKeys` method, which would place `ID` at the first position).
Also, the output in the example now does not match the input code.
> Fix example in sortKeysUsing method in the collection docs

- releases.md
This pull request adds the artisan test `--coverage` option to release notes.
> [9.x] Adds artisan test `--coverage` release notes

- upgrade.md
This pull request adjusts the `Request::getSession` upgrade guide, regarding the `SessionNotFoundException` that may be throw.
> [9.x] Adjusts `Request::getSession` upgrade guide

- testing.md
This pull request adds documentation regarding the new artisan test `--coverage` option.
> [9.x] Adds artisan test `--coverage` documentation

- testing.md
This pull request adds the `--coverage` option requirements to our docs.
> [9.x] Adds `--coverage` requirement 

- releases.md
This pull request clarifies that named arguments are covered by Laravel's backwards compatibility guidelines.
> [9.x] Named arguments are covered by Laravel's backwards compatibility guidelines

- helpers.md
This pull request adds documentation regarding the new `to_route` helper: https://github.com/laravel/framework/pull/40522.
Note: I've not added this change to the upgrade guide, as having people defining a `to_route` helper is less likely than `str`.
> [9.x] Adds `to_route` helper documentation

- helpers.md
- upgrade.md
This pull request adds documentation regarding the new `str` helper: https://github.com/laravel/framework/pull/40520.
> [9.x] Adds `str` helper documentation

- releases.md
This pull request adds `ignition` to release notes.
<p align="center">
</p>
> [9.x] Adds `ignition` to release notes

- upgrade.md
When upgrading several apps from Laravel <=8.5.23 to L9 I needed to update the TrustProxies middleware from Fideloper trustproxies to the Illuminate version.  This is not mentioned in the docs.
> [9.x] Mention the update for TrustProxies middleware in upgrade guide if upgrading from Laravel <=8.5.23

- releases.md
This pull request adds `to_route` and `str` to release notes.
> [9.x] Adds `to_route` and `str` to release notes

- mail.md
For some reason, this was removed from the documentation [from 5.5+](https://laravel.com/docs/5.4/mail#mail-and-local-development) but it still seems to be useful to the community.
https://twitter.com/fideloper/status/1484263823074856961
Positive feedback:
- https://twitter.com/larstwolters_/status/1484480146803462145
- https://twitter.com/LanceRigdon/status/1484304192399417345
- https://twitter.com/iampoul/status/1484275012706185218
- https://twitter.com/JosueYenga/status/1484387580552613889
- https://twitter.com/yorkiebar16/status/1484276979574652934
- https://twitter.com/benjymancox/status/1484277136823402497
- https://twitter.com/davorminchorov/status/1484334016677380099
- https://twitter.com/8ivek/status/1484520620394446855
> [8.x] Mail - Document the global to address

- passport.md
These aren't recommended anymore by OAuth2 Server and we should warn people who are using them: https://oauth2.thephpleague.com/authorization-server/which-grant/
> [8.x] Don't recommend legacy Passport grants anymore

- helpers.md
Add docs for: https://github.com/laravel/framework/pull/40472
> [8.x] Add `scan` fluent method to Stringable

- http-client.md
This was fixed in https://github.com/laravel/framework/pull/40636. Related issue: https://github.com/laravel/framework/issues/34505 and original docs PR https://github.com/laravel/docs/pull/6457
> [9.x] HTTP middleware now runs when the client is faked

- billing.md
Documents https://github.com/laravel/cashier-stripe/pull/1304
> [8.x] Document invoice renderer

- blade.md
Currently reading the docs usres can think they can use `$loop` variable in any loop. But that is not the case. `$loop` variable is only available in `foreach` loop. This PR clarifies that.
> Clarify that Blade `$loop` variable is only available in `foreach` loop

- upgrade.md
- The title says `failed`, but the rest of the section means `flush`, so I think that was a typo. Also, the argument changed from `$age` to `$hours` ([source](https://github.com/laravel/framework/commit/6daecf43dd931dc503e410645ff4a7d611e3371f#diff-e21923e2ff937000ffb1ecb58376f9868079ebf98a249a49e43160cb4f23c8f6)), so this needs to change as well, I think.
> Fix FlushFailedCommand method name and argument in upgrade guide

- valet.md
Ngrok requires you to register an account first these days and set up an authentication token. By noting this in the docs we can warn users in advance about this.
Resolves https://github.com/laravel/valet/issues/1172
> [8.x] Document Ngrok account signup and auth token

- installation.md
In the ./vendor/bin/sail up, docker-composer (or docker-compose) is used. If it is not installed, a cryptic error message is shown to the user (`unknown shorthand flag: 'q' in -q` followed by the --help output of docker).
For the installation guide to work as easily as possible, I think it would be useful to add this small note, so a user (me) does not have to read the sail script to figure out what this error means.
> Add that docker-compose should be installed

- envoy.md
Following up on laravel/envoy#242, this PR documents the new `@before` hook in Envoy.
I opted to put it in with the other hooks rather than create a whole new section for it, so I renamed the existing section from "Completion Hooks" to just "Hooks". I left all the existing anchor names like `#completion-hooks`, `#completion-after`, etc. intact to not break any existing links in the wild.
> [8.x] Document new Envoy `@before` hook

- database.md
Now that we have a MariaDB build on framework it'll be easier for us to add tests that verify the behavior of MariaDB.
> [8.x] Add MariaDB to list of official supported databases

- deployment.md
PHP >= 8.0
PCRE PHP Extension is required by vlucas/phpdotenv which is requried by laravel/framework v9.0.0
DOM PHP Extension is required by tijsverkoyen/css-to-inline-styles which is required by laravel/framework v9.0.0
> Deployment - New server requirements

- upgrade.md
- Adds a hint that may be helpful to the upgrade guide in **TrustProxies** section
By following the actual Upgrade guide, I found the next issue:
This issue is caused because some Laravel projects that were started since 5.x can have the next line:
Since the new 9.x upgrade doesn't use **Fideloper\Proxy** this can cause the previous mentioned issue. To fix this problem you can change that line with:
> [9.x] - Added a line that need to be changed in TrustProxied.php at upgrade.md

- releases.md
In the section for the new `Rule::forEach` validation rule, it was misspelt as `Rule::foreEach`.
> [9.x] Correct typo for `Rule::forEach` validation section

- scout.md
In the section about the new `database` driver it says "indexing [...] is unnecessary when using the collection engine." If I am not mistaken I think it should refer to the database driver as the section about the collection driver has it's own paragraph about search engine indexing.
> [9.x] Fix typo in the scout docs

- queues.md
The section explaining the after_commit queue option was a bit unclear with regards to what transaction(s) Laravel waits for before dispatching a job within a database (see StackOverflow post asking this exact question - https://stackoverflow.com/questions/67943199/clarification-for-aftercommit-in-laravel-queues).
It is also a bit unclear what happens in cases where nested database transactions are used, for instance, a nested transaction where the parent transaction fails, but the child transaction succeeds eg:
Sorry for the screenshot, but I couldn't get the formatting to work properly.
In the example above, the job should not be dispatched because the parent transaction failed, even though the child transaction completed successfully. The proposed changes would make this, in my …
> Update wording explaining after _commit

- helpers.md
Looks like it's copied from `Str::substrReplace` and forgot to review its content.
> fix argument description of fluent substrReplace

- mail.md
- upgrade.md
The Symfony HTTP client is needed for the Mailgun and Postmark transports.﻿
> [9.x] Document http client

- filesystem.md
- upgrade.md
This PR notes the separate FTP driver that needs to be installed. I forgot to add this originally. I also moved the requirements in the filesystem docs to their respective section.﻿
> [9.x] Add FTP requirement

- installation.md
Since Laravel 9.0 has released, older installation commands should "downgrade" to 8.0.
Not sure what other command need to specify version, just started with this one.
> Added version number when install via Composer

- requests.md
api.symfony.com no longer exists. It was redirecting to GitHub before they shut it down.
It should be changed for older versions, too.
ie. Laravel 8 --> [https://github.com/symfony/symfony/blob/**5.4**/src/Symfony/Component/HttpFoundation/File/UploadedFile.php](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/HttpFoundation/File/UploadedFile.php)
> Replace Symfony API link

- redis.md
Since we're in a config file there is no current namespace and `use Redis` will generate a PHP warning. (Applies to 8.x docs as well)
> [9.x] Remove unnecessary use statement from Redis example

- cashier-paddle.md
Clarifies that the instance of a billable user needs to be an existing instance from the database. This wasn't always clear it seems.
> [9.x] Clarify instance of billable user

- helpers.md
This pull request adds `Str::excerpt` documentation: https://github.com/laravel/framework/pull/41000.
> [9.x] Adds `Str::excerpt` documentation

- queries.md
https://github.com/laravel/scout/pull/592
> [9.x] Remove redundant `return` key for `when` methods

- sail.md
The filesystems configuration under Sail's File Storage section was using wrong environment variable name FILESYSTEM_DRIVER. It should be FILESYSTEM_DISK.
> Update env variable example for sail minio

- broadcasting.md
Fixed Typo for broadcastsOn instead of broadcastOn.
> fixed typo `broadcastsOn` @ LN:885

- validation.md
Changed `Rule::foreEach` to `Rule::forEach` in the [Validation](https://laravel.com/docs/9.x/validation#accessing-nested-array-data) docs.
> [9.x] Fix Rule::foreEach typo

- scout.md
This adds basic information on how to use the currently-undocumented `query` callback method on Scout searches, and an example of using the method to eager-load related models in a result set. The section name is fairly arbitrary and probably needs adjustment, I wasn't sure how best to briefly describe the method's behavior and use case without naming it for something specific like eager loading.
> Adding Scout query callback documentation

- helpers.md
`lang_path` was originally added in Laravel 8.x.
[PR](https://github.com/laravel/framework/pull/39103)
> [9.x] Adds `lang_path()` documentation

- valet.md
I checked with @mattstauffer and he was okay with removing this. Lumen support is not explicitly removed from Valet.
> [9.x] Remove Lumen from Valet's support list

- installation.md
See https://github.com/laravel/sail-server/pull/9 & https://github.com/laravel/framework/issues/39182
> [9.x] Clarify allowed characters for site name.

- filesystem.md
Added new possible values for the SFTP Driver Configuration example.
The new optional values were added to match the order of the arguments for: `League\Flysystem\PhpseclibV3\SftpConnectionProvider`.
```
return new SftpConnectionProvider(
$options['host'],
$options['username'],
$options['password'] ?? null,
$options['privateKey'] ?? null,
$options['passphrase'] ?? null,
$options['port'] ?? 22,
$options['useAgent'] ?? false,
$options['timeout'] ?? 10,
$options['maxTries'] ?? 4,
$options['hostFingerprint'] ?? null,
$options['connectivityChecker'] ?? null
);
```
> [9.x] Added new env options for v3 sftp adaptor

- migrations.md
The `char` column type is modifiable now laravel/framework#41320
> [9.x] Add `char` to modifiable column types

- eloquent-mutators.md
If a user isn't aware that the `APP_KEY` isn't being used, they may regenerate an `APP_KEY` using the key generator command.
> Add warning about the possibility of losing encrypted data

- http-tests.md
Was confused what was a signed route in the testing documentation for "assertRedirectToSignedRoute" so this is adding a reference to the "signed route" documentation for convenience.
> Link to reference Signed Routes in assertRedirectToSignedRoute

- upgrade.md
Queue job instances implementing the `failed` method should accept the `Throwable` interface instead of `Exception`
> [7.x] Upgrade Guide Failed Queue Job

- eloquent.md
The anchor was changed from #streaming-results-lazily to #chunking-using-lazy-collections but some links still pointed to the old anchors.
> Updating to use proper anchor for links

- eloquent.md
When enabling soft deletes for a model, by adding the `Illuminate\Database\Eloquent\SoftDeletes` trait to the model, these 2 events are also being dispatched: `trashed` and `forceDeleted`.
> Add soft delete `trashed` and `forceDeleted` to the events list

- mail.md
- notifications.md
Ref: https://github.com/laravel/framework/pull/40783
> [9.x] Add mail/notification tags & metadata docs

- collections.md
The `reduceMany` function does not actually exist on the Collection class, instead its called `reduceSpread` as is documented below the `reduceMany` documentation. This causes confusion if one tries to use `reduceMany` instead of `reduceSpread`.
> Remove reduceMany from the Collection docs

- releases.md
Laravel 10 will not support php 8.0 according to the composer.json file of the master branch.
https://github.com/laravel/framework/pull/41250
> Remove support for php 8.0 for Laravel 10

- migrations.md
`dropFullText` was missing from the "Dropping Index" examples.
> Add missing `dropFullText` in examples

- collections.md
I think the second callback argument in the `when` collection method is an important part of the functionality.
> Added `when` second callback argument.

- helpers.md
Fixes the link as it was not working before and removes `()` so that the it's consistent with others.
> Fix lcfirst method link

- eloquent-resources.md
Adjust the code examples to use the `$request` variable that is passed to the `toArray` method when possible. I thought it might be nice if there was examples that used the Request that is passed.
> Update eloquent-resource toArray examples to use $request

- redis.md
The current documentation re: using Predis for Redis suggests uncommenting the Redis alias in config/app.php.  However, that commented out alias was removed when Facade::defaultAliases() was added.  This commit instructs users who are using Predis and who want a Redis alias to insert the alias into config/app.php
> update The Redis Facade Alias section of Redis docs

- mocking.md
This page should clarify the requirements for calling `UploadedFile::fake()->image()`. This method  [calls functions like `imagecreatetruecolor`](https://github.com/laravel/framework/blob/89e43ae6be9f173233e89a2f452f8a0c43f0e857/src/Illuminate/Http/Testing/FileFactory.php#L77), which requires the [GD Library](https://www.php.net/manual/en/function.imagecreatetruecolor.php). This extension is not always present by default, such as when working with a [PHP base image from Docker](https://hub.docker.com/_/php).
I hope I added the tip correctly. I was not sure how to preview it properly.
> [9.x] Review mocking - Clarify requirements for `image` method

- helpers.md
There are fine differences between different Markdown parsers. Without studying source code, it should be documented, which Markdown parser is being used.
> doc: add info about used markdown parser

- installation.md
This PR is to address the display on the list of server requirements. In dark mode the list of server requirements is not clearly legible. This problem exists in version 5.1 to 5.8
Light mode
Dark mode
> Fix Server Requirements list 

- validation.md
The merged pull request https://github.com/laravel/framework/pull/41691 adds a new `exlcude_with` validation rule in v9.0
> Update validation.md with new rule paragraph

- database.md
Support for 9.6 has ended on Postgres' side.
https://www.postgresql.org/support/versioning/
> Bump PostgreSQL minimum support version

- mocking.md
There's already a link to `Mail Fake` from `Testing Mailables`.
This reverse link would be helpful.
> Add a link to Testing Mailables

- broadcasting.md
Correct the namespace of Order model in broadcasting section
```https://laravel.com/docs/9.x/broadcasting#the-shouldbroadcast-interface```
> Correct order model namespace

- dusk.md
Since it has only 1 argument I think we don't need the text 'first' here.
> Unnecessary text in dusk press description

- http-client.md
Hey! This PR is only a really small one and just adds a typehint and 'use statement' to a code example.
When I was writing some tests today I needed to use the `Http::fake()` that allows you to define the response in a closure. I wasn't 100% sure what type `$request` would be straight away, but managed to figure out what it'd be by looking at the other examples on the page.
So, I just thought I'd propose adding the typehint to this example to make it a bit easier to tell what type `$request` is :)
> [9.x] Added type to closure

- authentication.md
onlyInput() uses PHP func_get_args() which receives value as ARRAY and converts to ARRAY.
onlyInput(['email']) - converts to multi-dimensional array. (latter in framework Arr::set() breaks code to TypeError)
onlyInput('email') - converts to simple array.
> onlyInput() method pass values as single array

- collections.md
As requested by @driesvints, I documented the `lazy()` method on the `Collection` class.
---
It's a little tricky to explain, and I'm not sure what tone we want here.
I mainly copied it from [this post](https://josephsilber.com/posts/2020/07/29/lazy-collections-in-laravel#converting-a-regular-collection-into-a-lazy-collection). I'll let Taylor tweak it to his liking.
> Document the eager `Collection`'s `lazy()` method

- billing.md
add the `tabPrice` method to the documentation for multiple items per invoice.
> add tabPrice for multiple items

- logging.md
In `\Illuminate\Log\LogManager::createDailyDriver()` one can find usage of the config setting `days` which isn't documented yet.
It seems helpful to mention this setting along with its default in the documentation.
> [9.x] Added undocumented retention policy for daily log channel

- container.md
The method was described as only having one argument, the closure. This is not true as its first argument is the service class that is being extended.
I believe the complex sentence might be why it has been overlooked for so long, so I simplified it and corrected the description to provide details on both arguments required by the method.
> Updated container 'extend' method description

- collections.md
Follow-up to #7866
1. Removed parenthesis that don't belong there.
2. Fixed the wording, so that it doesn't use one long run-on sentence.
> Improve `lazy()` docs

- dusk.md
Adds a section to the Dusk documentation describing the new `waitForEvent` method added in laravel/dusk#972, as requested by @taylorotwell.
I hope the text is clear, my written English is far from perfect.
Thanks for reviewing!
> Add docs for `waitForEvent` method

- blade.md
Hey! Thanks for the accepting the PR for anonymous component namespaces. 
@adelf contacted me via Twitter to point out a small mistake in the docs for this feature, so this fixes that example in the docs.
> Fix anonymous component namespace example

- valet.md
After discussing with @mattstauffer we decided to add an explicit note about custom tld usage. Even though Valet ships with a `tld` command to set a custom one we don't document this. This is because it can potentially lead to unexpected results (see https://github.com/laravel/valet/issues/1231). We believe Valet was intended to be used with the shipped `.test` tld and using a custom tld should only be done as a last resort. However, if you do so we can't offer support because there's too much unknowns that can lead to broken usage.
> [9.x] Add note about custom tld's

- http-client.md
Sample was showing `response` as a property on the recently added `$request` parameter when it is actually a property on `$exception` (when exception is an instance of `RequestException`).
> [9.x] Fix code sample showing incorrect usage

- blade.md
It's more intuitive to have them in their respective order 😄
> [9.x] Rearrange phrases in respective order (Blade)

- collections.md
I *believe* this was the intended syntax here, using PHP 8.0 named arguments. Apologies if I am incorrect :p
Couldn't find any other places where this occurred.
> [9.x] Improve `groupBy` preserveKeys argument syntax

- upgrade.md
It seems this was mistakenly referencing "number of recipients" which wasn't returned in the first place. That happened on transport level, not mail level. It's of more interest to document the Mailer return types of the most common methods.
Related: https://github.com/laravel/framework/pull/42035
> [9.x] Fix description of Mailer return types

- sail.md
Since [sail v1.10.1](https://github.com/laravel/sail/releases/tag/v1.10.1) the `extra_hosts` option makes the definition of the `XDEBUG_CONFIG` environment variable unnecessary for Linux.
I think the only thing to consider will be the [Docker Engine and Compose versions.](https://docs.docker.com/compose/compose-file/compose-versioning/#version-23)
The main reason to change this is that it could be confusing for people that use `sail down` and `sail up` since the internal IP address of the container will change every time is created. Other than that, as stated above, since the incorporation of `extra_hosts` the steps of Linux Host IP Configuration are no longer needed in most cases.
> Fix description of Linux Host IP Configuration

- horizon.md
Dashboard is _always_ accessible in local environment even if the `viewHorizon` gate is returning `false`.
PS: I was not able to test my `viewHorizon` gate in my local environment, as the gate is ignored. xD
> Dashboard is always accessible

- eloquent-relationships.md
custom pivot models can do more than just define methods, such as cast attributes. we'll also make the wording a little more open ended so the reader doesn't think the capabilities are limited.
> [9.x] update description of custom pivot model capabilities

- valet.md
This changeset is an attempt to more explicitly warn users away from
serving sites from within folders protected by macOS by default or give
them instructions on elevating Nginx's permissions to do so. I've
slightly reorganized the table of contents to create a 'Troubleshooting'
section and placed this information and the `Valet Directories & Files`
section is now an H3 and moved under the new Troubleshooting H2 section.
> A response to laravel/valet discussion #1207

- filesystem.md
The -W flag added in 2892fac027c04851f5193804bc5c58dc89ea9f63 was carried forward but is no longer required in a vanilla install. Addresses continuity with other commands that do not use the flag.
Best regards
> Continuity fix

- http-tests.md
I'm currently writing some tests on a project, then I run the psalm tool that finds this issue related to 
`Too many arguments for method hasAll, and the same for missingAll`.
Illuminate\Testing\Fluent\Concerns\Has::hasAll
```php
/**
* Assert that all of the given props exist.
*
* @param  array|string  $key
* @return $this
*/
public function hasAll($key): self
{
$keys = is_array($key) ? $key : func_get_args();
foreach ($keys as $prop => $count) {
if (is_int($prop)) {
$this->has($count);
} else {
$this->has($prop, $count);
}
}
return $this;
}
```
> [9.x] For multiple arguments for hasAll and missingAll, it would be an array.

- homestead.md
Updated the paths that were missing `.backup` in them.
> Correcting backup paths for database backups

- sail.md
This adds documentation for the new `testing` database introduced in https://github.com/laravel/sail/pull/388.
> Document Sail testing database

- collections.md
- dusk.md
- eloquent-collections.md
- helpers.md
- http-tests.md
- migrations.md
- validation.md
Some parts of the docs contain lists of methods in two or three different columns. They look good on larger screens, but for mobile, the links break:
This PR fixes this by making the columns responsive and makes sure the links don't take up more space than they should. For example, on mobile they might have one column:
And then they get bigger on medium screens:
And then back to three solumns on large screens:
Finally, in order to avoid having to create columns that are too wide, names that are too long will simply get cut off on smaller screens:
> Make columns responsive

- blade.md
The old sentence "You should define required component's data in its class constructor." could be read as that optional parameters for the component do not need to be specified in the constructor. I think other may have read it in the same way: https://github.com/laravel/framework/issues/36256
> Be specific what to add to components constructor

- mocking.md
An easier method to document on demand notifications was added here: https://github.com/laravel/framework/pull/39203
This easier method is now documented instead of the old verbose way.
> Documented new feature

- collections.md
Illuminate\Support\Enumerable contract now defines a sole method in Laravel 9
> Add `sole` method to Enumerable available methods

- requests.md
I needed to disable `TrimStrings` just for one webhook controller, and I discovered this method looking at the source code. I thought it would be useful to surface it in the docs.
> Add documentation for TrimStrings::skipWhen

- validation.md
Fixes the example of `Rule::in` to the correct usage.
See https://github.com/laravel/framework/issues/42399
> [9.x] Fix example for Rule::in

- migrations.md
Related to issue: https://github.com/laravel/framework/issues/42336
**The problem**
The documentation currently states the following:
`The default modifier accepts a value or an Illuminate\Database\Query\Expression instance. Using an Expression instance will prevent Laravel from wrapping the value in quotes and allow you to use database specific functions. One situation where this is particularly useful is when you need to assign default values to JSON columns:`
The problem is that the ChangeColumn is currently looking at the difference between two doctrine objects and utilizes the Doctrine DatabasePlatforms to generate sql to alter a table. The problem is that the SQL is generated by a database platform which does some validation but does not know about Laravel itself, so when DB::raw or …
> [9.x] Document the usage of expressions and raw statements within the default() modifier

- routing.md
Added the 2 parameters that the custom response callback is called with in the ThrottleRequests::buildException method. I tried to implement my own custom response and lost the throttle headers (X-RateLimit-Limit, etc). It was not obvious to me how to get the header info into my response. I tried to dig through the code, but missed the spot where the callback is called. Got a response to my problem on Laracasts, through I'd help put it in the docs for others.
> Updating custom throttle response.

- ssh.md
It does not work when you click on "Notifications". This PR will solve the problem.
> [4.2] Envoy Task Runner's Notifications link fixed

- scout.md
Every now and then (admittedly not very often) you might have different models registered on different search engines. This PR adds to the scout docs explaining how to override on a model basis the engine it is using - removing the need for hot swapping configuration at runtime.
```php
<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\EngineManager;
use Laravel\Scout\Searchable;
class User extends Model
{
use Searchable;
/**
* Get the value used to index the model.
*
* @return \Laravel\Scout\Engines\Engine
*/
public function searchableUsing()
{
return app(EngineManager::class)->engine('meilisearch');
}
}
```
> [SCOUT] Adding Declaring Model Engine to Scout docs

- artisan.md
- mix.md
The sail binary is referenced as `./vendor/bin/sail` across all the docs pages, except for the sail docs page (where the alias is referenced).
This is however neither the alias or the vendor bin path and this is a left over from O.G. sail when it was copied into the root.
> [9.x] fix sail binary references

- validation.md
See https://github.com/laravel/framework/commit/c6d1a2da17e3aaaeb0ff5b8cc4879816d214b527
And see https://github.com/laravel/framework/pull/42562
> [9.x] Fix documentation for digits rule

- validation.md
This adds the validation response format with an example of a validation response containing
- A flat key
- A nested object key
- An array with nested objects
Which i feel gives a pretty good example of the response format in general.
> [9.x] Add validation response example

- collections.md
It seems the current behavior isn't properly documented. This got documented here: https://github.com/laravel/docs/pull/6212.
But the current behavior is actually differently. I also didn't expect the current behavior but think we shouldn't change this as it could maybe lead to breaking changes? I think it's best to just properly document the current behavior instead. 
There also don't seem to be any tests about this behavior in the framework right now.
See https://github.com/laravel/framework/issues/42653
> Fix pluck example using dot notation

- sail.md
I added the missing `coverage` value to `SAIL_XDEBUG_MODE` in order to have `php artisan test --coverage` working, this was missing in the docs.
> [9.x] Added coverage to SAIL_XDEBUG_MODE

- queues.md
This PR replaces the suggested `protected` properties on the example jobs for `public`.
This aligns the `Bus::assertDispatched()` documentation which suggests public properties for testing:
https://github.com/laravel/docs/blob/9.x/mocking.md#bus-fake
```php
Bus::assertDispatched(function (ShipOrder $job) use ($order) {
return $job->order->id === $order->id;
});
```
This is a small hiccup for new Laravel users, since they may copy the example and go to test, puzzled that the test docs show accessing a `public` property but the example jobs show `protected`.
> [9.x] Suggest `public` job properties for `Bus::assertDispatched()` testing

- sail.md
I'd love to convey 2 messages here:
1. Base URL has to be explicitly defined in order to be generated well by the [Filesystem](https://github.com/laravel/framework/blob/15b45877b2e8928635bfd3ebe28b536f8b5e7aec/src/Illuminate/Filesystem/AwsS3V3Adapter.php#L46) in Sail.
2. When updating the base-URL, old files need to be re-uploaded to have the correct URL.
So with the default settings shown in the [docs](https://laravel.com/docs/9.x/sail#file-storage), a file will have `http://minio:9000/example.file` URL which will cause a `GET net::ERR_NAME_NOT_RESOLVED` error.
But if we add an `AWS_URL=http://localhost:9000/local` environment variable, and **upload the file again**, then the Filesystem will generate the correct URL for it. ( `http://localhost:9000/local/example.file` )
Note: I haven't …
> [9.x] Noted about explicit base-url generation for MinIO in Sail

- broadcasting.md
Looking at the laravel-echo [source](https://github.com/laravel/echo/blob/cd608aac40f136b9a50da8b1785615cadf95b04c/src/connector/pusher-connector.ts#L29) it expects an instance (as the title suggests), not the class.
> Fix example in 'Using An Existing Client Instance'

- vite.md
Without the leading slash on the aliases, Vite fails to find the import correctly. Typically I've adjusted Vite aliases by calculating a path. I've given an example of this at the bottom of this PR. I think it could be justified to adjust the docs to the commonplace `path.resolve` version, but didn't want to create an overly complex PR when just adding the leading slash seems to work.
```typescript
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import path from 'path';
export default defineConfig({
plugins: [
laravel(['resources/ts/app.tsx']),
],
resolve: {
alias: {
'@': path.resolve(__dirname, './resources/ts'),
},
},
});
```
> Vite - Add leading slash on aliases

- octane.md
It appears that every start command has 500 as the default value for `max-requests`:
https://github.com/laravel/octane/blob/master/src/Commands/StartCommand.php#L23
https://github.com/laravel/octane/blob/master/src/Commands/StartRoadRunnerCommand.php#L29
https://github.com/laravel/octane/blob/master/src/Commands/StartSwooleCommand.php#L27
This change clarifies that the limit is already enabled.
I'm not sure, but maybe "specify `0` to disable reloading" is also worth specifying?
> Clarify octane max-requests defaults

- blade.md
Fixes a few references to directories that were written using namespace syntax.
> [7.x] Fix directory paths in Blade docs

- blade.md
Fixes a few references to directories that were written using namespace syntax.
> [8.x] Fix directory paths in Blade docs

- blade.md
Fixes a few references to directories that were written using namespace syntax.
> [9.x] Fix directory paths in Blade docs

- vite.md
See: https://github.com/laravel/vite-plugin/pull/43, https://github.com/laravel/vite-plugin/pull/55
> [9.x] Document Vite refresh option

- starter-kits.md
When installing version 8 of the laravel/framework, we need to install a specific version of the breeze package.
> fix: clarified breeze version

- validation.md
This PR is to fix the **available validation rules** section in v5.1, now on the website it shows like this 
After fixing it shows like this
> Fix available validation rules section in v5.1

- authorization.md
See: https://github.com/laravel/framework/pull/43097
> [9.x] Authorization HTTP status customisation

- contributions.md
- documentation.md
- pint.md
This pull request adds Laravel Pint documentation. Note that, this pull request its on draft, as it should be only merged on the day we tag the next version of `laravel/laravel`.
Related to: https://github.com/laravel/laravel/pull/5945, https://github.com/laravel/docs/pull/8043.
> [9.x] Adds Laravel Pint documentation

- configuration.md
- packages.md
This pull request adds documentation to the new `about` command.
> [9.x] Document `about` command

- sail.md
On first run, the MinIO container starts without any buckets. Clarify to indicate that on first run the user must create the `local` bucket.
> Update sail.md to reflect initial setup for MinIO

- upgrade.md
I'm adding this because I faced this in our app. This is the message I originally sent to Laravel's Discord for help
> In Laravel 8 I override the method `getHttpExceptionView` from the Exception Handler class and changed the binded instance with this code
> 
> ```php
> app()->bind(\App\Exceptions\Handler::class, Handler::class);
> ```
>  
> I did it this way because I need to change the path for the error views depending on the URL you're visitng. Like different app domains
> 
> This code does not work anymore with Laravel 9.
> Explain how to bind Exception Handler after upgrade

- scout.md
Whilst the ability to pass an array of queue configuration details to the `scout.queue` option is possible, it was not previously documented.
> Update Scout docs to clarify configuration of queue connection and name

- cashier-paddle.md
I've updated the link to Paddle dashboard, because the previous one returned 404.
Based on the context, I assumed it should link to dunning settings:
Let me know if that's not what the old link was representing.
> [9.x] Fix Paddle dunning link

- horizon.md
The last sentence in the balancing block was slightly confusing to read. I believe this more clearly reflects what the default behavior is. Also removed an erroneous 'to'.
> Remove erroneous 'to' and clarify balancing behavior.

- vite.md
I had version 14 installed, and I got an error message: `module node:path not found`.
After upgrading to Node 16, it works fine.
> Add Node version message

- vite.md
This PR adds documentation for https://github.com/laravel/framework/pull/43442 which allows developers to configure CSP, SRI, and other arbitrary attributes on the script and style tags generated by Laravel when using Vite.
> [9.x] Document Script & Style Attributes with Vite

- starter-kits.md
`npm run dev` keeps running so it's better to put `php artisan migrate` before this command so that it executes successfully if copied and pasted for execution.
> Made installation scripts order suitable for exec

- billing.md
Right now, the Cashier Stripe docs aren't on par with the Stripe docs when it comes to subscriptions with multiple products. We speak of "Multiprice Subscriptions" but this isn't a correct overlap with how Stripe names these: "Subscriptions with Multiple Products". The main differentiation is that Stripe indicates that the subscription could hold multiple products and not necessarily multiple prices from the same product. This is an important gotcha. I feel our own docs should follow this.
See the Stripe docs and their own terminologie here: https://stripe.com/docs/billing/subscriptions/multiple-products
> [9.x] Improve wording for subscriptions with multiple products

- vite.md
This fixes a mistake in the Vite CSP middleware example
> [9.x] Fix Vite CSP middleware example

- contributions.md
According to https://github.com/laravel/framework/pull/43488#issuecomment-1200441200 the 8.x branch is no longer supported for bugfixes ...
> Updated the bugfix branch

- filesystem.md
Fix the filesystem config option that corresponds to the `AWS_ENDPOINT` environment variable.
> Fix filesystem config option name for S3

- http-client.md
There was original no documentation for the recorded method for HTTP faking. this pr adds that documentation.
> [9.x] added documentation for the Http record method

- sail.md
This PR updates the "Configuring a Bash Alias" section of the documentation by making the following changes:
* Renames the section to "Configuring A Shell Alias" because this is not Bash-specific, and Bash is no longer the default shell on macOS.
* Updates the alias to not depend on `bash`. `sh` should be a safe alternative, but it also seems to work fine without specifying a shell.
* Adds a note on adding this to the user's shell configuration to make it always available. I've seen people run the alias command in their terminal, run `sail up`, and then open a new terminal and are understandably surprised when `sail artisan migrate` doesn't work. I'm not sure if specifying actual filenames is a little dicey, but hopefully, it at least helps the user understand that they need to take …
> [9.x] Update Sail shell alias docs

- sail.md
Documents the limitation at https://github.com/laravel/sail/issues/453.
> [9.x] Document MinIO limitation with temporaryUrl

- upgrade.md
Support for `pusher/pusher-php-server:^4.0` was dropped in Laravel 9 (see https://github.com/laravel/framework/pull/36528 ).
Because the constraint is just a `suggest`, users are not prevented from running Laravel 9 with `pusher/pusher-php-server:^4.0`. Users with this combination will experience runtime errors like `preg_match(): Argument #2 ($subject) must be of type string, array given`
(I wasn't sure where to fit in this "please upgrade this optional package" text in the docs)
> Mention pusher/pusher-php-server upgrade from ^4.0|^5.0 to ^5.0 in upgrade guide

- validation.md
This PR update doc for validation rules `doesnt_start_with` ([#42683](https://github.com/laravel/framework/pull/42683), [de35bf2](https://github.com/laravel/framework/commit/de35bf2a8ab40013d997c62b5a80cdb907c73b99)) and `doesnt_end_with` ([#43518](https://github.com/laravel/framework/pull/43518) _not yet released_)
> Added doc for validation rules `doesnt_end_with` and `doesnt_start_with`

- packages.md
As outlined in https://github.com/laravel/framework/pull/43329, I believe that we should only promote the use, internally and in the docs, of the lazy binding of data values to the about command.
This can improve boot performance and memory usage for invocations of the framework for via an incoming HTTP request or console command.
Additionally, I've suggested moving the example to the `boot` function rather than the `register` function. This is to ensure that services have completely booted before they are interacted with, e.g. if someone is adding a value from the cache or DB into the mix:
```php
AboutCommand::add('My Package', 'Average throughput', Cache::get('avg_thoughput'));
```
we'd want this specified in the `boot` func to ensure the Cache is actually ready for use. The closure …
> [9.x] promote lazy about command registration in boot function

- collections.md
The Laravel docs do not provide a clear list of comparison operators for collections.
> [9.x] Adds collection comparison operators list

- homestead.md
Docker was moved to the base box on `laravel/settler` and can no longer be installed as optional software.
https://github.com/laravel/settler/commit/8b1f706f507d2be1b019d178955bb6b98e996582
https://github.com/laravel/homestead/pull/1716
> [9.x] Move Docker to "Included Software"

- mocking.md
It previously was not possible to fake only a subset of jobs - now it is but needs to be documented.
> Document faking a sub-set of jobs

- vite.md
This PR adds documentation for the `withoutVite` test helper.
> [9.x] Document `withoutVite` method

- eloquent-relationships.md
I came across this method the other day and have had many use cases for it but was unaware it existed. This PR adds a mention to the docs. I'm not sure where it is best to go, whether with `Querying Relationships` or `Eager Loading` as it covers both. I've tried to keep the example relevant with other examples in the eager loading section.
https://github.com/laravel/framework/pull/42597
> [9.x] Add `withWhereHas` documentation to Eloquent

- installation.md
This PR updates the documentation regarding the `sail up` time due to the changes from the following PRs:
* https://github.com/laravel/sail/pull/467
* https://github.com/laravel/sail/pull/468
* https://github.com/laravel/sail-server/pull/11
> [9.x] Update docs regarding `sail up` time

- vite.md
Depends on: https://github.com/laravel/framework/pull/43702
---
Note that we are attempting to improve this experience in the further by allowing assets to be specified in the Vite config and rather than via an entry point, so these docs will be iterated on once we improve things. Currently we are waiting on https://github.com/vitejs/vite/pull/9693 to be merged / tagged before we can continue on, so this is a nice stopgap solution.
> [9.x] Including static assets in Vite builds

- validation.md
Clarify what "empty" means when using prohibited.
See https://github.com/laravel/framework/issues/43776
> [9.x] Clarify prohibited

- facades.md
The url of vite facade api document should be `https://laravel.com/api/9.x/Illuminate/Foundation/Vite.html` which apparently is not ready yet.
But I'll send a PR anyway.
> [9.x] Add Vite Facade to Class Reference

- collections.md
A layout change to add columns for the previously unreadable list https://laravel.com/docs/9.x/collections#the-enumerable-contract
I copied the column style from https://laravel.com/docs/9.x/validation#available-validation-rules as seen here:
https://github.com/laravel/docs/blob/7635641c79c76dd30c3c0987a982577da5f4ddf2/validation.md?plain=1#L785-L798
> Update collections.md layout

- queues.md
Adds more explicit documentation to the 'Dispatching Jobs' section regarding Laravel's default queue connection of `sync`.
I am using queues in Laravel for the first time, and this was a footgun for me. As I was trying to dispatch jobs to my queue, I noticed that they were running synchronously and I immediately assumed I was doing something wrong, even though I followed the docs. I would expect this to be documented a little more explicitly which would have helped with my development experience.
> Update queues.md - add explicit documentation of `sync` default queue connection

- helpers.md
Since we are examining a sequential array, variable name should be $isList instead of $isAssoc 
- seem that $isAssoc was accidentally copied from previous helper docs
> $isAssoc variable name is misleading in isList() helper documenation

- installation.md
I've noticed that the installation docs don't mention `laravel new`. Maybe I missed that it'ss deprecated, if so, please ignore this PR. Otherwise, it would be great to see it in the docs.
I suggest:
* mentioning the basic usage in a compact way in the installation guide
* (in a separate PR), move the docs tregarding the `-git` and other command-line options to the `README.md` of the `laravel/installer` repo, and link the installation page to it.
> Return installation using `laravel new` to docs

- validation.md
See: https://github.com/laravel/framework/pull/43868
> **Warning**: This is a change that should likely be recorded in the Upgrade Guide for 10.x.
> [10.x] Make invokable rules default

- validation.md
Note that the range specified in the 'between' validation rule is inclusive.
I needed to know this today, and I couldn't find it anywhere. I had to test it to find out.
> [9.x] Note that the range specified in the 'between' validation rule is inclusive

- eloquent-mutators.md
I found the current docs about this super confusing as the object referenced is a value object rather than a model. Hoping to clarify this with proper namespaces.
> [9.x] Improve cast value object docs

- eloquent-mutators.md
The current docs have two things that need to be adjusted to give better clarity into the `decimal` cast.
First, there is a space between "decimal:" and "<digits>" that is created because of putting two code blocks next to each other. It could easily be conceived that the cast should be written as `decimal: 2`, for example with a space between the colon and the precision value. This PR corrects that by wrapping the entire cast example in a single code block.
Secondly, the "digits" parameter has been changed to be "precision" as that gives better understanding as to what that value is intended to do/be. While the `asDecimal` method in `HasAttributes` and the `number_format` function call this parameter "decimals", both "decimals" and "digits" are vague as to their intended purpose in the …
> Decimal cast update

- queries.md
See: https://www.sqlite.org/json1.html
> The JSON functions and operators are built into SQLite by default, as of SQLite version 3.38.0 (2022-02-22). They can be omitted by adding the -DSQLITE_OMIT_JSON compile-time option. Prior to version 3.38.0, the JSON functions were an extension that would only be included in builds if the -DSQLITE_ENABLE_JSON1 compile-time option was included. In other words, the JSON functions went from being opt-in with SQLite version 3.37.2 and earlier to opt-out with SQLite version 3.38.0 and later.
The code for this is already supported as a result of PR https://github.com/laravel/framework/pull/41802
> [9.x] SQLite 3.38.0+ Supports whereJsonContains

- blade.md
Insted of selected="selected", that sounds very old and to prevent horizzontal scroll on desktop
before:
after:
> HTML5 selected attribute

- session.md
The Session `missing()` method will return `false` if the item is `null`, since it's defined as the inverse of the `exists()` method:
https://github.com/laravel/framework/blob/fc9dc59b8e9f42092cc0499a56c357265acb2ed4/src/Illuminate/Session/Store.php#L268
> [9.x] Fixed the Session `missing()` method description

- vite.md
Replaces "public directly" with "public directory" in vite.md
> [9.x] Fix typo in vite.md

- artisan.md
This pull request adds documentation about Signal Traps.
https://github.com/laravel/framework/pull/43933
> [9.x] Adds documentation about Signal Traps 🚦

- billing.md
The current documentation on the creation of new subscription with payment on invoice does not work until the `days_until_due` argument is supplied. So I modified the example code snippet to: 
```
$user->newSubscription('default', 'price_monthly')->createAndSendInvoice([], [
'days_until_due' => 30
]);
```
> Fixing new subscription via invoice example

- validation.md
All the other rules seems to have the prefix `rule-`
> Fix inconsistent link to `multiple-of` rule

- queues.md
It would be great to mention the default `hours` option value for the `queue:prune-failed` command.
```
protected $signature = 'queue:prune-failed
{--hours=24 : The number of hours to retain failed jobs data}';
```
> [9.x] Add default behaviour of `queue:prune-failed`

- migrations.md
Related to laravel/framework#44101
> [9.x] Add `double` and `tinyText` to list of modifiable columns

- vite.md
> [9.x] Update TLS configuration options

- vite.md
Just noticed a small issue in the docs.
When using Pest if the setUp method is public you will get the following exception error
Corrected the docs updated the setup method to protected matching Pest Testable trait and the default BaseTestCase.
> Corrected access level for TestCase setUp method when using Pest

- helpers.md
- testing.md
This pull request adds documentation for the `Benchmark` facade.
Refers to https://github.com/laravel/framework/pull/44252.
> [9.x] Adds `Benchmark` facade documentation

- seeding.md
Where the `DB` command uses the `--class` option, the `migrate` command uses `--seed`, this can be confusing and may mean other developers miss this as an option.
> Add reference to --seeder option

- dusk.md
Github Actions allows you to place environment variables at either the "workflow", "job", or "step" level.  This commit moves them from the "step" level to the "job" level.
https://docs.github.com/en/actions/learn-github-actions/environment-variables
Dusk is a unique situation because running `php artisan dusk` starts the tests in one process, but hitting `$this->browse()` within the test spawns a **new** process, that **DOES NOT** inherit the environment variables set at the "step" level.
Therefore, for Dusk CI on Github, it's better to set ENV variables at the "job" level so both the "test process" and "browser process" inherit them.
Added the `DB_USERNAME`, `DB_PASSWORD`, and `MAIL_MAILER` env variables. The current value in the default `.env.example` for the password is empty, so …
> [9.x] Move environment variables to the "job" level

- dusk.md
This PR adds a basic documentation about the `phpunit.dusk.xml` file and also updates the phpunit link to the one dusk [currently uses](https://github.com/laravel/dusk/blob/8409095a4022386b3649965086966669299726da/composer.json#L27).
> [9.x] Update outdated PHPUnit link and add simple documentation about phpunit.dusk.xml

- eloquent.md
The command `php artisan make:scope MyScope` will put the scope in the `App\Models\Scopes` namespace. This PR will update the example code namespace.
> [9.x] Change global scope namespace to `App\Models\Scopes`

- octane.md
It should not be ended after adding the configuration.
> [9.x] Use `,` instead of `;`

- vite.md
Remove first punctuation in file path.
> [9.x] Fix error wrong locate

- passport.md
* laravel/passport#1567
* laravel/passport#1569
* laravel/passport#1577
> [9.x] Document prompt parameter when redirecting for authorization

- routing.md
This PR will improve the route model binding documentation by explicitly stating that only string-backed Enums are supported in implicit Enum binding.
The feature that was introduced in [#40281](https://github.com/laravel/framework/pull/40281) explicitly ignores int-backed Enums which potentially leads to confusion because the binding just silently won't work when using Enums backed by integers.
> Improve implicit Enum binding documentation

- vite.md
This PR fixes the Torchlight annotations on the `Asset Bundling (Vite)` page.
In some annotations, the exclamation mark is placed before `tl`, but it should be placed after to be interpreted correctly.
This currently results in additional comments being rendered in the docs, as the following screenshot illustrates.
> [9.x] Fix Torchlight annotations

- eloquent.md
The AncientScope class is declared above with the namespace `App\Models\Scopes` but is then imported from `App\Scopes\AncientScope`. The namespace does not match the declaration nor the default structure when created with the `make:scope` command.
> Use consistent namespace for AncientScope

- migrations.md
The goal of this PR is to document an opaque part of Laravel: if you are [squashing migrations](https://laravel.com/docs/9.x/migrations#squashing-migrations), the documentation should explain which file name is used when running a migration. It uses the connection name to find out the schema file in your database folder. That's explained in the changes to the migrations.md file.
Happy coding!
> [9.x] Document which dump file Laravel picks when running migrations

- scheduling.md
`quarterlyOn` was missing from scheduling page
> [9.x] Add missing `quarterlyOn`

- mail.md
Typo in example: assertHasAttachementFromStorage and assertHasAttachementFromStorageDisk both have an 'e' too many.
> Typo in example

- migrations.md
Removed typo with extra square bracket
> Fix markdown typo on migrations.md file

- testing.md
Parallel testing will automatically create your testing databases but not your "main" database which you still need to run migrations, etc.
See: https://github.com/laravel/framework/issues/44806
> Clarify main database requirement

- middleware.md
In the documentation, the `\Illuminate\Foundation\Http\Middleware\HandlePrecognitiveRequests::class` middleware class is not listed on the array `$middlewarePriority` but is present on the implementation of `Illuminate\Foundation\Http\Kernel`.
> [9.x] Add missing middleware to $middlewarePriority list

- octane.md
As requested in https://github.com/laravel/octane/issues/609, this PR adds information about the maximum number of tasks that can be passed into `Octane::concurrently` at once.
> Add information about maximum number of Octane concurrently tasks

- pint.md
Hi,
to show the version of pint it must be with the "v" in uppercase, used like this in the example will start Pint with applying the changes.
-v (lowercase)
```
./vendor/bin/pint -v 
.................................................................................................................................................................
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── PSR 12  
PASS   ...................................................................................................................... 123 files  
```
-V  (uppercase)
```
./vendor/bin/pint -V
Pint …
```
> Updated pint version command typo

- filesystem.md
Scoped and read-only filesystems require additional Flysystem packages.
See https://github.com/laravel/framework/issues/44935
> document scoped and read-only filesystem dependencies

- validation.md
See: https://github.com/laravel/framework/pull/44883
> [9.x] Adds "lowercase" validation rule documentation

- sail.md
When the full path contains uppercases characters, Docker complains with `docker: invalid reference format: repository name must be lowercase.`.
By encapsulating the path in quotation marks, this problem is solved. This pull request implements that.
See also: https://stackoverflow.com/a/52818152/7410951
> Added quotation marks around docker run command

- pint.md
To show the thorough list of updated files the flag here needs to be lowercase `-v` not `-V` which instead provides the version number of Pint.
> [9.x] Fix Pint Verbose Flag Typo

- container.md
The `app()` helper is (probably) the most concise way of resolving an instance from the container, but it's not mentioned in context next to the other methods. This PR adds that information.
> [9.x] Add mention of the app() helper in the Container docs.

- queues.md
- add notes for queued callbacks to not use '$this'
s. https://github.com/laravel/framework/issues/38573 for a similar case related to batches
> [9.x] Add note to 'Chain Failures' and 'Queueing Closures' section to not use '$this' in callbacks

- helpers.md
Adding documentation for the fluent string helper `headline`. 
```php
$headline = Str::of('string_here')->headline()
```
> Documents the fluent string helper `headline`

- upgrade.md
It is not clear what traits were part of the authentication scaffolding since they are mentioned individually in multiple places in previous versions of the docs.
Users upgrading from older versions may not know whether they are using those traits or not.
In this PR, I am adding a link to the commit where the list of files can be checked. Alternatively, we could also list all traits directly in the documentation instead of linking to a commit.
> Add link to the list of moved scaffolding files

- controllers.md
`Singleton` method is a great addition to existing options, however, `apiSingleton` is undocumented. It's pretty intuitive for a seasoned developer, not so much for someone starting with the docs.
It's a single addition that should clear this up.
> [9.x] Add apiSingleton documentation

- http-tests.md
I found myself wanting to make an assertion similar to what was proposed within this [PR](https://github.com/laravel/framework/pull/43846) and didn't realise you could pass a closure to the `->where()` method so figured a few examples in the docs would help with visibility.
> [9.x] Include closure examples for where JSON assertions

- validation.md
The `lowercase` and `uppercase` validation rules don't have any parameters.
> Fix the syntax of lowercase and uppercase rules

- scout.md
The current documentation for `Configuring Indexes Settings (Meilisearch)` may imply that ONLY `filterableAttributes` can be configured.
This PR intends to clarify that other supported fields can also be configured. These includes `searchableAttributes`,`filterableAttributes`,`sortableAttributes`,`rankingRules`, `stopWords`, and [settings supported by Meilisearch](https://docs.meilisearch.com/reference/api/settings.html#settings-object).
Each of the fields serves different roles e.g
- `searchableAttributes` - the fields that should be checked for matching query words
- `filterableAttributes` - fields that can be used to filter results using Scout's `where` method.
- `sortableAttributes` - fields that can be used to to sort search results using Scout's `orderBy` method.
> Clarity for Meilisearch Configuring Indexes Settings

- facades.md
More language that, sounds fine when talking to native English speakers, it just doesn't add to the clarity of the docs.
> Remove "under the hood"

- passport.md
the latest version of Passport does not support Laravel 5.8,
we have to install an earlier version.
> add passport version

- scout.md
Added documentation for manage good fltering on meilisearch.
Since meilisearch can perform `>`, `>=`, `<`, and `<=` only on numeric values and will ignore all other types of values.
[https://docs.meilisearch.com/learn/advanced/filtering_and_faceted_search.html#conditions](https://docs.meilisearch.com/learn/advanced/filtering_and_faceted_search.html#conditions)
Specifying attributes types allows meilisearch to filter attributes correctly, otherwise it will ignore filter request. 
E.g.: if you try to filter `price < 500`, without specifying types, meilisearch do not perform filtering. 
Instead, setting `price => (int) $price,` into `toSearchableArray()` will filter models that have `price < 500`
> Added colum type docs for filtering in meilisearch

- validation.md
> [9.x] Add `ascii` and `ulid` validation rules

- notifications.md
https://github.com/laravel/framework/pull/45264
> add viaConnections to notifications doc

- queues.md
I tried to integrate the clarification into the existing text instead of introducing a notice. As per requested on #8415
Original ticket text below
I stumbled on this edge case (of feature) in Laravel while working on a client code base and couldn't find any documentation for it. 
Apparently a job with `0` $tries will be retried indefinitely. What is more, I tried defining `0` on the job and `1` on the worker, because if `0` meant infinite then,  `1` attempt  would be more specific to `infinite` attempts right? But the Laravel workers doesn't check for specificity, it is the default if the Job didn't specify anything. 
The word `specific` threw me off, because what does it mean to be more specific? In this case it meant: The job as a `$tries` set, which means it is more granular and thus …
> Add clarification for job attempts

- validation.md
Not knowing this causes problem when the _format_ contains `,` character. `date_format:D, d M Y H:i:s` should be `date_format:"D, d M Y H:i:s"` to work as expected.
> The date_format validation rule accepts a list of formats

- cashier-paddle.md
This part was still using the old way of overwriting the webhook while you now have a more easier way to listen to an event.
> [9.x] Rewrite docs on failed subscription payments

- queries.md
Documents the possibility of passing a query object to `whereIn` method family as the second parameter.
This feature is tested in this PR: https://github.com/laravel/framework/pull/45452
> [9.x] Passing a subquery to whereIn

- validation.md
Apparently the `:input` parameter gets replaced for all validations as well, allowing you to show the user input in the validation message. I was unaware of this feature and I had to dig into the code.
I found the placeholders `:index` and `:position` as well and together with `:attribute` those seem to be the 4 placeholders that will be replaced at all times.
> [9.x] Improve validation placeholder replacements

- valet.md
ref: https://github.com/laravel/valet/issues/1322
This PR is a change suggestion for the "Upgrading/Resetting Valet" command from `composer global update` to `composer global require laravel/valet`
`composer global update` for some reason won't bump to a major version (from 2.18.10 to 3.2.2)..even `composer global update laravel/valet` won't do it.
Using the same installation command might be confusing for some users; however, it seems to be the safest way to upgrade.
> [9.x] change upgrading valet command

- upgrade.md
I spent several hours analyzing every potential edge case that could result in breaking changes on my types PR for the core of Laravel. After thorough review, I have determined that there are no possible breaking changes. Therefore, the upgrade guide for this PR will be empty.
Of course, I've added a small note explaining this to the user.
> [10.x] Types upgrade guide

- sail.md
Hello, default node version installed from Dockerfile is 18 now.
> Update default node version to 18

- billing.md
The `php artisan cashier:webhook` command creates a webhook which also listens for the `invoice.payment_succeeded` event. I've added it to the list to ensure people don't miss it when creating the webhook and adding events manually instead of using the command.
> [9.x] Add missing Cashier Stripe webhook event

- authorization.md
- facades.md
- logging.md
- releases.md
- scheduling.md
- valet.md
This should fix the problem where tables sometimes overflow and cause the entire page to become horizontally scrollable.
To reproduce: open this [page](https://laravel.com/docs/master/releases) on a mobile device.
Device: Pixel 4
Before:
After wrapping the table with a div with overflow set to auto:
> Fix table overflow

- sail.md
Updated Laravel Sail documentation to consider PHP 8.2 in the installation instructions for existing projects.
> [9.x] Update Laravel Sail Docs

- eloquent-collections.md
- eloquent-serialization.md
This PR documents the `setVisible` and `setHidden` methods on Eloquent models and collections.
> [9.x] Document `setVisible` and `setHidden`

- mail.md
I think the example for the mailchimp custom transport needs to be updated.
I followed the example given while trying to create a custom transport and ran into an issue.
Without calling the parent constructor for AbstractTransport the following exception is thrown:
```
Typed property Symfony\Component\Mailer\Transport\AbstractTransport::$dispatcher must not be accessed before initialization
```
> Custom mail transport needs to call parent constructor

- http-client.md
The `withHeader` method returns a request instance with the provided value replacing the specified header and doesn't change the current request itself.
> [9.x] Fix Guzzle Middleware example

- filesystem.md
This information is hidden on the pages relating Laravel Sail. I consider it be note worthy here as well. I spent hours on researching for bugs and upgrade package versions only to accidentially read the actual reason in the docs relating Laravel Sail.
> Copy filesystem informations from sail to filesystem | Minio |  AWS_URL + temporary urls

- validation.md
As it currently stands, and with our recent work on prohibited, the prohibited rule does allow an empty string; it is not implicit.
This may be merged independently of the other PRs, as this is currently correct.
> [9.x] Reverts prohibited definition

- filesystem.md
Currently the documentation does not mention `Storage::mimeType()`. This PR adds a small line of documentation to bring awareness to this function.
> [9.x] Added documentation for Storage::mimeType()

- queues.md
The current link is not dead as it redirects to the new page, but the anchor is lost with the redirection.
> Queues: fix link to Redis Cluster docs

- upgrade.md
This pull request adds Laravel Ignition v2 to Laravel 10's upgrade guide.
> [10.x] Adds Laravel Ignition v2 to Laravel 10's upgrade guide

- mail.md
The current documentation was missing a few steps needed to use other symfony transports.
I've updated the composer require command to include the `symfony/http-client` depdendency and added docs about adding the new transport to `config/mail.php`
> Adds some missing steps when using additional symfony transports

- queries.md
Updated the `whereExists` docs to include the new ability to pass closures OR query objects.
Hi! First time pusher. I was looking for a way to pass a query object to the `whereExists` method just like the `whereIn` method has. After realizing it didn't exist yet I went to the repo to see how hard it would be to implement, but thankfully the wonderful @gdebrauwer had already done it(twice)! So I'm doing my small part by getting the docs updated so everyone knows about it.
> [10.x] Adds docs for `whereExists` query objects

- upgrade.md
I've updated the "Service Mocking" link in the Upgrade Guide because it wasn't redirecting the user anywhere.
> [10.x] Fix Service Mocking Link on Upgrade Guide

- sail.md
This PR updates the default PHP version currently used by sail for v9.x.
Actual Framework version installed: v.9.48.0
PHP Version: 8.2
> [9.x] Update for the default PHP version used by sail.

- mail.md
Hi,
Mailpit is  a rewrite of Mailhog
https://github.com/axllent/mailpit
It far far better than Mailhog
I can send a PR to [laravel-sail](https://github.com/laravel/sail/blob/1.x/stubs/mailhog.stub) to replace Mailhog with Mailpit too.
> Add Mailpit along with Mailhog

- vite.md
The namespace for the Vite class in the Laravel Documentation is incorrect.
> Fix namespace of the Vite class

- helpers.md
* helpers.md - changes/extends the negative numbers example for Str::mask
Changes provide a more comprehensive example of the Str mask method that includes a negative number as a 4th argument as well as used as the 3rd argument.
> [9.x] 4th argument negative number example for Str::mask

- eloquent.md
Added note about default attribute format needing to be as they would come from the raw database query.
Related: laravel/framework#45857
> docs: Added note about default attribute format

- queues.md
For https://github.com/laravel/framework/pull/45869
> Skip if batch cancelled

- validation.md
- laravel/framework#45769
Since this rule has been misunderstood by many, I'm convinced that `:ascii` option needs to be informed to users with a warning box.
I would be happy to correct my poor English.
> [9.x] Introduce validation `:ascii` options

- horizon.md
- telescope.md
Refer to the general `laravel-assets` tag when upgrading Horizon and Telescope that's already present in the skeleton.
> [9.x] Refer to general laravel-assets tag

- vite.md
The current documentation assumes the user is already aware of and has installed the respective Vue and React plugins for Vite.
This PR makes it clearer that these plugins are a requirement and briefly covers their installation and configuration, primarily for those not using a starter kit.
> [9.x] Document installation of Vue and React plugins

- helpers.md
Updated the docs for the `value` function to [reflect the fact parameters can be passed to the closure if one is provided as the first parameter and then additional parameters are given](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Collections/helpers.php#L186-L189).
> [9.x] value helper function further parameters passed to closure

- cache.md
This is a very important piece of info that can be overlooked as I did, and the effects will not be noticed until it's too late. Honestly, it should be either bolded or included as a warning.
> Move tagged cache access info to correct section

- deployment.md
Because Laravel 10 requires 8.1, I changed the requirements in deployment.md
Feel free to close this PR if you are already reviewing the whole deplyoment.md file.
> changed PHP requirement for Laravel 10 (PHP 8.1 min)

- releases.md
This pull request adds the new artisan test `--profile` flag to release notes. The image used, is this one:
<p align="center">
</p>
> [10.x] Adds artisan test `--profile` flag to release notes

- broadcasting.md
Their website url has changed but the wsHost stays the same. Just tested and confirmed.
> Revert wsHost for ably

- starter-kits.md
This PR fixes a small typo in the starter kits documentation.
> Fix typo in Starter Kits documentation.

- vite.md
See: https://github.com/laravel/vite-plugin/pull/195
~In draft until it is tagged.~
Tagged: https://github.com/laravel/vite-plugin/releases/tag/v0.7.4
> [9.x] Document `transformOnServe` Vite configuration

- processes.md
This pull request updates the documentation of the process module with minor fixes. The word "real-time" has been removed as processes run concurrently, but the output is still incremental.
> [10.x] Applies minor fixes on process module

- homestead.md
The downloads page was previously located at /downloads.html, but it changed recently to:
https://developer.hashicorp.com/vagrant/downloads
See the download button at: https://www.vagrantup.com
/downloads.html redirects to the new location for now, but maybe later results in a 404.
This PR changes the link to the new correct one.
> [9.x] Changed vagrant download URL to new URL

- sail.md
As a new user to Sail (and Docker) it wasn't clear to me the credentials I should use when connecting to MySQL via TablePlus. While not a leap to use the values from my `DB_USERNAME` and `DB_PASSWORD` environment variables, I received "access denied" errors when working with the tables.
This additional sentence aims to clarify where the credentials come from and which to use when connecting to the MySQL instance directly.
> Clarify MySQL credentials

- pennant.md
> [10.x] Notes on using Pennant outside of a HTTP context

- passport.md
add  --hours= options to docs
Undocumented option --hours=
its very useful especially with shorter token lifetime
```sh
php artisan passport:purge --hours=1
```
> add --hours= option to docs
