facades.md
See: https://github.com/laravel/laravel/pull/5556
=> [8.x] Add Date facade

eloquent-relationships.md
=> Fix missing word in eager loading

installation.md
=> Revert "[8.x] Remove note about Git protocol"

installation.md
After tagging the Installer later later on we can finally remove the note about the protocol. Also adds docs for the new branch flag.
=> [8.x] Installer updates

helpers.md
Adds documentation for the following PR: https://github.com/laravel/framework/pull/36639
=> [8.x] Adds documentation for the new `Str::remove` methods

validation.md
Codebase change made in commit https://github.com/laravel/framework/commit/72ea328b456ea570f8823c69f511583aa6234170
=> [8.x] Add strict parameter to distinct validation rule

eloquent.md
See here: https://github.com/laravel/docs/pull/6943#pullrequestreview-620572144
=> [8.x] Clarify that `lazy` flattens the chunks

cache.md
Documents https://github.com/laravel/framework/pull/36776
I've also added a part to document on how people can use something like CloudFormation to set this up. Taken from the AWS docs here: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/SQLtoNoSQL.CreateTable.html
=> [8.x] Dynamodb table

billing.md
Documents https://github.com/laravel/cashier-stripe/pull/1106
=> [8.x] Document cancelAt for Cashier Stripe

socialite.md
This should be a top level item like on the docs for our other libraries.
=> [8.x] Update level for upgrading socialite

sail.md
Corrected the path to the Schema facade under the soft deletes section on the Eloquent page.
=> Schema Facade Correction

eloquent.md
This wasn't documented yet it seems
=> [8.x] Document generating pivot models

migrations.md
See PR [#36949](https://github.com/laravel/framework/pull/36949)
=> [8.x] Update to include new tinyText() method

billing.md
The quantity should be passed as the second argument in an array
=> [8.x] Fix checkout docs

queues.md
Reference
https://github.com/laravel/framework/pull/36898
=> [8.x] Add retry jobs by queue name

sail.md
Related to https://github.com/laravel/sail/pull/33
=> Document how to connect to application container as root

cashier-paddle.md
Similar to https://github.com/laravel/docs/pull/6990
=> [8.x] Add section about payment confirmation

helpers.md
=> [8.x] Add documentation for the `wordCount` helper function

sail.md
See https://github.com/laravel/sail/issues/113
=> [8.x] Document trusted proxies for Sail

collections.md
Hey! I've just put together a couple of quick examples for the new ` sole() ` method for the collections. I'm hoping that these are all okay?
=> [8.x] Added documentation for Collection sole() method

scout.md
Docs for Meilisearch in Scout v9.0
More docs are probably needed but this is already a basis to get started.
=> [8.x] Scout Meilisearch docs

validation.md
A very interesting thing that should be documented. Seems a few people needed this already in the past:
https://stackoverflow.com/a/37347678/8280247
Since laravel supports it, documenting it here would make sense.
=> Docs on authorization using route model binding

eloquent-relationships.md
Documents new functionality merged: https://github.com/laravel/framework/pull/37144
=> [8.x] New withOnly functionality

valet.md
Add a tip about the valet proxy secure option.
=> Documenting valet proxy secure option.

scout.md
Contains the absolute URL. Change to relative URL like other in-document links.
=> Unification of URL

contributions.md
This should hopefully clarify our process for reviewing PR's. See https://github.com/laravel/framework/pull/37288#issuecomment-833831814
=> [8.x] Clarify pull request reviews

fortify.md
The paragraph was adapted from the Laravel Jetstream docs
=> [8.x] Explain how to customize Fortify Authentication Pipeline

eloquent-relationships.md
Add missing method syncWithPivotValues
=> [8.x] Update eloquent-relationships

homestead.md
Following @svpernova09's [very appreciated help](https://github.com/laravel/homestead/pull/1653) help, I thought it would be useful to update the docs on the available softwares
=> Updating optional softwares list

collections.md
Fix alphabetical order of the collect() method
=> Fix alphabetical order

session.md
Improves on the readability of the storing data in the session documentation. See #7088 for more information
=> Added clarification

configuration.md
**Ref**: https://github.com/laravel/framework/issues/35635
=> [8.x] Fix maintenance mode exception

eloquent-mutators.md
I find this pretty useful when I want to cast attributes differently in only particular scenarios.
=> [8.x] Add the mergeCasts method.

broadcasting.md
Has a first timer reading broadcasting, it was relatively difficult to understand how broadcasting works. This little paragraph helps explain how broadcasting works in a nutshell.
=> Explains the broadcasting core mechanic

authentication.md, installation.md
corrected some spelling mistakes and typos
=> fixed typos

billing.md
Docs for https://github.com/laravel/cashier-stripe/pull/1137
=> [8.x] Document tax ID's in Cashier

packages.md
=> Revert "[8.x] Indicate correct service provider method"

facades.md
Changed "compliment" to "complement".
=> Fix wording in facades.md

notifications.md
It's actually email as the key and the name as the value 🤙
=> [8.x] Reverse key and value in on-demand notifications

collections.md
For https://github.com/laravel/framework/pull/37751
=> [8.x] Document the collection's new `sliding()` method

notifications.md
Added missing notification event's response property, accessible to listeners.
=> Add Notification Event Response Property

mail.md
Pertaining to `laravel/framework` PR https://github.com/laravel/framework/pull/37878
=> [9.x] Update Mail docs for use of SesV2Client over SesClient

billing.md
Documents https://github.com/laravel/cashier-stripe/pull/1216
=> [8.x] Document customer balances

dusk.md
Available since v6.15.1: https://github.com/laravel/dusk/releases/tag/v6.15.1
Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>
=> Add `$browser->select()` example for select multiple.

dusk.md
The ChromeDriver link will be depreciated soon. Updated to the new link
Old Link -> https://sites.google.com/a/chromium.org/chromedriver/home
New Link -> https://sites.google.com/chromium.org/driver/
=> Updated ChromeDriver link

blade.md, helpers.md
Documentation for laravel/framework#38016.
=> `@class` Blade directive and array helper

mail.md
Most of the time changing from address also require changing from name.
So, it's better to include it in a code sample.
=> Guiding that"from name" can also be supplied

collections.md
This pull request updates the documentation to reflect the changes to pop() and shift() from https://github.com/laravel/framework/pull/38093
=> Update docs for pop() and shift()

broadcasting.md
Documenting PR https://github.com/laravel/framework/pull/38137
=> [8.x] Model Broadcasting - Adding broadcastWith() and broadcastAs() support

broadcasting.md
Documenting PR https://github.com/laravel/framework/pull/38086
=> [8.x] Ability to specify the broadcaster to use when broadcasting an event

pagination.md
See discussion in https://github.com/laravel/framework/pull/38371
=> [8.x] Clarify that nullable columns aren't supported for cursor pagination

migrations.md
Changes example to use foreign keys naming conventions.
=> changes column name for foreignUuid example

helpers.md
Documentation for https://github.com/laravel/framework/pull/38330
=> add documentation for stringable isUuid

errors.md
I found this very helpful when you have a specific condition that you need met, and otherwise a having a default Http response returned.
=> Add return false on exception render method documentation

queries.md
Add the `havingBetween` method to the Query Builder page.
=> [8.x] Add havingBetween method

validation.md
Documents the newly added behavior of https://github.com/laravel/framework/pull/38443/
=> [8.x] Document 'Make $validator->sometimes() item aware to be able to work with nested arrays' (PR #38443)

validation.md
Added in [laravel/framework#38480](https://github.com/laravel/framework/pull/38480)
=> Document make:rule new --implicit option

validation.md
This adds usage documentation for the `prohibits` validation method
=> [8.x] Added `prohibits` validation documentation

billing.md
Not having the import could be confusing to people.
=> [8.x] Import queueable function

validation.md
Add documentation for https://github.com/laravel/framework/pull/38537
=> Document exclude rule

dusk.md
See https://github.com/laravel/dusk/pull/918/
=> Document `waitUntilEnabled` / `waitUntilDisabled`

validation.md
=> Document `merge`

responses.md
Adds an additional line to outline expected formatting of the options string.
=> [8.x] Enhance cache.headers option string description

helpers.md
Give power back to this wonderful helper example 👼
=> [8.x] Make the example functionnal

blade.md
Updated the documentation to reflect https://github.com/laravel/framework/pull/39014
=> Document anonymous option on make:component command

blade.md
=> Revert "Document anonymous option on make:component command"

eloquent.md
Docs for https://github.com/laravel/framework/pull/38945
=> Add docs on model:prune --pretend

testing.md
This adds documentation for https://github.com/laravel/framework/pull/38966
=> [8.x] Adds documentation for `make:test` `--pest` option

queues.md
Update id in doc to match example.
=> Update id in doc to match example.

logging.md
=> Remove a repeated word "the the"

billing.md
Documents https://github.com/laravel/cashier-stripe/pull/1276
=> [8.x] Document `createAndSendInvoice` method

sail.md
Link to Windows WSL2 Documentation is added to the installation instructions.
=> [8.x] Link to Windows WSL2 Documentation is added.

migrations.md
Lists the alternative syntax provided in the Database/Schema/ForeignKeyDefinition.php file.
=> Lists helpers for onDelete and onUpdate actions.

telescope.md
Hi,
I found this  `$entry->isSlowQuery()` method was not included in batches. It was working in batch.
=> A method was missing in batches

pagination.md
- Just a small clarification on UserController example commentary at Pagination section.
=> [8.x] Clarification on Pagination

notifications.md
=> Revert "[8.x] Remove queueable trait from example"

releases.md
This PR accompanies https://github.com/laravel/laravel.com-next/pull/194 and both need to be merged in order for this to work.
=> Colorize supported versions

installation.md
Documents new devcontainer parameter added here https://github.com/laravel/sail-server/blob/master/routes/web.php#L25
=> documents devcontainer support

seeding.md
This pull request adds documentation regarding Database Sending `WithoutModelEvents` trait.
=> [9.x] Adds documentation regarding Database Sending `WithoutModelEvents` trait

database-testing.md
- Add example to run an array of specific seeders
=> [8.x]: Add an example to run array of specific seeders

helpers.md
As of https://github.com/laravel/docs/pull/7502
=> [8.x] Fix invalid id, this must be a class

migrations.md
=> [8.x] Fix duplicated tag

collections.md, eloquent-collections.md, helpers.md
As of https://github.com/laravel/docs/pull/7502
=> [7.x] Fix duplicated ids when rendering, missing style definitions

octane.md
This pull request adds links to Swoole / Open Swoole documentation.
=> [8.x] Adds links to Swoole / Open Swoole documentation

sail.md
Fix in: https://laravel.com/docs/8.x/sail#sail-customization
=> [8.x] Fixed markdown typo in sail.md

collections.md
Docs for recently merged new Collection [method](https://github.com/laravel/framework/pull/40044)
=> [8.x] Add docs for doesntContain Collection method

octane.md
This could help solve problems such as https://github.com/laravel/octane/issues/442#issuecomment-996049934
=> Add swoole's configuration

billing.md, broadcasting.md, cashier-paddle.md, dusk.md, fortify.md, homestead.md, horizon.md, notifications.md, octane.md, passport.md, sail.md, sanctum.md, scout.md, starter-kits.md, telescope.md, valet.md
Noticed these weren't yet linking to their GitHub repositories. I also fixed some Echo links.
=> Add GitHub repository links to projects

middleware.md
Make sure the PHPDoc type matches the current Foundation value.
=> Fix `middlewarePriority` docblock

collections.md
I just copied the description from the `Arr::undot()` section with a slightly different example.
=> [8.x] Add the collection undot method

broadcasting.md
Explained "PHP driven", however, "Open Source Alternatives" mentioned about node based "Soketi", it is not PHP based.
=> correct tip about open source alternative.

scout.md
I noticed this Scout Builder method wasn't documented yet.
=> [8.x] Document whereIn method for Scout

eloquent.md, queries.md
The return value of update method in queries and  eloquent were missing.
=> added missing return value of update method

sail.md
Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>
=> Add information regarding setting NODE_VERSION on docker-compose.yml on Sail

filesystem.md
When I was trying these out, I figured it be better if we already added env variables for these so it's easier to copy/paste these and get started with them.
=> [8.x] Add env variables to ftp examples

collections.md
docs updated regarding to the [PR](https://github.com/laravel/framework/pull/40253)
=> [8.x] Add the collection pipeThrough method

validation.md
=> add mac address validation rules to docs

upgrade.md
This pull request adds notes about PHP and packages on the upgrade guide.
=> [9.x] Adds notes on PHP and packages

releases.md
This pull request adds `Improved Route Groups` section to release notes.
=> [9.x] Adds `Improved Route Groups` section to release notes

collections.md, releases.md
Fix minor html issues which leads to fatal errors when validating the html
=> [master] Minor html fixes

eloquent.md
Changed '0021-02-18' to '2022-01-26'
=> [8.x] Fix a date typo in eloquent.md

eloquent.md
=> Revert "[8.x] Fix a date typo in eloquent.md"

releases.md
This pull request adds release notes regarding generic collections.
=> [9.x] Adds release notes regarding generic collections

filesystem.md
=> Fix default file permissions for local driver.

upgrade.md
=> [9.x] Add upgrade guide section about removed Doctrine method

mail.md
Adds a section on how to write custom transports either through a package or in your own app. It seems `Mail::extend` was undocumented before this. Is the `register` the correct method for this? Or should it be `boot`? 🤔 
I tried my best with providing a realistic example. But haven't tried this one out manually. The code should be good (based on https://mailchimp.com/developer/transactional/guides/send-first-email/#send-your-first-email).
See https://github.com/laravel/framework/issues/40330
=> [9.x] Custom mail transports

mail.md
@taylorotwell See https://github.com/laravel/docs/pull/7644#issuecomment-1028881220 for more information.
=> [9.x] Updated custom mail transports

queues.md
Explains the behavior reported here: https://github.com/laravel/framework/issues/40804
=> [8.x] Explain eager/lazy load behavior when serializing models in a queued job

upgrade.md
This is a requirement. See https://github.com/laravel/framework/issues/40883
=> [9.x] Clarify trusted proxies in upgrade guide

releases.md
Fix little typo of MeiliSearch.
=> [9.x] Fix MeiliSearch typo.

structure.md
In Laravel 9 the lang directory was moved in the root project directory
=> [9.x] The lang Directory was moved

upgrade.md
See https://github.com/laravel/laravel/pull/5782
=> Align version with laravel/laravel repo

helpers.md
[PR](https://github.com/laravel/framework/pull/41144)
=> [9.x] Adds `Str::betweenFirst` documentation

eloquent.md
Moving the same note we have on Query Builder Upsert to Eloquent Upsert:
https://laravel.com/docs/9.x/queries#upserts
This took me a while to track down what was the issue 😅
=> Adding note about upsert to Eloquent page

migrations.md
Add missing Schema Events of SchemaDumped and SchemaLoaded
=> Added missing Schema Events

pagination.md
Add method to indicate if user is on the last page.
=> [9.x] Add new method for last page in pagination

contributions.md
It seems to me that the current docs aren't entirely accurate/clear yet so I tried to improve the wording here.
=> [9.x] Clarify "which branch" further

homestead.md
=> [9.x] Add miss line break between list tags

events.md
=> [9.x] A few missing words in events.md

database-testing.md
=> [9.x] Missing article "a"

testing.md
* Very small typo on this page
=> [9.x] Replace "to" with "the"

billing.md
=> must be same as title in overview

authentication.md
It might be nice to see the email value filled in again on the form.
`$request->validate()` does. 
Unless it is intentional.
=> Add withInput method to manual authentication example

eloquent-serialization.md
=> [9.x] Proofread eloquent-serialization

eloquent-mutators.md
=> [9.x] Proofread eloquent-mutators

eloquent-relationships.md
* Accidental capitalization
* Add missing word
=> [9.x] Proofread eloquent-relationships

installation.md
=> Fix Server Requirements list

mail.md
=> Fix syntax error on mail.md

validation.md
Document new `Rule::excludeIf()` and `Rule::prohibitedIf()` validation rules add in PR https://github.com/laravel/framework/pull/41617.
=> Document new excludeIf and prohibitedIf Rules

collections.md
Add `firstOrFail` method to `Collections` documentation.
=> Add firstOrFail method to Collections documentation.

http-client.md
Documents https://github.com/laravel/framework/pull/41779
=> [9.x] Http client: document retry method $request parameter

helpers.md
=> Formatting

installation.md
Fixes the below incorrect formatting of docs for v5.8:
=> [5.8] Fix Installation Page

horizon.md
=> Revert "Dashboard is always accessible"

billing.md
Documentation for https://github.com/laravel/cashier-stripe/pull/1345
=> [9.x] Document new pay and payWith methods

events.md
Added dispatchIf & dispatchUnless methods in docs
=> Added dispatchIf & dispatchUnless methods in docs

lifecycle.md
i was wondering what a service provider was the entire time i was reading this section. this sentence would have been much more helpful at the top like this.
=> moved service provider definition to the top

eloquent.md
Documents the new `findOr` method introduced in https://github.com/laravel/framework/pull/42092
=> Document `findOr` method

billing.md
Documentation for https://github.com/laravel/cashier-stripe/pull/1354
=> [9.x] Document coupon and promotion code additions to Cashier Stripe

http-tests.md
Ref https://github.com/laravel/framework/pull/42361
=> Add `assertJsonMissingPath()` to HTTP Tests

billing.md, cashier-paddle.md
=> [9.x] Document hasExpiredTrial

helpers.md
Adds documentation for `Str::isJson()`
https://github.com/laravel/framework/pull/42545
=> [9.x] Adds documentation for `Str::isJson()`

mail.md
- Fix attachable object example missing contract implementation
=> [9.x] Fix attachable object example missing contract implementation

database.md
These arguments may be helpful.
https://github.com/laravel/framework/blob/v9.18.0/src/Illuminate/Database/Connection.php#L821
=> [9.x] Add parameters to the closure for whenQueryingForLongerThan

helpers.md
=> [9.x] feature: `Str::inlineMarkdown()`

routing.md
This Pull Request solves the suggestion on the issue [#43214 on the Laravel Framework](https://github.com/laravel/framework/issues/43214) as Discussed in [#43213](https://github.com/laravel/framework/discussions/43213)
=> Update --path Flag in the Route Listing Documentation

blade.md
This PR adds `@pushIf` in docs, and reformats the `@readonly` directive.
=> Adds `@pushIf` directive with some formatting

eloquent.md
This pull request adds documentation to the new `model:show` command.
=> [9.x] Adds `model:show` documentation

eloquent-resources.md
This PR adds documentation for the newly added `whenCounted()` method on `JsonResource`'s:
https://github.com/laravel/framework/pull/43101
=> [9.x] Add `whenCounted` resource method docs

pint.md
The missing Pint installation hint for older applications.
=> Added installation tip for older applications

collections.md
containsOneItem method document
=> containsOneItem method document

http-tests.md
This isn't very clear atm and can lead to confusion: https://github.com/laravel/framework/issues/43346
Happens here: https://github.com/laravel/framework/blob/9.x/src/Illuminate/Auth/AuthManager.php#L203
=> [9.x] Clarify actingAs behavior when setting a guard

validation.md
This import isn't actually used in the code example. 👍🏻
=> docs: remove unused import from File validation

migrations.md
See what SQL statement will be executed before running migrations artisan command.
=> [9.x] Dry running migrations command

passport.md
minor change due to changes of auth config file in :
https://github.com/laravel/laravel/commit/226d1bfc3c774e24a79e68e9f1264b5ca359551f#diff-66a4eb6caa45de87ad409f2f5f2d5e7dd30aacd12de32af921aa32317cf9b2e2L44
=> [9.x] add api config in auth

frontend.md
Should be plural "applications" rather than possessive "application's".
=> Remove possessive apostrophe from frontend docs

eloquent.md
Adds docs for quietly family methods of eloquent models
=> [9.x] Add docs for eloquent quietly methods

collections.md
In collections the function `implode()` also supports using a callback.
=> Collections implode function supports callback

dusk.md
Hey! I was just setting up Dusk for a project and thought I'd use the sample file from the docs to get started with running it on PRs with GitHub Actions.
From what I can see, the workflow fails because there's something slightly wrong with the database command (I think). I've replaced the `'` with escaped backticks and it seems to get it working.
I've also updated the `actions/checkout@v2` to use `v3` because I think it's the newest available version.
Apologies if any of these changes aren't right! If you need me to change anything at all, please give me a shout and I'll get them fixed ASAP 😄
=> [9.x] Update GitHub Actions sample workflow for Dusk

http-tests.md
- Fix component method to correct return type
=> [9.x] Fix component wording

validation.md
=> [9.x] feature: `max_digits` and `min_digits` validation docs

vite.md
See: 
- https://github.com/laravel/framework/pull/43620
- https://github.com/laravel/vite-plugin/pull/118
Tucked this away in a single spot throwing it all in a single example, try and de-emphasise it all - as it should only be for rare cases that this is even needed.
=> [9.x] Document advanced customisations

fortify.md
=> fix sentence in fortify.md

billing.md
Amending "one off" to match other instance of "one-off" to improve search/find in page
=> Change to billing to achieve consistency

requests.md
Right now it's not clear that it's meant for strings: https://github.com/laravel/framework/issues/43940
=> [9.x] Clarify filled on Request

http-tests.md
See https://github.com/laravel/framework/issues/43990
=> [9.x] Clarify `etc` behavior on nested attributes

mail.md
Update code example for Mail events, so it will be more align with the style of event listener mappings at the Laravel's Events documentation
=> Update Mail Events example

verification.md
Update code example for Email Verification events, so it will be more align with the style of event listener mappings at the Laravel's Events documentation
=> Update Email Verification Events example

notifications.md
Update code example for Notification events, so it will be more align with the style of event listener mappings at the Laravel's Events documentation
=> Update Notification Events example

mail.md, mocking.md
Documentation for https://github.com/laravel/framework/pull/43967
=> add mailable attachment test documentation

controllers.md
Removing unnecessary imports from the same namespace
=> Update Controllers example

broadcasting.md
The signature can be found here: https://github.com/pusher/pusher-js/blob/v7.4.0/src/core/auth/options.ts#L12
=> Update channel authorization signature

container.md
Update the example of binding primitives so it can be align with the style of other Service Container bindings.
=> Update binding primitives example

validation.md
It was not documented yet
https://github.com/laravel/framework/pull/32711
=> [9.x] filter_unicode email validation

billing.md
Reword after https://github.com/laravel/cashier-stripe/pull/1437
=> [9.x] Reword createAndSendInvoice docs

eloquent-factories.md
This PR adds documentation for the new `recycle` method on Eloquent Factories.
=> [9.x] Document Factory `recycle` method

helpers.md
=> [9.x] Adds ULID helper section

eloquent.md
See: https://github.com/laravel/framework/pull/44138
=> [9.x] Document withoutTimestamps

vite.md
See: https://github.com/laravel/framework/pull/44198
Draft until release.
=> [9.x] Document blade alises

vite.md
Draft until the plugin has been released.
=> [9.x] Update Vite plugin refresh paths

eloquent-relationships.md
I came across the `orderByPivot` method while solving this [thread](https://laracasts.com/discuss/channels/eloquent/orderby-on-a-pivot-data-in-a-belongsto-relationship).
=> [9.x] Add the orderByPivot method.

dusk.md
Document https://github.com/laravel/dusk/pull/999
=> Document `pauseIf()` / `pauseUnless()`

dusk.md
Document https://github.com/laravel/dusk/pull/986 and https://github.com/laravel/dusk/pull/960
=> Document `assertIndeterminate()` and `waitForInput()`

blade.md
This pull request adds documentation of writing php code in parenthesis of Blades `@php` statement.
=> [blade] Single statement `@php`

blade.md
=> Fix typo in blade comment

mail.md, notifications.md
See: https://github.com/laravel/framework/pull/44527
=> [9.x] Update mail syntax

controllers.md
docs for https://github.com/laravel/framework/pull/44405
probably hodl off on merging until next Tuesday's release.
=> [9.x] loading soft deleted models on resource routes

collections.md
Found and fixed two small grammar errors
=> Fixed grammar errors

passport.md
In case someone wants to modify the throttle behavior, the middlewares, etc.
See https://github.com/laravel/passport/issues/1585
=> [9.x] Document overriding Passport routes

requests.md
Right now it's not clear that existing keys will be overwritten.
=> Clarify behavior of request merge

mail.md
See https://github.com/laravel/framework/issues/45162
=> Pass array to replyTo param in Envelope

helpers.md
* `Str::isUlid`: laravel/framework#44074
* Fluent string `isUlid`: laravel/framework#45100
* Fluent string `whenIsUlid`: laravel/framework#45183
=> [9.x] Add `Str::isUlid`, fluent `isUlid` and `whenIsUlid`

valet.md
See https://github.com/laravel/valet/blob/master/cli/Valet/Drivers/LaravelValetDriver.php
=> LaravelValetDriver namespace

middleware.md
Can we let go of this phrase? "Out of the box, "
=> There is no "box"

http-tests.md
The docs for this merged PR: https://github.com/laravel/framework/pull/45298
=> [9.x] Add assert streamed content documentation

cache.md
Set up is being used as a verb in this case and should be two words.
=> Correct grammar

cashier-paddle.md
Paddle update their documentation url
=> Update API documentation url cashier-paddle.md

billing.md, cashier-paddle.md
=> [9.x] Document multiple subscriptions in Cashier

queries.md
Subsequent to https://github.com/laravel/docs/pull/8426
=> change 0 to 1 denoting user active = clearer for most devs

pint.md
This pull request documents the new Pint `--dirty` option: https://github.com/laravel/pint/pull/130.
=> [9.x] Adds Pint `--dirty` option documentation

upgrade.md
This pull request adds introductions about Composer's Minimum Stability for Laravel 10.
=> [10.x] Adds introductions about Composer's Minimum Stability

homestead.md
MySQL is now a "feature", so we'll add it to the list here.
ping @svpernova09
=> add "mysql" to list of available features

contributions.md
This pull request clarifies when pull requests should contain types, starting Laravel 10.
=> [10.x] Clarifies when pull requests should contain types

passport.md
Add useRefreshTokenModel to Overriding Default Models Section
=> Add useRefreshTokenModel Method

validation.md
See: https://github.com/laravel/framework/pull/45716
=> [10.x] Updates prohibits rule definition

validation.md
See https://github.com/laravel/framework/pull/45717
=> [9.x] Documents "missing" validation rule

helpers.md
In addition to https://github.com/laravel/framework/pull/45761
=> [9.x] Add Arr::sortDesc() description

eloquent.md
Updated Eloquent model's lifecycle events
=> Add forceDeleting method to events list

sail.md
This fixes the broken link to the Mailpit repository.
=> Fix Mailpit link

blade.md
Docs for PR: laravel/framework#44774
=> [9.x] Add Fragment Helpers

validation.md
See https://github.com/laravel/framework/pull/45729
=> [9.x] Removes dependency on bcmath

upgrade.md
This section is anchored in the High Impact Changes Section
=> [10.x] Fix missing anchor

broadcasting.md
Ably has changed its URL to https://ably.com
=> Update Ably url on Broadcasting

upgrade.md
This pull request adds a few notes about how to migrate to PHPUnit 10.
=> [10.x] PHPUnit 10 migration guide

http-client.md
Docs for PR: https://github.com/laravel/framework/pull/45681
=> [9.x] Add notFound response helper

fortify.md, helpers.md, localization.md, packages.md, passwords.md, structure.md, validation.md
This updates the documentation to reflect the `lang` directory being an opt-in directory.
=> Lang updates

dusk.md
https://github.com/laravel/framework/pull/46025
=> Document usage of `$tablesToTruncate` when using `DatabaseTruncation`

documentation.md, pennant.md
```php
if (Feature::active(Pennant::class)) {
$this->merge();
}
```
=> [10.x] Pennant

pennant.md
=> [10.x] Documents nullable scope for Pennant

blade.md, cashier-paddle.md, collections.md, container.md, helpers.md, horizon.md, http-tests.md, localization.md, mail.md, notifications.md, passport.md, queues.md, validation.md
This pull request implements enhancements in the promotion of properties and the use of types - that were added after my latest work on types in docs. It's worth mentioning that I have deliberately left the regular class properties un-typed with the intention of addressing them collectively later in the future.
=> [10.x] Improvements on property promotion and types

eloquent-relationships.md
Can someone help me add the `createQuietly` and `createManyQuietly` methods to the documentation, since my English is limited?
=> [9.x] Add docs for pushQuietly method

scout.md
This pull request clarifies the builder class on `makeAllSearchableUsing`.
=> [10.x] Clarifies builder class on `makeAllSearchableUsing`

pennant.md
=> [10.x] Documents passing array to `for`

pennant.md
=> [10.x] Documents `Feature::values()`

pennant.md
Dependent on https://github.com/laravel/pennant/pull/21
=> [10.x] Improves events documentation

pennant.md
=> [10.x] Add testing documentation

releases.md, upgrade.md
Prepares master for Laravel v11.
=> Prepare Laravel v11

pennant.md
=> [10.x] Documents when method when used with a rich value

releases.md
In this PR, I added the exact release date for version 10 in the "Support Policy" table.
=> [10.x] Added exact release date

contributions.md
In this PR, I changed the current Laravel version in “Which Branch?” section.
=> [10.x] Update Laravel version in Contribution Guide

pennant.md
=> [10.x] Document `all` and `discover`

controllers.md
I teach a new course about start beginner in Laravel.
When the course arrive into a controller section, They didn't section about make controller OR where is my controller when created.
=> [10.x] Add make controller command into the basic controller

starter-kits.md
Updated link to Jetstream v3.0 docs.
=> [10.x] Updated link to Jetstream v3.0

blade.md
I found some inconsistencies in Blade's directive writing.
=> [9.x] add `@` to improve consistency

collections.md
It updates the doc according to [PR](https://github.com/laravel/framework/pull/46265).
=> [10.x] Add `dot` method to collections

validation.md
Added a Class import that was missing.
=> Add missing Class import

fortify.md
This pull request fixes Fortify's custom response. Note that, we can't really type this interface as it gets extended all over the place.
=> [10.x] Fixes fortify custom response

logging.md
changed options .. 'is' housed in to options ... 'are' housed in
=> minor wording change

passport.md
=> Incorrect Passport snippet to override default routes

queues.md
=> [10.x] Updated queues.md doc

queues.md
Fixed a grammatical error on line `1006`.
=> [9.x] Updated qeueus.md Doc

billing.md
Docs for https://github.com/laravel/cashier-stripe/pull/1516
=> [10.x] Confirming payments

console-tests.md
Code PR: https://github.com/laravel/framework/pull/46694
=> Document using `WithConsoleEvents` trait

mail.md
This page points to a Symfony Mailer Documentation which is not maintained anymore.
=> Update Symfony Mailer link

cashier-paddle.md
I'm not sure what this section was doing here as this isn't possible right now with Cashier Paddle.
=> Remove extra section about subscribedToPlan

events.md
-  Update doc block to make consistent with core Laravel application's practice.
=> update doc block to make consistant with core Laravel application's practice. 

http-tests.md
Default ExampleTest in real Laravel app.
=> [10.x] Add correct ExampleTest in http-tests

http-tests.md
PR related to: https://github.com/laravel/docs/pull/8768
=> [10.x] Add missing asserts in http tests

http-client.md
Update documents with respect to this [closed PR](https://github.com/laravel/framework/pull/46931).
=> Warning about Http::pool()

sail.md
See https://github.com/laravel/sail/pull/580
=> [10.x] Remove sail PHP 7.4 support

scout.md
Related to https://github.com/laravel/scout/pull/738
=> [10.x] Scout - 'makeSearchableUsing' method public instead of protected

filesystem.md
Should be fixed in older branches too
=> [8.x] Fix text for caching configuration in filesystem.md

octane.md
This pull request fixes roadrunner installation on sail.
=> [10.x] Fixes roadrunner installation on sail

precognition.md
In Using React & Inertia section is mentioned wrong package for React with Inertia.
=> [10.x] Fix package name in Precognition page

precognition.md
'name' is where 'email' should be used.
=> correct input setData inside react example

precognition.md
Makes the examples a little more concise and sticks to conventions
=> [10.x] Improve react conditional examples

precognition.md
This is the last broken link I've seen
=> Fix broken link

helpers.md
=> [10.x] Sleep hook

vite.md
=> [10.x] Vite HMR + Sail + WSL2

precognition.md
https://github.com/laravel/precognition/pull/3
=> [10.x] Alpine + Precognition

vite.md
I saw Laravel 9.x docs also have the same mistake but I will not create a PR for it
=> [10.x] Update vite.md - Grammar fix

http-client.md
This PR related to : https://github.com/laravel/framework/pull/47335
=> [10.x] Add `replaceHeaders` method into http-client

valet.md
IMHO it's better to write down a working example of the $PATH variable change.
=> Change tilde to $HOME for $PATH variable

container.md
Fix description of `singletonIf` section
=> [10.x] Add `singletonIf` into container

sail.md
Moved the user to the correct section on the installation page!
=> [10.x] Fix `sail` link

upgrade.md
Upgrade doc matched code snippet with laravel framework
=> Upgrade doc updated

validation.md
For consistency of both.
https://laravel.com/docs/10.x/validation#rule-array
https://laravel.com/docs/10.x/validation#validating-arrays
=> Keep consistency of the allowed array keys

eloquent-mutators.md
Hello!
This PR documents the feature in https://github.com/laravel/framework/pull/47423
Thanks!
=> [10.x] Add documentation on how to disable caching for custom casts

eloquent.md
Added a Class import that was missing.
=> [10.x] Add missing Builder import to Dynamic Scopes

queues.md
Hey, folks!
This PR aims to introduce the documentation about `ShouldBeEncrypted` queue interface.
Hope this helps,
Thanks.
=> Add Doc: `ShouldBeEncrypted` Interface to Queue

helpers.md
This PR ships `Str::wrap` usage
=> [10.x] `Str::wrap` usage

database.md
Appropriated to their official supported versions
=> Bump supported database versions

dusk.md
Added an example of the **withinFrame** function.
=> [10.x] Laravel Dusk interacting with elements inside an iframe

prompts.md
=> fix code example

prompts.md
There is a typo error in the password import.
=> Fix typo in password import

pennant.md, precognition.md
Draft until tagged: https://github.com/laravel/pennant/pull/64
=> Document Feature::useMorphMap()

facades.md
Process Facade is missing from Architecture Concepts / Facades page.
=> Add Process Facade

prompts.md
- Just small and minor change when you copy paste the code from `laravel.com` 😄
=> [10.x] Improve variable Naming

validation.md
more infomation for [laravel/framework#41123](https://github.com/laravel/framework/pull/41123#issuecomment-1050141836)
=> [10.x] Add more info for deeper nested indexes/positions

events.md
Hello!
As promised, here's the docs for https://github.com/laravel/framework/pull/48026.
Thanks!
=> [10.x] Add Listener `withDelay` docs

prompts.md
=> [10.x] Adds prompts example image

facades.md
=> Improve Real time facades

middleware.md
=> Revert "[10.x] Recommend scoped method for binding terminable middleware"

folio.md
This pull request adds documentation about https://github.com/laravel/folio/pull/100.
=> [10.x] Adds documentation about Folio's `render` function

queues.md
As discussed here:
https://github.com/laravel/framework/pull/48180
Honestly seems like we could just add note to the docs.
_Originally posted by @taylorotwell in https://github.com/laravel/framework/issues/48180#issuecomment-1699685697_
=> Add waring for redis queue serializer and compression

starter-kits.md
also applies 4 https://github.com/laravel/docs/blob/master/starter-kits.md
=> [10.x] shorten `jetstream` link

precognition.md
Think these are both best demonstrated within the one code example.
=> [10.x] Document Precognition testing

scout.md
Updated use cases for whereIn / whereOn methods.
=> Updated usage examples for whereIn and whereNotIn in Laravel Scout Query Builder documentation

urls.md
Explained how to create a signature for the relative part of a url only, and how to validate it.
=> [10.x] Added details on using relative signed urls

queues.md
- Additional information about correlation between further attempts and exponential backoff
=> [10.x] Document additional attempts for exponential backoff

cashier-paddle.md
Hey guys – we've seen a bit of confusion around this popping up and wondered if it would be worth calling out this limitation here (or potentially above the TOC?)
Thanks,
Kieran
=> Add warning re: Paddle Classic

errors.md
https://github.com/laravel/framework/pull/48288
=> Document deduplicating exceptions

contributions.md
Add github link to `laravel/folio`
=> [10.x] Add `laravel/folio` to contributions page

prompts.md
This PR documents the new `table` function from Prompts, contributed by @joetannenbaum.
=> [10.x] Document `table` prompt

frontend.md
Update to Inertia v1 import syntax.
Reference: [Upgrade Guide](https://inertiajs.com/upgrade-guide)
=> Renamed Inertia imports in frontend.md

dusk.md
Adds documentation on how to use the feature added in this commit https://github.com/laravel/dusk/commit/cf04717664f80204567ad3077ea7484a0be16497
=> Added documentation about how to use the Dusk::selectorHtmlAttribute

helpers.md
As the title shows, extra </div> existed. Remove it.
=> Remove superfluous </div> to make div tags consistent.

errors.md
https://github.com/laravel/framework/pull/48391
=> [10.x] Document throttling exceptions

sail.md
Clarify that running `php artisan sail:install` will overwrite values in an existing app's `.env` file.
See https://github.com/laravel/sail/issues/621
=> [10.x] Clarify env variables overwrite

prompts.md
This PR documents the new `multisearch` and `progress` prompts.
There are also a few minor fixes and improvements to existing prompts I noticed.
=> [10.x] Document `multisearch` and `progress` prompts.

eloquent-factories.md
"Trashed State" header is missing link.
=> Missing link for <h4> header

homestead.md
Add new apache proxy site and sshare alias added in:
https://github.com/laravel/homestead/pull/1891
https://github.com/laravel/homestead/pull/1892
=> Update Laravel Homestead Documentation

sail.md
It is added last month
https://github.com/laravel/sail/pull/614
=> Added 8.3 runtime in sail documentaion

events.md
=> [10.x] Update events.md (specify correct types)

homestead.md
This is adding documentation for the change made here:
https://github.com/laravel/homestead/pull/1897
I've also cleaned up some of the links since they just redirect to the links I've provided.
=> Add network device setting to homestead

routing.md
Adds docs for https://github.com/laravel/framework/pull/48703
=> [10.x] Docs for route:list -vv

migrations.md
Related PR #9094
- add PostgreSQL and SQLite
=> [9.x] update `virtualAs` description to include all supported databases

migrations.md
Related PR #9094
- add PostgreSQL and SQLite
=> [8.x] update `virtualAs` description to include all supported databases

queues.md
Adds some initial documentation for https://github.com/laravel/framework/pull/48633
=> Document new ability to add batches to job chains

logging.md
This pull request adds pail documentation.
=> [10.x] Adds pail documentation

installation.md
=> [9.x] Simplify SQLite initial configuration

telescope.md
Add documentation for the `telescope:prune`  `--quiet` option in https://github.com/laravel/telescope/pull/1409
=> Docs for https://github.com/laravel/telescope/pull/1409

telescope.md
=> Revert "Docs for https://github.com/laravel/telescope/pull/1409"

billing.md
https://github.com/laravel/cashier-stripe/issues/1603
=> [10.x] Note about deleting users in billing

helpers.md
This PR adds documentation for the [Number Utility](https://github.com/laravel/framework/pull/48845) that will be introduced in next week's update.
=> [10.x] Add Number Utility

homestead.md
Added in https://github.com/laravel/homestead/pull/1916
=> [10.x] Homestead add dragonflydb feature

pulse.md
=> [10.x] Improve Pulse documentation

pulse.md
=> Fix typo in Pulse sampling section

pulse.md
=> Revert "Pulse: Change `extra` to `email` for Pulse::users"

pulse.md
Depends on tagging https://github.com/laravel/pulse/pull/81
=> [10.x] Document publishing Pulse migrations

cashier-paddle.md
See https://github.com/laravel/cashier-paddle/issues/225
=> [10.x] Add note about payment link page

migrations.md
This is a re-send of https://github.com/laravel/docs/pull/9183 because people keep running into it.
See https://github.com/laravel/pulse/issues/175 & https://github.com/laravel/pulse/issues/254. 
Hope it can be reconsidered?
=> [10.x] Explain migrate:fresh limitation

pulse.md
This PR adds documentation on how to create custom cards for Pulse.
This is a complex topic, as Pulse is almost a framework in itself. There are different considerations depending on whether the custom card is part of an application or a package. I have biased the documentation towards application-based cards but called out any package-specific concerns where applicable.
=> [10.x] Document creating custom cards for Pulse

blade.md
This PR adds documentation for the `@session` blade directive introduced in https://github.com/laravel/framework/pull/49339.
=> [10.x]  @session Blade Directive

sanctum.md
Adds explanation on specifying the expiration of a single token
=> [10.x] Independent token expiration

redis.md
=> Format name of PhpRedis extension

artisan.md
Tinkerwell isn't really a graphical UI but solves PsySh contraints, so mentioning the main benefits makes sense.
=> Improving the note copy

pulse.md
Draft pending release of:
* https://github.com/laravel/pulse/pull/251
* https://github.com/laravel/pulse/pull/257
* https://github.com/laravel/pulse/pull/258
=> [10.x] Update Pulse user resolving docs

seeding.md
Many people copy and paste this code.
=> [10.x] Use safe email domain

horizon.md
Document the feature introduced on https://github.com/laravel/horizon/pull/1361
=> [10.x] Document tags for event listeners

scout.md
Hi,
More clarification/explication on the use of a queue with Scout and php artisan queue:work .
I was stuck a moment due to this.
So i want to help other and laravel.
Ty for your framework.
=> More clarification/explication on the use of a queue with Scout

http-client.md
This third parameter is very import when you upload file on various API.
=> Http Client attach method with third parameter

eloquent-relationships.md
See https://github.com/laravel/framework/pull/49695.
=> [11.x] Support eager loading with limit

scout.md
Add Typesense Dynamic Search Parameters Doc
=> [10.x] Add Typesense Dynamic Search Parameters Doc

scout.md
Based on feedback from here: https://github.com/laravel/scout/issues/796#issuecomment-1908591943
=> Add mention of required Typesense configuration in Scout config

upgrade.md
* laravel/framework#49810
* laravel/framework#49148
=> [11.x] Deprecated Schema Methods Removal

strings.md
Could not find the documentation for `stripTags()`, so I added it.
=> Added documentation for stripTags()

installation.md
This pull request updates `Databases and Migrations` on installation.
=> [11.x] Updates `Databases and Migrations` on installation

blade.md
```php
@php
use \App\Models\Flight as FlightModel;
@endphp
@use('App\Models\Flight ', 'FlightModel')
```
=> [10.x] Add example for `@use` directive

cashier-paddle.md
For: https://github.com/laravel/cashier-paddle/pull/245
=> Update Paddle token

artisan.md, contracts.md, mail.md, processes.md, prompts.md, requests.md
This pull request updates Symfony related docs links
=> [11.x] Update Symfony related docs links

deployment.md
This pull request adds documentation about the new **Health Check Endpoint**.
=> [11.x] Adds `Health Check Endpoint` documentation

helpers.md
This pull request documents the `literal` helper.
=> [11.x] Documents `literal` helper

helpers.md
This pull request documents `once` helper.
=> [11.x] Documents `once` helper

deployment.md
I hope I optimized the description.
=> [11.x] Add a description for deployment optimization

upgrade.md
Not sure about the likelihood of impact: A lot of people use MariaDB, but you don't _have_ to switch to the new driver immediately.
=> [11.x] Document upgrade to MariaDB driver

http-client.md
See: https://github.com/laravel/framework/pull/49767
=> [10.x] Global Http client options

octane.md
As discussed in https://github.com/laravel/octane/issues/829#issuecomment-1930014964.
This is largely inspired by https://chriswhite.is/coding/frankenphp-and-laravel-octane-with-docker/.
=> [10.x] Document FrankenPHP Docker install

pennant.md
=> [10.x] Pennant purge --except docs

pulse.md
Just duplicated the block, rather than reworking how it all fits together.
=> [10.x] pulse:restart

upgrade.md
This header has no text linked to it.
=> Remove unused header

fortify.md
Depends on https://github.com/laravel/fortify/pull/524.
=> [11.x] Documents `fortify:install` Artisan command

reverb.md
=> Add missing "to" in "in order to"

upgrade.md
Add updated versions for Breeze and Inertia
=> [11.x] Add updated versions for Breeze and Inertia

upgrade.md
similar to the "Miscellaneous" notes we've had in past upgrade guides.
=> [11.x] add miscellaneous upgrade note

upgrade.md
Add new Dusk version to upgrade guide
=> [11.x] Add new Dusk version to upgrade guide

broadcasting.md
I think this must have ended up here after merging 10.x.
=> [11.x] Removes duplicate section

broadcasting.md
39cbb5dee15de938f269a674de650119be653806 introduced multiple duplicate sections. 0e27d90897987784eeb10a68cb566380e384666e fixed one of them. This fixes another
=> Broadcasting - remove another duplicate section

helpers.md
Document the newly added helper function `Arr::mapSpread()` introduced in https://github.com/laravel/framework/pull/50474
=> Document Arr::mapSpread

dusk.md
=> Add reference to the new helper method `sreenshotElement`

validation.md
Document https://github.com/laravel/framework/pull/50454
=> [11.x] Document the list rule

upgrade.md
Related to laravel/framework#47083.
=> [11.x] cURL minimum version and workarounds

authentication.md, hashing.md
As per https://github.com/laravel/framework/pull/50718, this adds in documentation for the new `HASH_VERIFY` env var. I also added in automatic rehashing, since that's needed too.
=> Add Automatic Rehashing and Mixed Hash verification

context.md
Remove the section
https://github.com/laravel/docs/pull/9544
=> [11.x] Add Conditional Context to context

console-tests.md
https://github.com/laravel/framework/pull/50702
=> [11.x] Documents `doesntExpectOutput`

queues.md
Docs for https://github.com/laravel/framework/pull/50896
=> [11.x] Document `report` method of ThrottlesExceptions middleware

dusk.md
=> Add missing import

dusk.md
- Correct code (surplus closing braces)
- Payments don't generally require the `/` to be entered for the expiry date
- Trim trailing spaces
=> Correct code

socialite.md
See https://github.com/laravel/socialite/pull/698.
=> Document Facebook Limited Login support in Socialite

context.md
this PR, fixes grammar in context.md
=> [11.x] Fix grammar

authorization.md
Would be great to see the Inertia approach when using authorization in the frontend.
I'm not super happy about the Warning copy, but figured this would be a good way to get the discussion happening around this
Sorry, I don't know who to tag
=> [11.x] Update authorization.md - include Vue JS approaches

scheduling.md
This PR, Fixed a spelling mistake in scheduling.md
=> [11.x] Fixes spell in scheduling.md

cashier-paddle.md
This PR, fixes some minor issues in cashier-paddle.md for better readability.
=> [11.x] Fixes cashier-paddle.md

pulse.md
Pulse v1 was released today, so some installation instructions can be updated.
=> [11.x] Pulse v1

octane.md
https://github.com/laravel/octane/pull/882
=> [11.x] Puts frankenphp out of beta

pulse.md
This feature has already been released.
=> [11.x] Document disable highlighting

facades.md
https://github.com/laravel/docs/pull/9619
=> [11.x] Add Exceptions to facade table

structure.md
Added by https://github.com/laravel/framework/pull/48115 but undocumented.
=> [10.x] Mention the LARAVEL_STORAGE_PATH env var

prompts.md
Couldn't stop ignoring it any longer..
=> Remove extra "to" word in Multi-select section [prompts.md]

horizon.md
=> Fix typo in horizon

broadcasting.md
Updated the variable type hint from \App\Order to \App\Models\Order for consistency with the model's namespace.
=> Update variable type hint in OrderShipmentStatusUpdated event

broadcasting.md
=> Revert "Update namespace \App\Order  to \App\Models\Order in broadcasting.md"

pulse.md
Requires https://github.com/laravel/pulse/pull/362
=> [11.x] Rename component prop

pulse.md
See: https://github.com/laravel/pulse/pull/355
=> [11.x] Pulse: Ignore offline servers

folio.md
Depends on https://github.com/laravel/folio/pull/134
=> [11.x] Namespace folio make command

validation.md
https://github.com/laravel/framework/pull/51348
=> [11.x] add documentation for new "contains" validation rule

pulse.md
Document pattern based threshold support.
https://github.com/laravel/pulse/pull/340
=> Pulse thresolds

routing.md
=> [11.x] Missing ` ...` in Routing

collections.md
previous code was still working but not for the right reasons
=> Fix typo in passing named argument

billing.md
- Fixed invalid success,cancel route declarations in quickstart-selling-products section by following
[View Routes](https://laravel.com/docs/11.x/routing#view-routes)
=> [11.x] Fixes invalid route declarations

releases.md
I'm updated the release date and php version support
=> Update the release date and php version for laravel v10

migrations.md
Added`Illuminate\Database\Events\NoPendingMigrations` event when there is nothing to migrate
=> docs(migrations): NoPendingMigrations - nothing to migrate event

cache.md
Added a second parameter to the `Cache::pull` method to specify a default value.
=> Add default value in `Cache::pull` method

helpers.md
=> Revert "Fix Lottery helper method name"

upgrade.md
- Apologies, I put the wrong release in on [this PR](https://github.com/laravel/docs/pull/9713), this fixes that
=> Update upgrade.md to include Scout dependency

strings.md
See https://github.com/laravel/framework/pull/51910
=> [11.x] Document Str::chop* methods

dusk.md
=> Align with `waitForRoute()` making it more obvious how to pass parameters

cache.md
=> [11.x] Update cache.md

pennant.md
See https://github.com/laravel/pennant/pull/111
=> [11.x] Document Pennant's `before` hook

pint.md
It also fixes a tiny typo. (define)
=> Add docs for the `empty` preset

eloquent.md, migrations.md, queries.md
Continuation of #9744. I verified that all these features actually work with MariaDB.
=> [11.x] Explicitly document MariaDB support

installation.md
Enumerate features of the Laravel installer to show how it's different than `composer create-project`.
=> Elaborate on Laravel installer's features

upgrade.md
Move `Spatie Once Package` item to `Medium Impact Changes` according to the detail part of it: `Likelihood Of Impact: Medium`
=> Update upgrade.md: Move Spatie Once Package notice to Medium impact list

migrations.md
=> [11.x] Support SQLite foreign keys

requests.md
Document the fix from https://github.com/laravel/framework/pull/50877, triggered by issue https://github.com/laravel/framework/issues/50845
Apologies if I'm not following any protocol for something like this. I couldn't find a lot of information on how to submit a pr.
=> Update trustHosts() documentation to reflect fix

helpers.md
https://laravel.com/docs/11.x/helpers#testing-sleep
=> Update PHPunit test reference to match Pest

eloquent-resources.md
=> Rename `link` to `links`

http-client.md
https://github.com/laravel/framework/pull/52412
=> Add the resource method to the http client docs

middleware.md, routing.md, session.md, strings.md, upgrade.md
Some things I noticed with making some improvements to the laravel.com repository.
=> [11.x] Header fixes

precognition.md
=> [11.x] document async validate

eloquent.md, envoy.md
Fix a duplicate tag and stray tag.
=> [5.0] Header fixes

authorization.md, envoy.md, migrations.md
Backports https://github.com/laravel/docs/pull/9861
=> [5.1] Header fixes

middleware.md, routing.md, session.md, strings.md
Backport https://github.com/laravel/docs/pull/9836 to `10.x`
=> [10.x] Header fixes 

vite.md
See https://github.com/laravel/vite-plugin/commit/eb1f6524160d5617c387be3fed6746cd5d9ba69c
=> Add Livewire directory to full page refresh on file save

authorization.md, controllers.md, eloquent.md, helpers.md, requests.md, verification.md
Maybe some of the links' sentences should be rewritten instead to not reference what they're referencing.  At least this PR highlights the dead links.
=> [11.x] (attempted to) fix/remove dead internal links

queues.md
Following: laravel/framework#52645
=> [11.x] Add Skipping Jobs section

queues.md
See: https://github.com/laravel/framework/pull/52696
=> [11.x] Add dispatching without delay section

passport.md
Namespace fix in `Purging Tokens` section.
=> [11.x] passport.md - Purging Tokens, updated namespace

strings.md
Following on from https://github.com/laravel/docs/pull/8919
=> Document fluent string wrap()

contributions.md
Correcting the active version 10.x to 11.x
=> fix: contributions.md - bug fixes active version

strings.md
Just documenting the new string method doesntContain that was recently merged!
=> [11.x] feat: document new Str::doesntContain method

helpers.md
Just documenting the new currency methods `withCurrency` and `useCurrency` that were recently merged!
=> [11.x] feat: document new Number::withCurrency and Number::useCurrency

middleware.md
document the newly added global middleware
https://github.com/laravel/framework/blob/11.x/src/Illuminate/Foundation/Configuration/Middleware.php#L411
=> [11.x] update the list of global middleware

octane.md
See https://caddy.community/t/confused-about-access-logs/25992 for a use case.
=> Explain how to get structured logs when using FrankenPHP through Octane

mail.md, sail.md, scout.md
Change code block language from "shell" to "ini" for environment variables
=> [11.x] Fix code block language

authorization.md
My colleague made this https://github.com/laravel/framework/pull/53259. So I am making this fix for the docs
=> docs: updating authorization.md

eloquent-relationships.md
Changed the name of the method in the description from 'hasOne' to 'morphOne'
=> Changed the name of the method in the description to the appropriate one

database-testing.md
I was searching for a method to test that a given table was empty, but seemed the docs for `$this->assertDatabaseEmpty()` were missing.
=> Docs for `$this->assertDatabaseEmpty('table')`

container.md
I have written a small scenario about the rebinding method for the events section in container.md
=> Add rebinding method to container docs

installation.md
Bun is a Node/NPM alternative that can handle dependency management and frontend asset compilation, with better 
performance, and simpler installation/upgrading.
I've been solely using Bun for the past 6 months with great success.  I would say Bun fits in more with the "It Just Works" ethos of Laravel than Node/NPM, and IMO we should start encouraging it's use. One of the biggest draws to me is how easy installation and upgrading are, especially compared to Node/NPM.  They have a simple one line Window, Linux, and MacOS install command, and the application can then self-update, much like Composer.  This gets rid of the headache of something like Node Version Manager.
https://github.com/laravel/docs/pull/9064
https://github.com/oven-sh/bun/releases/tag/bun-v1.0.0
=> [11.x] add suggestion for using Bun

validation.md
Document laravel/framework#53341 and laravel/framework#53368
=> Add documentation about version constraint to validation docs

eloquent-serialization.md
syncs up both the comment and the var declaration with `laravel/laravel`
https://github.com/laravel/laravel/pull/6495
=> [11.x] update docblock for Model `$hidden`

container.md
I added missing `RouteParameter` to the example and fixed the `Connection` class path.
=> Update contextual attributes example

scheduling.md
documentation for this [PR](https://github.com/laravel/framework/pull/53795)
=> [11.x] pingOnSuccessIf and pingOnFailureIf -scheduling.md-  PR:#53795

billing.md, contributions.md, database.md, envoy.md, homestead.md, installation.md, mix.md, queues.md, session.md, upgrade.md, valet.md
Although this is an old version of the document, as someone with OCD, I find it difficult to read. I just added simple line breaks where needed
https://laravel.com/docs/5.5/installation#configuration
The correct display should be like version 5.8
https://laravel.com/docs/5.8/installation#configuration
=> [5.5] fix: Link rendering error

queries.md
Changed "Advanced Where Clauses" to heading 2.
=> [11.x] Advanced where clauses

strings.md
documentation for this [PR](https://github.com/laravel/framework/pull/53981)
=> [11.x] update Str::is()  strings.md

dusk.md
Add documentation of assertAttributeMissing.
=> [11.x] Add documentation for dusk.md/assertAttributeMissing

pint.md
Adds documentation for [this new feature](https://github.com/laravel/pint/pull/327)
=> [11.x] Adds documentation for `pint --diff=[DIFF]`

queries.md
It should be `$sender` rather than `$user`.
=> Minor variable fix on example

collections.md
documentation for [collapseWithKeys](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Collections/Collection.php#L149)
=> [11.x] update collections.md : add collapseWithKeys doc

collections.md
Documentation for [intersectAssocUsing](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Collections/Collection.php#L679) and [intersectUsing](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Collections/Collection.php#L656)
=> 11.x update collection md

helpers.md, validation.md
https://laravel.com/docs/5.1/helpers
=> [5.1] fix: The lack of blank lines leads to invalid styles

migrations.md
Changes : 
- Regrouped migrations available column types.  Column types are now grouped for better organization and easier navigation.
=> Regrouped migrations avalable column types.  Column types are now grouped for better organization and easier navigation.

events.md
Add documentation for the feature introduced in
<https://github.com/laravel/framework/pull/53932>.
=> feat: wildcards in event discovery paths

cashier-paddle.md
the `$user` variable does not exist. we need to retrieve the user via `$request->user()`
=> [11.x] pull the user from the `$request`

collections.md, dusk.md
=> [12.x] remove extra linebreaks

releases.md
=> Fix typo in Release Notes page

installation.md
=> [12.x] Added Laravel official Extension support

upgrade.md
These were updated mid-year and there's a possibility devs may have not upgraded this
=> Added PHPUnit and PEST as dependency update

helpers.md
This PR adds **code fences** to missing code blocks to maintain consistency.
=> [12.x] Format code examples in helpers.md for consistency

helpers.md
Documentation for this [PR](https://github.com/laravel/framework/pull/54859)
=> Feat: Add Docs for Array Partition

cache.md
More explicit docs about Cache::lock()->block()
=> [12.x] Update cache.md: Cache::lock()->block()

dusk.md
Removed superfluous ```PHP\n\n```.
=> Fix markdown formatting.

processes.md
Documents the new `ensureNotTimedOut` method.
=> [12.x] Document `ensureNotTimedOut`

eloquent.md
The eloquent method `getOriginal` is already documented, and we should do the same with `getChanges`.
=> Add documentation for getChanges

authentication.md
This is probably not the best place but I wanted to point out this undocumented method
=> Explain redirectUsersTo functionality

mail.md, middleware.md, migrations.md, mix.md, mocking.md, mongodb.md, notifications.md, octane.md, packages.md, pagination.md, passport.md, passwords.md, pennant.md, precognition.md, prompts.md, providers.md, pulse.md, queries.md, queues.md, rate-limiting.md, redis.md
Removed Trailing whitespaces
No other changes
Continuation of #10259
=> [12.x] Fix markdown formatting

http-tests.md
Added documentation for the ddBody method added in Laravel 12.2
=> [12.x] Add `ddBody` to http-tests.md

migrations.md
Great new feature :+1: 
Thanks @danmatthews!
=> Document the new `Migration::shouldRun()` feature

mocking.md
=> Correct remaining `shouldReceive` reference

documentation.md
Fixed a broken link to api docs
=> fixed broken link to api docs page

collections.md
This change aligns the phrasing with Laravel's standard documentation tone, which commonly uses `You may...` to introduce optional or flexible usage.
=> [12.x] Improve consistency in countBy method description

collections.md, eloquent-collections.md
document the code change in https://github.com/laravel/framework/pull/53304
resubmission of #10003
=> [12.x] document change in Eloquent Collection partition behavior

contracts.md, events.md, http-client.md, mail.md, notifications.md
Description
---
Updates the documentation to accurately reflect the comments generated by Artisan commands, ensuring consistency between generated class comments and the corresponding examples in the documentation.
=> [12.x] Updating the docs to reflect the actual generated comment

broadcasting.md
Removes redundant `will` word.
=> Fix typo in `broadcasting.md`

collections.md
https://github.com/laravel/framework/pull/55622
=> [12.x] Support callback `containsOneItem` in Collection

collections.md
Description
---
This PR adds missing type hints to callback parameters.
=> [12.x] Add Missing Type Hints

requests.md
https://github.com/laravel/framework/pull/55735
=> [12.x] Add a default value to the `enum` method

helpers.md
https://github.com/laravel/framework/pull/55815
=> [12.x] Add `Arr::hasAll` method to helpers

requests.md
Description
---
This PR documents how to retrieve an array of input on the request instance. I have placed this after the boolean method example, now we have the following order:
- Retrieving Stringable Input Values.
- Retrieving Integer Input Values.
- Retrieving Boolean Input Values.
- Retrieving Array Input Values.
- Retrieving Date Input Values.
---
Rework of #10440
=> [12.x] Add array method in Request

middleware.md
=> [12.x] Format middleware tables

queries.md
https://github.com/laravel/framework/pull/55885
=> [12.x] Add `reorderDesc` method to queries

container.md
Description
---
This PR complementing the previously added Context attribute.
see: laravel/framework/pull/55799
=> [12.x] Add hidden parameter to the Context attribute in Container

eloquent-mutators.md
https://github.com/laravel/framework/pull/56046
=> [12.x] Add `asFluent` to casting

queues.md
Description
---
This PR removes an unnecessary blank line, reducing two consecutive blank lines to a single one.
=> [12.x] Remove extra blank line

mail.md
Description
---
This PR utilizing the imported `Illuminate\Queue\SerializesModels` trait.
=> [12.x] Format the Queued Email Failures code

helpers.md
Description
---
This PR enhances the `url` function in the `helpers.md` by adding a small mention to `Generating URLs` section in the `urls.md`
Note
---
I used the same tone that we use here: [laravel/docs/pull/10348/files](https://github.com/laravel/docs/pull/10348/files)
=> [12.x] Add proper link

helpers.md
Description
---
Removing it makes the sentence more concise and clearer.
=> [12.x] Improve clarity

configuration.md
https://github.com/laravel/framework/pull/56200
=> [12.x] Add `Config::collection()` to configuration

strings.md
This fixes a couple broken links on the strings page.
=> [12.x] Fix broken links on strings page

prompts.md, queues.md
Description
---
This PR enhances the PCNTL PHP extension by adding links to point to the official PHP docs.
=> [12.x] Add proper links

mail.md
Description
---
Add documentation for the newly introduced option in: https://github.com/laravel/framework/pull/55222
=> [12.x] Add retry_after option

prompts.md
Description
---
Add documentation for the newly introduced prompts tests methods in: https://github.com/laravel/framework/pull/56260
=> [12.x] Add prompts tests

eloquent.md
Description
---
Removes unnecessary space to improve cleanliness.
=> [12.x] Remove redundant space

mail.md
This featured has been [merged](https://github.com/laravel/framework/pull/56340) to Laravel recently.
=> [12.x] Update the example to include the usesMailer method

queues.md
=> Revert "Fix wrong grammar in comment"

collections.md
https://github.com/laravel/framework/pull/56522
=> [12.x] Add `doesntContainStrict` method to Collections

migrations.md
Related to https://github.com/laravel/framework/pull/56565
=> [12.x] Document Enum::cases()

strings.md
Continuation of: #10680 and https://github.com/laravel/framework/pull/56453
=> [12.x] Document version-specific UUID string validation

container.md
Description
---
Update to singular form for clarity.
=> [12.x] Update the link of the newly introduced Bind Attribute

validation.md
- Removed words, added words, and added commas for what I hope is more clarity
=> [12.x] Fix a few typos in validation.md

queues.md
Description
---
This PR improves the **Max Exceptions** example by:
- Add a missing `ShouldQueue` import.
- Add a missing `Queueable` trait.
=> [12.x] Enhance the Max Exceptions code

queues.md
Description
---
This PR improves the explanation by adding why we might share a bucket without overexplaining.
=> [12.x] Clarify common throttling bucket usage

queues.md
Description
---
This PR enhances the **PHP GD library** by adding link to point to the official PHP docs.
=> [12.x] GD proper link

queues.md
Description
---
Display the method name in bold.
=> [12.x] Fix method name formatting

collections.md
https://github.com/laravel/framework/pull/56697
=> [12.x] Add `toPrettyJson` method to collections

processes.md
Description
---
This PR reorders and expands the example in the Processes documentation for improved clarity.
Reasoning
---
The updated order gives the example a clear, narrative flow:
1. What command ran.
2. Did it succeed or fail.
3. What output or errors it produced.
4. What was the final exit code.
=> [12.x] Add command method to ProcessResult

dusk.md, pint.md
there are new versions of these actions. I ran a small test in a dummy repo and they behaved correctly
- https://github.com/actions/checkout
- https://github.com/stefanzweifel/git-auto-commit-action
=> [12.x] update GitHub actions to latest versions

eloquent-factories.md
An “s” is added to variables if the count method is used, and vice versa.
=> Fix plural form
