blade.md
broadcasting.md
collections.md
container.md
contracts.md
controllers.md
eloquent-mutators.md
events.md
horizon.md
mail.md
queues.md
views.md

using promoted properties makes the docs more succinct.
I did not switch to promoted properties when the properties were not explicitly defined in the code already.

[10.x] Use promoted properties

---

migrations.md

[10.x] Support native column modifying

---

notifications.md

Make it clearer that you should set this environment variable for Vonage notifications to work.
As it was before the docs could lead users to believe that this environment variable was optional. But if it is not set and the `toVonage()` method of the notification doesn't set a custom sender with `->from()` (which is also described as optional later in the documentation), sending the message will fail with an error because `\Vonage\SMS\Message\SMS::__construct()` expects the $from argument to be a string, which crashes here : https://github.com/laravel/vonage-notification-channel/blob/3.x/src/Channels/VonageSmsChannel.php#L60

Update VONAGE_SMS_FROM documentation

---

upgrade.md

This pull request follow up on https://github.com/laravel/framework/pull/46096, and specifies that Laravel now requires Composer 2.2 or greater.

[10.x] Specifies that Laravel now requires Composer 2.2 or greater

---

pennant.md

We don't have to include the `'auth'` in the example, but I thought it might help.

[10.x] Add note to feature middleware about authentication

---

pennant.md

This adds a section on how to add a custom driver for Pennant's storage. A stub Redis storage implementation code is used for clarity.

[10.x] Add documentation for custom pennant driver

---

blade.md

Another try of https://github.com/laravel/docs/pull/8583
As this method is not included in Component class stub, not everyone knows that we can render component by some conditions. Previously I had to return null from `render` method for that.
Or maybe it just should be included in Component class stub?

Add information about shouldRender method

---

pennant.md

1. Moved the "Retrieving All Features" to after discussing "values". Felt "values" was really prior knowledge and it goes will with "Eager Loading".
2. Renamed "Retrieving Multiple Features" and added documentation on `Feature::values(['foo', 'bar'])`
The only change to the `all` docs was the addition of `'billing-v2'` to the output array to differentiate from the output of the `values` example.

[10.x] Documents `Pennant::values`

---

eloquent-serialization.md

the current wording makes it seem like you have to add the attribute to the `$appends` property.  I'm hoping this new wording emphasizes that it is optional, and helps the reader understand when and why they would or would not want to use it.
this is a resubmission of #8535, hoping it is a good compromise from where I originally started.

[10.x] update note about appending accessors

---

upgrade.md

This PR addresses laravel/framework#46132

[10.x] upgrade doc updated for removed registerPolicies method

---

documentation.md

Change `9.x` to `10.x` in the master docs.
Or maybe it should lead to `master`? That apparently didn't work at some point in time (#7249) but at the moment https://laravel.com/api/master/ is a fine page.

Update link to API docs

---

upgrade.md

**I'm trying to upgrade from laravel 9 to laravel 10.**
I've followed [the Upgrade Guide](https://laravel.com/docs/10.x/upgrade#updating-dependencies) by updating the dependencies like this:
Then I'm stuck with this error:
I tried to change only the `laravel/sanctum` to `^3.2` (https://github.com/laravel/laravel/commit/af241e157245de5013ea97aabdf3b5aa789bf01a). And **it's works**!
So, I think is necessary to **mention the `laravel/sanctum` version update** in [the Upgrade Guide](https://laravel.com/docs/10.x/upgrade#updating-dependencies).

[10.x] Add `laravel/sanctum` to the list of dependencies to update

---

upgrade.md

fix the minor mis-type of the method name

[10.x] correct `registerPolicies` method name

---

valet.md

As the minimum PHP version for Laravel 10 is `8.1`, this pull request updates the version of PHP to `8.1` in the Valet documentation.

[10.x] Update PHP version to `8.1` in Valet documentation

---

contributions.md

We still get issues about docblocks regularly so I figured I'd add a note about this to the contribution guide.

[10.x] Add note about IDE warnings

---

eloquent-factories.md
validation.md

Based on https://github.com/laravel/laravel/pull/6119, this pull request removes `@return $this` when returning static.

[10.x] Removes `@return $this` when returning static

---

telescope.md

This pull request documents Telescope's new log `level` option: https://github.com/laravel/telescope/pull/1312.

[4.x] Documents Telescope's log `level`

---

authorization.md
cache.md

Since Laravel requires PHP 8, [Null-safe operators](https://php.watch/versions/8.0/null-safe-operator) can replace the `optional()` helper function.

[10.x] Replace optional by Null-safe operator

---

upgrade.md

DBAL v2 is no longer supported: https://github.com/laravel/framework/pull/44733

[10.x] Mention minimum DBAL version in upgrade guide

---

eloquent-mutators.md
validation.md

Removed PHP 8.1 requirement warnings as `laravel/laravel` and `laravel/framework` already requires `^8.1`
---
Additional warnings found not included in this pull request:
- [Octane](https://github.com/laravel/docs/blob/10.x/octane.md) (Line 50)

[10.x] Removed PHP 8.1 warnings

---

mocking.md

I thought the Time manipulation of the _Mocking_ section of testing could have more details on what is offered, and why you may use it.

[10.x] Adds more examples to time manipulation

---

upgrade.md

"In previously releases of Laravel..." -> "In previous releases of Laravel..."

[10.x] fixed small typo in upgrade documentation

---

artisan.md

Explain that when writing a command `--queue=default` equals to `-Qdefault` and not to `-Q=default` (otherwise `$this->option('queue');` returns `"=default"` instead of `"default"`)

[10.x] Pass a value to an option with a shortcut without =

---

upgrade.md

There is a possible undocumented breaking change with the implementation of Flysystem 3.x if an application uses private-public key authentication for the SFTP Adapter. The config key `password` needs to be renamed to `passphrase`.

[9.x] Config key renaming with Flysystem upgrade

---

eloquent-mutators.md

As per the discussion at https://github.com/laravel/framework/issues/46005, while using ```casts``` on primary keys may work in simpler scenarios, it seems to break down in more complex situations (e.g. pivot models).
This PR attempts to document that using casts on primary key fields should not be attempted.
Suggestions are welcome on how to formulate this limitation better.

Document primary keys as castables not being supported

---

valet.md

So many times I hear people using `valet use` and breaking their setup. I feel like this warning should help push people to use `valet isolate` when it's more likely than not the command they're actually wanting to/should use.

[10.x] Added warning for valet use, pushing usage of valet isolate instead

---

eloquent-relationships.md

when constraining the eager loaded relationship, the class actually passed into the closure is an instance of the actual relationship class, which implements `Illuminate\Contracts\Database\Eloquent\Builder`, and **not** `Illuminate\Database\Eloquent\Builder`.
it would be very easy for a user to be confused, since in most of these other examples an `Illuminate\Database\Eloquent\Builder` is actually passed to the closure.

[10.x] import correct Builder namespace

---

middleware.md

middl**e**ware instead of middlware

[10.x] Fix small typo

---

collections.md

The first example of the `reduce` method does not specify a value for the first iteration.
This will result in a TypeError when using the example; specifying the first parameter as nullable will resolve this.

[10.x] - Declare $carry as nullable

---

upgrade.md

I wanted to upgrade project which contained laravel/passport in *composer.json* file as a dependency to Laravel 10. I found out that Laravel Password needed to be updated because of low version of `illuminate/support` in its *composer.json*.
As this happened, I decided to create this P.R. which contains updated *upgrade.md* with Laravel Passport mentioned.

[10.x] - Add laravel/passport to upgrade guide

---

valet.md

(https://github.com/laravel/valet/issues/1378)
This PR updates the docs for Valet v4:
- Update `.valetphprc` to `.valetrc`
- Add upgrade instructions for v4
- Add some commands we hadn't documented to the "other commands" list
- Update the `valet share` instructions to add the new `share-tool` concept and the `set-ngrok-token` command
- Add the note about `127.0.0.1` in your DNS settings if you're using alternate DNS servers

Update Valet docs for v4

---

helpers.md

When passing a callable to `Str::replaceMatches()`, the callable actually receives an array, not `Stringable`, as in the current documentation

fix input parameter type

---

filesystem.md

This will save people a few hours of searching as setting file and directory permissions for the SFTP driver is not well documented. This is particularly useful for people upgrading from SFTP v2 as config params have changed in SFTP v3.
Hope this helps.

[10.x] Fix Missing Config Params on SFTP Driver

---

eloquent-resources.md

A Google search on "how to customize eloquent resource pagination metadata" shows that I'm not the only one who wants to know how to do this. Unfortunately none of the results provide the correct answer.
After a bit of digging, I discovered that [PaginatedResourceResponse](https://github.com/laravel/framework/blob/136ed754f2d80e5c7cd407a4262eb2eac478e7e8/src/Illuminate/Http/Resources/Json/PaginatedResourceResponse.php#L53-L56) allows you to override the default result. And as far as I can tell, this feature hasn't been documented.

Document how to customize pagination information for resources

---

passport.md

Add exception message on `throw_unless` for `InvalidArgumentException`. This will guide developer to custom the message and make logs capture more readable.

Add exception message for InvalidArgumentException

---

testing.md

Reproduction steps:
1. Install a fresh version of Laravel 10 with `composer create-project laravel/laravel=10.0.4 example-app`
2. Run `php artisan test -p`
This returns the following error message:
```
NunoMaduro\Collision\Adapters\Laravel\Exceptions\RequirementsException 
Running Collision 7.x artisan test command in parallel requires at least ParaTest (brianium/paratest) 7.x
```
By reading the docs, I got the impression that all I needed to do was to require "nunomaduro/collision" to get parallel tests running, but it's not the case.

Running parallel tests require brianium/paratest

---

eloquent-resources.md

The explanation is not relevant for the current example.

Remove obsolete explanation

---

migrations.md

The Postgres grammar creates an `INET` column instead of a `VARCHAR`. https://github.com/laravel/framework/blob/be2ddb5c31b0b9ebc2738d9f37a9d4c960aa3199/src/Illuminate/Database/Schema/Grammars/PostgresGrammar.php#L943

indicate postgres-specific handling for ipAddress

---

events.md

Fixed a typo by changing
"...helpers makes it a cinch"
to
"...helpers make it a cinch"

Fixed typo in events.

---

migrations.md

Currently it seems `useCurrentOnUpdate` would work in any database, but both PostgreSQL & SQLite ignore this modifier.

Cited useCurrentOnUpdate modifier to be MySQL specific.

---

eloquent-factories.md

PR adds an indication that setting the $model is not required when normal naming conventions are being followed as Laravel is able to resolve the model class based on the name of the factory class.

Minor Clarification on Eloquent Factory Creation

---

dusk.md

Dusk is very commonly used in Chipper CI. We have [docs](https://chipperci.com/docs/testing/laravel-dusk-new/) on using Dusk, but it would be very handy if the official docs mentioned Chipper as well!

[10.x] Add Chipper CI to Dusk docs

---

eloquent-mutators.md

This commit replaces the actual date example in the "Eloquent: Mutators & Casting" section with a more generic representation of the UTC ISO-8601 format. The change aims to prevent search engines from misinterpreting the example date as the publication date of the documentation page and to provide a clearer representation of the format for readers.
refer to 
"https://developers.google.com/search/blog/2019/03/help-google-search-know-best-date-for#:~:text=Google%20determines%20a%20date%20using,can%20be%20prone%20to%20issues."

Update ISO-8601 date example in Eloquent: Mutators & Casting

---

processes.md

This is fixing the examples to use `;` instead of `,`

[10.x] Fix typo on process pipeline examples

---

eloquent.md

When we want to read scope section in Eloquent page, there is no section about how can generate scope with artisan command!
When I'm teach Laravel course, I had a old knowledge to generate scope. But many developers didn't know about to generate scope in Laravel!

[10.x] Add generate scope in eloquent

---

rate-limiting.md

Was copying and pasting some example code from docs and discovered missing comma before 4th argument in the example.
I'll admit I'm embarrassed to submit such a pathetic PR.

Missing comma before argument in example code.

---

notifications.md

When using UUID/ULID primary keys on notifiable models, you can get a confusing error with the default migration created by `artisan notifications:table` when it tries to store the UUID in an integer column:
```
SQLSTATE[01000]: Warning: 1265 Data truncated for column 'notifiable_id' at row 1 at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:578
```
This PR adds a note to the [Database Notifications](https://laravel.com/docs/10.x/notifications#database-notifications) section of the docs reminding users to update the migration to use the `uuidMorphs`/`ulidMorphs` methods.

[10.x] Add note about UUID/ULID keys on notifications table

---

logging.md

In response to [this blog post by @Crell](https://peakd.com/hive-168588/@crell/using-psr-3-placeholders-properly), I've added PSR-3 compliant placeholders in the documentation where the 2nd `$context` parameter was passed to any of the methods on the Logger.
This promotes better data-hygiene and hopefully prevents newcomers from introducing potentially exploitable code.

Use PSR-3 placeholders in logging docs

---

homestead.md

VirtualBox recently released the 7.x version, but Homestead still requires the 6.1.x version.
Changed the link to the 6.1.x download page so that people don't accidentally download the 7.x version.

Update VirtualBox link on Homestead page

---

configuration.md

This change adds a small tip on how to clear the config cache. Because for now documentation tells us how to create a cache, but doesn't tell us how to clear the existing cache

[9.x] add a small tip on how to clear the config cache

---

configuration.md

This change adds a small tip on how to clear the config cache. Because for now documentation tells us how to create a cache, but doesn't tell us how to clear the existing cache

[10.x] add a small tip on how to clear the config cache

---

broadcasting.md

This is a super minor typo fix :) But, it makes the channel names consistent between examples to eliminate any possible confusion.

[10.x] Change channel prefix for presence channel example

---

validation.md

The Str class has not been used in the example of the passedValidation method, So I just removed the line that imports the class.

[10.x] Remove Importing 'Illuminate\Support\Str'

---

vite.md

The example in "Correcting Dev Server URLs" shows code that will prepend the dev server URL, but the description says "append". This PR fixes that.
Before:

Replace 'append' with 'prepend' in Vite example.

---

notifications.md

This PR replaces the unused 'Formatting Shortcode Notifications' anchor link to the currently non-linked 'Unicode Content' section

[10.x ] Update notifications.md to replace unused anchor link

---

scout.md

When https://github.com/laravel/scout/pull/732 is released

[10.x] Scout - Document 'makeSearchableUsing' method

---

scout.md

I don't fully understand why this has been changed to a Collection. Also the `$query` variable is not included.
If this is correct, how does it work?
Thanks.

Fix makeSearchableUsing using $query instead of $models

---

queues.md
scout.md

We recently ran into an issue with scout under the following conditions:
- Development environment with lazy-loading disabled
- Sync queue
- Scout queue enabled
- Bulk importing records to scout using `artisan scout:import modelname`
As noted in https://github.com/laravel/framework/pull/36712 relationships on collections/arrays in jobs are not restored, and this is intended behavior as of now. 
However, this also prevents scout from using previously loaded relationships configured using `makeAllSearchableUsing`.
This PR adds clarifying language so that developers know that if they want to utilize the eager loading functionality provided in scout for bulk adding, they cannot use the queue at the same time.

[10.x] Add warnings to scout and queue pages to clarify functionality

---

upgrade.md

This pull request adds the `Dumpable` changes to upgrade guide, regarding the `Enumerable` contract.

[11.x] Adds `Dumpable` changes to upgrade guide

---

billing.md

Related PR:
- https://github.com/laravel/cashier-stripe/pull/1534
Also slightly adjusts the order of the webhooks to match the `cashier:webhook` command

[10.x] Add `payment_method.automatically_updated` webhook for Cashier

---

billing.md

Related PR:
- https://github.com/laravel/cashier-stripe/pull/1534
Also slightly adjusts the order of the webhooks to match the `cashier:webhook` command

[9.x] Add `payment_method.automatically_updated` webhook for Cashier

---

rate-limiting.md

It might seem obvious once you get it, but it took me a while (too much... 🤦🏻 ) to realize that the `tooManyAttempts` method does not increment the attempts count, therefore the code snippet was somewhat misleading. 
I think this small change would make super clear how to manually interact with the limiter.
**Before:**
**After:**

Clarification about rate limiter

---

homestead.md

Adds in additional features that have been added.
Remove section on symbolic links on Windows as the latest Homestead versions now automatically add this option if running on Windows

Update Laravel Homestead Documentation

---

horizon.md

The default balancing strategy has been `auto` for quite some time now, but the docs still state that `simple` is the default. This change brings the docs in line with the default Horizon config.
https://github.com/laravel/horizon/blame/5.x/config/horizon.php#L186

[10.x] Horizon: update the default strategy wording to match default config

---

filesystem.md

This pull request temporarily adds `--with-all-dependencies` to require `league/flysystem-aws-s3-v3`, as at this time, AWS Client does not support `guzzlehttp/promise@^2.0`.
https://github.com/aws/aws-sdk-php/blob/17d7df5b89bb06e915931a65f643cf3469f8994c/composer.json#L22

[10.x] Temporarily adds `--with-all-dependencies` to require `league/flysystem-aws-s3-v3`

---

helpers.md

The first $array parameter is missing

Fix error in Arr::mapWithKeys() example code

---

http-tests.md

These classes have not been used in the examples.

[10.x] Remove importing classes from some examples of HTTP Tests

---

migrations.md

It may be useful to document how to pretend a migration rollback without execution.

Update migrations.md - migrate:rollback --pretend

---

http-tests.md

It is worth having the method `assertMethodNotAllowed` in the document of HTTP Tests.

[10.x] Document `assertMethodNotAllowed`

---

http-tests.md

This class has been used once in HTTP Tests and has never been imported in the other examples of this page.

[10.x] Import `Crypt` in the example of `assertSessionHasInput`

---

eloquent-relationships.md

Fixed a word in Eloquent Relationships page.
The `or` clause in the query is referring to posts, not the user.

[10.x] Fix word in Eloquent Relationships page

---

hashing.md

Importing `Controller` is unnecessary When `PasswordController` is in the same namespace as `Controller`.

[10.x] Remove importing `Controller` from one example in hashing.md

---

vite.md

The current docs only describe a `module.exports` example for `postcss.config.js`. With the changes to the skeleton (laravel/laravel#6090) the export would have to be changed to an ESM export

[10.x] Add ESM export to Vite `postcss.config.js` example

---

queries.md

Added single space around construct in "Or Where Clauses" example

[10.x] Added single space around construct

---

eloquent-relationships.md

When I tried to use `Illuminate\Database\Eloquent\Builder` namespace I got **Argument #1 ($query) must be of type Illuminate\Database\Eloquent\Builder, Illuminate\Database\Eloquent\Relations\HasMany given** error, and when I used `Illuminate\Contracts\Database\Eloquent\Builder` namespace the issue was solved 🎉.

[10.x] Fix the invalid namespace issue

---

helpers.md

We have the `toCssClasses` method in docs, but there is no section for `toCssStyles`.

[10.x] Add `toCssStyles` to helpers

---

requests.md

To follow the convention set by `has`, `whenHas`, and `hasAny`, it would be appropriate to include the method `anyFilled` as part of the `filled` method.

[10.x] Add anyFilled request method

---

requests.md

The `fullUrlWithoutQuery` method is a useful method in Request, but there isn't in docs!!

[10.x] Add `fullUrlWithoutQuery` method in requests

---

vite.md

Fixes: https://github.com/laravel/framework/issues/47670
With the recent change to ESM, the SSR server location in the docs needs to be updated.
I've also included a note about the `inertia:start-ssr` Artisan command, which automatically handles this for Inertia users.

[10.x] Update SSR server location and include `inertia:start-ssr` command

---

helpers.md

Fixes the error:
```
{closure}(): Argument #1 ($match) must be of type Illuminate\Support\Stringable, array given
```
Relates to: https://github.com/laravel/framework/blob/6d690edda8c5b0d400a8753def02d9ecd3e98e40/src/Illuminate/Support/Stringable.php#L661-L676

Fix erroneous typehint for `Stringable::replaceMatches`

---

installation.md
sail.md

Related to this issue: https://github.com/laravel/sail/issues/81#issuecomment-1626401679
Now includes how to switch docker context.
Please let me know if there is another place in the docs where this warning is more suitable.

Add warning to switch docker context

---

precognition.md

The placeholder {version} in the text was corrected to {{version}} to ensure proper rendering. This change improves the accuracy of the documentation.

[10.x] Fix placeholder in Precognition documentation

---

eloquent-factories.md

This prevents PHPStan from displaying the following error:
`PHPDoc type string of property is not covariant with PHPDoc type class-string<Illuminate\Database\Eloquent\Model> of overridden property`

[10.x] Fix type hint

---

filesystem.md

update the comment according to the defaults from https://github.com/thephpleague/flysystem/blob/3.x/src/UnixVisibility/PortableVisibilityConverter.php#L13

[10.x] update the permissions comment in the public visibility of sftp driver

---

vite.md

This might have ended up here when copy-pasting from somewhere else. But of course it'll throw an exception when using the snippet as-is.

Remove faulty parameter

---

eloquent-factories.md

The current docs on [factory callbacks](https://laravel.com/docs/10.x/eloquent-factories#factory-states) seem to read as though `afterMaking` and `afterCreating` can only be used inside the `configure` method.
I think it's worth highlighting that they can be used separately and in combination with a factory state so they can be used conditionally.

Indicate how states and factory callbacks can be used together

---

sail.md

The latest Sail version doesn't support PHP 7.4 anymore and therefor this can be removed.

[10.x] Remove PHP 7.4 reference in sail docs

---

http-client.md

This PR adds a `use` statement for the `RequestException` referenced in the code sample below it, as the other classes referenced in the sample are also imported:
```php
use Exception;
use Illuminate\Http\Client\PendingRequest;
$response = Http::withToken($this->getToken())->retry(2, 0, function (Exception $exception, PendingRequest $request) {
if (! $exception instanceof RequestException || $exception->response->status() !== 401) {
return false;
}
$request->withToken($this->getNewToken());
return true;
})->post(/* ... */);
```

[10.x] Add missing `RequestException` use statement in HTTP Client docs

---

sail.md

Scout now natively supports Meilisearch, and the linked Github repo has been archived.

Remove link to archived Meilisearch Scout package

---

container.md
octane.md
queues.md

The `Models` folder was missing from some of the models' usages.
P.S: `use App\\[A-Za-z]+;`

[9.x] Consider 'Models' folder for the models path usages

---

container.md
octane.md
queues.md

The `Models` folder was missing from some of the models' usages.
P.S: `use App\\[A-Za-z]+;`

[10.x] Consider 'Models' folder for the models path usages

---

broadcasting.md
container.md
octane.md
queues.md
releases.md

The `Models` folder was missing from some of the models' usages.
P.S: `use App\\[A-Za-z]+;`

[8.x] Consider 'Models' folder for the models path usages

---

validation.md

It seems that if a field is not found, the validation rule falls back to the value. This was not immediately clear when reading the documentation. It would be great to capture this in the header title of this rule, but I'm not sure how to capture that properly (maybe `gte:_field_ or gte:_value_`?)

[10.x] Add validation docs for `gt` and `gte` with value as the parameter

---

helpers.md

The docs don't provide an example of the third parameter available to the rescue helper function. This PR adds an example explaining how reporting can be conditional via a closure.

Update rescue helper examples

---

eloquent.md

This PR moves the `updateOrCreate` docs from `upserts` section to `updates` section for reasons as detailed below:
This function is a convenience method for `firstOrNew`/and save (see code below). It has potential race conditions, which a proper upset shouldn't have - so it's misleading to be under the `upsert` section and could bite a few people (like it did for our project!). The `upsert` method produces a proper query using `INSERT ... ON DUPLICATE KEY UPDATE` which doesn't have race conditions.
```php
/**
* Create or update a record matching the attributes, and fill it with values.
*
* @param  array  $attributes
* @param  array  $values
* @return \Illuminate\Database\Eloquent\Model|static
*/
public function updateOrCreate(array $attributes, array $values = [])
{
return …
```

Move updateOrCreate from upsert to update section

---

upgrade.md

Deprecated removal was brought back in https://github.com/laravel/framework/pull/41923

[10.x] getBaseQuery -> toBase was reverted

---

middleware.md

Current recommendation is to use the `singleton` binding method - but this won't return the correct instance if running under Laravel Octane.

[10.x] Recommend scoped method for binding terminable middleware

---

helpers.md

Descripción de uso del nuevo método `Str::wordWrap`
```php
use Illuminate\Support\Str;
$text = "A very long woooooooooooord."
Str::wordWrap(string: $text, characters: 8);
/*
A very
long
wooooooo
ooooord.
*/
```

[10.x] Description of use of the new method `Str::wordWrap`

---

mail.md

This PR adds the `transport` key to the Mailgun driver example.
**Why is this important?**
- **Consistency:** By specifying the `transport` key explicitly, we make the driver configuration more consistent with the other configurations.
- **Clarity:** For developers unfamiliar with the specifics of the Mailgun driver, having the transport explicitly defined can make the configuration more self-explanatory.

[10.x] Add transport key to Mailgun driver in Laravel mail config

---

helpers.md

In line with other string replace functions, the argument order of `replaceStart` and `replaceEnd` is `$search`, `$replace`, `$subject`.

[10.x] Fixes argument order

---

notifications.md

Need to edit the example for sure.
The new version (^3.0) of the `slack-notification-channel` package, fails if we provide the route as a slack hook `(https://hooks.slack.com/services/...)` instead of a channel `#slack-channel`.
Apart from the example fix, I have also added a note for people who would be upgrading. This is exactly the issue I faced. The upgrade seems to be backwards compatible except when you start using block-notation. Then, you also need to update the route type from a URL/URI to `#sample-channel`

Fix Slack notification routing

---

socialite.md

This pull request removes the `linkedin` provider from Socialite documention, and starts mentioning `linkedin-openid` only.
Refers to: https://github.com/laravel/socialite/pull/662.

[10.x] Adds `linkedin-openid`

---

vite.md

Documents the `Vite::content()` method - which is useful if using something like Browsershot for PDF generation.

[10.x] Add Vite::content() to Vite docs

---

pennant.md

Simplifies and also corrects the method, as it was changed to `using`.
Before:
After:

[10.x] Simplify Pennant middleware.

---

database.md

Related to #8923
| Database | On Laravel 10 | End of Life | Bumped to |
| ------------- | ------------- | ------------- | ------------- |
| MariaDB  | 10.10+ | Nov 2023 | 10.11+ |
| MySQL  | 5.7+ | Oct 2023 | 8.0+ |
| PostgreSQL | 11.0+ | Nov 2023 | 12.0+ |
| SQLite | 3.8.8+ | - | 3.35.0 |

[11.x] Bump supported database versions

---

collections.md

Documentation for the `Collection::diffAssocUsing()` method introduced in laravel/framework#23192

[10.x] Document Collection::diffAssocUsing() method

---

views.md

Refers to https://github.com/laravel/framework/pull/48330.

Adds `make:view` command documentation

---

routing.md

The current docs contains some unrecommended legacy PHP syntax to make types nullable.
See PHP docs for referencece:
https://www.php.net/manual/en/language.types.declarations.php
> Note:
>
> It is also possible to achieve nullable arguments by making null the default value. This is not recommended as if the default value is changed in a child class a type compatibility violation will be raised as the null type will need to be added to the type declaration.
> 
> Example #2 Old way to make arguments nullable
> ```php
> <?php
> class C {}
>
> function f(C $c = null) {
>    var_dump($c);
> }
>
> f(new C);
> f(null);
> ?>
> ```

fixed legacy PHP syntax in Optional Routing 

---

mail.md

Change warning that inline attachments will not be rendered to a note that says attachments will be shown as data urls.

Note about inline attachments rendered as data urls in browser

---

prompts.md

Just a suggestion for an alternative way to document the `hint` feature by including it in the "kitchen sink" example for each prompt instead of a dedicated section.

[10.x] Alternative prompt hint documentation

---

contributions.md

Add github link to `laravel/prompts`

[10.x] Add `laravel/prompts` to contributions page

---

sanctum.md

According to the issues below, sanctum requires the referer or origin header:
https://github.com/laravel/sanctum/issues/203
https://github.com/laravel/sanctum/issues/218
I think it would be better to write that in the manual.

Add that sanctum requires origin or referer header

---

errors.md

So much easier to just set the property in the exception handler, which is where you are probably looking for this feature. Keeps everything colocated.

Improve deduplicating reporting setup example

---

migrations.md

In both cases, the documentation says that the column type is `UNSIGNED BIGINT `, but that can vary depending on the model key type.

Adjust documentation for `foreignIdFor` and `morphs` migration methods

---

billing.md

This PR adds info about the subscription_items table to the Database Migration section.

Add the subscription_items table to the Cashier Migration section

---

authentication.md

Avoids introducing a crash when one does copy 'n paste coding.

Properly terminate group/closure method call

---

precognition.md

I found and fixed a typo in the Precognition docs.
`it's` vs `its`

Fix typo in Precognition docs

---

controllers.md

Hi,
These classes have not been used in the example of `Single Action Controllers`.

[10.x] Remove importing unused classes in one example of controllers.md

---

session.md

Hi,
Importing Controller is unnecessary When `UserController` is located in the same namespace as `Controller`.

[10.x] Remove importing Controller from one example in session.md

---

eloquent-mutators.md

Fixed the URL to the Strings page from the Helpers page as the string methods are moved to their own page from the Helpers page.

Fix URL in Eloquent: Mutators & Casting page

---

validation.md

Hi,
Importing Controller is unnecessary When `PostController` is located in the same namespace as `Controller`.

[10.x] Remove importing Controller from two examples in validation.md

---

processes.md

Passive voice of the verb "to run" is "run" not "ran."

[10.x] Corrected trivial grammatical error on Processes page.

---

migrations.md

While looking into the `virtualAs` modifier it looks like PostgreSQL & SQLite are missing from the description based on the [ColumnDefinition](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Database/Schema/ColumnDefinition.php#L33) class doc block and [10.x virtualAs api docs](https://laravel.com/api/10.x/Illuminate/Database/Schema/ColumnDefinition.html#method_virtualAs). 
This also looks to be the case in 9.x & 8.x documentation. Can open subsequent PRs if welcomed.

[10.x] update `virtualAs` description to include all supported databases

---

logging.md

There's no "null" driver for logging. There is only a "null" channel.

Remove reference to "null" log driver that doesn't exist

---

homestead.md

Vagrant Cloud now supports specifying architecture on boxes so Apple Silicon users no longer need to specify the `laravel/homestead-arm` box.
Related links:
* https://github.com/laravel/homestead/issues/1901
* https://app.vagrantup.com/laravel/boxes/homestead/versions/13.0.0 (now contains the arm64 box)

[10.x] Update homestead.md removing laravel/homestead-arm reference

---

sail.md

* Update default node version after https://github.com/laravel/sail/pull/628
* Bump example of alternate Node version

Sail: Update Node versions

---

logging.md

minor update who we should set request id in header, this will fail for `BinaryFileResponse`.
We can be reproduced with Livewire package, the request to `livewire/livewire.js` will fail.

update for setting request id in header  logging.md

---

facades.md

This will highlight the difference between the first and the second code examples in the [Real-Time Facades section](https://laravel.com/docs/10.x/facades#real-time-facades), that actually two more things in the `publish` method has also changed.
Before            |  After
:-------------------------:|:-------------------------:

[10.x] Highlight diff in Real-Time Facades code examples

---

horizon.md

After investigation into why our Horizon installs are still reporting long waits after 60 seconds when it's explicitly stated otherwise in the config, we did some further research. 
We have seen that the `waits` array in the Horizon config does not accept multiple queues passed with commas, as seen in the code itself (see link below).
https://github.com/laravel/horizon/blob/fd5c8957e08419455cce6efdfc8f2c38a812debd/src/Listeners/MonitorWaitTimes.php#L56
Due to this, the documentation seem to be outdated/incorrect and has been updated to reflect both the default wait, which is 60 seconds, and how it would look if you have multiple queues with different wait times to report on.

[10.x] Update Horizon Documentation to reflect the allowed waits config values

---

events.md

The event that gets passed into the `withDelay` method is actually the Event `OrderShipped`, not the Listener `SendShipmentNotification`. Because of the way that the docs chunk up the examples, it's not clear that this is, in fact, the Listener. As such, when I went to add a delay to a Listener (following this example) I received a type error. This change updates the docs to show the actual event that will be passed to the `withDelay` method.

[10.x] Update the withDelay example to include the event, not the listener

---

homestead.md

Rust was merged into homestead: https://github.com/laravel/homestead/pull/1905
I've also included other features I noticed that were missing

[10.x] Add Homestead Rust Feature

---

queues.md

This PR adds documentation for the [`assertBatchCount()`](https://github.com/laravel/framework/blob/3d37d781d4bd299e17e4c58c6a85963747ac4762/src/Illuminate/Support/Testing/Fakes/BusFake.php#L461-L472) and [`assertNothingDispatched()`](https://github.com/laravel/framework/blob/3d37d781d4bd299e17e4c58c6a85963747ac4762/src/Illuminate/Support/Testing/Fakes/BusFake.php#L474-L482) methods.

[10.x] Add `assertBatchCount()`, `assertNothingBatched()`

---

validation.md

while the previous code is correct, and the new code is simply a wrapper for the old code, every other example on this page uses the static method call to `Illuminate\Validation\Rule`, so we'll do this for consistency.

[10.x] consistently use `Rule` static methods

---

eloquent.md

Fix the incorrect link of `"ordered" UUIDs` to [/strings#method-str-ordered-uuid](https://laravel.com/docs/10.x/strings#method-str-ordered-uuid) from [/helpers#method-str-ordered-uuid](https://laravel.com/docs/10.x/helpers#method-str-ordered-uuid).

Laravel 10.x docs: Fix incorrect link to "ordered" UUID.

---

installation.md

Laravel was suggesting to create `database.sqlite` file automatically once it was missing [since `9.x`](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Console/Migrations/MigrateCommand.php#L166). To make full use of this code I suggest to remove the unnecessary
```Shell
touch database/database.sqlite
```
step.

[10.x] Simplify SQLite initial configuration

---

queues.md

This method doesn't exists on the PendingChain class.

Remove incorrect "then" method

---

events.md

By default, Laravel will use the `handle` method on an event. To remove confusion - when somebody would change the `handle` and now `make:listener` does not work anymore out of the box - it would be better to not have the customisation in the docs.

Remove array syntax from Events docs

---

validation.md

both removing the `authorize()` method, and returning `true` will result in the same behavior, so adding a comment to explain this is an option.
https://github.com/laravel/framework/blob/10.x/src/Illuminate/Foundation/Http/FormRequest.php#L190
I would even go so far as to say we should *recommend* removing the method, as it's less code to run through, but this is probably good enough to start.

[10.x] `authorize` method may be removed if not used

---

strings.md

I've seen the `charAt()` method used quite a bit, and so I was surprised to see it's [not documented](https://twitter.com/jordankdalton/status/1724206892401020937). Hoping to remedy that (unless there's a reason not to). 
Thanks!

Add documentation for charAt().

---

validation.md

This PR adds documentation to the newly introduced `hex` validation rule.
https://github.com/laravel/framework/pull/49056, https://github.com/laravel/framework/pull/49069

[10.x] Add Hex validation rule

---

localization.md

This PR adds a section to the localization docs describing how to use the `handleMissingTranslationKeyUsing` method.
I've tried to keep the wording as simple as possible but provide detail in the code example. Let me know if there are any suggested improvements.
The relevant feature was originally merged in https://github.com/laravel/framework/pull/49040

Localization: Add section about handling missing translation strings.

---

responses.md

Added the word 'absolute' to clarify the path to the file() method should be absolute.

Changing 'path' to 'absolute path' in File Response section

---

sanctum.md

In later versions of Axios ([v1.6.0](https://github.com/axios/axios/releases/tag/v1.6.0)) the `withCredentials` credentials option has had a breaking change in regards to automatically forwarding XSRF tokens to third party domains / subdomains. In response to this breaking change, Axios has [re-added the functionality back in](https://github.com/axios/axios/releases/tag/v1.6.2) via a `withXSRFToken` option. Here are the issue links (in oldest to latest order):
CVE Issue: https://github.com/axios/axios/issues/6006
CVE Fix: https://github.com/axios/axios/pull/6028
XSRFToken Option Addition: https://github.com/axios/axios/pull/6046
From the new option's PR:
```
📢 This PR added 'withXSRFToken' option as a replacement for old withCredentials behaviour. 
You should now use withXSRFToken along …
```

[10.x] Add new Axios v1.6.2 `withXSRFToken` option to documentation

---

validation.md

I thought there's missing closing underline char according to markdown format

Fix some formatting in validation doc

---

validation.md

Related https://github.com/laravel/framework/pull/49082

[10.x] Update validation.md with extensions validator

---

documentation.md
horizon.md
pulse.md
telescope.md

This PR adds documentation for [Laravel Pulse](https://pulse.laravel.com).
There are a few things I still need to finish documenting, but they can be added in a separate PR:
* Vapor-specific considerations.
* Removing Postgres warnings once testing is complete.
* Custom recorders.
* Custom cards.
Some notes on custom recorders and custom cards:
Custom recorder classes can be created and registered in the Pulse config file, but it's also possible to use the `record` and `set` methods from the `Pulse` facade directly in controllers, jobs, etc.
The dashboard uses Livewire and Blade, so putting pretty much anything in there is possible. However, card authors will probably want to extend our `Card` Livewire component and use our various Blade components (`<x-pulse::card>`, `<x-pulse::table>`, …

[10.x] Laravel Pulse

---

pulse.md

I was following along in the docs and believe `extra` may be a typo for `email`? I did a quick source dive to check it isn't trying to supporting additional metadata and it does appear to just look for email.
Thanks for Laravel Pulse - this will be incredibly useful!

Pulse: Change `extra` to `email` for Pulse::users

---

pulse.md

We use a trimming strategy, `MINID`, that is only available in 6.2 or greater: https://redis.io/commands/xtrim/

[10.x] Include version requirement

---

validation.md

the validation rule currently requires a backed Enum if the value being validated is a `string` or `int`.
I think it would be nice if the rule also handled pure Enums when passed a `string`, but that's a separate issue. I'm going to attempt a PR for that in `laravel/framework`, but until then this clarification in the docs should help.

[10.x] clarify need for backed Enum

---

eloquent-mutators.md

This came about from [this Github thread](https://github.com/laravel/framework/issues/40506#issuecomment-1781244517).
Basically took some connecting of dots to realize json data using the shorthand operator needed to be added to fillable in the same syntax. It's in the docs but not very clear when looking at the Eloquent Mutators section.
Thanks!

[10.x] Add connection to json shorthand fillable documentation

---

pulse.md

I saw that @jessarcher added PostgreSQL support for Pulse, therefor this limitation can be updated. (Maybe it can even be removed? Not sure how it looks with MariaDB which is MySQL compatible and for not first party supported databases like MongoDB)

Add PostgeSQL for Pulse

---

helpers.md

Looks like there was a copy/paste oversight here

Fix documentation mistake for Number::abbreviate() section

---

queues.md

From PR: https://github.com/laravel/framework/pull/49169

Document using Dynamo for job batches

---

migrations.md

[11.x] Make floating-types consistent

---

requests.md

See https://github.com/laravel/framework/issues/49371
I also added a warning from the `getClientIps` method's docblock.

[10.x] Document `ips` method

---

queries.md

I find the wording "This feature [whereJsonContains] is not supported by SQLite database versions less than 3.39.0" misleading. This wording suggests that the `whereJsonContains` method can be used by merely using a compatible version of SQLite, which is not true; while SQLite does support JSON functions since version 3.39.0 (as already stated in the previous paragraph), the SQLite Grammar does not support the `whereJsonContains` clause regardless of the version of SQLite.

Improve wording on the `whereJsonContains` method and SQLite support

---

pulse.md

The most commonly reported issue in Pulse relates to having a non-standard user model. This is currently documented under the Application Usage card, however, it may not be obvious to look there.
This PR moves the information about resolving users to a dedicated section to make it more discoverable and more likely to be encountered when initially configuring Pulse.

[10.x] Add dedicated section for resolving users in Pulse

---

octane.md

This pull request adds documentation related to Octane's FrankenPHP integration. As discussed on Slack with @dunglas, Mercure-related features will not be mentioned for now, as we plan to better integrate them with Laravel's broadcasting features.

[10.x] Adds FrankenPHP documentation

---

artisan.md

This PR adds documentation for the second argument to the `$this->ask()` console method:
```php
$name = $this->ask('What is your name?', 'Taylor');
```

Mention the second argument of ask() in console

---

validation.md

Validation rules `present_if`, `present_unless`, `present_with` and `present_with_all` already exists in the framework but aren't documented. This PR fixes it.

[10.x] Document previously undocumented `present` validation variation rules

---

octane.md

This pull request specifies how to install FrankenPHP on Sail.
Depends on https://github.com/laravel/octane/pull/793.

[10.x] Specifies how to install FrankenPHP on Sail

---

mail.md

This PR adds documentation for the 'roundrobin' mail transport driver which is introduced here: https://github.com/laravel/framework/pull/49435 
The doc is adopted from the Symfony mailers doc: https://symfony.com/doc/6.2/mailer.html#load-balancing

[10.x] doc updated to add 'roundrobin' mail transport driver

---

octane.md

In the new section "FrankenPHP Via Laravel Sail" there is a typo in the instructions for modifying docker/supervisord.conf

Fix typo in octane.md

---

horizon.md

Explains how to force running Horizon when maintenance mode is enabled. 
See https://github.com/laravel/horizon/issues/1362

[10.x] Document maintenance mode with Horizon

---

installation.md

I feel like we should still have a mention of the installer in the docs as many people, including myself, still use it as their preferred way to start new projects with the framework.
Also see https://github.com/laravel/installer/issues/296

[10.x] Re-add Laravel installer docs

---

sail.md

Should be merged after the next release of sail, where the default version will be changed.

[10.x] Sail uses PHP 8.3 by default

---

processes.md

Updated the example code in the documentation from `$this->get('/');` to `$this->get('/import');` to ensure accuracy.

[10.x] Fix incorrect route in documentation example

---

octane.md

This should be merged after https://github.com/laravel/sail/pull/645 is released

[10.x] Adjust documentation to use new Laravel Sail supervisord environment substitution support

---

dusk.md
migrations.md

[11.x] Remove Doctrine DBAL

---

scout.md

@taylorotwell @driesvints This PR contains documentation for the recently merged Scout PR (https://github.com/laravel/scout/pull/773) that adds Typesense support to Scout.

Docs for Typesense integration in Scout

---

cashier-paddle.md

I mostly took over the docs from the Cashier Stripe QuickStart and modified them to the Paddle equivalents. For the order/cart example I used an event listener as the same approach using the redirect parameter in Cashier Stripe isn't available with Paddle.

[10.x] Cashier Paddle quickstart docs

---

authorization.md

Inline authorization does not execute your "before" and "after" checks, so we'll add a warning about it.
This has bitten me a couple times, so figured I'd make it explicit.

add warning about Inline Authorization

---

validation.md

In the Section for [Available Validation Rules](https://laravel.com/docs/10.x/validation#available-validation-rules) on the validation site, there is an entry for the `password` rule, which is marked to have been renamed and removed in Laravel 9. I think enough time has passed for the entry to be removed completely as to not cause confusion with the intended way to verify passwords, which is described on the bottom of the page.

[10.x] Removed redundant entry for password rule

---

migrations.md
upgrade.md

* laravel/framework#49634
* MySQL: https://dev.mysql.com/doc/refman/8.0/en/spatial-type-overview.html
* PostgreSQL (on PostGIS)
* Geometry type: https://postgis.net/docs/manual-3.4/using_postgis_dbmanagement.html#Create_Spatial_Table
* Geography type: https://postgis.net/docs/manual-3.4/using_postgis_dbmanagement.html#PostGIS_Geography
* SQL Server: 
* Geometry type: https://learn.microsoft.com/en-us/sql/t-sql/spatial-geometry/spatial-types-geometry-transact-sql?view=sql-server-ver16
* Geography type: https://learn.microsoft.com/en-us/sql/t-sql/spatial-geography/spatial-types-geography?view=sql-server-ver16
* SQLite (on SpatiaLite): https://www.gaia-gis.it/fossil/libspatialite/home

[11.x] Make spatial types consistent

---

homestead.md

- Mailhog is gone. Mailpit is the default and only option now.
- Ubuntu is now version 22.04
- PostgreSQL is no version 16
- The "mysql" feature flag never actually did anything, so we drop it.
- Add PHP 8.3
@svpernova09 can you confirm the Mailpit config has not changed?

[10.x] updates for the new Settler box and Homestead version

---

upgrade.md

* laravel/framework#48861
* laravel/framework#48864
@taylorotwell the new schema methods (`Schema::getTables()`, `Schrma::getViews()`, `Schema::getColumns()`, `Schema::getIndexes()`, `Schema::getForeignKeys()` etc.) for inspecting database  may worth mentioning in the "release notes" page, please let me know if you want me to include a section for this.

[11.x] Schema Upgrade Guide

---

queries.md

Hi,
Importing Controller is unnecessary When `UserController` is located in the same namespace as `Controller`.

[10.x] Remove importing Controller in queries.md

---

installation.md

So people don't unintentionally install older versions: https://github.com/laravel/installer/issues/303

[10.x] Add version to installer command

---

installation.md
sail.md

This PR adds docs for the Typesense Sail integration contained in this other Sail PR: https://github.com/laravel/sail/pull/655

[10.x] Add docs for Typesense Sail support

---

billing.md

The docs mention extending a controller for webhooks but then show adding event listeners instead
There is no specific controller mentioned or demonstrated.. unlike the listeners.
I expect this to get rejected and closed.. there was no way to point to it in an issue and not sure the best way to handle.

"extending controller" or "defining listener"

---

migrations.md
upgrade.md

* laravel/framework#49925
* laravel/framework#49897

[11.x] Index modifiers when modifying columns

---

billing.md
console-tests.md
database-testing.md
dusk.md
events.md
facades.md
filesystem.md
helpers.md
http-tests.md
mail.md
mocking.md
notifications.md
packages.md
passport.md
pennant.md
processes.md
queues.md
sail.md
sanctum.md
structure.md
testing.md
vite.md

Depends on https://github.com/laravel/laravel.com/pull/318.
This pull request adds Pest snippets alongside PHPUnit:
https://github.com/laravel/docs/assets/5457236/d6240e8b-706d-47d3-a738-a478ddbf3ef4

[11.x] Adds Pest snippets

---

testing.md

This pull request removes documentation of `--pest` as the testing framework is detected by the `make:test` command in Laravel 11.

[11.x] Removes documentation of `--pest` as is detected now

---

socialite.md

This pull request specifies that `services` configuration file must be published for working with socialite in Laravel 11.

[11.x] Specifies that `services` must be published

---

database-testing.md
testing.md
vite.md

This pull request removes references to `CreatesApplication` as the trait no longer exists.

[11.x] Removes references to `CreatesApplication`

---

dusk.md

For all pages for installing packages, the `--dev` flag is the end of the `require` command but for Dusk, it is not the end.
https://laravel.com/docs/10.x/pint#installation
https://laravel.com/docs/10.x/envoy#installation
https://laravel.com/docs/10.x/telescope#local-only-installation

[10.x] Add `--dev` flag at end of the command in Dusk

---

eloquent-mutators.md
eloquent-serialization.md

This pull request documents `casts` method in favour of `$casts` property.
Also replaces things like `AsCollection::class.':'.OptionCollection::class` by `AsCollection::using(OptionCollection::class),`.

[11.x] Documents `casts` method in favour of `$casts` property

---

upgrade.md

The upgrade guide indicates that Redis cache tags got a performance improvement. However based on discussions linked below, it appears that usage of redis cache tags is not recommended. The outdated guidance in the upgrade guide caused a series of significant bugs in our production application. This PR updates the docs to recommend against using cache tags until a suitable solution can be found.
- Discussion of the problem: https://github.com/laravel/framework/discussions/49159
- Evidence that redis cache tagging isn't coming back or getting fixed any time soon: https://github.com/laravel/framework/pull/48078#issuecomment-1716332925
The current upgrade guide still contains a broken link to the documentation on cache tagging (which was removed as a result of Taylor's comment in the second …

Don't suggest cache tags for Redis

---

scout.md

Typesense's collection schema can actually be updated using native scout commands, and not just the Typesense API as the docs previously mentioned.
@karakhanyans tested and verified this.

Update info about handling Typesense schema changes

---

eloquent.md

This section explains how to manage primary keys they are not numeric. The phrase "auto-incrementing" does not make sense in this context. This PR rewords the example's comment.

Generalise a comment

---

migrations.md

The docs have a warning in the "Squashing Migrations" section that schema dumps may not be restored to in-memory SQLite database. However, I believe this issue was resolved in PR [#45375](https://github.com/laravel/framework/pull/45375), which was released in v9.45.1.
To test this, I ran the following steps in a project that had existing migrations:
1. Place an sqlite schema at: `database/schema/sqlite-schema.dump`
```
CREATE TABLE IF NOT EXISTS "migrations" ("id" integer not null primary key autoincrement, "migration" varchar not null, "batch" integer not null);
```
2. Update the .env file with the following values:
```
DB_CONNECTION=sqlite
DB_DATABASE=:memory:
```
3. Run the migration (`php artisan migrate`) and see them all succeed.
According to a previous issue …

[10.x] Remove warning about schema dumps and in-memory SQLite databases.

---

upgrade.md

* laravel/framework#49965
* laravel/framework#48864 the alternative approach for inspecting databases was not clear for package maintainers (e.g. [barryvdh/laravel-ide-helper#1510](https://github.com/barryvdh/laravel-ide-helper/pull/1510#issuecomment-1931959295))
We may also add a section for these new schema methods to [Inspecting Your Databases](https://laravel.com/docs/10.x/database#inspecting-your-databases) if you want?

[11.x] Inspecting database

---

passport.md

* laravel/passport#1715
* laravel/passport#1712

[11.x] Enable passport's password grant type

---

blade.md

This pull requests updates the $slot section of the blade component docs.
Folks might mistakenly expect `@if($slot)` to work to check if `$slot` content exists, like I did. It would be helpful to clarify with an example of `@if($slot->isEmpty())`.

Update blade docs to show how to conditionally check for $slot content

---

deployment.md

For info the `--optimize-autoloader` flag is not needed because we already have `"optimize-autoloader": true,` in our composer json.

[11.x] Updates L11 requirements for deployment

---

http-client.md

Doc updated to explain how to pass an array as the first argument to the `HTTP::retry` method and a Clouse as the second argument. 
Reference PR: https://github.com/laravel/framework/pull/50064

[10.x] HTTP client doc update for retry backoff option

---

packages.md

We can use `loadJsonTranslationsFrom` for load translations in JSON format.

[10.x] Add `loadJsonTranslationsFrom` into packages

---

billing.md

Currently the payment status is not checked.
This means the user can start a Stripe checkout session, get the session ID from the URL, and manually construct the checkout success route, marking the order as paid without paying.

[10.x] Fix security vulnerability in Cashier Stripe quickstart example

---

sail.md

This is the shell alias described and recommended in the Laravel Sail documentation:
```shell
alias sail='[ -f sail ] && sh sail || sh vendor/bin/sail'
```
The alias is supposed to have the following functionality:
- Check if a file called `sail` does exist in the CWD / Laravel project directory.
- In case it does exist, execute it
- In case it does not exist, execute the `vendor/bin/sail` script provided by the package.
- Pass all arguments to either sail script being executed
This functionality allows developers to add a custom script to their Laravel projects to wrap around and customize Laravel Sail's behaivour.
However, due to how shell alias does work, arguments are only passed to the false-part of the if-condition - **`sh sail` will never receive any arguments**. This limitation …

Fix Laravel Sail Shell Alias not passing arguments

---

helpers.md

This PR fixes a typo in the `Arr::take()` example docs.

Fix typo in Arr::take() examples

---

helpers.md

This pull request addresses a consistency issue in the Laravel documentation for array helpers. In the `Arr::toCssStyles()` method snippet, a namespace import was missing. This PR adds the necessary import statement, ensuring uniformity with other code blocks. The changes enhance readability and maintain a consistent coding style throughout the documentation.

[10.x] Update helpers.md

---

strings.md

This PR adds documentation for `toBase64`. Feel free to update the description so it aligns with the quality of the rest of the docs.

[10.x] Added missing `toBase64` docs

---

dusk.md

Updates Dusk documentation for mouse events to match merged pr on Dusk at [https://github.com/laravel/dusk/pull/848](https://github.com/laravel/dusk/pull/848) 
Add's selector documentation for mouse event methods doubleClick(), clickAndHold() and controlClick().

Adds selector to dusk documentation for mouse events

---

upgrade.md

This better explains the "change" behaviour for migrations in Laravel v11 with a concrete example and also a tip on how to easily deal with it.

[11.x] Clarify change behaviour in Laravel v11

---

telescope.md

I couldn't easily locate the telescope dashboard route. The only mention of it is further down the page.

[10.x] Adds instructions for accessing the Telescope dashboard

---

queries.md

Adds documentation for `joinLateral` and `leftJoinLateral`
https://github.com/laravel/framework/pull/50050

[10.x] Adds documentation for `joinLateral` and `leftJoinLateral`

---

queues.md

The exception may be `null` if you call the `fail` method without passing a string or exception, as documented.
So having this nullable in the docs seems more sensible, as the two documented version do not currently work together. If this were typed with `Throwable` an exception would be thrown when the queue worker attempts to call the job's `failed` method.
```php
<?php
namespace App\Jobs;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
class TestJob implements ShouldQueue
{
use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;
public function handle(): void
{
$this->fail();
}
public function failed($e)
{
dd($e); // null
}
} …
```

[10.x] Nullable `failed` method

---

migrations.md

[11.x] Add binary type and other enhancements on migartions

---

database.md

Reverts laravel/docs#9017. It is much too soon to do this, and this will only stop people upgrading to Laravel 11. The effort for us to continue supporting these older databases is very low and just because their OSS versions are EOL, it doesn't mean there aren't OSs providing security backports or other support plans, etc.
---
Is there a good reason to not support postgres 9.6 on Laravel 10, too? Would we consider lowering the min version in the Laravel 10 docs for postgres back to 9.6?

Revert "[11.x] Bump supported database versions"

---

middleware.md

Adds information on how to set up global and group middleware manually. [Request for this](https://github.com/laravel/framework/discussions/50156#discussioncomment-8571465) was received in related discussion.

[11.x] Adds manual middleware configuration for L11

---

releases.md

This PR adds Laravel 11 release date, March 12th, 2024

Update releases.md, fix laravel 11 release date

---

octane.md

Also, fix a (non-blocking) permission issue in the HTTP example.
Discussed here: https://github.com/laravel/octane/issues/811#issuecomment-1893210575

[10.x] Document how setup HTTPS with FrankenPHP and Sail

---

passport.md

* laravel/framework#50386
* laravel/passport#1724

[11.x] Rewrite Laravel Passport installation

---

dusk.md

The [https://docs.phpunit.de/en/10.1/annotations.html#group](https://docs.phpunit.de/en/10.1/annotations.html#group) is not found (404)

[10.x] Fix group link of PHPUnit in `Dusk`

---

strings.md

Following on from https://github.com/laravel/framework/pull/50090, I've updated the Str::markdown() docs to advise about the XSS risks and the options that should be used.

Add XSS warnings to the markdown() functions

---

upgrade.md

If you are running an older version of the Laravel Installer, you will not have all the correct installation options for a new Laravel 11 Application.
Assuming there will be a 5.6 release tomorrow, otherwise another version number can be documented.
Kind of related PR: https://github.com/laravel/installer/pull/319

[11.x] Add Laravel Installer update instructions

---

configuration.md

In `configuration` documentation for `10.x` there are references to typed getters that will be available in `11.x`.
This PR removes any references to them.
They are already there in `11.x` documentation.
See https://github.com/laravel/framework/pull/50140 for more info.

Remove references to config getters

---

broadcasting.md
reverb.md

Related to: https://github.com/laravel/framework/pull/50428 - that now installs JS dependencies.

[11.x] Adjusts for `install:broadcasting` changes

---

reverb.md

Very small typo fix I noticed when reviewing the docs.

[11.x] Typo: Changes "commmand" to "command"

---

upgrade.md

Cashier Stripe package is not named cashier-stripe, just cashier. This was a bit confusing when upgrading.

[11.x] Fixes Cashier stripe package name - just cashier not cashier-stripe

---

upgrade.md

When i upgraded my Laravel project that had Jetstream from 10 to 11, I had to do this change, and maybe others would find this useful too.

Added a line about jetstream upgrade to the upgrade docs

---

installation.md

Because `database` is the session's driver by default, people need to run their database migrations when using the `curl -s "https://laravel.build/example-app" | bash` command.

[11.x] Adjusts installation docs

---

helpers.md

see https://github.com/laravel/framework/pull/50392

Sleep::syncWithCarbon

---

upgrade.md

The `redirectTo()` method on the `AuthenticationException` now requires a `Request` instance:
https://github.com/laravel/framework/commit/1d878ccac4ed1e2a0cc337bf32fac4e52f893dfb#diff-321608159b002b8e92d19ef7ab6f68f568f79b2a08877e074eb6479b70e5ceacR63-R72

Added upgrade note about `AuthenticationException::redirectTo()`

---

database.md

With Laravel 11, the var `DATABASE_URL` has changed. It is now `DB_URL` (see [config/database.php](https://github.com/laravel/laravel/blob/11.x/config/database.php))

Change DATABASE_URL to DB_URL

---

errors.md

The current docs state:
> When rendering an exception, Laravel will automatically determine if the exception should be rendered as an HTML or JSON response based on the Content-Type header of the request.
Whilst building my latest API, I noticed that the `Content-Type` header doesn't determine if the exception should be rendered at HTML or JSON, but rather the `Accept` header.
In this PR, I'm simply updating the header name to reflect the reality I experienced.

[11.x] Change deterministic header name

---

pulse.md

This was added in https://github.com/laravel/pulse/pull/330. cc @jessarcher

[11.x] Add MariaDB to supported DB engine list

---

structure.md

In fresh laravel 11 application, there is only one service provider in providers directory. It seems like docs is not updated for this specific thing.

update providers for L11

---

pennant.md

I was looking at the documentation for Pennant and noticed the events do not line up with the actual events in the package. I can see they were renamed and updated in this PR https://github.com/laravel/pennant/pull/21, but accidentally reverted in this commit https://github.com/laravel/docs/commit/075b0ceebac575e24c9c00958e3f662d43809c00.
I have correctly renamed the events to what they actually are while keeping the amendments that have been made to the docs since.
Whilst making this change, I thought it made sense to document the new events that have also been added. I'm not sure they all need descriptions as some of them are self-explanatory but have added them for now so they can be amended or removed.
I used the information in this PR https://github.com/laravel/pennant/pull/31 to …

[11.x] Document all Pennant events

---

artisan.md

Before : 
```
->withCommands([
__DIR__.'../app/Domain/Orders/Commands',
])
```
After :
```
->withCommands([
__DIR__.'/../app/Domain/Orders/Commands',
])
```
It was missing a slash symbol.

[11.x] Artisan Console - Modify `withCommands` DIR path

---

cache.md

Hey! This PR proposes a small change that explains to the reader that they need to install the `aws/aws-sdk-php` Composer package if wanting to use DynamoDB as their cache.
Without installing the SDK, it appears that an exception is thrown when we try and interact with the cache. I ran into this issue myself earlier today and couldn't see any mention in the cache docs of needing to install the package (apologies if it's there and I just missed it!).
The only mention of the SDK that I saw was in the queues section (https://laravel.com/docs/11.x/queues#dynamodb-configuration) but that's not until further in the docs so it might be confusing to newer developers.
So, I copied a small part over from the queues section and added it to the DynamoDB cache section. Although there is a slight bit …

[11.x] Add "aws/aws-sdk-php" install step for DynamoDB cache setup

---

scheduling.md

https://github.com/laravel/framework/pull/50755

[11.x] Documents `withSchedule`

---

structure.md

In Laravel 11 there is no Exceptions/Handler.php but not updated in Laravel 11 docs.

update Exceptions directory descriptions

---

eloquent.md

Before:
```bash
protected $connection = 'sqlite';
```
After:
```bash
protected $connection = 'mysql';
```
As 11.x using `sqlite` by default, I think, it is more convenient to use `mysql` or something else in this example (specify a different connection for a particular model).

modify-example-of-db-connection-name

---

installation.md

Fixes https://github.com/laravel/framework/issues/50959. As the `^` is not supported on Windows terminals.

[11.x] Removes `^11.0` from installation step

---

eloquent-collections.md

The documentation for `Illuminate\Database\Eloquent\Collection::unique` currently states the following:
> Any models of the same type with the same primary key as another model in the collection are removed.
This is incorrect, as items with a different type but the same primary key are still removed, as indicated by the following code snippet (which will output 1 instead of 2):
```php
<?php
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
class ModelA extends Model {protected $fillable = ['id'];}
class ModelB extends Model {protected $fillable = ['id'];}
echo (new Collection([
new ModelA(['id' => 1]), 
new ModelB(['id' => 1])]
))->unique()->count();
```
This can be very confusing when working with collections produced by `MorphTo` relations.
If the …

Correction for unique method in eloquent collections

---

contributions.md

The support policy says that 10.x has bug fixes until August 6th, 2024: https://github.com/laravel/docs/blob/661689450c2cea25c4634da0dcbd3be9e990744d/releases.md?plain=1#L30

Should bug fixes be targed to 10.x?

---

sanctum.md

I tried both Reverb and Pusher using Sanctum, both service are not able to authenticate if putting the `channels` in `auth:sanctum` group only. However, adding `api` or `web` will work. 
I think it's because the `withBroadcasting` method does not include `api` middleware group since `11.x`.

[11.x] add api middleware group for private broadcast channels

---

prompts.md

Documentation for https://github.com/laravel/prompts/pull/118.

[11.x] Adds documentation for Prompts form support

---

validation.md

Documenting the new RequiredIfDeclined validation (see PR https://github.com/laravel/framework/pull/51030)

[11.x] Documenting the new RequiredIfDeclined validation rule

---

prompts.md

Fixes the docs for Prompts. Basically, `CMD+BACKSPACE` only works in certain terminal environments, like Warp.

[11.x] Fixes a typo about forms in the Prompt docs

---

vite.md

Now that we have the blade `@use` directive, it's better to stick with it instead of using a PHP `use` inside the blade `@php` directive.

Use the blade @use directive instead of @php

---

dusk.md

Document the following [Dusk PR](https://github.com/laravel/dusk/pull/1100):
- `assertPathEndsWith()`
- `assertPathContains()`

Document `assertPathEndsWith()` and `assertPathContains()`

---

notifications.md

Replace the class type with the intended one (see the class import above).

[11.x] Fix the class type in notifications.md

---

mail.md

The documentation for Mailersend is currently missing a step in the Laravel documentation.
Currently following the documentation throws `InvalidArgumentException` "Mailer [mailersend] is not defined."
The documentation shouldn't miss a step.

Add missing Mailersend step

---

artisan.md

Fixes the docs for Closure Commands by removing a duplicate word in the text.

[11.x] fixes typo on closure commands

---

urls.md

This PR adds documentation for the new `URL::query()` method added in the below PR:
https://github.com/laravel/framework/pull/51075

Add `URL::query()` method documentation

---

fortify.md

This contribution aims to provide a little more background on throttling specifically for Fortify. 
I also mentioned that IP-only throttling can be accomplished in Fortify, without rehashing the example in the section immediately above, and pointed out that a hybrid approach including WAF provides the best all round protection.

Add a section on authentication throttling

---

notifications.md

After submitting a [PR](https://github.com/laravel/framework/pull/51174) to implement support for notification middleware, it turned out that Laravel already [has this functionality](https://github.com/laravel/framework/pull/44767), albeit undocumented.
This PR adds documentation for notification middleware.

[11.x] Write documentation for notification middleware

---

pulse.md

Now it uses the same wording and method as [Laravel Reverb](https://laravel.com/docs/11.x/broadcasting#reverb) to install the beta package.

Update instructions to install the beta release of the pulse package without downgrading application's minimum-stability setting

---

providers.md

When the user uses the `make:provider` command to create a provider, the provider is automatically registered in the `providers.php` file.

[11.x] Add note for `make:provider` command

---

deployment.md
octane.md

Some tiny tweaks and a link to our updated documentation entry explaining how to package standard Laravel apps and Octane apps as standalone binaries.

[11.x] Update FrankenPHP docs

---

requests.md

This configuration is required for applications behind a proxy that uses the standard Forward: "" header described in RFC 7239, like HAproxy with the "option forwarded" directive.

Add note about standard "Forwarded" header in Trusted proxies

---

cashier-paddle.md

Fixing the method name from `productPrices` to `previewPrices` and example code in **Price Preview** section.

Fixing method name and example code under Price Preview section

---

helpers.md

Looks like it was a typo, the example used `config` instead of `context`

Helpers - Fix context example

---

pulse.md

Removes an extra "return" from Pulse docs.

[11.x] Pulse: Remove an extra "return"

---

cashier-paddle.md

Fixing typo of `subscription()` function.

Fixing typo in extend trial example code

---

authorization.md
csrf.md
sanctum.md

- add missing word in `authorization.md`.
- consistently use "an SPA" vs "a SPA". there were of mix of uses in the docs, and "an" is more appropriate as "SPA" starts with a vowel sound.

[11.x] minor grammar

---

upgrade.md

Adds a bit more context about changes to Carbon 3's `diffIn*`changes.

Add details about Carbon 3 upgrade

---

deployment.md

It is recommended in the OWASP guide to hide the `X-Powered-by` header in the web server config. 
https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html#x-powered-by
That's why I've updated the nginx config given in the `Deployment` section to add a directive for this.

[11.x] Hide X-powered-by in nginx config for deployment

---

pint.md

This helps to run Laravel Pint only on changed files inside `PR`. 
Maybe it can be helpful.

[11.x] Adds documentation on GitHub Actions with Laravel Pint

---

artisan.md

This adds a simple writeup and example for the new `Command::fail` method in [#51435](https://github.com/laravel/framework/pull/51435) to the `artisan` docs page.

[11.x] Adds documentation for Command::fail method

---

middleware.md

In Laravel 10 this middleware was added in the middlewarePriority property but it was not reported in the documentation https://github.com/laravel/framework/pull/46130

[10.x] Added missing middleware in middlewarePriority array

---

scout.md

- adds documentation for `removeAllFromSearch()` so times when we want to flush in PHP we don't have to use `Artisan::call('scout:flush', ['model' => Order::class]);` like an animal 😅

[11.x] Documents removeAllFromSearch method

---

events.md

The description of the `shouldQueue` method in the Events documentation seems to have a typo. The last sentence states that if `shouldQueue` returns false, the listener will not be "executed", when I think it should say "queued". This commit replaces "executed" with "queued" in the last sentence.

Fix typo in `shouldQueue` method description

---

strings.md

Currently the `->matchAll` returns only the matches for the first group. Added documentation to prevent people debugging their code for ages.

Update matchAll to include first only matching group

---

releases.md

This pull request updates the PHP version compatibility and corrects the release date for Laravel 10 in the documentation.
- **PHP Version Compatibility:**
- Updated from `8.1` to `8.1 - 8.3`
- **Release Date:**
- Corrected from `February 7th, 2023` to `February 14th, 2023`
The PHP version range has been expanded to include versions `8.2` and `8.3` for better accuracy and up-to-date information. Additionally, the release date for Laravel v10 was corrected to ensure the documentation reflects the accurate historical release information.
Thank you for reviewing these updates!

Update PHP Version Range and Correct Release Date for Laravel 10 

---

queries.md

In the new version of Laravel, we can pass Closure to the `updateOrInsert` method.

[11.x] Add example for `updateOrInsert` method in queries

---

prompts.md

Following the current docs about the `table()` helper results in a TypeError. Array is expected, Collection given.

table() expects an array, collection given

---

container.md

I removed two unnecessary imports from the `UserController` class example.
1. `App\Http\Controllers\Controller`: This import is redundant because the `UserController` class is in the same namespace.
2. `App\Models\User`: This import is unused in the current example.

Remove unnecessary import statements

---

eloquent.md

Fixes a code example where `\Illuminate\Database\Eloquent\Model::increment` is called with an array as its first argument. [The function expects a string](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Database/Eloquent/Model.php#L926).

Fix call to Model::increment()

---

errors.md

Since the documentation has caused confusion in a few places:
- https://github.com/laravel/framework/issues/46865
- https://github.com/laravel/framework/pull/46877

Clarify exclusions for fallback HTTP error pages

---

horizon.md

This is simply documenting the possibility of using `"*"` as a key in Horizon's `environments` array for fallback or catch all behaviour.

Document using wildcards in Horizon environments

---

collections.md

Added the `before` and `after` Collection methods that have been added in https://github.com/laravel/framework/pull/51752.

[11.x] Add `before` and `after` methods to Collection

---

installation.md

This PR adds an installation guide for Laravel Herd for MacOS and Windows users so that they get up and running without leaving the Laravel docs.

Add Herd installation guide

---

deployment.md

This PR is related to #9710. @taylorotwell expressed that he was not in disagreement with the veracity of this info, but did not think [structure.md](https://laravel.com/docs/11.x/structure) was a good place for this and was unsure if this was important enough to mention.
Please see #9710 for the **Problem**, **Solution**, and **Notes** sections that explain why these docs should inform devs there are two folders, `storage` and `bootstrap/cache`, that the framework needs to write into.
Also, take a look at [this guide on setting up permissions on a Linux web server](https://serverfault.com/questions/357108/what-permissions-should-my-website-files-folders-have-on-a-linux-webserver) that explains more about secure user and folder permissions in such an environment.
I've been working with …

Add crucial note about folder permissions to deployment.md

---

events.md

Added concrete domain name directory  for consistency with **other places.**
1. Subsequent  example on the same page
https://github.com/laravel/docs/blob/33d43e187d466be64edb49b63f135a268fd7fb2c/events.md?plain=1#L93-L94
2. `artisan.md` example 
https://github.com/laravel/docs/blob/33d43e187d466be64edb49b63f135a268fd7fb2c/artisan.md?plain=1#L660-L662

Add concrete domain name directory to example code

---

upgrade.md

While upgrading a project I found out that livewire needs to be upgraded from ^2.12 to ^3.4

Added missing dependency upgrade `livewire/livewire`

---

reverb.md

The docs recommend using `/` for the Nginx location block which will allow all Reverb routes to be handled.
However, we have seen several issues now where more granularity is required or where a different web server is being used and the server is being configured to respond on URIs prefixed with `/app` or `/apps` only. In this scenario, the Reverb server will be able to respond to only WebSocket connections or API requests (event broadcasing etc), but not both.

[11.x] Adds warning for Reverb URI

---

queues.md

Fixes a minor grammatical error in the Queue docs.

Fixes grammar for queue/connection customization heading

---

helpers.md

It looks like a typo; an unnecessary double quote exists.

Fix typo in helpers

---

helpers.md

I tried the example codes in the doc and found that actual results include two decimal places.

Fix results of Number::currency() example

---

queries.md

Explicitly lists MariaDB as a supported DBMS for JSON queries. There was some confusion because it looked like MariaDB wasn't supported. These passages were written before Laravel officially supported MariaDB.
Also, SQLite nowadays includes support for JSON queries by default and no longer requires the `JSON1` extension.

[11.x] Improve database support for JSON queries

---

precognition.md

The `for` attribute is not allowed in JSX syntax and should be replaced with `htmlFor`

[11.x] Precognition: Replace attribute `for` with `htmlFor` in React example

---

errors.md
urls.md

By default, Laravel use the `errors` directory, but the example specifies the error directory.
In addition, I used named arguments for the best look.

Fix errors directory in URL Generation

---

vite.md

This is in line with the Google HTML guide and with other files in the framework.
https://google.github.io/styleguide/htmlcssguide.html#HTML_Validity
(https://github.com/laravel/framework/commit/55e459049c09572998cbbb8e277224cf91cd4102 flashback)

Use consistent uppercase for DOCTYPE

---

rate-limiting.md

This link lacks a version prefix (but still works).
Fun fact: this typo has been around since 8.x.

Add `/docs/{{version}}/` prefix to URL

---

contracts.md
validation.md

I updated `@return` in PHPDoc because it was returning an obsolete data type (taken from `request.stub`). And updated the Contracts table.
https://github.com/laravel/framework/blob/11.x/src/Illuminate/Foundation/Console/stubs/request.stub#L20
https://github.com/illuminate/contracts/blob/11.x/Validation/Rule.php#L6
https://github.com/illuminate/contracts/blob/11.x/Validation/ImplicitRule.php#L6

Update return type & remove deprecated from contracts

---

controllers.md
eloquent-serialization.md
routing.md

All routes in the documentation (except resources) have a slash. These three have been stripped of it for some reason.

[11.x] Add missing slash to routes

---

billing.md
cashier-paddle.md
middleware.md
pennant.md
requests.md
responses.md
validation.md

I'd like to add a slash to all `redirect()` helper so that developers who are just joining realize that it's about the path, not the route. Some may confuse this with the `redirect()->route()` construct.
I also removed the `to()` method from the Pennant section.

Redirect slash

---

database.md
upgrade.md

* laravel/framework#51373
Note: We may also fix this on 10.x docs, should be 3.16.0+ for SQLite, can be 10.3+ for MariaDB and 10.0+ for PostgreSQL.

[11.x] Extend SQLite support to 3.26+

---

queries.md

Docs that go along with:
https://github.com/laravel/framework/pull/52147

Update docs with information about the whereLike query

---

horizon.md

See https://github.com/laravel/horizon/issues/1480
This hopefully will clarify some things regarding process counts, as this is not clear from the variable names themselves.

Document process count configuration for Horizon

---

queues.md

I noticed a small typo when investigating Dynamodb for batches.
https://laravel.com/docs/11.x/queues#storing-batches-in-dynamodb
```
'batching' => [
'driver' => env('QUEUE_FAILED_DRIVER', 'dynamodb'),
'key' => env('AWS_ACCESS_KEY_ID'),
'secret' => env('AWS_SECRET_ACCESS_KEY'),
'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
'table' => 'job_batches',
],
```
I think `QUEUE_FAILED_DRIVER` should be `QUEUE_BATCHING_DRIVER`
thanks 🚀

Possible typo on queues.md

---

database.md

This MR fixes the doc to be consistency about the collation being used by the framework by default
The example given in laravel 11.x docs refers to the mysql default collation instead of the collation the laravel framework uses by default for mysql
**Docs**
https://laravel.com/docs/11.x/database#read-and-write-connections
**Database config from framework version 11**
https://github.com/laravel/framework/blob/11.x/config/database.php#L55

Change default collation to match default config in framework

---

prompts.md

This PR fixes unformatted block of code on the [Prompts](https://laravel.com/docs/11.x/prompts#:~:text=You%20may%20allow) (link with anchor) page:
And also adds named arguments in places where they don't exist for better understanding. It is up to the developer to decide whether to add them to his code or not. And small corrections in headers, commas (removed commas before the end of the function and put them in arrays). Removed `name` from the `unique` validation since it doesn't differ from the value. And changed `where` with `like` to `whereLike` recently added in Framework.
You can roll some changes back with your commit or you can write in a review about it to me I'll fix it.

Fix and format Prompts

---

collections.md
errors.md
helpers.md
horizon.md
logging.md
middleware.md
queues.md
releases.md
scheduling.md
strings.md
validation.md

Removing unnecessary double newlines and spaces.

Fix double newline and space typos

---

dusk.md

The @actions/upload-artifact github action version 2 is deprecated since *June 30, 2024*. Version 3 is also scheduled for deprecation on *November 30, 2024*.
The [action repository](https://github.com/actions/upload-artifact) recommands to update workflows to use v4 of the artifact actions.
The provided workflow **currently works**, however it displays a deprecation warning in its output.

doc: bump actions/upload-artifact github action to v4

---

http-tests.md

There's no more `assertArraySubset' in PHPUnit itself.
I think it's time to remove this part.
This is the Laravel version.
https://github.com/laravel/framework/blob/11.x/src/Illuminate/Testing/Assert.php

Remove the `assertArraySubset' part

---

pulse.md

This PR removes a `;` from a `view` example that will generate an error when the dev tries to copy the example code thinking about reproducing the steps in the documents, including because Pulse is something "new" that a lot of people are studying and reproducing.

Removing semicolon from `view` example of Pulse page

---

middleware.md

Use "allow" instead of "allows" because the subject "aliases" is plural.

Fix grammatical error in middleware.md

---

queries.md

Updated docs by adding documentation for the `whereNone` method. If you decide to merge pull request [#52260](https://github.com/laravel/framework/pull/52260) to the framework.

Add documentation for the `whereNone` method

---

cashier-paddle.md

The current documentation for Laravel Cashier Paddle suggests importing classes using `use Laravel\Cashier\Model`.
For example:
```php
use Laravel\Cashier\Transaction;
```
However, this results in an error as the correct namespace for the Transaction class is [Laravel\Paddle\Transaction.](https://github.com/laravel/cashier-paddle/blob/7c5bf79bbcd1cdb996c855b20ad66f4588baa337/composer.json#L46-L50)

Correct import statement for Laravel Cashier Paddle

---

collections.md

- Code formatting copied from `session.md`. However, I realise `$collection->all();` is no longer present which other collection examples use.
https://github.com/laravel/docs/blob/696cad17f80605f1cf2ff68c97f60873500c55ca/session.md?plain=1#L223-L227

Expand `forget()` example to include removing multiple keys at once

---

blade.md

this was a little confusing to me when I first saw it, so wanted to add some clarification.
it is likely, especially when using a component for your layout, that the `$slot` variable will contain HTML.  however, the docs show the `{{ $slot }}` escaped version. although I'm not exactly sure where this happens in the code, it seems that a slot is treated specially, and does not escape content.  All code inside the slot appears to respect any escaped or unescaped content.
I've also added a wrapping `<div>` around each task to more closely reflect a real world use, and to further drive home the `$slot` will handle any HTML content it is provided.

[11.x] add clarification on component slot escaping

---

fortify.md

Was working through a tutorial on how someone improved the Jetstream Invite process and discovered the `Fortify::authenticateThrough()` default pipeline documentation has been outdated since the addition of https://github.com/laravel/fortify/pull/485.

Bring Fortify::authenticateThrough() default pipeline definition up to date

---

authentication.md
cache.md
configuration.md
passport.md

fix: avoid page overflow with long table rows

---

requests.md

I noticed the documentation https://laravel.com/docs/11.x/requests#configuring-trusted-proxies does not mention anything about subnets. I went through the code of when trusted proxies is used and you are able to use subnets but it is not obvious. 
This also better mirrors the symfony docs that are referenced https://symfony.com/doc/7.0/deployment/proxies.html
I really hope this addition is added just to help clarify for people in the future. Let me know if I did anything wrong or you want me to make any changes to my PR

Added subnet to trustedProxies example to show it's supported

---

sail.md

Reopening #9823 as the usage is wrongly documented in the Sail documentation and wont work: https://laravel.com/docs/11.x/sail#sharing-your-site
I believe the previous PR has been overlooked too fast with the comment:
> That named argument doesn't even accept a string in its type hint.  
As I commented in the earlier PR: It does accept a string and using the wildcard in an array syntax won't work as expected: https://github.com/laravel/docs/pull/9823#issuecomment-2291888940
_There was an another PR about the documentation of `trustHosts(at: callback)` at the same time. The confusion is comprehensible since they both are very similar but doesn't share the same argument signature. `trustHosts()` doesn't accept a string, but this PR is about `trustProxies()`_
It's worth noting that the …

Fix trustProxies usage in Sail configuration (2)

---

vite.md

This PR addresses a Vite issue that occurs during local development when absolute paths are used with a dedicated CSS entrypoint.
Resolves https://github.com/laravel/vite-plugin/issues/302

[11.x] Update caveat for Vite URL processing with absolute paths and dedicated CSS entrypoints.

---

authentication.md

Hello, in [authentication docs](https://laravel.com/docs/11.x/authentication), there are 2 links that point to https://laravel.com/docs/11.x/middleware#middleware-alias , but actually that link in middleware docs is https://laravel.com/docs/11.x/middleware#middleware-aliases

Fix broken links to #middleware-aliases

---

strings.md

Hi!
I've added information and code examples on how to ignore the case when using "contains" and "containsAll" methods.
Thank you!

Added info on ignoring case for "contains" and "containsAll" methods

---

prompts.md

It looks like this parameter was reverted and replaced with a keyboard shortcut. See the PR here: https://github.com/laravel/prompts/pull/147
This option does not exist in the helper signature at all. Se: https://github.com/laravel/prompts/blob/main/src/helpers.php#L59

Remove canSelectAll example from multiselect

---

artisan.md

Adds `migrate:install` to the Tinker Command Allow List.
References: https://github.com/laravel/tinker/commit/8531d0f0e0285783f420bdd743c37f99c0f394d1

[11.x] Updates Artisan Docs

---

collections.md
helpers.md

Collection and helper function heading tags are currently broken for several older versions of the docs. This PR targets `6.x`.
```html
```

[6.x] Use classes instead of IDs

---

collections.md
helpers.md

Collection and helper function heading tags are currently broken for several older versions of the docs. This PR targets `5.8`.
```html
```

[5.8] Use classes instead of IDs

---

collections.md
helpers.md

Collection and helper function heading tags are currently broken for several older versions of the docs. This PR targets `5.7`.
```html
```

[5.7] Use classes instead of IDs

---

collections.md
helpers.md

Collection and helper function heading tags are currently broken for several older versions of the docs. This PR targets `5.1`.
```html
```

[5.1] Use classes instead of IDs

---

collections.md
helpers.md

Collection and helper function heading tags are currently broken for several older versions of the docs. This PR targets `5.3`.
```html
```

[5.3] Use classes instead of IDs

---

dusk.md

See https://github.com/laravel/dusk/pull/1124

Explicitly include `--port=9515` when running `chromedriver` on CI

---

envoy.md
migrations.md
valet.md

Backports https://github.com/laravel/docs/pull/9859 for `5.3`.

[5.3] Header fixes

---

envoy.md
valet.md

Fixes a duplicate broken header link and backports https://github.com/laravel/docs/pull/9855 for `5.5`.

[5.5] Header fixes

---

valet.md

Backports https://github.com/laravel/docs/pull/9855 for `5.6`.

[5.6] Header fixes

---

valet.md

Backports https://github.com/laravel/docs/pull/9855 for `5.7`.

[5.7] Header fixes

---

upgrade.md
valet.md

Duplicated tag and also broken header links. The paragraphs / list items after the headers end up getting the link.

[5.8] Header fixes

---

middleware.md
session.md

Backport https://github.com/laravel/docs/pull/9836 to `8.x`

[8.x] Header fixes

---

middleware.md
routing.md
session.md

Backport https://github.com/laravel/docs/pull/9836 to `9.x`

[9.x] Header fixes

---

fortify.md

The `ValidateSignature` middleware is actually for validating signed routes, so the docs should list `EnsureEmailIsVerified` in this section.

Fix incorrect middleware listed in Fortify docs

---

filesystem.md

This PR clarifies that MinIO actually supports the `temporaryUrl` method.
In a dockerized environment, the `endpoint` variable normally points to `https://minio:9000` as stated in the documentation.
But since the hostname `minio` only exists within the docker network, the client cannot access the resource.
If MinIO is configured for a production environment, it will be accessible directly or thanks to a reverse proxy.
This can be useful for people who want to use their own instance of MinIO in production.
I am using Laravel Herd for development connected to my own MinIO instance hosted on a private VPS for testing.
For local development it might be more reasonable to use the `temporaryUrl` with local storage as just presented in Laracon US.

[11.x] Clarify MinIO support for temporary URLs 

---

pint.md

This PR updates the execution command for Laravel Pint.
Changes:
- Added `./vendor/bin/` before the `pint` command to explicitly specify the binary installed via Composer.
This change makes the method of executing the Pint command clearer and ensures that users are using the Pint version installed through Composer. This modification helps maintain consistency throughout the documentation and prevents confusion for new users.

[11.x] chore: Update Pint CLI commands to use vendor/bin directory

---

broadcasting.md
collections.md
container.md
events.md
queues.md

- always use trailing commas in signature
- always use multiline arguments
- correct indentation
- remove empty bodies

[11.x] standardize constructor examples

---

responses.md

Support for [streamed JSON Response](https://github.com/laravel/framework/pull/49873) was added in 10.x but it hasn't been documented yet, neither was the `stream` method.
I referenced Symfony's [streamed response docs](https://symfony.com/doc/current/components/http_foundation.html#streaming-a-response) for this contribution.

Document `Response` "stream" and "streamJson" methods

---

sail.md

This PR addresses the issues discussed in [this thread](https://github.com/laravel/framework/discussions/38678) regarding the Linux Host IP Configuration for Xdebug in the Laravel documentation.
Why the change is necessary:
- Docker 20.10+: As outlined in the [merge request](https://github.com/moby/moby/pull/40007), `host.docker.internal` became available on Linux starting with Docker 20.10. This means Linux users no longer need to manually configure the host IP, simplifying Xdebug configuration.
- Incorrect Documentation for Docker 17.06+: The previous documentation incorrectly suggested that Docker 17.06.0+ would resolve the issue for Linux users, but `host.docker.internal` was not supported on Linux until Docker 20.10. Users still had to manually set the host IP even with Docker 17.x. …

Update Xdebug configuration instructions for Linux to support Docker 20.10+

---

strings.md

Documention for the `Str::deduplicate` method, introduced in Laravel v11.20.0.
See https://github.com/laravel/framework/pull/52350

[11.x] Document Str::deduplicate method

---

scout.md

Added note under Typesense section about setting the TYPESENSE_HOST to match the Docker container for Typesense allowing Scout to properly connect.

[11.x] Update scout.md about connecting to Typesense in Laravel Sail

---

requests.md

Getting the `per_page` input from a request and passing it to `Builder`'s `paginate()` doesn't make PHPStan happy, nor does casting the result of `$request->input()`, which is `mixed`, to an `integer`. This method is quite useful but doesn't seem to be documented.

Add documentation for retrieving input values as integers to requests.md

---

concurrency.md

This pull request updates the documentation to include a hint about the potential absence of the ConcurrencyServiceProvider class if the project was upgraded from an earlier Laravel version, therefore not having the current Laravel structure, causing the Concurrency facade to not work.

Add hint about ConcurrencyServiceProvider for old Laravel structure

---

helpers.md

In my [Add cancel abilities to Deferred Callbacks #52816](https://github.com/laravel/framework/pull/52816), Taylor mentioned that there is an existing way to cancel deferred functions by using the method `forget`.
This PR includes in the documentation that reference by explaining:
- The capability of the `defer` helper to be identified with a name
- Use the name as a identifier to remove the callback from the collection
---
The forget method allows you to cancel a specific deferred function before it runs. Simply assign a name to the deferred function and use forget to remove it:
```php
defer(fn () => Metrics::report(), 'reportMetrics');
defer()->forget('reportMetrics');
```

[11.x] `helpers.md` - Cancelling deferred functions

---

middleware.md

This pull request adds information about registering a middleware alias for the `EnsureUserHasRole` middleware example in the "Middleware Parameters" section of the documentation.
The current documentation provides an example of the `EnsureUserHasRole` middleware and how to use it with parameters, but it doesn't mention the necessary step of registering the middleware alias. This addition will help users avoid confusion when implementing the middleware in their applications.
Changes made:
1. Added a code snippet demonstrating how to register the `EnsureUserHasRole` middleware alias in the `bootstrap/app.php` file.
2. Placed the new information immediately after the middleware class example and before the route definition examples.

[11.x] Add middleware alias registration example for EnsureUserHasRole middleware

---

upgrade.md

I know I'm late to the game with my 11.x upgrade, but I came across what I think is an undocumented breaking change related to the password rehashing. I tested logging in after upgrade and got an exception `Column not found: 1054 Unknown column 'password' in 'field list'`. (Which is true - the app I'm upgrading uses a different field name for the password.) Based on the related documentation about the `Authenticatable` trait, I took a closer look at that trait and determined that if I defined `$authPasswordName` in my User model it fixed the issue. I adjusted the documentation on this in the upgrade guide to account for this possibility.
I also added the missing likelihood-of-impact for this subheading, which I'm calling "low" since most folks probably use the default 'password' field …

Document breaking change in password rehashing if custom password field

---

contributions.md

While reviewing the Laravel Contribution Guide, I noticed that Laravel Breeze was missing from the list of repositories. This merge request adds the link to that repository.

Add Laravel Breeze to Contribution Guide Repository List

---

mail.md

Update links to Mailgun docs

---

eloquent-factories.md

`HasFactory::newFactory()` doesn't actually enforce the `Factory` return type. Following the docs here as is leads to an exception.
https://github.com/laravel/framework/blob/abf86b08b08c5ea5c9247877bc8b6ea259805f80/src/Illuminate/Database/Eloquent/Factories/HasFactory.php#L31

fix incompatible return type

---

events.md

This PR clarifies the event subscriber registration process and adds a note about automatic registration through event discovery. The PR addresses the concerns mentioned in issue [#52404](https://github.com/laravel/framework/issues/52404) as @njpanderson faced the same issue.

[11.x] Clarify event subscriber registration

---

cache.md

DynamoDB tables don't automatically delete expired items.  Thought it might be a good idea to help users understand that they should enable TTL based on the cache item's `expires_at` attribute to avoid storage creep.

DynamoDB Cache TTL

---

helpers.md

As the global function conflicts with Swoole, I felt we had two options: add a warning explaining the conflict of reference the namespaced function.
Referencing the namespaced function felt more friendly.

[11.x] Document namespaced function

---

eloquent-relationships.md

added " / Has Many" to the "One to Many" header and corresponding TOC line.

changed "one-to-many" header on eloquent-relationships page

---

eloquent.md
queries.md

This PR is to help others avoid hitting this issue: https://github.com/laravel/framework/issues/29655 / https://github.com/laravel/framework/pull/29721

Add note about logically grouping "or" queries for chunkById and lazyById

---

prompts.md

This PR adds paragraphs to the `search` and `multisearch` sections to warn users that are intending to return a list from their callback to ensure that the array doesn't become associative after filtering, as this changes the behaviour and leads to unexpected results.
Fixes: https://github.com/laravel/prompts/issues/173

[11.x] Prompts: Warn about inadvertently returning associative arrays after filtering

---

eloquent-relationships.md

From [laravel/framework \#53041](https://github.com/laravel/framework/pull/53041), it turns out there's Polymorphic equivalent to `whereBelongsTo()` that is not mentioned anywhere in the docs.
This PR adds a mention of said method on Eloquent relationships page. I'm open to suggestions on what and where to put it.
Thank you.

added missing "whereMorphedTo" on Eloquent relationship page

---

routing.md

I discovered that if I had both a per-minute and per-day rate limit on the same segment, only the first limit worked. It looks like I'm not the only one who has encountered this, and I noticed [this note](https://github.com/laravel/framework/issues/46290#issuecomment-1449910366) on the [suggested workaround here](https://github.com/laravel/framework/issues/46290#issuecomment-1447427560) inviting a PR to the docs, so here you go!

Document solution for multiple rate limits on same segment

---

vite.md

Example given in the docs works but produces a type error when used with typescript because `setup` function given to  `createInertiaApp` has the following signature:
`(props:{ el: Element; App: InertiaApp; props: InertiaAppProps; plugin: Plugin; }) => void | App<any>`
While the example (because it ends with `.mount(el)`) returns `ComponentPublicInstance`.
Changes I made work and do not produce type errors.
[Example from inertia docs](https://inertiajs.com/client-side-setup#initialize-the-inertia-app) doesn't return created instance either so I don't think it's necessary.

fix inaccurate return type

---

blade.md
validation.md

we had a mix of multiline attribute styling, some with the first attribute on the first line and some on the second line.
this converts them all to be the same.

[11.x] consistent styling for multi-line attributes

---

installation.md

After a recent edit, the link to the Laravel installer package was missing so it's not obvious how to actually get to the point where you can run `laravel new example-app` without installing Herd or using the php.new script.
That creates a dead-end for developers who already have PHP and composer installed, but not the Laravel installer.

[11.x] Reinstate link to Laravel installer package

---

validation.md

This PR adds docs for the optional parameter in the `confirmed` validation rule.
https://github.com/laravel/framework/pull/52722

[11.x] Optional param for Confirmed rule

---

migrations.md

This PR adds documentation for the migration method, `nullOnUpdate()`
https://github.com/laravel/framework/pull/52798

[11.x] Migration `nullOnUpdate` 

---

helpers.md

This PR adds Number helpers, `defaultLocale` and `defaultCurrency`.
https://github.com/laravel/framework/pull/53101

[11.x] Add Number Helpers: `defaultLocale`, `defaultCurrency`

---

installation.md

New way of installation is nice in case you want to have Laravel development setup ASAP, but it's not enough for complete setup — sometimes you need to have extra PHP extensions, sometimes you are using Bun, Deno or different version of Node.js. And for such cases developers prefer to manage their binaries manually. I think removal of standard installation methods from the docs in 44f2375021852c0b1f0c9b6d3316436d3fc590d3 are a bit [harmful](https://reddit.com/r/laravel/comments/1g47c4r/). In this PR I tried to address 2 issues created by this change:
- **What if developer already have PHP and Composer setup?**
Then he may only need a Laravel installer binary.
- **What if developer don't want to use Laravel installer and/or don't need extra configuration for starter repository?**
Just use …

[11.x] Get back old installation/application creation methods

---

events.md

It's something I simply discovered. It simplifies some of my listeners, so I thought it would be helpful for other developers to know that this is possible. By using union types in Laravel event listeners, you can handle multiple related events in a single listener. This reduces redundancy and makes it easier to manage similar events in one place.
The example in the documentation shows how to use union types in the `handle` method, leveraging the `instanceof` operator to differentiate and handle each event accordingly.

[11.x] Add support for union types in event listeners in Laravel 11

---

installation.md

Changed "In you already have PHP and Composer installed, you may install the Laravel"
to "If you already have PHP and Composer installed, you may install the Laravel"

Update typo error in installation.md

---

eloquent.md

While reading the documentation right now I think I found a typo, I mean it works because the position of the column parameter is the same but it is instead defining a variable.

Update typo error in eloquent.md

---

collections.md

the wording here is just a little unclear. the first sentence seems to suggest that the `forget()` method does not return anything, even though it does.
you are free to assign the result to a new variable even though you don't need to (and maybe shouldn't?)
```php
$collection = collect(['name' => 'taylor', 'framework' => 'laravel']);
$newCollection = $collection->forget('name');
dump($collection === $newCollection); // true
```

add clarification about `forget` method return value

---

blade.md

we can now use either `index.blade.php` or `{directory}.blade.php` for our anonymous index components.
https://github.com/laravel/framework/pull/52669

[11.x] new allowed filename for anonymous index components

---

blade.md

https://github.com/laravel/framework/pull/52669

[11.x] document "index" class components

---

installation.md
validation.md

my preference would be to go the other direction, but this at least makes it consistent across the docs

[11.x] consistently use "an" when preceding "SQL" or "SQLite"

---

octane.md

This pull request updates the Octane configuration when using sail to use a dynamic port for the supervisor PHP command instead of a hardcoded port. This allows for more flexibility and avoids conflicts with other services running on the same port.

[11.x] Update Octane configuration to use dynamic port

---

container.md

I explained that scopedIf can be used to register bindings that have not previously been registered to this type

Add scopedIf method for container

---

http-client.md

Sometimes we need to access the PendingRequest options like the timeout value in a test case, hopefully this could save someone else time in the future
Am not sure about the wording as English isn't my native language, let me know if it needs any tweaking.

[10.x]: Updated Http `fake` method callback signature to include options array

---

helpers.md

In draft until the methods are tagged.

[11.x] without defer testing docs

---

migrations.md

Add docs for new `vector` method added in the following PRs:
- https://github.com/laravel/framework/pull/52884
- https://github.com/laravel/framework/pull/53316

[11.x] Add new `vector` method to migrations docs

---

authentication.md
cache.md
database.md
documentation.md
mongodb.md
queues.md
session.md

MongoDB maintains a package for Laravel integration: [mongodb/laravel-mongodb](https://www.mongodb.com/docs/drivers/php/laravel-mongodb/)
- Add MongoDB page under "Databases" menu
- Add MongoDB relevant information on authentication, cache, database, queue and session pages.

Add documentation for MongoDB support

---

upgrade.md

Just ran into an issue of having verification notifications sent twice when upgrading to Laravel 11 and noticed [others have had the same issue](https://github.com/laravel/framework/issues?q=SendEmailVerificationNotification) so I propose adding a note to the upgrade guide.
I am not sure how the guide is supposed to be organized and which topics should be included in the TOC, so in the initial revision I've made the change as small as possible.

Warn about automatically registered event on the upgrade guide

---

eloquent.md

Got warned by PHPStan because of mismatch in PHPDoc types, and found that the documentation is not up to date with the current type of the GuardsAttribute trait after this PR:
[Make GuardsAttributes fillable property DocBlock more specific (https://github.com/laravel/framework/pull/50229)](https://github.com/laravel/framework/commit/30324cf06d1f34fe359c5e458bcbb8da5413db71
)

Adds type hint to fillable and guarded DocBlocks to match trait structure

---

sail.md

Documentation for https://github.com/laravel/sail/pull/748

[11.x] Add MongoDB to Sail doc

---

context.md

Documentation update for changes introduced in https://github.com/laravel/framework/pull/53403

Introduction support popping items from stackable context item

---

routing.md

This warning is unnecessary as the code will find the fallback route and put it at the end of the route list regardless as seen here in the source:
https://github.com/laravel/framework/blob/a296e813d041ddff000d856aa2f7ae1cd4d616b7/src/Illuminate/Routing/AbstractRouteCollection.php#L81-L85
L81-83 partitions the routes into the fallback and the rest of the routes, L85 merges the fallback partition into the regular routes partition, ensuring it is always last.

Remove unnecessary warning about Route::fallback() being last

---

pennant.md

[11.x] Document defining Pennant features externally

---

pint.md

This PR replaces deprecated PHP CS rules with other examples.
https://mlocati.github.io/php-cs-fixer-configurator/#version:3.64|configurator|fixer:new_with_braces
https://mlocati.github.io/php-cs-fixer-configurator/#version:3.64|configurator|fixer:braces
The mentioned values are opposites of what's configured in the [laravel preset](https://github.com/laravel/pint/blob/main/resources/presets/laravel.php).

[11.x] Replace deprecated PHP CS rules

---

releases.md
sail.md

Laravel 11 and 12 will support PHP 8.4.
Sail already has a PHP 8.4 runtime, but it should not be the default until PHP 8.4 is released.
Laravel Homestead does not support PHP 8.4 yet. (At least I saw no commit indicating that)
Depends on https://github.com/laravel/framework/pull/52633

[11.x] Add PHP 8.4

---

validation.md

In `eloquent` documentation, we're omitting the `return` keyword for `Builder` $query.

Remove return keyword from example

---

filesystem.md

I have added documentation for this pull request [#53620](https://github.com/laravel/framework/pull/53620#event-15383498785)

Add assertCount for filesystem doc

---

scheduling.md

This is to update the docs to clarify how the schedule:work will handle sub-minute tasks.
Related framework PR: https://github.com/laravel/framework/pull/53710

[11.x] Clarify how schedule:work will handle sub-minute tasks.

---

deployment.md

Dear Developers and Community,
Thank you very much for the incredible marvel you do! :sparkles: 
Since Laravel should work for the most cases serving the index PHP file only on HTTP endpoints, there's probably no point allowing any PHP processing except the index itself.
Please consider checking out how Symfony [approaches](<https://github.com/symfony/symfony-docs/blob/605961e1ed03327bb26577d8056262958354533f/setup/web_server_configuration.rst?plain=1#L76>) the case:
```nginx
server {
server_name example.com www.example.com;
root /var/www/project/public;
location / {
try_files $uri /index.php$is_args$args;
}
location ~ ^/index\.php(/|$) {
fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
fastcgi_split_path_info ^(.+\.php)(/.*)$;
include fastcgi_params;
```
Otherwise, may I ask what is the …

Allow only /index.php to be passed to FastCGI.

---

events.md

This PR adds documentation informing developers that it is possible to configure a backoff, like you can on a queued job:
https://laravel.com/docs/11.x/queues#dealing-with-failed-jobs
https://github.com/laravel/framework/blob/7db7ea950d3df663391718730f4490a4e189234a/src/Illuminate/Events/Dispatcher.php#L673-L679

[11x.] Add queued listener `backoff` docs

---

telescope.md

Not a groundbreaking contribution, but I've been annoyed by this quite a few times. (Because what we do in the documentation is mostly copying and pasting.)
When you install Telescope as a dev dependency, you need to check for the class' existence first. This avoids breaks when deployed to production.
Before:
```php
/**
* Register any application services.
*/
public function register(): void
{
if ($this->app->environment('local')) {
$this->app->register(\Laravel\Telescope\TelescopeServiceProvider::class);
$this->app->register(TelescopeServiceProvider::class);
}
}
```
After:
```php
/**
* Register any application services.
*/
public function register(): void
{
if ($this->app->environment('local') && class_exists(\Laravel\Telescope\TelescopeServiceProvider::class)) { …
```

Updated Telescope setup for local environments

---

installation.md

This PR updates the installation documentation to use PHP 8.4, replacing the current installation of PHP 8.3.
https://php.new/install/mac/8.4
https://php.new/install/windows/8.4
https://php.new/install/linux/8.4

[11.x] Bump PHP Installation from 8.3 to 8.4

---

filesystem.md

Storage:link source and target directory statement updated as **public/storage is the target** and **storage/app/public is the source**.
Example : 
```
ln -s /var/www/html/laravel11-x/storage/app/public /var/www/html/laravel11-x/public/storage
```

[11.x] Storage:link source and target directory statement updated

---

sail.md

This MR updates the Xdebug documentation in Laravel Sail to include critical steps about publishing Docker configurations and updating the `php.ini` manually, aligning with previous community discussions ([PR #358](https://github.com/laravel/sail/pull/358) and [Issue #357](https://github.com/laravel/sail/issues/357#issuecomment-1067811723)). The "Customize" section was moved before the "Xdebug" section to allow direct reference in the documentation, ensuring that references precede their related content for clarity and ease of understanding.

Add missing steps for enabling Xdebug in Laravel Sail docs

---

cashier-paddle.md

The documentation incorrectly suggests using ``:url="$payLink"`` with ``<x-paddle-button>``. However, this should be ``:checkout="$checkout"`` as per ``<x-paddle-button>`` component code source  https://github.com/laravel/cashier-paddle/blob/2.x/resources/views/components/button.blade.php

Fix incorrect prop name in Paddle Button documentation

---

strings.md

Move documentation for `toHtmlString()` to fluent strings as it's not even a method on `Illuminate\Support\Str`.

Move `toHtmlString()` to fluent strings

---

pint.md

PR updates Pint GitHub Actions instructions from PHP 8.3 to 8.4 and removes the reference to customizing a commit message as it defaults to writing one automatically for developers.

[11.x] Bump Pint GitHub Actions instructions to use PHP 8.4

---

homestead.md

https://laravel.com/docs/5.8/homestead
This is normal
https://laravel.com/docs/6.x/homestead

[5.8] fix: The lack of blank lines leads to invalid styles

---

installation.md
sail.md

Sail valkey

---

sanctum.md

This PR adds info to indicate that the CSRF token is URI encoded.
The token must be decoded before it is sent from the client to the server. The examples show how to do this with Axios. I mistakenly assumed that Axios was simply adding the `xsrf-token` header. However, it is also decoding the URI encoded token automatically. This wasn't specified in the docs which created issues when I tried to use CSRF with fetch.
(Followup for https://github.com/laravel/docs/pull/10085)

Add Sanctum CSRF Token Encoding Info

---

validation.md

RFC 4122 has been made obsolete by RFC 9562 which the uuid rule does actually implement. So uuid validation rule docs should be updated to reflect that change

[11.x] Update validation.md documentation for uuid to mention RFC 9562

---

reverb.md

Update `id` to be `app_id` in the Reverb Allowed Origins section

[11.X] Incorrect property name for Reverb Allowed Origins

---

cashier-paddle.md

Checkout::guest() expects an array, not a string: https://github.com/laravel/cashier-paddle/blob/5019728a54604c9fede22c7162d33f8cf7a820d9/src/Checkout.php#L33

Make argument to Checkout::guest() an array

---

filesystem.md

feat(docs): Expand S3-compatible storage options in file storage documentation
- Updated the file storage documentation to include additional S3-compatible storage services.
- Added references to Amazon S3, MinIO, DigitalOcean Spaces, Akamai / Linode Object Storage, Vultr Object Storage, and Hetzner Cloud Storage.
- Ensured all links are accurate and point to the respective service documentation.

Expand S3-compatible storage options in file storage documentation (filesystems.md)

---

queries.md

I do not expect everyone to be "database masters" to wrap their head around locking, so the added example should be enough to understand when and how it should be used: avoid data races by keeping the data immutable until the transaction completes.

Add pessimistic locking extended example

---

eloquent.md

In discussion about incorrect usage of truncate (https://github.com/laravel/docs/pull/10118 , https://github.com/laravel/docs/pull/10116), supprisely found, that Eloquent page does not contain example of deletion all rows in table other than with truncate.
To delete it with query we should write `Model::query()->delete()`, not just `Model::delete()`, and this is not obvious, because this page does not contain any other example starting with `Model::query()`.
As the result, many users use `truncate` for deletion of all records, leading to issues like https://github.com/laravel/framework/issues/35157 and https://github.com/laravel/framework/issues/29506 . Now i understand, is because truncate is documented better and higher in documentation, than delete.
This PR adds example of deletion of …

[11.x] Delete all models example

---

redis.md

Rebased https://github.com/laravel/docs/pull/10117 to 11. x
Phpredis extention does not provide client-side sharding, only Predis can do so. Currently this is unclear from docs.
This PR makes this more clear

[11.x] Note about client sharding only with predis

---

eloquent.md
queries.md

Rebasing https://github.com/laravel/docs/pull/10116 for 11.x . (has some discussion)
There are some issues and long dicsussions around `truncate` method and PostgreSQL CASCADE behaviour. 
some of them (and many more pull requests): 
* https://github.com/laravel/framework/issues/35157 
* https://github.com/laravel/framework/issues/29506 
* https://github.com/laravel/framework/pull/53343
* https://github.com/laravel/docs/pull/10118
Currently documentation says `This means that all foreign key related records in other tables will be deleted as well.`. This wording is very soft and does not highlight the full danger. Truncate cascade will fully truncate any tables, that has foreign keys pointing current table. Not only those records, that has foreign keys. Records, having null in foreign key …

[11.x] Remove mentions of Eloquent truncate from docs

---

controllers.md

fixes laravel/framework#54181
This note will be useful for upgraded application coming from Laravel 10 and below which would default to extending `Illuminate\Routing\Controller`.

Add warning regarding using `HasMiddleware` interface and extends `Illuminate\Routing\Controller`

---

vite.md

Adds docs to help guide users with custom origin to configure CORS with Vite.
This is under "Advanced" as majority of Laravel applications should never need this unless they are doing something very custom. All the first-party tooling is supported out of the box.

[11.x] Add CORS configuration to Vite plugin docs

---

urls.md

```
// Get the full URL for the previous request...
echo url()->previous();
+    // Get the path for the previous request...
+    echo url()->previousPath();
```

[11.x] Add `previousPath` usage to urls.md

---

validation.md

Split from #10136
This PR enhances the validation documentation with the following updates:
1. **Improved Structure**:
- Adds consistent headings for file validation rules like file sizes and image dimensions.
- Separates the explanation of `dimensions` from `File::image()` for better focus.
2. **Expanded `File::image()` Details**:
- Clearly lists supported file types (`jpg`, `jpeg`, `png`, `bmp`, `gif`, `svg`, `webp`).
- Adds a warning about potential XSS risks with SVG files and how to handle them safely.
3. **Streamlined Examples**:
- Moves method chaining examples (e.g., `dimensions`) to dedicated sections for clarity.
- Includes a concise example for file size validation.

[11.x] Improve File validation structure and clarify `File::image()` usage

---

scout.md

Explanation of the functionality added here https://github.com/laravel/scout/pull/889, which enables the sync of index settings to Algolia in Laravel Scout.

Add explanation for index-settings for Algolia in Scout

---

filesystem.md

This PR adds Cloudflare R2 to the list of S3-compatible filesystems integrated with Laravel's storage system.

Add cloudflare R2 to the list of S3 Compatible Filesystems

---

precognition.md

Documents API improvements introduced, and already tagged, in https://github.com/laravel/precognition/pull/105
Much cleaner 🧼

[11.x] Improve wizard documentation

---

migrations.md

this method is a simple direct alias of the `timestamps()` method. even though it is left in the `framework` for backwards compatibility, we should remove it from the documentation to discourage its use.
https://github.com/laravel/framework/blob/11.x/src/Illuminate/Database/Schema/Blueprint.php#L1258

[11.x] remove `nullableTimestamps()` documentation

---

authorization.md
eloquent-mutators.md
notifications.md
passwords.md
pennant.md
queues.md
routing.md
telescope.md
validation.md

use a single indent for multiline ternary statements. this is better than alignment with an arbitrary pattern in the first line because it doesn't need to be shifted as adjustments are made to the code.
along with #10166

[11.x] standardize multiline ternary alignment

---

billing.md
eloquent-factories.md
eloquent-relationships.md
http-client.md
http-tests.md
queries.md
validation.md

use a single indent for chains on a new line, rather than trying to align it with some arbitrary pattern in the first line. this arbitrary alignment very easily gets out of sync as changes occur to the code, and often times the adjustments are not made to the chained alignment. the single indent alignment does not suffer this problem.
this is to bring us in line with https://github.com/laravel/framework/pull/53835 and https://github.com/laravel/framework/pull/53748
this commit only contains whitespace changes.
if accepted, I will make these adjustments to the remaining docs pages.

[11.x] remove arbitrary chaining alignment

---

eloquent-relationships.md
eloquent.md

An attempt to document the feature added in laravel/framework#53720. I wrote everything that felt like it might be useful. And tried to put it in places where a reader might look exactly when this could be useful for them.  Some of my reasoning below.
The initial description of `withAttributes` is in the scopes' section of `eloquent.md` because IMO that's where the simplest use of this feature makes sense.
The feature feels most useful inside relationships so I mentioned it in that doc as well. But I added a broader section introducing the various options of "scoping" relationships. I suspect this might be useful as I've seen many new devs viewing the relationship methods as some special syntax that may only include the `$this->relationshipMethod(RelatedModel::class);` and nothing else.
I …

Document `withAttributes`

---

cashier-paddle.md
console-tests.md
container.md
controllers.md
database.md
dusk.md
eloquent-mutators.md
eloquent-resources.md
eloquent.md
facades.md
helpers.md
http-tests.md
mail.md
migrations.md
mocking.md
notifications.md
octane.md
processes.md
queries.md
queues.md
responses.md
routing.md
scheduling.md
seeding.md
strings.md
views.md

[11.x] single indent of multiline chains

---

concurrency.md
folio.md
hashing.md
logging.md
sanctum.md
scheduling.md

both `bash` and `shell` are used interchangably for the code blocks they surround, so we'll standardize to the more common `shell` option.

[12.x] standardize `bash` vs `shell` code fence language

---

billing.md

`composer` is shell code, not PHP code

[11.x] use correct language for code fence

---

helpers.md

documentation for https://github.com/laravel/framework/pull/44069

[11.x] init Timebox helper section

---

http-tests.md

This PR updates the docs to include the new `ddJson()` function.
[[11.x] new: ddJson method on TestResponse class](https://github.com/laravel/framework/pull/54673)

[11.x] update docs to include `ddJson()` 

---

fortify.md
migrations.md

[12.x] remove extra spaces

---

context.md
dusk.md
filesystem.md
http-tests.md
pennant.md
pulse.md
redirects.md
reverb.md

- use "ini" for `.env` examples
- use "text" for plain text blocks
- remove some empty line breaks at and inside the end of code blocks
- add some missing "php" and "shell" entries

[12.x] fix code fence language

---

broadcasting.md
passport.md
queues.md
reverb.md
telescope.md

in order to indicate "more content" or "content not relevant to example", we often use an ellipsis. in PHP and other languages, this pattern actually is relevant to the language.
this change standardizes usage of the ellipsis for the above examples to be in a comment. this give us valid PHP and Javascipt, and reduced ambiguity with the language construct.

[12.x] standardize ellipsis usage

---

container.md

The Defining Custom Attributes code sample in its present form will not work if copied/pasted as the following two files aren't included in the usage list:
```php
use Attribute;
use Illuminate\Contracts\Container\Container;
```
This PR adds these to the code sample which will provide a better develop experience when using this amazing feature.

Update container.md : Defining Custom Attributes : Improved Code Sample

---

upgrade.md

A small quality of life addition.
This PR adds a link to the migration guide of Carbon from v2 to v3. It took me a couple of minutes to find the list of changes on Carbon website.

[12.x] Add link to migrate Carbon from version 2 to 3

---

errors.md

Updates "...to an external service Sentry or Flare." -> "...to an external service **like** Sentry or Flare."

[11.x] Minor fluency fix on Errors

---

upgrade.md

* https://github.com/laravel/framework/pull/54274

[12.x] Upgrade guide entry for Multi-schema Database Inspecting

---

artisan.md
http-tests.md

- Updated anchor name from 'assert-server-unavailable' to 'assert-service-unavailable'
- Removes unwanted line break for better readability.

Fix anchor link for assertServiceUnavailable and line break in Artisan documentation

---

upgrade.md

With laravel 12, the `HasUuids` trait using v7 UUIDs by default. If we compare the examples below, the order of the database records may become confusing.
```
Str::orderedUuid()
Ramsey\Uuid\Rfc4122\UuidV4 {#5343
uuid: "9e4bb9bd-f73d-41c2-aecf-8c9bf81eb188",
}
Str::uuid7()
Ramsey\Uuid\Lazy\LazyUuidFromString {#5295
uuid: "01953cbc-ceac-73a4-9829-a14fc6528306",
}
```
I'm not sure about my writing style, but I think there should be such a section in the upgrade documentation.

[12.x] Add UUID v7 section for Models to upgrade guide

---

installation.md

Fixed broken link reference in Laravel docs: updated `#local-installation-using-herd` to `#installation-using-herd` for accurate navigation.

[12.x] fix link reference in installation documentation

---

strings.md

During an update and in the upgrade guide, I saw that v7 type uuids are now used instead of v4.
In the course of the update, I briefly looked into the topic of migrating IDs and realized that there is already a `Str::uuid7` method in the code, but it does not appear anywhere on the documentation page of the [string helpers](https://laravel.com/docs/12.x/strings#strings-method-list). 
I have now tried to add this new method.

[12.x] Add Str::uuid7 to string helpers

---

starter-kits.md

Refined the Laravel Starter Kits documentation with grammatical corrections.
> Fixed missing ‘to’ in two places for better clarity.”

Updated starter-kits.md to correct grammatical error

---

notifications.md

Although this note is also mentioned inside the similar [markdown mailables documenation](https://laravel.com/docs/12.x/mail#writing-markdown-messages), I think it should also be mentioned inside the Notifications documentation, as I have just been caught out for longer than I care to admit.

Added note warning about excess indentation for markdown notifications

---

collections.md

This PR fixes an issue in the `collections.md` file where some code snippets contained extra backticks (`````` instead of ```). The extra backticks were causing display issues in the documentation. This change ensures proper formatting of the code snippets.
No functional code changes were made; only the formatting of the documentation was fixed.

Fix/remove extra backticks in code snippets in collections.md

---

validation.md

ASCII characters in the `\p{L}` regex ranges are clarified as `a-z` and `A-Z` for the `alpha_dash` and `alpha_num` validation rules. ASCII numerals in the `\p{N}` range (`0-9`) are not.
This PR adds ", and `0-9`" where relevant.

Clarify ASCII numerals in `alpha_dash` and `alpha_num` validation rules

---

starter-kits.md

Following the release of the laravel installer 5.13.0 the livewire starter kits now come with a traditional livewire components option.
This PR serves to update the starter kit documentation to inform users of this new addition.

add documentation for traditional livewire components in starter kit

---

validation.md

This PR fixes a small typo in the validation documentation where "use" was repeated twice.

Removed the duplicated use in the validation documentation

---

context.md

Documentation for new `Context::scope()`. https://github.com/laravel/framework/pull/54799

Add documentation for `Context::scope()`

---

filesystem.md

This pull request corrects the code block formatting in the [Local Files and Visibility](https://laravel.com/docs/12.x/filesystem#local-files-and-visibility) and [Deleting Files](https://laravel.com/docs/12.x/filesystem#deleting-files) section of the file storage documentation by replacing incorrect code fences.

Remove unnecessary code blocks in file storage documentation

---

routing.md

This PR addresses an issue with outdated API documentation URLs in the Routing section. The Laravel API documentation has changed its URL format from `https://laravel.com/api/{{version}}/` to `https://api.laravel.com/docs/{{version}}/`.
- Updated the URL format in the documentation to reflect the new API documentation structure
- Fixed a broken link in the "Accessing the Current Route" section that was returning a 404 error
Fixes [#54927](https://github.com/laravel/framework/issues/54927)

Fix API documentation URLs in Routing section

---

vite.md

Before the this PR, the documentation included a reference to the new v4 installation while explaining the old v3 integration.
I moved the mention of Start Kits to the beginning.
After that, I introduced the TailwindCSS v4 Vite plugin (`@tailwindcss/vite`), illustrating it in a code snippet alongside the `laravel-vite-plugin`.
Then, I kept the original v3 description about PostCSS plugins and their automatic integration into Vite.

[12.x] Mention different Vite integration for Tailwind v3 vs v4

---

strings.md

There are six code blocks  ( ``````php ) which do not serve any purpose.
- [wordWrap](https://laravel.com/docs/12.x/strings#method-str-word-wrap)
- [words](https://laravel.com/docs/12.x/strings#method-str-words)
- [wrap](https://laravel.com/docs/12.x/strings#method-str-wrap)
- [str()](https://laravel.com/docs/12.x/strings#method-str)
- [trans()](https://laravel.com/docs/12.x/strings#method-trans)
Image for reference:

[12.x] strings.md - Remove redundant fenced code blocks

---

logging.md

This PR updates the logging documentation to reflect the recent change in the Laravel framework, where the `with` option for handlers was renamed to `handler_with`.
Why?
The framework now uses `handler_with` instead of `with` to explicitly indicate that these options configure the log handler's constructor parameters.
This ensures consistency between the documentation and the actual implementation.
[Reference](https://github.com/laravel/laravel/pull/6574/commits/fd7f1deecb6cdc89ed79c65abf412ea3a516d7bd)

[12.x] Update Logging Documentation to Use handler_with

---

upgrade.md

See: https://github.com/laravel/framework/pull/53522
Thanks!

[12.x] docs: document container respecting property default values

---

strings.md

The code example for the `whenEmpty` method is incorrect, as `whenEmtpy` doesn't execute the closure for a string containing spaces. The string would first need to be trimmed.
```php
$string = Str::of('  ')->whenEmpty(function (Stringable $string) {
return $string->trim()->prepend('Laravel');
});
// '  '
$string = Str::of('  ')->trim()->whenEmpty(function (Stringable $string) {
return $string->prepend('Laravel');
});
// 'Laravel'
```

[12.x] Fix strings whenEmpty code example

---

blade.md

With blade and livewire being used more frequently with flux, I get asked more and more about components. These two come in handy and I've forgotten more than once if we can do this or not.
Let me know if you would like additional blocks to show that they both can also accept an array.
https://github.com/laravel/framework/blob/be9dea9a6ad4323514dc25736b0126e5455e17d7/src/Illuminate/View/ComponentAttributeBag.php#L133
https://github.com/laravel/framework/blob/be9dea9a6ad4323514dc25736b0126e5455e17d7/src/Illuminate/View/ComponentAttributeBag.php#L152
Could also just add them as a second line to the existing code blocks, perhaps:
```blade
{{ $attributes->except('class') }}
{{ $attributes->except(['class', 'style']) }}
```

Document 'only' and 'except' for blade attributes

---

context.md

Document the new `increment` and `decrement` methods for `Context`.

[12.x] Document `increment` and `decrement`

---

errors.md

The generated exception class when using the `--render` option contains the comment:
`Render the exception as an HTTP response.`
However, the documentation example currently states:
`Render the exception into an HTTP response.`
For consistency, the docs should be updated to match the actual generated class.

[12.x] Updating the docs to reflect the actual generated comment

---

precognition.md

In the Precognition for Alpine.js example where it's shown how to manually submit the form, `form` is being referenced instead of `this.form`.
This PR will result in:
```alpine.js
<form @submit.prevent="submit" x-data="{
form: /* ... */,
submit() {
this.form.submit()
.then(() => {
// form.reset();
this.form.reset();
});
},
}">
```

Fix typo in a Precognition for Alpine.js example

---

authorization.md
controllers.md
database.md
eloquent.md
events.md
facades.md
filesystem.md
frontend.md
logging.md
mail.md
pagination.md
queues.md
redis.md

**Problem:**
The explicit using for `use App\Http\Controllers\Controller;` in Laravel controllers is unnecessary when the base controller `Controller.php` is in the same `namespace`. Since Laravel's artisan `make:controller` command does not include this import, and Laravel `Pint` also removes it, it makes sense to align the documentation with this convention.
**Reasons:**
- The import statement is redundant because the `base Controller` is in the `same namespace`.
- Laravel's `artisan command` does not generate this import.
- Laravel `Pint` removes it as an unnecessary statement.
Updating the documentation will ensure consistency with Laravel's best practices.

[12.x] Consistency with Laravel's best practices

---

artisan.md
authentication.md
authorization.md
billing.md
blade.md
broadcasting.md
cache.md
cashier-paddle.md
collections.md
concurrency.md
configuration.md
context.md
controllers.md
csrf.md
database-testing.md
database.md
deployment.md
eloquent-factories.md

Removed Trailing whitespaces
No other changes

[12.x] Fix markdown formatting

---

starter-kits.md

If this value is not set on WorkOS settings, logout redirect will fail, I think is better to be sure this is included :).

[12.x] Improve workOS docs

---

artisan.md

This PR enhances the anticipate method example by replacing the placeholder comment with a real-world example using Eloquent. The new example demonstrates how to fetch address suggestions dynamically based on user input.
**Why?**
This makes the documentation more practical by providing a concrete use case, helping developers understand how anticipate can be used with database queries.

[12.x] Improve `anticipate` method example

---

artisan.md

This PR updates a reference link to Symfony’s documentation in the Laravel docs. The current link points to `Symfony 7.0`, which is no longer maintained. Since `Symfony 7.3` is the latest maintained version, I’ve updated the link accordingly.

Update Symfony documentation link to the latest maintained version (7.3)

---

errors.md

This PR adds the missing `use App\Exceptions\InvalidOrderException;` statement to the exception reporting example in the Laravel error handling documentation.
Explicitly importing the exception eliminates any confusion about whether `InvalidOrderException` is part of Laravel's core or a user-defined class.

[12.x] Add missing import for clarity and to eliminate confusion

---

collections.md

This PR modifies the `LazyCollection::make` implementation to explicitly close the file handle after reading. This prevents potential resource leaks and ensures proper cleanup.
**Changes:**
Added `fclose($handle);` after the `while` loop to close the file handle once reading is complete.
**Why?**
Ensure better resource management.

[12.x] Ensure Proper Closure of File Handle in LazyCollection

---

http-tests.md

Updating the `PHPUnit` example to match the structure and completeness of the `Pest` example.
This PR updates the `PHPUnit` example to align with the `Pest` example by including all debugging methods in the same order. This ensures consistency across both testing approaches and provides a more comprehensive debugging reference for users.

[12.x] Improve PHPUnit Example to Match Pest Example in Testing Documentation

---

console-tests.md
dusk.md
eloquent-relationships.md
eloquent.md

in the framework, we are usign a single indent on new lines, so this mirrors that in the docs

[12.x] sync indentation with framework formatting

---

broadcasting.md

Laravel documentation does not provide default values for `wsPort` and `wssPort`, while the actual implementation assigns them default values (`80` and `443`, respectively).
For consistency, the docs should be updated to match the actual generated code.

[12.x] Updating the docs to reflect the actual implementation

---

scheduling.md

Add information about how to configure the scheduling cache store that should be used for storing mutexes, and that it can differ from the primary application cache store.

[12.x] Add schedule useCache example

---

upgrade.md

In https://github.com/laravel/framework/pull/53746 the `DatabaseTokenRepository` constructor was altered to parse the `$expires` argument as given in seconds rather than minutes. When manually instantiating this, using a custom class extending it that calls the parent constructor or override the `resolve` method on the `PasswordBrokerManager`, this may cause changes in behavior resulting in incorrect expiry times. I think this makes it noteworthy enough to mention in the upgrade guide.

[12.x] Add `DatabaseTokenRepository` constructor signature update to upgrade guide

---

http-tests.md

The variable name for these methods is `$escape`, not `$escaped`, which is good to know if using named parameters when calling these methods.

docs: parameter is `$escape`, not `$escaped`

---

broadcasting.md

Added the Missing semi-colon in `broadcasting.md` file.

[12.x] Missing semi-colon

---

migrations.md

This PR adds the missing imports in the migration example under the `Skipping Migrations` section of the Laravel documentation. without these imports, the example may cause confusion for users unfamiliar with `Laravel Pennant` or the `Flights model`.
This improves clarity and ensures the example is functional as expected.

[12.x] Add missing imports in migration example

---

mocking.md

This streamlines `shouldReceive->once` calls to the more succinct, but explicit `expects`. Generally, this code is the same as `expects` is an alias for `shouldReceive->once`. However, using `expects` avoids pesky false positives when a developer forgets to quantify `shouldReceive`. So I feel the docs should build  the habit by using `expects`.
In the case of spies, `once` is unnecessary as `shouldHaveReceived` is built with `atLeast->once`. Again, removed for succinctness.

Use `expects` and remove unnecessary `once`

---

contributions.md

Laravel Website do not have public repo link at contributions page, worth removing.

Remove Laravel Website Link, no github repo found

---

upgrade.md

laravel/framework#51821 introduced `\Illuminate\Database\Schema\Blueprint` public constructor change. Although a rare scenario, this class can be used in application-level code to write DB type-agnostic code to get string representation of SQL DDL command (i.e. SQL command to add a comment to table), which later can be executed via `\Illuminate\Database\Connection::unprepared()`.

Add \Illuminate\Database\Schema\Blueprint changed constructor signature description

---

broadcasting.md

This PR fixes a small JSON syntax issue. The original JSON snippet contained a trailing comma after the last key-value pair, which is invalid JSON and can cause parsing errors. The corrected version removes the trailing comma to ensure valid JSON syntax.

[12.x] Fix invalid JSON syntax

---

artisan.md

Added a link to the official Laravel Tinker GitHub repository for easier access to the source code and more up-to-date information.
Additionally, the Tinker link was previously not mentioned in the documentation, and this update provides direct access to the repository.

[12.x] Add link to Laravel Tinker GitHub repository

---

contracts.md
mail.md
processes.md
prompts.md
requests.md

This PR updates a reference link to Symfony’s documentation in the Laravel docs. The current link points to `Symfony 7.0`, which is no longer maintained.
Continuation of #10266

[12.x] Update Symfony documentation link to the latest maintained version

---

telescope.md

Updated the `Telescope::avatar` callback to use the `null-safe` operator when accessing `avatar_path`. This ensures that if `User::find($id)` returns null, it doesn't cause an error and simply returns null instead of attempting to access a property on a non-object.
This change improves safety and prevents potential Attempt to read property on null errors.

[12.x] Nullsafe operator

---

broadcasting.md

This change clarifies that it's referring to a file (broadcasting.php), not a directory.

change "directory" to "file" in broadcasting configuration description

---

blade.md

This PR fomatting markdown for an uncolorized closing tag in blade.md

Fix : Formatting markdown in blade.md

---

redis.md

This update adds documentation on how to configure Laravel to use Redis via a Unix socket when using the PhpRedis extension. Connecting over a Unix socket can improve performance by eliminating TCP overhead for local connections. The .env example and the config/database.php configuration have been included to guide developers through the setup process.

[12.x] Add support for Redis Unix socket connections with PhpRedis

---

collections.md

Previously, these links were displayed in `bold`. Now, they appear as normal links with `red underlined text`, making them more readable and predictable for users.

[12.x] Fix link formatting

---

collections.md

This PR updates the `implode` method's first and third output examples for consistency with the second example, which correctly shows the return value as a string.

[12.x] Fix implode method examples to show actual return values

---

collections.md

Documented the newly introduced `fromJson` method see laravel/framework#55310.
Also added an example for the `make` method and included a hint for both `make` and `fromJson` methods in the `Creating Collections` section.

[12.x] Document `fromJson` method on `collections` docs

---

container.md

`die` can cause problems if run in certain environments (Octane-based runtimes), since it's meant to "terminate a process". Plus, it's a nice opportunity to show readers the `dd` helper.
Reference in the case of RoadRunner (Octane):
https://spiral.dev/docs/basics-debug/current/en#avoid-using-die-and-exit-functions

[12.x] Replace `die` with `dd`

---

context.md

I ran the same code while exploring, and here is the ss of dd. it also aligns with docs.

[12.x] fixed the incorrect output in scope context example

---

database.md

Documented the newly introduced argument to `DB::transaction()` see: laravel/framework#55338

[12.x] Document the optional argument on database transactions

---

blade.md

This PR updates the second `@use` directive example to use the `blade` code block instead of `php`. Currently, the first example uses the correct Blade syntax. However, the second example is using a php block. This causes inconsistent syntax highlighting and may be confusing for readers. Updating it to use the blade code block. Ensures visual consistency and better represents how this directive is used in Blade templates, similar to the experience in code editors.

[12.x] Use consistent Blade syntax highlighting for @use directive examples

---

validation.md

As of a [commit since 12.x](https://github.com/laravel/docs/commit/572395406fc6cf79d1577c335d7aa6e50a210b4e), the email validation docs could be seen as misleading/confusing.
The email validation does not validate against RFC 5322, but also allows other RFCs. This is important, as other RFCs allow emails that are not compatible with several (most?) major email platforms.
Also, the `strict` validation mentions "rejecting trailing periods or multiple consecutive periods", which I think is an oversimplification.
I don't see a way in the upstream [`egulias/EmailValidator`](https://github.com/egulias/EmailValidator) to selectively validate against certain RFCs.
As the list of RFCs is subject to change, I propose changing the docs to mention "supported RFCs", with a link to the list. The link …

[12.x] Make it more clear what is happening with email RFC validation

---

validation.md

---
This pull-requests adds the missing document for this pull-request [#54608](https://github.com/laravel/framework/pull/54608)

feat: [12.x] Prohibited If Declined and Prohibited If Accepted validation

---

blade.md

For https://github.com/laravel/framework/pull/55461

[12.x] Group imports in Blade `@use` directive

---

eloquent-mutators.md

As part of [#55383](https://github.com/laravel/framework/pull/55383).

Adds `AsColection::map()` section

---

eloquent-mutators.md

while this is definitely a subjective change, I think it provides some significant benefits:
- consistent naming pattern with Laravel internal casts
- prefix helps indicate a cast object, and avoid confusion with names of value objects
- avoids having to alias imports. value objects get the noun, and casts get the prefix.
generally speaking, I think these changes improve readability and consistency.

[12.x] prefix casts with "As"

---

eloquent-mutators.md

I find the side scrolling for code snippets to decrease readability. these lengthy method signatures are often the culprit on this page. switching to multiline parameters to help avoid the necessity to side scroll.
followed the PSR-12 recommendation for when dealing with multiline parameters AND a return type.
I know this will be a constant battle in the documentation, and while changes like this won't completely eliminate the problem, I do think they help.
I would also like to see the Laravel documentation site make better use of the space it has available. On larger screens we have the ability to increase the container size. I would also suggest there is a lot of unused space between the columns of our 3 column layout. Changes here would also go a long way to help remove the need for …

[12.x] use multiline parameters for casting methods

---

billing.md

Small fix for Cashier (Stripe) page with a missing closing in the PHP tag.

Closing missing `php` Tag

---

notifications.md

Scope `chat:write:bot` was mentioned in docs for [chat.postMessage](https://api.slack.com/methods/chat.postMessage) but this is outdated as perspective scopes are deprecated, see [here](https://api.slack.com/authentication/quickstart#perspective)

 Slack notification prerequisites

---

urls.md

The correct link is: https://laravel.com/docs/12.x/helpers#uri
Not: https://laravel.com/docs/12.x/helpers#uris

[12.x] Correct the URI documentation link

---

sanctum.md

Adds documentation to the Sanctum helper functions.

Documents changes in https://github.com/laravel/sanctum/pull/564

---

scout.md

In this context, 'models' is not possesssive. 
> your searchable **models** must define a
**Note:** something that I cannot fix via this repository is a navigation error on the Packages/Dusk page. When clicked, the main navigation jumps to the 'Testing' section.

Grammatical fix in scout.md

---

http-client.md

https://github.com/laravel/framework/blob/fef0498be5f61ce5fae45a8a8a0056a963164098/src/Illuminate/Http/Client/PendingRequest.php#L232

Add default connect timeout (10 seconds) to HTTP client documentation.

---

scheduling.md

There are two problems with the current example:
- It's invalid PHP syntax (method call after semicolon)
- It makes you think that the cache connection can be configured _per event_, which you can't.

Fix invalid useCache() example

---

broadcasting.md

This PR adds the missing namespace to ensure consistency across all event examples and to avoid any confusion for readers following the documentation.

[12.x] Add missing namespace declaration to event example

---

eloquent-mutators.md

This pull request corrects a small typo where the interface name `JsonSerilizable` was misspelled. The correct spelling is `JsonSerializable`, which matches the [official PHP interface](https://www.php.net/manual/en/class.jsonserializable.php).

[12.x] Fix typo in interface name

---

helpers.md

Adds typed getter helpers (`Arr::string()`, `Arr::integer()`, `Arr::float()`, `Arr::boolean()`, `Arr::array()`) as also exist on the `Config` facade, in an effort to make static analysis easier when using the `Arr::get()` helper.
Framework PR: https://github.com/laravel/framework/pull/55567

[12.x] Typed getters for Arr helper (docs)

---

blade.md

[12.x] Add documentation on `@use` directive modifiers

---

prompts.md

This PR includes the missing import for the `text()` function. Without it, the example throws an error:
> Error: Call to undefined function App\Console\Commands\text()
This change ensures the example runs as expected.

[12.x] Fix the missing text import

---

billing.md

Fixes a missing codeblock start tag in [Custom Invoice Renderer](https://laravel.com/docs/12.x/billing#custom-invoice-render). Should make `Checkout` and `Product Checkouts` work again. 👍

[12.x] Add missing codeblock start to billing

---

eloquent-mutators.md

To avoid confusion, the option constructor should receive an `array`, not each array member values. This is because `mapInto` and `map` will receive the item array completely.

Minor fix to the AsCollection Option example

---

queries.md
scout.md

This is the first mention of `Builder` on the page. Should the `use` reference be included here since there are several possible imports?

Query builder first mention

---

helpers.md

Description
---
This change reflects the actual behavior returned by the current implementation of `Number::pairs`.

[12.x] Fix Number::pairs example to reflect actual behavior

---

collections.md

Description
---
This PR clarifies the behavior of the `collapse` method to reflect that it can collapse both arrays and collections. Currently, the documentation only mentions arrays, but the method also supports nested Collection instances.
This change not only improves clarity and accuracy but also ensures consistency with the `collapseWithKeys` method, which explicitly states support for both arrays and collections.

[12.x] Clarify collapse method behavior

---

queues.md

See: https://github.com/laravel/framework/pull/55671

[12.x] Document releaseAfter method

---

validation.md

I recently stumbled upon this bit of (to my knowledge) undocumented behaviour of the `exists` rule. 
I assumed that `exists` would not work on array values because the documentation did not specify that it would. So I validated incoming arrays of IDs like this:
```php
'user_ids' => ['array'],
'user_ids.*' => ['integer', 'exists:users,id'],
```
This queries the database for every single item in the array. Instead, you can specify the 'exists' rule as:
```php
'user_ids' => ['array', 'exists:users,id'],
```
... which only generates a single `WHERE id IN (...)` query. This PR adds a little note on this to the docs.

[12.x] Add docs about using 'exists' rule on array

---

helpers.md

In the Number helper class currency method precision not documented, but exist in the code, there is a lot of currency that do not use any subb currency Like (HUF)

Update undocumented precision in documentation

---

collections.md

Description
---
The first argument passed to the `when` method is a bool, `not` an `int`.

[12.x] Fix typo in when method argument type

---

collections.md

Description
---
This PR updates the description for the `unless` method to clarify that both the collection instance and the first argument are passed to the closure similar to the behavior of the `when` method.
As the `when` method explicitly states that:
> The collection instance and the first argument given to the when method will be provided to the closure:
Let's do the same for the `unless` method to maintain consistency and improve clarity for developers reading the documentation, especially since `when` and `unless` are behave similarly in terms of callback parameters.

[12.x] Clarify unless method usage in collections docs

---

helpers.md

This PR adds the `Arr::from()` method to helpers. 
https://github.com/laravel/framework/pull/55715

[12.x] Add `Arr::from()` to helpers

---

broadcasting.md

Removes redundant `will` word.
Continuation of: https://github.com/laravel/docs/pull/10398

[12.x] Fix typo in broadcasting.md

---

queues.md

Laravel allows developers to define a retryUntil() method on queued jobs to specify a time limit for retry attempts. The documentation correctly describes this as an alternative to setting a tries limit.
However, the current text does not clarify what happens when both retryUntil() and tries are defined on the same job. In practice, Laravel prioritizes the retryUntil() constraint, allowing the job to continue retrying until the specified time expires — even if it exceeds the configured number of attempts.
This behavior is handled within the markJobAsFailedIfAlreadyExceedsMaxAttempts()(https://github.com/laravel/framework/blob/12.x/src/Illuminate/Queue/Worker.php) method, where the retryUntil() timestamp is checked before enforcing the maxTries logic.
This PR proposes the following note to …

[12.x] Clarify retryUntil() precedence over tries in queue jobs

---

queues.md

https://github.com/laravel/framework/pull/55718

[12.x] Add `deleteWhen` method in job middleware

---

context.md

Description
---
This PR introduces the `exceptHidden` method, complementing the previously added `onlyHidden` method. I have added the `exceptHidden` method after the `onlyHidden` method.
Continuation of https://github.com/laravel/framework/pull/55692 and https://github.com/laravel/docs/pull/10388

[12.x] Add `exceptHidden` method in Context

---

context.md

Description
---
This PR introduces the `missingHidden` method, complementing the previously added `hasHidden` method. I have added the `missingHidden` method after the `hasHidden` method.

[12.x] Add `missingHidden` method in Context

---

events.md

Description
---
This PR fixes a minor formatting inconsistency in the Laravel Events docs. Specifically, it removes an extra space before the ellipsis (...)
This change aligns it with the formatting used in other comments throughout the codebase, where no space precedes the ellipsis.

[12.x] Fix spacing inconsistency before ellipsis in event comments

---

http-tests.md

https://github.com/laravel/framework/pull/55750

[12.x] Add `assertClientError` method to http-tests

---

http-tests.md

`assertAccepted` should come before `assertBadRequest` to maintain alphabetical ordering.

[12.x] reorder assertions alphabetically

---

queues.md

This PR updates the Laravel documentation to clarify that the tries property and retryUntil method are also available on queued notifications, in addition to queued event listeners.
Why this change is necessary:
Currently, the documentation only mentions that these properties can be defined on "queued event listeners." However, Laravel also supports tries and retryUntil on queued notifications. This change provides better clarity for developers utilizing notification queues, ensuring they are aware of retry capabilities.

[12.x] Update queue docs: Include queued notifications for tries and retryUntil

---

sail.md

This PR changes information about the version of Node that is installed by default by `laravel/sail`, it seems that new default version is `22`. https://github.com/laravel/sail/blob/3e7d899232a8c5e3ea4fc6dee7525ad583887e72/runtimes/8.0/Dockerfile#L6

Update default node version installed by laravel/sail

---

events.md

Continuation of: https://github.com/laravel/docs/pull/10404

[12.x] Clarify retryUntil() precedence over tries

---

helpers.md

Description
---
This PR removes the warning that labels Laravel's Deferred functions as "currently in beta."
Reason for Change
---
The Deferred functions appears to have moved beyond beta, it has no changes across recent versions.
Goal
---
This update helps prevent confusion for developers who may hesitate to use the feature due to outdated messaging.

[12.x] Is the defer function still in beta?

---

concurrency.md

Description
---
This PR removes the warning that labels Laravel's Concurrency facade as "currently in beta."
Reason for Change
---
The Concurrency facade appears to have moved beyond beta, it has no changes across recent versions.
Goal
---
This update helps prevent confusion for developers who may hesitate to use the feature due to outdated messaging.

[12.x] Is the Concurrency facade still in beta?

---

collections.md

Description
--
This PR updates the examples for the `dd` and `dump` methods in the Collections documentation.
Problem
---
Currently, the examples show the output as a Collection object with internal properties. However, both `dd` and `dump` actually output the underlying `array`, not the `Collection` object itself.
Proposed Fix
---
Update the sample output to accurately reflect what is printed when using these methods.
Reasoning
---
This change improves accuracy and prevents confusion for developers referencing the documentation to understand the behavior of these methods.

[12.x] Update the output of `dd` and `dump` methods

---

context.md

Problem
---
The original example lacks context about where the `DB::listen` logic is expected to live, which may confuse developers unfamiliar with the typical usage patterns.
Proposed Fix
---
Add a comment to clarify that the `DB::listen` code should be placed in a service provider.
Reasoning
---
This small change improves readability by helping readers understand where the code belongs within a typical Laravel application structure.

[12.x] Clarify where the code should be placed

---

helpers.md

Description
---
This PR removes the section that begins with:
"If you upgraded to Laravel 11.x from a Laravel 10.x application ..."
Since this instruction is only relevant to projects upgrading to Laravel 11.x, I believe it doesn't belong in the Laravel 12 documentation. Keeping it in the Laravel 11 docs is sufficient and avoids cluttering the latest version's documentation with upgrade steps that no longer apply.

[12.x] Remove outdated upgrade note from Laravel 12 docs

---

releases.md

Description
---
This PR updates the version support table in the documentation to:
- Remove Laravel 9, which is now end-of-life and no longer receives bug or security fixes.
- Add a row for Laravel 13, with a tentative release in Q1 2026, following Laravel's typical release cycle. Estimated dates for bug and security fixes are also included based on the standard 18-month and 24-month support timelines.
This change helps keep the table focused on currently supported and upcoming versions, making it easier for developers to understand what’s relevant today and in the near future.

[12.x] Update version support table

---

collections.md

Description
---
This PR updates the documentation for the `pop` method in Laravel's `Collection` class to explicitly mention that it returns null when called on an empty collection. This clarification helps avoid confusion and aligns the docs with the actual method behavior.

[12.x] Clarify behavior of pop method when the collection is empty

---

broadcasting.md

Description
---
This PR uses environment variable for `pusher channels key` instead of hardcoding it. This change aligns with Laravel’s recommendation to avoid hardcoding sensitive values and to use `import.meta.env` for accessing environment variables.

[12.x] Use environment variable for Pusher Channels Key

---

events.md

Description
---
This PR uses a more concise and active phrasing. Change `which will be passed an event dispatcher instance` to `which receives an event dispatcher instance` for improved readability and consistency with the overall tone of the Laravel documentation.

[12.x] Improve clarity in event subscriber docs

---

collections.md

Description
---
This PR updates the description of the `replaceRecursive` method in the `Collections` docs to improve consistency and clarity. Begins the sentence with the method name, matching the style used in other method's descriptions like `replace`. Uses "behaves similarly" instead of "works like" for a more formal and consistent tone.
This change aligns the tone and structure with other method's descriptions.
> The `replace` method behaves similarly to `merge` ...
> The `replaceRecursive` method behaves similarly to `replace` ...

[12.x] Refine `replaceRecursive` method description for consistency

---

events.md

Description
---
This PR updates the PHPDoc for the `backoff()` method to use `list<int>` instead of `array<int, int>`. Since the method returns a numerically indexed array with consecutive integer keys starting from 0, I think `list<int>` more accurately describes the return type.
Note
---
I do not know how the `backoff()` method behaves behind the scenes.

[12.x] Improving the return type annotation

---

validation.md

Related https://github.com/laravel/framework/pull/55809

[12.x] Add documentation for "Rule::contains"

---

responses.md

Totally understand if these changes don't get merged. Spent a day trying to understand the new streaming docs and had to go to the source of the package to see why I was having issues.
The Laravel stream package is hardcoded to use POST requests yet the second example is a GET request. Updating to POST to make it easier to onboard new developers.
The CSRF token is not alway present in the head of a layout. Make sure to call this out otherwise new users see 419 without a good error message on how to address.

Update responses.md to make easier for new users to use stream package.

---

strings.md

Adds documentation for the static versions of `match` and `matchAll`.

Add `Str::match` and `Str::matchAll` to 'Strings'

---

container.md

Description
---
This PR fixes a class name conflict caused by importing two classes with the same name:
- `App\Contracts\Repository`
- `Illuminate\Contracts\Cache\Repository`
Since both share the same base name (Repository), PHP throws the following error:
> Cannot use Illuminate\Contracts\Cache\Repository as Repository because the name is already in use
To resolve this, I updated the constructor to use a custom `UserRepository` interface in place of the generic `Repository` contract from our app domain. This makes the intent clearer and avoids naming collisions.

[12.x] Avoid class name conflict

---

eloquent-mutators.md

Description
---
Reordered `AsStringable::class` and `AsUri::class` alphabetically for consistency and readability.

[12.x] Reorder Attribute casting

---

validation.md

Description
---
This PR updates instances of `date based` to `date-based` across the docs. I think in standard grammar rules, compound adjectives should be hyphenated. This change ensures grammatical correctness.

[12.x] Fix hyphenation of `date-based` for grammatical correctness

---

homestead.md

Description
---
This PR fixes a small typo in the Homestead docs. Replaces `Laravel Homestead if a legacy package` with `Laravel Homestead is a legacy package`.

[12.x] Fix typo in Homestead deprecation notice

---

artisan.md

Description
---
This PR updates the wording in the docs regarding `Isolatable console commands` to avoid confusion about the behavior of the `--isolated` option.
Reason
---
The current documentation state:
> "When a command is marked as Isolatable, Laravel will automatically add an --isolated option to the command."
User may understand that the command will automatically run in isolated mode when marked as Isolatable, which is not the case. In reality, Laravel makes the `--isolated` option available, and it's up to the user to explicitly pass it during execution.

[12.x] Refines wording related to Isolatable commands

---

artisan.md

Description
---
Laravel docs use both `without you needing` and `without needing`. This change aims to improve clarity and maintain consistency with the more common phrasing used elsewhere in the docs.

[12.x] Improve clarity in Isolatable commands

---

dusk.md

This PR updates `dusk.md` to include the `assertCount()` assertion and `component()` method.

Add assertCount() and component() to Laravel Dusk docs

---

helpers.md

Description
---
This PR adds the missing use `App\Exceptions\RetryException;` import statement to the retry helper example in the docs.
Since RetryException is a user-defined class (not provided by Laravel), including the import makes it clearer to readers that they need to define this exception themselves and avoids confusion about it being a built-in class.

[12.x] Add missing import for RetryException in retry helper example

---

authentication.md
pagination.md
passport.md
releases.md
scheduling.md

[12.x] Format remaining tables

---

strings.md

Description
---
This PR adds a missing comma in the sentence "By default this method is case sensitive" to improve clarity and follow standard grammar rules. The updated sentence is: "By default, this method is case sensitive"
This is a minor documentation fix for readability.

[12.x] Fix punctuation

---

queues.md

This PR adds `make:job-middleware` command to queue docs.

[12.x] Add make:job-middleware command to queue docs

---

eloquent-mutators.md

I noticed that the documentation for the `compare` method was a bit incorrect.

[12.x] Correction in eloquent-mutators.md Comparing Cast Values

---

horizon.md

I didn’t even realize you could clear Horizon metrics until I went looking for it. Adding this to the docs makes it easier for others to discover without having to dig around.

[12.x] Add `php artisan horizon:clear-metrics` command

---

strings.md

This PR adds documentation for the `Str::of('...')->fromBase64()`, `Str::fromBase64('...')` and `str('...')->fromBase64()`.

Add documentation for fromBase64()

---

mix.md

Description
---
This PR adds a short deprecation note to clarify that Laravel Mix is now a legacy package and no longer actively maintained, similar to the recent update regarding Homestead. It suggests using Vite as the modern alternative, in line with current Laravel recommendations.
This update helps guide developers toward using the officially supported frontend tooling and avoids confusion when choosing between Mix and Vite.

[12.x] Add deprecation notice for Laravel Mix

---

helpers.md

Description
---
The `mix()` helper has been deprecated in recent Laravel versions in favor of the Vite-based asset bundling. This PR removes it from the `helpers.md` documentation to keep it aligned with current Laravel standards.

[12.x] Remove deprecated mix() helper

---

eloquent.md
queries.md

`skip()` and `take()` are alias methods to `offset()` and `limit()`. IMO we should only use and document the main methods, not the aliases.  This will encourage more performant coding, just like we now do in `laravel/framework`.
IF it's decided we still want to mention the aliases, I'd recommended listing them second as the alternatives.  I can make that change if desired.
follow up to https://github.com/laravel/framework/pull/56080 and https://github.com/laravel/framework/pull/56081

[12.x] only use and document the `limit` and `offset` methods

---

vite.md

Description
---
Laravel Mix has been deprecated in recent Laravel versions in favor of the Vite-based asset bundling. This PR removes it from the `vite.md` documentation to keep it aligned with current Laravel standards.
---
Continuation of: #10520

[12.x] Remove Mix from Vite docs

---

http-client.md

Description
---
This PR corrects the order of the "Inspecting Requests" and "Preventing Stray Requests" sections in the HTTP Client testing documentation. Previously, the main content displayed "Preventing Stray Requests" before "Inspecting Requests", which did not match the order shown in the right sidebar (table of contents). The sections are now reordered to ensure consistency between the sidebar and the main documentation content.

[12.x] Fix order of sections in HTTP Client docs

---

mail.md

A long time ago, I read the source code, found out the `Illuminate\Mail\SendQueuedMailable::failed()` method and realized it's possible to do this.
We have been doing this in production for years, notified of occasional email failures. Some example errors are:
```
"App\\Mail\\OrderDelayed has been attempted too many times or run too long. The job may have previously timed out."
"Expected response code \"250\" but got code \"221\", with message \"221 Closing connection. Waiting command exceed timeout. Please use NOOP for keeping idle connection.\"."
"Expected response code \"250\" but got empty code."
"Error executing \"SendRawEmail\" on \"https:\/\/email.us-east-1.amazonaws.com\"; AWS HTTP error: Client error: `POST https:\/\/email.us-east-1.amazonaws.com` resulted in a `400 Bad Request` …
```

[12.x] Add the failed method to queued mailables.

---

redis.md

As per https://github.com/laravel/framework/pull/55641, predis/predis verison 3 is supported so the documentation should no longer specify version 2 for the composer require command.

[12.x] Allow latest version of predis

---

helpers.md

Description
---
Add documentation for the newly introduced methods in: https://github.com/laravel/framework/pull/55967
Note
---
I used the same tone that we used in `broadcast()`, `abort_if()`, and `abort_unless` methods.
Question
---
I'm not sure how to document the `FakePendingBroadcast` in this context. Could you take care of it, or do you think it doesn't need documentation?

[12.x] Add broadcast_if and broadcast_unless methods to helpers

---

validation.md

Description
---
Using person in array syntax like "person.*.email" might confuse non-native English speakers who could mistakenly think it's a typo and expect "persons". The word "users" is clearer and more conventional in this context. It also aligns better with the "users" database table name.
---
reopen: #10517

[12.x] Rename the person parameter to users

---

helpers.md

Description
---
Since the current implementation of `Arr::forget()` also can accept an array of keys, it would be more accurate to use "s" as we did with the `Arr::except()` method.
References
---
- The [forget comment](https://github.com/laravel/framework/blob/c0955af55f216ba0b864a3819acb435859957f0a/src/Illuminate/Collections/Arr.php#L358) indicates that it can "Remove one or many array items".
- The [current docs](https://github.com/laravel/docs/blob/388799f067a30bc0e0996e8d33fd1576548d1ece/helpers.md?plain=1#L392) about the `Arr::except()` method that uses "s" indicating that it can except one or more pairs.

[12.x] Fix wording in Arr::forget method

---

blade.md

Description
---
This PR updates a sentence to improve grammatical accuracy. The original wording uses "is" which implies present, alongside "escaped" which implies "past" at the same time.

[12.x] Fix grammatical inconsistency

---

passwords.md

document https://github.com/laravel/framework/pull/53428
I modeled the wording and organization after the [session](session.md) docs for hopefully a little consistency.
this is a resubmission of #10032. there were a lot of merge conflicts since I had based that off 11.x, so figured it was easier to start fresh.
@taylorotwell you made a comment in that PR about if I could "implement that automatic hashing of the keys so we don't need to worry about prefixes".  I could not find any prior reference to that request, and I wasn't exactly sure what you were asking, so I wanted to get some clarification before this is merged.
I think my confusion lies in I'm so used to hashing for passwords via `password_hash()` (non-deterministic) that I forgot there's also `hash()` (deterministic). Are you …

[12.x] document the password reset `cache` driver

---

helpers.md

Description
---
I think that only the word `context` should be displayed as a link, not `current context`.

[12.x] Reformat the link in context() helper description

---

passwords.md
session.md

Description
---
This PR updates instances of `cache based` to `cache-based` across the docs. I think in standard grammar rules, compound adjectives should be hyphenated. This change ensures grammatical correctness and consistency, as both `cache based` and `cache-based` are currently used in the docs.

[12.x] Fix hyphenation of cache-based for grammatical correctness and consistency

---

scout.md

Description
---
This PR updates instances of `driver based` to `driver-based` across the docs. I think in standard grammar rules, compound adjectives should be hyphenated. This change ensures grammatical correctness and consistency, as both `driver based` and `driver-based` are currently used in the docs.

[12.x] Fix hyphenation of driver-based for grammatical correctness and consistency

---

responses.md

When reviewing the [Build and AI Chat with Laravel](https://youtu.be/BuUbTRHuvAw) video, I noticed that the documentation for `useEventStream` was not correct to match the eventName that is specified in the JS packages.

[12.x] Fix Typo of eventName for useEventStream Hook

---

http-client.md

Description
---
The phrase `determine if the response has a given status code` suggests that these methods are parameterized, which they are not. Instead, each method is hardcoded to check for a `specific` status code, so they don't allow checking for a `given` status code.

[12.x] Improve clarity

---

queries.md

In January 2016 a feature was added to allow where clauses with associative arrays, where the column name is the array key and the where value is the array value. It seems like this was never documented, however I imagine since it's such an intuitive way to use the where clause a number of projects are likely using it without realising it's an undocumented feature. It's also a good feature that should stay as it's a common use case to already have such an array and want to be able to use it in a query.
- Original commit: https://github.com/laravel/framework/commit/491feeb82ac27542c6a5512f26735451a2d9c09f
- Framework code: /Illuminate/Database/Query/Builder.php::addArrayOfWheres()
Code block (the else statement is the feature implementation):
```    
protected function …
```

Document associative array where clauses

---

logging.md

Description
---
Since Laravel requires PHP 8.2+ as a minimal version to work, the PHP 8.2 warning is now obsolete and potentially confusing.

[12.x] Remove outdated PHP version warning

---

mail.md

Description
---
This PR updates two outdated and broken URLs in the Laravel mail docs to point to the correct locations.

[12.x] Fix outdated URLs in Mail

---

mail.md

Description
---
- Removed parentheses from `__toString` method to align with Laravel's documentation style.
- Updated config/mail.php path to use code style (`config/mail.php`) following the standard formatting for file paths.

[12.x] Improve formatting

---

mail.md

Description
---
Complete the Mailchimp custom transport example by providing the actual implementation for the `Mail::extend()` closure and configuration setup.
The current placeholder makes the example incomplete and potentially confusing for beginners, who might mistakenly assume that the service container will automatically handle the dependency injection.

[12.x] Complete Mailchimp transport example

---

mail.md

Description
---
This PR updates instances of `cloud based` to `cloud-based` across the docs. I think in standard grammar rules, compound adjectives should be hyphenated.

[12.x] Fix hyphenation of cloud-based for grammatical correctness

---

collections.md

Description
---
This PR updates the `push()` method documentation to clarify that it accepts multiple arguments via variadic parameters, not just a single value. This may help users to avoid unnecessary loops.

[12.x] The push method accepts variadic parameters

---

helpers.md

Description
---
This PR makes a code style improvement by updating the spacing in the Blade `@for` directive to follow the common Laravel style used elsewhere in the docs.

[12.x] Consistent spacing in Blade control structures

---

helpers.md

Description
---
This PR corrects a minor documentation issue for the `Arr::join()` method. The string used for the final element is actually passed as the `third` argument, not the `second`. This PR updates the text to accurately reflect that.

[12.x] Fix incorrect parameter reference

---

helpers.md

Description
--
This PR clarifies the behavior of the `head()` and `last()` helpers when used on an empty array. It helps developers understand that the method will return `false` in such cases, which might not be immediately obvious.
Note
---
I used the same tone that we have used elsewhere in the docs.

[12.x] Clarify the behavior of head and last helpers

---

responses.md

Not much description needed: Generator return type must be a supertype of Generator, not void.

Fix return-type typo

---

validation.md

Follow up docs for this change in Laravel 12 https://github.com/laravel/framework/pull/56313

[12.x] Adds bool:strict docs

---

strings.md

Fixes incorrect test results introduced in #10569.

[12.x] Fix doesntStartWith incorrect test results when passing array of values

---

validation.md

- adds additional documentation to the validation page for the numeric rule
Documentation for the new strict parameter for numeric rule added in https://github.com/laravel/framework/pull/56328

Adds strict param for numeric rule

---

notifications.md

Description
---
The "Unicode Content" section is an `h4` in the docs. So, I do not think we need to mention it in the table of contents. This improves the navigability of the documentation.
See
---
https://github.com/laravel/docs/blob/16978eb4f5adeb0a1106895336a07b902cf062b4/notifications.md?plain=1#L1240

[12.x] Remove "Unicode Content" from table of contents

---

notifications.md

Description
---
This pull request adds documentation for the `readNotifications` method, which exists on notifiable models through the `Illuminate\Notifications\Notifiable` trait.
This method can be particularly useful in cases where you want to display "unread" notifications first, followed by "read" notifications, providing more control over how notifications are presented to the user.
The `readNotifications` section has been documented before the `unreadNotifications` section to maintain alphabetical order, which is also the same order used in the [HasDatabaseNotifications trait within the Laravel core](https://github.com/laravel/framework/blob/d41f408ff1fde6b20c3a91e41ab9955e2fd52dff/src/Illuminate/Notifications/HasDatabaseNotifications.php#L5).
Lastly, the tone and wording used in …

[12.x] Add readNotifications relationship method

---

packages.md

Description
---
The PHPDoc for the `register` method currently says: `Register any application services.`. For consistency with the `boot` method's comment: `Bootstrap any package services.`, it should be updated to: `Register any package services.`
This aligns with the context of service providers within packages.

[12.x] Fix PHPDoc for consistency

---

queues.md

I want to:
- Add the `assertClosureNotPushed` method.
- Add an example passing a truth test to the `assertClosurePushed` method.
- Revise some wording.

[12.x] Add the assertClosureNotPushed method

---

events.md

Description
---
This PR updates the events docs to consistently use the "$" prefix when referring to class properties. This improves consistency, as it is used inconsistently: sometimes applied, other times not.

[12.x] Consistent usage of "$" prefix for property names

---

passport.md

There are several syntax errors in the Passport documentation.

Fix syntax errors in Passport examples

---

artisan.md

This was originally included in a previous PR (https://github.com/laravel/docs/pull/10653) alongside an incorrect change to the `choice()` method.
While that part was rightly rejected, I think this small addition remains valid and useful, so I'm submitting it here separately for clarity and completeness.

[12.x] Improve Artisan console docs

---

queues.md

"Timeout" is a noun. I'm highly frustrated when reading this 😅

Fix wrong grammar in comment

---

processes.md

Description
---
When I run this code for the first time, I encounter the following error:
```php
Call to undefined method Illuminate\Process\ProcessResult::start()
```
As stated in the docs, the closure should be passed as the second argument to the pipe method. See: https://github.com/laravel/docs/blob/d640df584c1a06656e4518074a08acc5ca7a1560/processes.md?plain=1#L205C52-L205C102

[12.x] Fix incorrect usage of Process::pipe()

---

queues.md

Description
---
This PR enhances the `UpdateSearchIndex` job example by:
- Adding the missing namespace.
- Correcting the @var PHPDoc annotation to reflect the correct model namespace.
- Remove the unused import.
These changes improve clarity and ensure the example accurately represents standard Laravel application structure.

[12.x] Fix namespace declaration and correct PHPDoc in job class example

---

queues.md

Description
---
This PR avoids potential confusion over the term "not acquired" and makes the behavior easier to understand at a glance.

[12.x] Clarify ShouldBeUnique job lock behavior

---

broadcasting.md

Fixed typo: "with prompt" → "will prompt" in the quickstart guide.

Fixes typo in broadcasting documentation

---

queues.md

Description
---
This code was newly introduced in #10508 and it uses the `InteractsWithQueue` trait which we do not use it throw the whole `queues.md` docs, so I think we should use the `Queueable` trait -which is already imported- for consistency with the job class generated by Artisan command.

[12.x] Enhance the FailOnException middleware example

---

queues.md

Description
---
This PR updates instances of `lower level` to `lower-level` across the docs. I think in standard grammar rules, compound adjectives should be hyphenated.

[12.x] Fix hyphenation of lower-level for grammatical correctness

---

queues.md

Description
---
According to the [.env](https://github.com/laravel/laravel/blob/8d8d3b729afacce5632ca8b42e20e09f5433d2d6/.env.example#L38)  and [config/queue.php](https://github.com/laravel/laravel/blob/8d8d3b729afacce5632ca8b42e20e09f5433d2d6/config/queue.php#L16) files, the default queue driver is the `database` driver.

[12.x] The database driver is the default queue driver

---

passwords.md

Description
---
This PR updates the sentence for consistency with other parts of the docs and removes redundancy ("service provider's").

[12.x] Use consistent phrasing for AppServiceProvider

---

queues.md

Description
---
This PR adds proper links to both **Redis Cluster** and **Blocking** titles.

[12.x] Add proper links

---

eloquent-relationships.md
queues.md

Description
---
Most examples use the `$condition` variable to represent a conditional check. However, two examples use `$someCondition` instead. This PR updates those instances for consistency across the docs.

[12.x] Replace $someCondition with $condition for consistency

---

queues.md

Description
---
This PR updates the punctuation to follow the Laravel documentation style guide. When a sentence introduces a code block, it should end with a colon (:) instead of a period (.).

[12.x] Format

---

horizon.md

Revert "[12.x] Fix incorrect default retry info in Horizon docs"

---

queues.md

Description
---
The current example uses `return` with the job's `handle()` method which returns `void`, this causes a PHP error:
```sh
A void method must not return a value
```
The example is updated to simply call `cancel()` without returning its result. This makes the code matches the actual method signature.

[12.x] Fix Cancelling Batches example

---

eloquent-relationships.md

This PR corrects the import statement for the `Builder` class in the eager loading documentation.
The example should import `Illuminate\Database\Eloquent\Builder` class, not the contract.

[12.x] Correct import statement for Eloquent Builder

---

queues.md

Description
---
This PR updates the example to use the default namespace for models.

[12.x] Fix model default namespace

---

helpers.md

Description
---
This PR enhances the **Swoole PHP extension** by adding link to point to the official PHP docs.

[12.x] Swoole proper link

---

helpers.md

Description
---
This PR updates the `Arr::push` documentation example to reflect the actual return value. Since `Arr::push` always appends the given value into an array, the corrected example should use the array form.
When I run this code I get:
```php
array:1 [
"office" => array:1 [
"furniture" => array:1 [
0 => "Desk"
]
]
]
```

[12.x] Fix Arr::push example to show the actual result

---

strings.md

Doc updates related to https://github.com/laravel/framework/pull/56802

[12.x] Document new Plural param for prependCount

---

upgrade.md

This PR updates the 9 to 10 upgrade guide to clarify the status of Redis cache tags across Laravel versions.
Currently, the upgrade guide warns users that cache tags is only recommended when using Memcached, and discourages Redis: https://github.com/laravel/docs/pull/9286
This small clarification helps developers upgrading from Laravel 9 avoid unnecessary driver migrations, while making it clear that flush Redis tags are supported again starting from `12.30.0`: https://github.com/laravel/framework/pull/57098

[10.x] Clarify Redis cache tags fix in Laravel `12.30.0`

---

sail.md

This PR changes references to `docker-compose.yml` in the Sail documentation into `compose.yaml` to reflect the changes in laravel/sail#818.

Change references to `docker-compose.yml` into `compose.yaml`

---

mcp.md

Fix: Redirect to the Resources Section Instead of Create Resources
The issue is that when clicking on the **Resources** navigation link, it incorrectly redirects to the **Create Resources** section. The expected behavior is that it should redirect to the main Resources section instead.
https://github.com/user-attachments/assets/58773790-0990-4deb-82b0-10f7b7ad1cc4

[12.x] fix: correct link reference for Resources section in MCP documentation

---

http-client.md

This PR adds documentation for the `Http::batch` method.

Add docs for `Http::batch`

---

strings.md

Some of the documentation examples are incorrect and make it seem like there's additional hidden functionality for removing whitespace.
I tested them in artisan tinker:
```
> Str::of('Arkansas is quite beautiful!')->remove('quite')
= Illuminate\Support\Stringable {#7012
value: "Arkansas is  beautiful!",
}
> Str::of('Foo Bar')->ucsplit()
= Illuminate\Support\Collection {#7005
all: [
"Foo ",
"Bar",
],
}
```

Fixed string utility examples

---

telescope.md

Makes it easier for users to find all the available types

Use const instead of plain text for Telescope entry type

---

controllers.md

There is a note just under this section that states that the `Illuminate\Routing\Controllers\HasMiddleware` contract cannot be used in conjunction with ` App\Http\Controllers\Controller`, yet the example itself has the class extending `Controller`.
I can confirm that if the class extends `Controller` you will get an error:
"Cannot make non static method Illuminate\Routing\Controller::middleware() static in class App\Http\Controllers\ArticleController"
This correction is applicable to documentation for Laravel 11.x and up.

Update controllers.md to correct HasMiddleware documentation
